### ISSUE TITLE
Text in the book is very small unless using large GUI scale

### ISSUE THREAD

**Issue by AutTheWizard** [Mithion/Mana-And-Artifice#1]
![5CHA53m](https://user-images.githubusercontent.com/42747387/84560094-cc268000-acfd-11ea-9a55-d90d7565c6cd.jpg)

**Comment by FoxMcloud5655** [comment]
Was about to make an issue about this very thing; glad it's already been posted!

**Comment by Mithion** [comment]
The book has been redesigned so that text scales along with the regular minecraft UI.
Fix will deploy in 1.0.2-pre1.
