### ISSUE TITLE
runescribing

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#10]
the runescribing table isn't working properly (for me at least) and no patterns seem to work
![2020-06-13_15 08 13](https://user-images.githubusercontent.com/8917961/84577144-c1183200-ad87-11ea-8bde-5a7f9e05ca08.png)
![2020-06-13_14 54 07](https://user-images.githubusercontent.com/8917961/84577154-cbd2c700-ad87-11ea-9433-cab8bd93f7c0.png)

**Comment by Mithion** [comment]
Version 1.0.2-pre1 fixes this issue.  Was related to server/client message handling.
