### ISSUE TITLE
Constructs ignore "Attack" command

### ISSUE THREAD

**Issue by groting** [Mithion/Mana-And-Artifice#1000]
**Describe the bug**

Constructs ignore attack command.

**To Reproduce**

1. Order construct to follow/guard.
2. Choose "Attack" command on bell wheel
3. Right click any entity
4. Nothing happens

**Expected behavior**

Construct starts attacking target entity. In Diagnostics menu you see corresponding message.

**Version Information (please complete the following information):**

 - Mod Version: 3.1.0.1
 - Forge Version: 47.3.11

**Additional context**

geckolib: 4.4.9
curios: 5.10.0

No additional mods are used.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
