### ISSUE TITLE
Name Tag Manaweave is listed as tier 1 but uses a T2 pattern

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#1003]
**Describe the bug**
The pattern used by the Name Tag manaweaving recipe is unusable at tier 1.

**Screenshots**
![image](https://github.com/user-attachments/assets/f6f73758-76fd-454e-af55-a9e65c8efe7d)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
