### ISSUE TITLE
Spell books in Curio slots don't work properly

### ISSUE THREAD

**Issue by Ghostofthemines** [Mithion/Mana-And-Artifice#1006]
Spells with shapes that require holding down the casting button (such as Fissure and Emanation) don't work when a spell books are placed in any curio slot but other spell shapes work just fine.

Forge: 47.3.10
Mod Version: 1.20.1-3.1.0.1

**Comment by Mithion** [comment]
This is intentional.  I originally didn't put a chat message with the intention of limiting chat spam, but it happens often enough that I have added one.  Channelled and bound spells won't function in curio slots.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
