### ISSUE TITLE
LegacyRandomSource (Involving Demon Armor)

### ISSUE THREAD

**Issue by jah83440** [Mithion/Mana-And-Artifice#1009]
**Describe the bug**
A crashing bug with the message "The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads"

**To Reproduce**
1. Get Infernal Armor (full set)
2. Equip Infernal Armor
3. Run around on the lava sea for a little while
4. Have particles set to "All"

**Expected behavior**
To not crash

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.3.0

**Additional context**
https://pastebin.com/EBQbxvUQ

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2

**Comment by Shibva** [comment]
This issue has reapeared for Deathcaps it seems; ill mkae a report when I can later
