### ISSUE TITLE
[Bug] Ritual of the Endless Void fails on dedicated server

### ISSUE THREAD

**Issue by zjdtmkhzt** [Mithion/Mana-And-Artifice#101]
I tried to perform the ritual of the endless void, but it seems to think that the ritual is not in darkness.

I have completely sealed the room, and f3 indicates 0 in the light columns on all positions in the room.
I tried it in SP, and it does work there. Maybe something with the fix for #71 did not work for multiplayer?

I will test this with just M&A on a locally running server soon when I have time.
Sorry if this turns out to be user error.

![image](https://user-images.githubusercontent.com/35579460/103168179-52855800-4831-11eb-9e78-0ee94bfebdfc.png)
![image](https://user-images.githubusercontent.com/35579460/103168181-587b3900-4831-11eb-8626-431865953442.png)
![image](https://user-images.githubusercontent.com/35579460/103168185-5e711a00-4831-11eb-9f49-83ce91accd33.png)
![image](https://user-images.githubusercontent.com/35579460/103168189-629d3780-4831-11eb-8255-215681eb24c3.png)

**Comment by zjdtmkhzt** [comment]
Oh, also, I read some recommendations on the discord to use a ritual bag, I did not have any luck with that either.
![image](https://user-images.githubusercontent.com/35579460/103168733-0f79b380-4836-11eb-9ded-966958894e64.png)

**Comment by Mithion** [comment]
This was fixed in 1.2.1.6 - endless void would check for no light in double its radius instead of within the bounds of its runes.
