### ISSUE TITLE
Difficulty jumping while under lava in Infernal Armor

### ISSUE THREAD

**Issue by jah83440** [Mithion/Mana-And-Artifice#1010]
**Describe the bug**
Jumping doesn't work while under the lava wearing the Infernal Armor. 

**To Reproduce**
1. Get Infernal Armor
2. Equip Armor
3. Get under lava
4. Attempt jumping

**Expected behavior**
Proper ability to move up and down while under lava.

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.3.0

**Additional context**
Having Pilgrim's Path alleviates some of the challenge, as does having sufficiently powerful cloudstep. Even with these however spamming the jump is necessary in practically every case to get out of the lava. It is also possible to rise by holding the shift key (not sure if intended or not), but overall without workaround enchantments it is very easy for a T5 Demon to get trapped in the lava sea.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
