### ISSUE TITLE
Boolean parameter in Activate Block to simulate sneak-clicking

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#1011]
**Is your feature request related to a problem? Please describe.**
Constructs being able to sneak click MagiChem multi state levers would greatly expand construct automation potential.

**Describe the solution you'd like**
A boolean parameter (false by default) that makes the construct activate the block while sneaking.

**Describe alternatives you've considered**
The player can queue up tasks on a multi-state lever "backwards" by sneak clicking, but you currently can't do "subtraction" operations if you're using multi state levers to store int variables.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
