### ISSUE TITLE
Ring of skies and Curio slot

### ISSUE THREAD

**Issue by Lord0fTurtles** [Mithion/Mana-And-Artifice#1015]
If you place the Ring of skies in the Curio slot, it's effects are not applied ( Fling damage immunity, extra air spell..ect)

**To Reproduce**
Simply put the item in the slot with the required minimum tier for it.

 - Mod Version: 3.1.0.1
 - Forge Version 1.20.1 Latest

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
