### ISSUE TITLE
Staff type items inconsistency with curio slots

### ISSUE THREAD

**Issue by Trejden** [Mithion/Mana-And-Artifice#1017]
**Describe the bug**
Angery Skull staff, Hellfire staff, Punkin staff, are missing curio slot assignment completely, which makes them unequipable into curio slots, staff of calling is set to be only equipable in back slot, while every other staff - generic or faction - are set to be equipable in back and spell slots.

**To Reproduce**
1. Get item Angery Skull staff, Hellfire staff, Punkin staff, staff of calling
2. Try to equip it in curio spell or curio back slot (only spell slot for staff of calling)
3. See that it does not equip

**Expected behavior**
I'd expect staff curio compability to follow some consistent rules on which staff is equipable where. Unless there is specific exception stated within codex on the relevant staff page, I think all staves should be equipable in both back and spell slots.

**Screenshots**
![image](https://github.com/user-attachments/assets/b824c292-5a31-43ca-8cc7-b435f245aeca)
![image](https://github.com/user-attachments/assets/4ba48ca6-716e-43a0-8a04-01d2d403e3c2)
![image](https://github.com/user-attachments/assets/9a41b89f-c834-432a-b87f-0c3355f104fb)
![image](https://github.com/user-attachments/assets/1db68cd8-479c-4b36-adeb-57b2ef45fa4b)
![image](https://github.com/user-attachments/assets/69974711-15e1-4375-970b-6d271096db9c)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version47.3.11

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
