### ISSUE TITLE
Eathern steppes ritual with practicioners pouch duplicates book of shifting lands

### ISSUE THREAD

**Issue by ShelLuser** [Mithion/Mana-And-Artifice#1020]
**My environment**

Forge 47.3.0 (Minecraft 1.20.1).
MNA 3.1.0.1

I've tested this on multiplayer (= private LAN server) as well as singleplayer.

**The issue**

When you perform the ritual of the Earthen steppes using the practitioners pouch then the book of the shifting lands is never removed from its inventory. But it _is_ placed in the world, the ritual starts and the book remains there ready for you to pick it up. You now have 2 books.

**How to reproduce**

- Set up the ritual of the Earthern steppes.
- Copy the ritual using the practitioners pouch.
- Add the wizzards chalk, purified vinteum dust, book of the shifting lands and an iron pick + shovel to the pouch.
- Perform the ritual.

Here's a screenshot showing the issue:

![steppes](https://github.com/user-attachments/assets/7429c628-b1e2-4894-8a74-bfad7e7b8bb8)

What you're looking at: I asked my friend Aya to perform the ritual (she's in survival while I'm normally in creative). I gave her 2 iron pickaxes and 2 iron shovels (one set for the ritual, the other as a means of thank you). As you can see the ritual is going on in the background, one set of items have been consumed but the book is still here.

After this ritual Aya now has one book still in the pouch, and a new one in her inventory.

Hope this can help!

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
