### ISSUE TITLE
Structure Crash

### ISSUE THREAD

**Issue by dheivs** [Mithion/Mana-And-Artifice#1021]
**Describe the bug**
It happens around 60% of the time for me. Whenever I go to near or just pass by a this abandoned house like this from your mod, it just crashes.

**To Reproduce**
1. Get close to the structure that has two Blast Furnaces inside it.
2. Then I get a crash. Log is [here](https://pastebin.com/zNpX73ZR).

**Expected behavior**
Usually I go inside that house to get the codex so I can start playing the mod or get some staves so I can learn other faction spells. But now, I can't play the game if I go close to this structure.

**Screenshots**
![image](https://github.com/user-attachments/assets/4e56fa9e-904d-42c4-932e-cbea5c2d9b65)

**Version Information (please complete the following information):**
 - Mod Version: [mna-forge-1.20.1-3.1.0.1-all]
 - Forge Version [1.20.1]

**Additional context**
Once more, here is the crash log: https://pastebin.com/zNpX73ZR

**Comment by Mithion** [comment]
Looks like a problem with FerriteCore/Quark/Sodium/Lithium, not M&A (It isn't even mentioned in the crash log).

Seems like they're trying to simplify block state cache updates and in doing so inadvertently deleting what is a valid state.  You'll need to report it to them.

**Comment by dheivs** [comment]
Thank you!
