### ISSUE TITLE
crashes once pressed play from launcher

### ISSUE THREAD

**Issue by fmaflow** [Mithion/Mana-And-Artifice#1023]
when i press play from launcher it begins to load the mod then fails and gives me this error 
The game crashed whilst stitching
Error: net.minecraft.client.renderer.texture.StitcherException: Unable to fit: mna:entity/lightning_ring - size: 1024x1024 - Maybe try a lower resolution resourcepack?

im using minecraft 1.20.1

**Comment by Mithion** [comment]
There's a lower res portal texture addon here:
https://discord.com/channels/398610095585624074/1265096693314224249
