### ISSUE TITLE
Bound spell doesn't return on drop

### ISSUE THREAD

**Issue by FabioRibeiro404** [Mithion/Mana-And-Artifice#1025]
**Describe the bug**
I crafted a bound sword spell and I use it turned into a sword like was intended, but when I dropped the sword to get the spell back it stayed has a sword

**To Reproduce**
1. Use Bound Sword spell
2. Drop sword
3. Stayed has a sword

**Expected behavior**
It was suppose to turn into a spell again

**Screenshots**
![image](https://github.com/user-attachments/assets/c2843b31-b13b-493a-af3d-0dbf62ef2051)

![image](https://github.com/user-attachments/assets/f4beb405-4b27-4c31-8cda-9c22b45b657e)

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.1.0.1-all
 - Forge Version 47.3.0

**Comment by ShelLuser** [comment]
This doesn't happen on my end so I can only assume that another mod is getting in the way here. Are there any specific messages in your logs which hint at possible issues? I also couldn't help but notice that all the items in your hotbar suddenly 'greyed out' while the sword was active, that's also a bit odd. 

Finally: what component did you use (the second part of the spell)?  That will make it easier to try and fully reproduce your issue.

**Comment by FabioRibeiro404** [comment]
I used frost damage and damage but I guess it's something messing with the mod
