### ISSUE TITLE
Spell Book Shear spell in curio slot deletes constructs in gantry 

### ISSUE THREAD

**Issue by frostedwolf1** [Mithion/Mana-And-Artifice#1031]
**Describe the bug**
Was using a earth spell to use for the gantry and i had my shear spell in a spell book in my spell curio spot, It deleted the parts.

**To Reproduce**
1. Get item 'Touch+Shear spell, Spell book, Set in spell curio spot'
2. Use on 'Constructs in gantry'
3. Have magic level '2'
4.N/A

**Expected behavior**
I expected to get the item back normally

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [3.1.0.1
 - Forge Version [47.3.0
**Additional context**
N/A

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
