### ISSUE TITLE
Staff of the Woodlands doesnt render properly

### ISSUE THREAD

**Issue by BriarThorn94** [Mithion/Mana-And-Artifice#1032]
**Describe the bug**
When equipping the Staff of the Woodlands, it does not render in any curios slot that its able to be equipped to. 

**To Reproduce**
1. Get The staff of the Woodlands
2. Equip in any curios slot
3. See that it does not render on the player

**Expected behavior**
Expected behavior is that it would render like any other staff

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 1.20.1

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
