### ISSUE TITLE
Arms on Double-Caster Constructs Switch Sides when Unloaded

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#1034]
**Describe the bug**
If you have a construct with two caster arms, what side each arm is on will randomly switch sides when the construct unloads and reloads.

**To Reproduce**
1. Create a caster construct with different spells on each arm.
2. Create a program that casts the left arm spell on a particular block
3. Leave the area and let the construct unload
4. Come back to the operating area
5. Check what spell the construct is using
6. Repeat a couple times, see that it will flip occasionally

**Expected behavior**
The left arm and right arm spells remain consistent

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1

**Additional context**
This happened on a server

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
