### ISSUE TITLE
Wakebloom staff can't have bound spells; wakebloom wand has duplicate spellbinding recipe

### ISSUE THREAD

**Issue by Fredhoof** [Mithion/Mana-And-Artifice#1035]
**Describe the bug**
[This is a _two part_ bug]
The wakebloom staff does not have a manaweaving recipe to bind a spell to it, while the wakebloom wand has two (identical) manaweaving recipes to bind a spell to it.

**To Reproduce**
PART A: Wakebloom _staff_:
1. Add a wakebloom staff and a magic spell to an empty manaweaving altar.
2. Manaweave the Orbeus shape.
3. No reaction occurs.

PART B1: Wakebloom _wand_:
1. Add a wakebloom wand and a magic spell to an empty manaweaving altar.
2. Manaweave the Orbeus shape.
3. The magic spell binds to the wand, as per normal manaweaving altar animation.

PART B2: Viewing recipes via JEI:
1. Open inventory.
2. Locate the wakebloom staff and wakebloom wand.
3. Left-click each to see which recipes _output_ their respective items, using the manaweaving altar tab to see which recipe(s) use that crafting station; note the respective number of recipes, and cycle through to see which ones they are.
5. Right-click each to see which recipes _input_ their respective items, using the manaweaving altar tab to see which recipe(s) use that crafting station; note the respective number of recipes, and cycle through to see which ones they are.
6. For comparison, repeat steps 3 & 4 with any other staff/wand pair of a different material.

**Expected behavior**
PART A: The magic spell should bind to the wakebloom staff.
PART B1: The magic spell should bind to the wakebloom wand.  **This works as expected.**
PART B2: The wakebloom _staff_ should have 1 output recipe at the manaweaving altar (spell binding), and 13 input recipes at the manaweaving altar (spell binding, staff of calling, staff of the pilgrim, wood/bone/stone/iron/gold caster arms (in both left and right versions)).  The wakebloom _wand_ should have 1 output recipe at the manaweaving altar (spell binding), and 1 input recipe at the manaweaving altar (spell binding).

**Screenshots**
Wakebloom staff manaweaving output (with cerublossom staff to show what's missing):
![wakebloom staff output](https://github.com/user-attachments/assets/fc1eece3-43fe-451f-ba1e-9024f7dd5414)
Wakebloom staff manaweaving inputs (with cerublossom staff to show what's missing):
![wakebloom staff input](https://github.com/user-attachments/assets/24180d03-75eb-48b1-a09d-eb63f4fc0255)
Wakebloom wand manaweaving outputs:
![wakebloom wand output](https://github.com/user-attachments/assets/c13ae5d1-96fc-4e04-b005-1a7243c81d57)
Wakebloom wand manaweaving inputs:
![wakebloom wand input](https://github.com/user-attachments/assets/3137386c-8090-4266-98e8-9cf8e7b1491c)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.3.0
 - Just Enough Items 15.20.0.105

**Additional context**
As the wand part of the bug is an identical twin recipe, I probably would not have noticed it if I hadn't been using JEI.  Given that the wakebloom _wand_ has **two** spell-binding recipes while the wakebloom _staff_ has **none**, I suspected that one of the wand's recipes was supposed to have been the recipe for the staff, but there was some variety of naming error in play; as a result, I am treating the two issues as a single compound bug for reporting purposes.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
