### ISSUE TITLE
Swift Swim doesn't Scale

### ISSUE THREAD

**Issue by Red1004** [Mithion/Mana-And-Artifice#1037]
**Describe the bug**
Because Dolphin's Grace is used for the Swift Swim spell effect, it doesn't receive any benefit above level 1.

**To Reproduce**
1. Get Swift Swim with the magnitude modifier
2. Cast on yourself when it's at level one
3. Swim
4. Cast on yourself when it's on a higher level
5. See no changes to swim speed

**Expected behavior**
Either increased swim speed (probably achieved using a custom effect), or no magnitude modifier.

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version: 47.3.0

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
