### ISSUE TITLE
Loot wands/staves and torn journal pages are unsortable with constructs

### ISSUE THREAD

**Issue by BriarThorn94** [Mithion/Mana-And-Artifice#1038]
**Describe the bug**
Constructs wont sort loot wand and staves or torn journal pages whether

**To Reproduce**
1. Have constructs adventure untill they bring back a loot wand or staff or a torn journal page.
2. Have them try to sort the wand/staff/torn journal page

**Expected behavior**
The item is put into the respective chests

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 1.20.1

**Comment by Mithion** [comment]
Sorting takes into account NBT data on the items; technically the staves differ in their data. 
 Plus, they're different items - a wakebloom staff vs a vinteum staff vs an aum wand, etc.

This is not a bug, it's working as intended.  Sorting cannot be done by tags.

I recommend you use the conditions and create a ledger with the staves in it (and match NBT turned off), instructing them to put matching items into a chest before the main sort happens, cascading to the main sort loop if the condition "fails" (aka doesn't match).
