### ISSUE TITLE
Particle effects of staffs don't originate at staff itself

### ISSUE THREAD

**Issue by JNoppers** [Mithion/Mana-And-Artifice#105]
As the title suggests, particle effects of a staff do not originate at the staff itself, but from the player hand. This makes that the player can't see the own particle effects either. Unsure if this is intended.

![afbeelding](https://user-images.githubusercontent.com/43132310/103373368-03f7e800-4ad5-11eb-8c44-744d4b49aa2e.png)

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
