### ISSUE TITLE
Construct plant_scan failing

### ISSUE THREAD

**Issue by leotheshade** [Mithion/Mana-And-Artifice#107]
When a construct is given the 'plant' instruction, the construct becomes frozen, as it cannot detect soil in the specified area- even when there is soil present. Using the diagnostic rod, I am given 'mana-and-artifice.constructs.feedback.plant_scan_starting', followed by 'I can't plant right now, I don't have any seeds in my hand. Sorry boss.'(even when he has seeds), and 'I can't find any soil blocks in the area you specified. Sorry boss.'

**Comment by Mithion** [comment]
The Runes of Marking bounding box creating has been improved, and constructs now plant things from the Forge **seeds** and **crops** tags, which should greatly improve interop and usability.
