### ISSUE TITLE
[1.16.4] Impossible to make Ritual of Forgotten Lore with Update Aquatic installed

### ISSUE THREAD

**Issue by drakray** [Mithion/Mana-And-Artifice#108]
As seen with https://github.com/team-abnormals/upgrade-aquatic/blob/main/src/main/java/com/minecraftabnormals/upgrade_aquatic/core/events/EntityEvents.java , they make the Inc Sac project blindness on right-click, which make it impossible to use in the ritual.

There should probably be a check on their side too, as it's not possible to open a chest with the sac in hand

**Comment by drakray** [comment]
reported there https://github.com/team-abnormals/upgrade-aquatic/issues/229

**Comment by Mithion** [comment]
This is an issue with Update Aquatic - they'll need to fix their override to cause the item to attempt to interact with blocks using the onItemUseFirst function.  I just recently had to do something similar for spell books.
