### ISSUE TITLE
rune pattern either undocumented or hard to find

### ISSUE THREAD

**Issue by seebs** [Mithion/Mana-And-Artifice#111]
JEI can't tell me how to make rune pattern scraps, and if the answer is in the Codex, I've not found it yet. I've checked in all the obvious places like the description of runesmithing, descriptions of constructs, and so on, I think? Unless I missed one. But I've looked around a lot for it, and tried various experiments like "what if I tried to combine a rune pattern with vellum". I'd just look up the source but I haven't got source. :)

**Comment by ewsmith** [comment]
it is documented very little, but they come from villagers. the workstations are the runesmithing table and the manaweaving altar.

**Comment by Mithion** [comment]
The codex has an entry on Villagers, but I've split that into 2 entries: one for the Manaweaver Villager and one for the Ritualist Villager.  Each entry specifically references the Manaweaving Recipe Scraps or the Runescribing Recipe Scraps to make searching more accurate.

JEI integration is planned, but not implemented yet.
