### ISSUE TITLE
Crash with ritual of return

### ISSUE THREAD

**Issue by groting** [Mithion/Mana-And-Artifice#112]
Got crash when perform ritual of return. Rune pattern yellow-red-yellow-red-yellow-red-yellow-red.

M&A version: 1.2.1.6

[crash-2021-01-06_15.45.13-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/5775831/crash-2021-01-06_15.45.13-server.txt)

**Comment by Mithion** [comment]
Sorry about that.  Added some extra null checks into the ritual of return so it should be more stable and fail gracefully.
