### ISSUE TITLE
Imps and Lantern Wraiths seem to be lacking AI

### ISSUE THREAD

**Issue by lamoyrl90** [Mithion/Mana-And-Artifice#114]
DW20 pack,
updated to Mana and Artifice 1.2.1.6

I found one of the Nether castle things, with spawners for Imps and Lantern Wraiths, but they don't seem to have any AI attached to them. They don't wander, look around, or react when you attack them. Makes a nice blaze powder farm but I don't think it's intended behavior :)

*edit* Well, I updated the pack and the Wraiths attack me back now. The imps still seem braindead, though.

**Comment by Mithion** [comment]
Fixed the imps, they were missing the task to retaliate
