### ISSUE TITLE
Many items don't have their respective tags

### ISSUE THREAD

**Issue by BetaCarotina** [Mithion/Mana-And-Artifice#115]
Materials don't have their respective forge tags. For example, forge:ores/vinteum, forge:gems/chimerite or forge:dusts/purified_vinteum.  If you are worried that some mods may add a recipe that allows any dust to be automatically smelted into its ingot (thus skipping Vinteum Coated Iron), you can add a separate tag for vinteum ingot (e.g forge:ingots/vinteum_alloy). Don't forget to add these tags to their respective recipes.

Also, flowers don't have the minecraft:small_flowers or minecraft:tall_flowers tags.

**Comment by Mithion** [comment]
All of these tags have been added.  Thanks!  I wasn't too familiar with tags prior so this helped.
