### ISSUE TITLE
The HUD makes every entity or block entity go dark in some locations.

### ISSUE THREAD

**Issue by Tuagabr** [Mithion/Mana-And-Artifice#116]
Near the spawn, there is almost no problem, but apparently the further I go, it happens more frequently, andit appears to be the hud causing the problem because when its turned off the game goes as normal, and when its on, it makes entities, block entities and items in inventory go dark in certain regions of the map. I'm on forge 35.1.13 and without optifine.

**Comment by Mithion** [comment]
Are you using Xaero's minimap by chance?

**Comment by Tuagabr** [comment]
I'm using Xaeri's minimap, Xaero's worldmap and more 32, excluding the already cited mana and artifice and counting all the api's. The modlist is:
Apotheosis
AppleSkin
Ars noveau
Astral sorcery
Biomes o' plenty
Botania
Clumps
Curios
Flux networks
Forbidden and arcanus
Geckolib
Hwyla
Jei
Mana and artifice
Mcjtylib
Mekanism
Mekanism tools
Mekanism generators
Observerlib
Patchouli
Placebo
Randompatches
Rftoolsbase
Silent gear
SilentGems
Silentlib
Silent mechanisms
U team core
Useful backpacks
Waystones
Xaeros minimap 
Xaeros worldmap
Xnet

**Comment by Mithion** [comment]
This is being tracked as well in #116 and there has been a possible solution suggested.  I'm going to try it and see if it solves the issue.
