### ISSUE TITLE
Ritual of Summoning and Ritual of Visiting not recognizing Bound Charm Target

### ISSUE THREAD

**Issue by Shadowfire86** [Mithion/Mana-And-Artifice#117]
Had a friend Bind a charm (is bound) and used the charm with a ritual kit. Ritual of Visiting just drops me back like 3 blocks, and the Ritual of Summoning says the player is either offline or does not exist. Player IS online, does exist, double checked the charm, it IS bound to his character. Edited: Works fine when cast manually but when using a ritual Kit the above issue happens.

**Comment by Mithion** [comment]
This has been fixed in dev, and will go out with version 14.0.0.
