### ISSUE TITLE
Using an unbound World charm in Ritual of the gate causes a NPE hard crash 

### ISSUE THREAD

**Issue by KingOnoi** [Mithion/Mana-And-Artifice#118]
Tested with pulling a world charm out of JEI in inventory screen, forgot to bind the world charm and used it in ritual of the gate. Upon doing so the ritual activates and a short time later the whole instance of Minecraft crashes. Crash log returns a NPE or Null Point Exception error.

**Comment by Mithion** [comment]
Fixed in 1.2.1.9
