### ISSUE TITLE
FPS issues with mage lights

### ISSUE THREAD

**Issue by KrAzYGEEK32** [Mithion/Mana-And-Artifice#119]
mod: 1.2.1.6
forge: 35.1.36

issue:
having huge fps issues due to the mage lights, my fps is down to 20 from a constant 60.
reporting here because i ran a spark profile, and as far as i can understand it, most lag comes from those lights.
here is the link https://spark.lucko.me/#BQjnStDomx

ill be happy to provide any further assistance regarding this issue.

**Comment by Mithion** [comment]
Added a config option in 1.2.1.9 which will enable more FPS-friendly magelights.
