### ISSUE TITLE
Chimerite Ore

### ISSUE THREAD

**Issue by CCheek** [Mithion/Mana-And-Artifice#12]
1. Seems to work with an iron pick, but doesn't, which is to say, please set up oneprobe/waila integration.
2. **The block drops as an ore, with no furnace recipe (or any at all for that matter), therefore Chimerite Gems are unobtainable.**

**Comment by Mithion** [comment]
Resolved in 1.0.1-pre1 (drops).  Chimerite requires diamond tools.
