### ISSUE TITLE
Add option to disable Raids

### ISSUE THREAD

**Issue by toruPuchuu** [Mithion/Mana-And-Artifice#120]
Please add an option to disable Raids.

**Comment by Mithion** [comment]
Already exists, there's an entire section in the config for faction raids.

**Comment by VorpalLemur** [comment]
I've set the following in the config and just got raided:
     raidSpawnAttempts = 1
     raidBaselineIncrease = 0.0
     raidTierIncrease = 0.0

which are all the minimum values according to the comments.  I don't see anything on how to completely disable raids absolutely and I'm about to rip this bloody mod out of my server.   The raid mechanic, or "jump scare" mechanic as I've come to call it, has nearly entirely killed the love and joy I found when I first explored this otherwise excellent mod.

**Comment by Mithion** [comment]
Based on the math, it's *technically* still possible if Math.random() generates 0 exactly, but those config settings make it extremely unlikely.

I would suggest any one of the following 6 options:

1. Look into enchanting up some armor and/or making an eldritch orb (and enchanting that).  I've had both ends of this debate, some say they're too easy, some say they're too hard.  Prot armor takes their damage down to negligible, and the eldritch orb can keep several enemies off of you while you deal with them.  Shielding spells also greatly reduce damage taken.

2. Make warding candles.  Once lit, they prevent raids (and all mob spawns) within a 32x32x32 block radius.  They can be extinguished for when you do want mob spawns.  It'll still play the sound of them spawning but no enemies will appear.

3. Look for a mod that can prevent certain mobs from spawning, and add the faction raid mobs to it.  It's likely that one exists somewhere.

4. Use the command /setFaction NONE to clear your faction.  This will however lock you out of faction-specific spells, though you'd still be able to use the artifacts if you already create them.

5. Play on peaceful.  Disables raids completely.

6. Remove the mod.  It's not for everyone, and while I like the fact that I can share it with the community, I'm making it for me and how I view a magical world.  And I view it as dangerous, requiring preparation and skill.  But I know I can't please everyone and so I'll offer suggestions but if it doesn't work out then no hard feelings.
