### ISSUE TITLE
Mana and Artifice (mana-and-artifice) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by Knoopp** [Mithion/Mana-And-Artifice#121]
I've been getting this error while trying to start up Minecraft, I've tried forge 1.16.4-35.1.13 (which is the lowest i can go, other mods need 1.13 or higher) 35.1.35 and 35.1.36 (.36 gave the same error, but also for Create). I've tried with both 1.2.1.8 and 1.2.1.6 versions of Mana and Artifice. The same error appears on my sisters mac. 

my latest.log from forge 35.1.35
https://pastebin.pl/view/142c3b01

**Comment by Mithion** [comment]
M&A is built against Forge 35.1.1 - you'll need to wait until I build it against a higher forge version.
