### ISSUE TITLE
Bug Constructs Runefoging - duped items and no rune update

### ISSUE THREAD

**Issue by DevilSushi** [Mithion/Mana-And-Artifice#124]
Mod Version: 1.2.1.8
Forge Version: 35.1.10 and 35.1.36

So I automated the forging of runes like the sample tells you to, but my construct wouldn't put a metal rune into my output chest.
When looking into what happened I saw him take out 1 Vinteum Ingot and place 2 into the runeforge, but only one was in there.
It also took 1 blank rune pattern and put it into the runescribing table, but held onto another one.
After finishing the runescribing it can't forge the rune, because the rune is still a blank pattern containing the metal rune. There seems to be an update missing to go from the blank to the metal rune.
When I stopped the construct using the Control Rod it dropped two of the held item, while it only took one out of the chest.

My Construct:
I tested it with a constuct completely made of stone with 8 air elements and later with 8 earth elements.

**Comment by Mithion** [comment]
Fixed in 1.2.1.9
