### ISSUE TITLE
Spell Modifiers Don't Modify the Spell  

### ISSUE THREAD

**Issue by Tuagabr** [Mithion/Mana-And-Artifice#125]
I'm on tier 3 and adding modifiers to the spell doesn't modify the spell attributes or its complexity, just adding cost to the crafting. I'm on forge 35.1.36 and I have 34 more mods with it.

**Comment by flarn2006** [comment]
Can confirm on 1.4.0.8, FTB University modpack version 1.3.0, 1.16.5-forge-36.2.4. The numbers aren't affected, and an attack spell that took 4 hits to kill a zombie remained that way after upgrading Damage via the Ritual of Alteration.

**Comment by flarn2006** [comment]
Never mind; I figured out what the problem was: I was using modifiers incorrectly. Now I understand why this was closed. See #377.
