### ISSUE TITLE
Spectral Elytra compatibility with Occultism "Flight-Assistant" Familiar.

### ISSUE THREAD

**Issue by klikli-dev** [Mithion/Mana-And-Artifice#126]
I got a bug report on my end that my familiar prevents the Spectral Elytra from engaging flight mode (https://github.com/klikli-dev/occultism/issues/103).

My familiar gives players the vanilla slow falling and jump boost effects, as well as a double jump capability.
Do you have an idea which of the three causes the issue & what each of us can do to get it out of the way?

**Comment by najlitarvan** [comment]
i think the multi jump dos it since it tries to activate but then instantly fails

**Comment by klikli-dev** [comment]
The double jump is relatively "mundane" in that it listens for the jump key binding to be down, but does not cancel the input event. That means, even if an additional jump somehow cancels the effect, after double jump is used up it should work

**Comment by Mithion** [comment]
The spectral elytra doesn't have any kind of mixins, it just implements the capability from Forge that allows an item to function as an elytra.  I do my own double jump using a ring that as far as I'm aware doesn't have this issue - how does your double jump work in this case?  I don't think slow falling or jump boost would do that, so I'm also gravitating towards the double jump implementation as well.

**Comment by klikli-dev** [comment]
@Mithion thanks for looking into it! My double jump is pretty mundane - it just conditionally calls player.jump() if the player presses jump key while in air.
That said, I am *not* calling jump if vanilla elytra is used. Is your elytra per chance tagged, or identifiable in any other way? 
I could add that to my conditions and have a quickfix. 
Otherwise: If you lmk your item id I can just add a compat tag on my end

**Comment by Mithion** [comment]
It's not tagged, though I can do that if it would help.  Could also check the chest item's isElytraFlyable() or something (not in front of the code atm, but it's on either Item or ArmorItem), and bypass jump based on that too.  That might be a more flexible way in general than trying to maintain a blacklist :)

The jump call will likely reset a timer used by the elytra to determine when to start flying.

**Comment by klikli-dev** [comment]
My latest build contains an experimental fix (for now based on a tag - but the mentioned property might be better as you said) and that seems to work based on a simple test with just our two mods, but I'll need to await verifications from those that reported it to be sure :)

**Comment by Mithion** [comment]
Haven't heard anything on this one; so going to close it for now.  LMK if it's still an issue and can reopen.
