### ISSUE TITLE
Village structures bug

### ISSUE THREAD

**Issue by DEX47** [Mithion/Mana-And-Artifice#128]
It appears some village structures are generated with some minor flooding issues.

![2021-01-16_16 59 20](https://user-images.githubusercontent.com/8147134/104825093-4895ba00-581d-11eb-868f-30c8e34ee4d2.png)
![2021-01-15_00 36 41](https://user-images.githubusercontent.com/8147134/104825096-4f243180-581d-11eb-9ed1-8f1629f84d38.png)

**Comment by DEX47** [comment]
Ars Magica 2 was my absolute all time favorite mod. I had to play Mana-And-Artifice when I got back into Minecraft. I'm currently running a modpack with about 150 mods. I'll pick it apart to see if this is a result of

**Comment by DEX47** [comment]
Just made a stand alone Vanilla+ Mana and Artifice build. Issue is native.

**Comment by 5kedone** [comment]
I too have had this issue for a while 



world gen structures and also a few of the blocks become or are spawn water logged its very odd
bellow is a screen shot of said error

https://ibb.co/Qbpp1hW

**Comment by iobiarg** [comment]
Same happening to me

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
