### ISSUE TITLE
[Bug] Ritual kit and fast ritual kit can consume themselves

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#13]
**Description:**
As far as ive been able to see, grimoire, rune pouch, ritual kit, and fast ritual kit, are immune to duping contents, however, since ritual kit and fast ritual kit can contain any item, and you cant move other container items if one is already open, if you use number key slot swapping to put any of the other containers into a ritual kit, it can no longer be removed, and swapping the open kit into itself deletes it.
(edit): none of them can be opened from offhand either, not sure if thats just how it works or if thats actually a problem

**To Reproduce:**
1.) open ritual kit
2.) using number keys, swap another container from hotbar into kit
3.) if container swapped is the currently open kit, inventory immediately closes and kit is deleted

**Demonstrated:**
![AM3Pouch](https://user-images.githubusercontent.com/33331567/84577913-55859300-ad8e-11ea-891c-0a829fff77b8.gif)

**Comment by Mithion** [comment]
Resolved in 1.0.1-pre1
