### ISSUE TITLE
Golem pathfinding and block facing

### ISSUE THREAD

**Issue by Karthas077** [Mithion/Mana-And-Artifice#130]
Golems using "Take item" on the west face of a chest while the east face is obstructed attempt to access the west face from above instead of from the west. Removing the block behind the chest causes them to path to the marked side and withdraw the items normally.

I have not tested every face combination but accessing from the south while the north is obstructed still behaves normally.

**Comment by Mithion** [comment]
Construct physical position doesn't matter when accessing containers; it's purely based on a "close enough to the block" and "what the rune of marking says".

**Comment by Karthas077** [comment]
So... it's intentional that adding a block that isn't even in the way will cause golems to pathfind up a cliff and around to reach the top instead of just walking to the not at all obstructed location they will stand when the extra block isn't there?

**Comment by Mithion** [comment]
Yep, that's vanilla pathing for you.
