### ISSUE TITLE
Explosion Spell + Hellfire Staff

### ISSUE THREAD

**Issue by SPYROHAWK** [Mithion/Mana-And-Artifice#131]
I'm not quite sure if this is a bug or intentional behavior, but there's a strange interaction here. Or, well, I guess the better description is no interaction at all. As of writing this I am using the current version of the mod, which should be 1.2.1.9. 

As you know (well, of course you know, you made the mod, I'm just reiterating for the sake of framing the issue) the Hellfire Staff is an item that can only be crafted by the demon faction. When fire spells are cast through it, it turns into green Hellfire instead (not entirely sure what the difference is, I'm assuming increased damage). The explosion spell is also a demon faction-specific thing, being a spell that creates a big explosion. The explosion also happens to create fire.

Weirdly, when the explosion spell is cast through the staff, the fire produced from the explosion isn't turned to hellfire.

I'm not sure if this is intended behavior and only the actual Fire Damage spell turns to hellfire (which I checked, it works, so it's not an issue with the staff in general or my modpack), or if this is a bug and all fire produced by spells from it are meant to turn to hellfire.

I was testing it using the Smite spell shape, if that makes any difference?

---

Also, unrelated bug, but I felt weird making two bug reports back-to-back. Some spells cannot be used with specific spell shapes, like Lifetap and Beam for example. But I noticed some I think can be used with spell shapes but don't have any effect.

Specifically, I put Nethergate on both Bolt and Beam to try to get it to apply to other entities, but it didn't work. I mean, it let me make the spell, but shooting the Bolt at a mob didn't send it to the Nether. However, using it with a range of Self still worked.

Another example I know I tried is using Earthsky or whatever it's called that lifts blocks into the air with the Eminence shape. I expected all the blocks around me to be affected by it and lifted into the air, but nope. Particle effect happened, but no effect (it works on Bolt though). 

I'm not entirely sure why some spells can't be used with specific shapes, which seems to be the indicator that the shape + spell combo won't work, yet others can't be used together but still don't work.

**Comment by Mithion** [comment]
Explosion creates an entity, which in turn creates fire - since I'm using the vanilla entity, it creates vanilla fire as it's unaware of hellfire.  

Please in the future do create multiple issues, it's better for tracking and tagging.

Nethergate only works on self for the moment; but the notification system isn't advanced enough to limit by that criteria alone.  Without that limitation it was way too open to griefing other players.

Earthsky should work on emanation, but remember for emanation to affect blocks below you, you need to sneak.  Otherwise it targets horizontally only.
