### ISSUE TITLE
Collapse and Earthsky spells don't change blockstates based on the block's new position

### ISSUE THREAD

**Issue by chandler05** [Mithion/Mana-And-Artifice#133]
Blocks such as fences have separate blockstates for connecting to blocks. When using earthsky or collapse on these blocks, the blockstate remains the same as it was before, and does not reset or attach to new blocks from the new positions, resulting in floating blocks with strange connections as seen in the picture.
![2021-01-18_21 07 13](https://user-images.githubusercontent.com/66492208/104983216-f5189d00-59d1-11eb-9965-eeed719a2e0e.png)

**Comment by Mithion** [comment]
Closing this as intentional, as everything I tried caused the blocks to void instead of correcting their state based on the new location.  Would rather have strange fences than block losses.
