### ISSUE TITLE
Ritual of the Ancient Council mistitled as Ritual of the Wizard's Council in the codex

### ISSUE THREAD

**Issue by chandler05** [Mithion/Mana-And-Artifice#134]
Very easy to misunderstand as a beginner, as I did, but the Ritual of the Ancient Council is mistitled as Ritual of the Wizard's Council  in its codex entry. However, it is properly named in the depiction of the setup for the ritual and everywhere else I have seen it, such as the Occulus.

**Comment by Mithion** [comment]
1.3.0.0 fixed this issue
