### ISSUE TITLE
Manaweaving shapes

### ISSUE THREAD

**Issue by JustJinxed** [Mithion/Mana-And-Artifice#138]
Just going to say this, thank goodness there's projectors, but triangles especially are not being recognized very well when using the mana weaving wand. 

out of 120 cases now, I've gotten only about 10% recognized.
I love this mechanic, but even drawing this figure in multiple sizes, it doesn't seem consistant.

**Comment by JustJinxed** [comment]
even worse, the diamond shape.. 
https://imgur.com/a/BhPbWON

**Comment by VorpalLemur** [comment]
I was struggling with this a lot.   I've since found I'm able to get vastly higher recognition rates if I be sure to pause at every corner of the shape I'm drawing for like half a second.   Just my two cents

**Comment by Mithion** [comment]
Manaweaving shapes are very much based on player skill, and that was my goal when creating the system.  
I'm able to get ~95% correct recognition while playing.

I do recognize that the manaweave patterns for the projectors are too difficult and tedious to get currently, though, and will be improving that aspect in future releases.

**Comment by smooze** [comment]
im sorry, but this is entirely too exactingly accurate to even play, anything other than the octagon refuses to recognize. I would like to know how this is not a triangle.
![javaw_2021-02-15_02-23-02](https://user-images.githubusercontent.com/4827696/107916787-e5d73180-6f34-11eb-966b-efafcf99c102.png)

**Comment by smooze** [comment]
but this is a square i call bs on the so-called "high accuracy"
![javaw_2021-02-15_02-26-00](https://user-images.githubusercontent.com/4827696/107917038-4c5c4f80-6f35-11eb-9554-f3d9021a721b.png)

**Comment by Mithion** [comment]
Call BS all you want, it's still based on player skill.  Git gud :P

Jokes aside, try this version I just uploaded which has a rewritten recognition engine with *much* better accuracy, tolerance, and efficiency:
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3205693
