### ISSUE TITLE
[Bug] another thing with ritual kits

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#14]
**Description:** 
Ritual kit and fast Ritual kit have more inventory slots than graphically suggested

**Demonstration:**
![image](https://user-images.githubusercontent.com/33331567/84578095-1b1cf580-ad90-11ea-94eb-89662e997ee1.png)

**Comment by Mithion** [comment]
Resolved in 1.0.1-pre1
