### ISSUE TITLE
Construct has gone rogue.  Refuses to listen to commands.

### ISSUE THREAD

**Issue by VorpalLemur** [Mithion/Mana-And-Artifice#140]
Version 1.2.1.9

I am using the direwolf20 1.6.4 modpack in singleplayer

I have a construct which is currently bound to a lodestar making runes for me.   Until now it's been working fine.

I just created a new construct and I used my control rod to successfully order it to stand still in the middle of the room.   However my original construct now refuses to listen to commands from me.   If I try to order it to do something (stop making runes for instance), nothing happens.  If I use the Construct Diagnostic Rod, I see the message "VorpalLemur tried to tell me to do something, but I don't have to listen to them."   It'll stop work making runes if I apply a redstone signal to the lodestar, so I can control it in that fashion, but I can't take it off the lodestar its on and put my new, faster construct on the same task, for instance.

I can't tell if this is a bug or intended behavior.   I really don't want to have to kill the guy considering how time consuming they are to make.

**Comment by VorpalLemur** [comment]
UPDATE:  quitting out to menu and reloading the game has fixed the issue.  I'm now able to control both constructs, suggesting this is indeed a bug.

**Comment by MacChuck** [comment]
Just ran into the same issue on a Direwolf20 1.16.4 server. No idea if re-logging or restarting the server fixes it, I just killed the construct and made a new one.

**Comment by Mithion** [comment]
Restarting servers should fix the issue in the interim, but I'll make sure it's fixed for next version.

**Comment by Mithion** [comment]
This was fixed in 1.3.0.0+
