### ISSUE TITLE
Crude Wand (feature request)

### ISSUE THREAD

**Issue by 12foo** [Mithion/Mana-And-Artifice#141]
Hello there,

I'm currently playing a very small pack that basically only has Create and Mana and Artifice. I'm enjoying the mod very much-- I was looking forward to it, but it's even better than I thought! So thank you for that. I don't know if you're taking feature requests, but one thing that (I feel) would make it even better in a pack without any other mods is one-time access to cantrips without carrying a manaweaving wand at all times, e.g. to call my grimoire or a cantripped Rift spell out in the wilderness (or after dying without a bed...), or just as an emergency firestarter.

Something like (Stick + magical plant) = crude wand that only works for one cantrip. Lore-wise, perhaps it's something like you have to be a certain tier or magic level to make do with such crude materials, and forcing the mana through this hasty construction destroys the wand after one use.

In any case, thanks very much for the mod!

**Comment by Mithion** [comment]
That's a really cool idea, I like it!

**Comment by Mithion** [comment]
Added in 1.3.0.1
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3205693
