### ISSUE TITLE
Right-clicking on a purple rune of a ritual in progress with item in hand voids your item

### ISSUE THREAD

**Issue by VorpalLemur** [Mithion/Mana-And-Artifice#142]
If you start a ritual and wait until all the ingredients are floating in the air awaiting you to input manaweaving shapes, and you right-click an item onto a purple rune on the floor (intentionally or, in my case, by accident), it will void your item.   

I found this out the hard way when, reaching for my manaweaving wand, I accidentally clicked my backpack full of 200+gameplay hours worth of my most precious enchanted tools and items onto a rune and lost everything in one click.   I took a moment to verify that indeed this seems to work repeatedly for a broad range of items before quitting my game and restoring from backups.

**Comment by Mithion** [comment]
I'm so glad you had a backup!

I'll make sure it gets fixed for next version.

**Comment by VorpalLemur** [comment]
Thank you!  Love the mod btw.   Been fun to explore its depths.

**Comment by madlemur** [comment]
So that's what happened to my pocket storage unit, manaweaving staff and fluxborer... Glad to know what did it, and that it'll be fixed!

**Comment by Mithion** [comment]
Oof.  That's rough.  Sorry about that!

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
