### ISSUE TITLE
Bug / Enhancement? - can't unequip eldritch orb

### ISSUE THREAD

**Issue by MacChuck** [Mithion/Mana-And-Artifice#143]
Mod version 1.2.1.9

Unless I'm completely blind, it would be nice to have a way to take down or unequip the eldritch orb.

edit: I ran around long enough that it ran out of juice and un-equipped on it's own. Maybe a codex entry stating that it's mana decays over time and will eventually fall?

**Comment by Mithion** [comment]
Yeah I'll update it to be more clear.  

Considering making the orb a curio as well instead that when equipped will pop out - then when it runs out of mana it just doesn't do anything, and you can stop it early by unequipping it.

**Comment by Mithion** [comment]
This has been fixed in 1.3.0.1, available on CurseForge:
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3205693
