### ISSUE TITLE
Crystalize Spell resets Mob state

### ISSUE THREAD

**Issue by olol5620** [Mithion/Mana-And-Artifice#144]
when picking up e.g. baby sheep's, with crystalize Spell, the afterwards placed animal will be a fully grown white sheep. 
Also picking up grown sheep's of any color, with no wool, afterwards they have wool and are white.

**Comment by Mithion** [comment]
You're likely on an old version, but I can't be sure because you didn't include that information.  

Please update to 1.2.1.9:
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice
