### ISSUE TITLE
Crystalize Spell failed result in voiding diamond

### ISSUE THREAD

**Issue by olol5620** [Mithion/Mana-And-Artifice#145]
Spell: Touch-->Crystalize,
Hitting the ground with Spell while having diamonds in inventory results in voiding diamond

**Comment by Mithion** [comment]
You're likely on an old version, but I can't be sure because you didn't include that information.  

Please update to 1.2.1.9:
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice
