### ISSUE TITLE
Occulus stops ceeping track of progress on server

### ISSUE THREAD

**Issue by olol5620** [Mithion/Mana-And-Artifice#146]
Currently I'm unable to identify what is exactly the cause. My guess is, when rejoining a server, with no shutdown of both server and client, the occulus don't register progress to tiering up.

**Comment by Mithion** [comment]
Can you provide more information?  What tier?  What steps are lost?  What version of the mod?

**Comment by olol5620** [comment]
Yes, I update the mod asap, it was 1.2.0.4. in MC-Version 1.16.4
My Character was tier 1.
Reach Level 30 was the task, but even after reaching Level 31 it was not recognised

**Comment by olol5620** [comment]
okay, I close it. I was stupid.
Sorry for wasting your time

**Comment by olol5620** [comment]
Somehow I read the leading 2 as a 3.
I should get some sleep

**Comment by Mithion** [comment]
Sleep is good :)
No need to apologize!
