### ISSUE TITLE
Ritual of the return and Homestead not activating

### ISSUE THREAD

**Issue by olol5620** [Mithion/Mana-And-Artifice#147]
mana-and-artifice-1.2.1.9
forge-1.16.5-36.0.1
playing on server

I'm not sure weather I'm doing something wrong or it is a bug.
I did the following setup ( https://imgur.com/a/PfTSjPg ) but non of the three rituals can be activated with purified vinteum dust.
I'm also confused what the ritual of homestead is supposed to do, because it is not explained in codex arcana

**Comment by IllutianGunn** [comment]
The Ritual of Homecoming has more spaces between the sides than you actually  have.  But in any case, it is still not working as I have also tried this a few times.

![2021-01-28_13 22 06](https://user-images.githubusercontent.com/77242186/106183057-ba4efb80-616d-11eb-83cd-f73ec492c854.png)

**Comment by Mithion** [comment]
Ritual of Homestead fits inside a 5x5 area - that is too big.  Draw the pattern shown in the codex within a 5 block by 5 block square.
