### ISSUE TITLE
unable to edit Lodestar command by inverted mouse settings

### ISSUE THREAD

**Issue by olol5620** [Mithion/Mana-And-Artifice#148]
mana-and-artifice-1.2.1.9
forge-1.16.5-36.0.1
playing on server

when changing mouse settings to attack on left click and use item on right click, the lodestar configuration of a command will be impossible, because left clicking removes command, right clicking does nothing.

**Comment by Xinja96** [comment]
I have also come across this, I have tried looking for other mods to be able to edit my keybinds in a way to work around this but I can't find one that is up to date with the version I'm on, meaning the only way I can use the lodestar is to temporarily change the 2 keybinds around while I'm working in it.

**Comment by Mithion** [comment]
Closing as 1.16.5 is no longer supported.
