### ISSUE TITLE
Warding Candle prevents Piglin trading

### ISSUE THREAD

**Issue by VorpalLemur** [Mithion/Mana-And-Artifice#149]
* Mod version: 1.2.1.9

So this is an odd one.  A lit warding candle prevents piglin gold trading.   

Repro is dead simple.   Create a pit with a couple piglins in it.   Set up a warding candle, but leave it unlit.   Throw a stack of gold into the pit and watch the piglins snatch it up and start trading.    Now light the candle and the piglins will no longer be able to pick up the gold.  They'll continue to swarm over it, but the stack of the gold will just sit there on the ground unmolested.   Now extinguish the candle and the piglins will suddenly remember how to pick up the gold on the floor and trade with it.   Candle works like an on-off switch for piglin trading.

This is unfortunate since faction raids have now become the bane of my existence in this game and I find myself using warding candles everywhere just to get some relief from their incessant and deafening jump-scares while I try to focus on exploring other mods.

**Comment by Mithion** [comment]
This should be fixed as of 1.3.0.1
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3205693
