### ISSUE TITLE
hopper interactions

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#15]
runic anvil: hoppering in allows a full stack each of any two items, and if they're a pattern and superheated vinteum, hammering deletes all but one of each

runescribing table: hoppering in allows any item in any open slot at the top
![2020-06-13_15 58 53](https://user-images.githubusercontent.com/8917961/84577969-dc3a7000-ad8e-11ea-94d6-affe2272edbc.png)

![2020-06-13_15 56 51](https://user-images.githubusercontent.com/8917961/84577939-8a91e580-ad8e-11ea-8db4-0e8cdae763b7.png)

runeforge: hoppering in allows a full stack of any item. If the forge smelts the item, then it voids all that were stacked inside and returns one of the result (if you hopper out earlier it's my other bug report)

chalk runes: allows a full stack in of the same item, items are invisible.

**Comment by Mithion** [comment]
Resolved in 1.0.1-pre1
