### ISSUE TITLE
Lit Warding Candle causes named piglins to despawn

### ISSUE THREAD

**Issue by VorpalLemur** [Mithion/Mana-And-Artifice#150]
* Mod version: 1.2.1.9

Discovered this issue while trying to build a piglin trading hall. 

A lit warding candle causes nametagged piglins to despawn when player leaves the dimension.

Repro
1. create a pit with a single piglin in it.
2. use nametag to give the piglin a name.  Usually this prevents despawning.
3. set up a warding candle nearby but don't light it (as a control)
4. leave the dimension and return as many times as you like.  Travel far from the area.   Piglin doesn't despawn. 
5. light the candle
6. leave the dimension and come back.  Piglin is gone. 

This is an issue for me due to the fact that warding candles are the only way to prevent incessant faction raids that otherwise make AFKing anywhere in the game unsafe.

repro setup.   (the Modular Routers Item Router has been disabled to hopefully eliminate it as a factor)

![Screen Shot 2021-01-30 at 9 58 30 AM](https://user-images.githubusercontent.com/16469763/106364317-f6579d00-62e2-11eb-91b7-9e60540bd02a.png)

**Comment by Mithion** [comment]
This should be fixed as of 1.3.0.1
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3205693

(as with the other one, if it isn't please let me know and I'll re-open the issue and continue to investigate!)
