### ISSUE TITLE
[1.16.4]  Eye Spy

### ISSUE THREAD

**Issue by optmisticnihilist** [Mithion/Mana-And-Artifice#152]
I'm testing a modpack that has both Mana and Artifice and Repurposed Structures. Repurposed Structures replaces strongholds in the overworld with stonebrick strongholds and gives the advancement Eye Spy The Overworld instead of Eye Spy. I want to either have Eye Spy The Overworld trigger completing Eye Spy or have Mana and Artifice accept the Eye Spy The Overworld advancement. I think I could do either using KubeJS however I still don't have a clue how to, even after looking at https://mods.latvian.dev/books/kubejs.

https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

**Comment by Mithion** [comment]
Hm, I didn't really think about that when I wrote it as the advancement checking isn't databound; it's hardcoded.
As far as triggering the progression it will need to find the original Eye Spy as found in vanilla as unlocked.

For the short term, you're better off ensuring that the vanilla one exists and is triggered along with the replacement until I can come up with a better way to handle progression for modpacks.

Sorry I don't have a simpler solution for you at this time.

**Comment by optmisticnihilist** [comment]
RS's mod author provided datapack to get both advancements when entering stonebrick strongholds. 

https://github.com/TelepathicGrunt/RepurposedStructures/issues/51

This closed for me unless you want it open for working on progression for modpacks.

**Comment by optmisticnihilist** [comment]
Just dawn on me, that another workaround is that FTB Quests can grant advancements as rewards.
