### ISSUE TITLE
Chimerite gems don't drop when Astral Sorcery's Spatial Manipulation perk is active

### ISSUE THREAD

**Issue by MatthiasMann** [Mithion/Mana-And-Artifice#154]
I'm using 
mana-and-artifice-1.2.1.9
astralsorcery-1.16.4-1.13.9
forge-1.16.5-36.0.15
on Minecraft 1.16.5

And I have the Perk 'Spatial Manipulation' from Astral Sorcery active (which puts all mined  items / monster loot directly into the players inventory). This prevents the generation of Chimerite gems (mined 200+ coal ore, 10+ emerald ore).

After temporarily disabling this perk the gems did drop as expected (got 13 gems from 2 emerald ore using fortune III diamond pickaxe from Tetra).

I'm mining emerald ores with a mana magic level of 30.

**Comment by Mithion** [comment]
The dev of Astral will need to call the global loot modifiers from within Forge.  Those will modify the drops accordingly.

**Comment by MatthiasMann** [comment]
According to @HellFirePvP Astral Sorcery is already doing that - it may be necessary that you two talk about this :)
