### ISSUE TITLE
Block doubling with silk ring

### ISSUE THREAD

**Issue by WindFox** [Mithion/Mana-And-Artifice#156]
Mod version 1.3.0.0

I noticed when I used touch-break while wearing a silk ring, I get both a silk touched drop and a non silk touch drop.

i.e. Break Grass Block, it drops Grass AND dirt. Diamond ore drops the ore AND a loose diamond. etc.

Is this intended?

**Comment by Mithion** [comment]
Nope, definitely not intentional!

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
