### ISSUE TITLE
Rituals in JEI not show properly

### ISSUE THREAD

**Issue by WindFox** [Mithion/Mana-And-Artifice#157]
Ver: 1.3.0.1
Looking at rituals in JEI show a missing texture and the text is not positioned right.
![Screenshot 2021-02-16 000908](https://user-images.githubusercontent.com/3812388/108020894-62c4e280-6feb-11eb-9ee2-53f89d91a249.png)

**Comment by Mithion** [comment]
How did you bring those up?  I couldn't figure out how when I was adding them; so I thought it just didn't work. 

I don't know JEI all that well apparently lol

**Comment by WindFox** [comment]
I was just seeing what things were used in.
Right-clicked cod in JEI and that page popped up.

**Comment by Mithion** [comment]
oh ok, cool.  I'll make sure I fix that up!  Appreciate it!

**Comment by Mithion** [comment]
1.3.0.2 fixed this issue
