### ISSUE TITLE
[Bug] Eventide and Aurora wonkiness 

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#16]
__Eventide__ 
**Description:** (fixed in 1.0.1)
When placed from ritual kit (either), chalk doesnt render till block update, materials(pink wool) needs to then be removed and replaced after updating the chalk, ritual doesnt automatically activate (yes i checked time of day, ritual kit cant even place the ritual at night)
**Demonstration:**
![AM3 eventide2](https://user-images.githubusercontent.com/33331567/84579496-1fe7a680-ad9c-11ea-979b-1dd77aac224c.gif)

__Aurora__
**Description:**
Aurora activates and requests manaweaving when placed from ritual kit as it should, but pink wool isnt consumed from ritual kit and ritual drops two blocks of pink wool after activated with manaweave symbol
(edit): if aurora is activated at night, and then the player waits until day to draw the manaweave symbol, the ritual still activates but fires its particle into the ground because thats where the moon now is, therefore can turn day to night.

__Eventide & Aurora__
**Description:**
This is the best one, activating multiple eventide rituals/ aurora rituals in rapid succession causes day and night to flash back and forth rapidly, due to each ritual flipping/adding world time
**Demonstration:**
![AM3 eventide 1](https://user-images.githubusercontent.com/33331567/84579600-072bc080-ad9d-11ea-8539-7844ff880d53.gif)
(apologies for massive compression on this one it was originally like 30 mb)

**Comment by Mithion** [comment]
Aurora returning the materials is intended, the rest is a bug.

**Comment by ace10102** [comment]
aurora doesnt consume the pink wool from the kit, so it's just spawning two pink wool into existence then dropping it

**Comment by Mithion** [comment]
Ah, I misunderstood - then yes, that's a bug.

**Comment by ace10102** [comment]
updated to 1.0.1 and eventide is now activating straight out of the kit

**Comment by ace10102** [comment]
even more info: reagents can be removed from a ritual while theyre being consumed and the ritual will still activate (tested with only eventide and aurora, havent moved to other rituals yet)

**Comment by ace10102** [comment]
just tested with ancient stone ritual, as long as the reagent that is currently being consumed by the ritual is removed, the ritual wont explode

**Comment by Mithion** [comment]
I have a rework in mind for reagent handling that should make this a non-issue.  Should fix #20 as well.

**Comment by Mithion** [comment]
Aurora and Eventide now check to ensure they can still apply when spawning the entity.  The entities also check before applying their effect.  In both cases, if not valid, they simply do nothing and despawn.

**Comment by Mithion** [comment]
The following fixes have been applied, that should address all of these concerns:

1.) Resolved as per your update

2.) Ritual Kits for rituals that have optional components will lock the item to the chalk rune (making it unable to be removed).  It also forces the ritual to consume the item as part of casting (though the optional component is not removed from the kit).  Breaking a rune that contains an optional reagent placed by a ritual kit will not drop the item.

3.) Once a ritual begins consuming the reagents, it will lock all chalk runes so that no reagents can be added or removed.
