### ISSUE TITLE
Villager librarian (novice) don't give a enchanted book trades

### ISSUE THREAD

**Issue by EngineeM** [Mithion/Mana-And-Artifice#160]
After installing the mod, all my villagers librarians (novice) stopped showing trades for enchanted books at all (they do not show them even after I break and put back lectern to reload trades), but after removing the mod, this problem disappears.
![2021-02-16_19 02 56](https://user-images.githubusercontent.com/79155199/108089083-41670380-708a-11eb-849a-1580e37a6871.png)

**Comment by Mithion** [comment]
Hey there - that's intentional.  The mod changes them since it adds somewhat of an enchanting overhaul.
A config option exists to turn it off and return them to vanilla behaviour :)
