### ISSUE TITLE
Cartographers trades changed to "Thaumaturgic Link"

### ISSUE THREAD

**Issue by StormCircuit** [Mithion/Mana-And-Artifice#161]
Using version 1.2.1.9 cartographers appear to have an unusable Thaumaturgic Link item that lists some sort of random feature from the base game biomes such as "minecraft:river" or "minecraft:tall_birch_forest" but are otherwise unusable. I have no idea if this is intended or not.

**Comment by Mithion** [comment]
It is, but I'll be removing it soon - they're a catalyst for the Ritual of Locating, which lets you enchant a compass to be able to find those various structures and biomes.
