### ISSUE TITLE
Doesn't generate structures with Terraforged

### ISSUE THREAD

**Issue by LordNoisy** [Mithion/Mana-And-Artifice#162]
The structures in this mod do not generate with Terraforged worlds, I've contacted the mod author for Terraforged and this is apparently because "The mod that added the structure needs to register their "structure separation settings". These settings tell the chunkgenerator how to space each structure type out - if they're not registered TF can't know how the structure should generate."

The mod author linked me: https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility
Which demonstrates how to implement the solution to this issue

**Comment by Mithion** [comment]
I already register all of those settings.  Other users in discord have reported no problems with Terraforged, so feel free to come ask them what they did differently.

**Comment by Mithion** [comment]
http://discord.gg/4nJEU4X if you want to ask them and need the invite
