### ISSUE TITLE
villagers dont loose their jobs after cristalised [bug]

### ISSUE THREAD

**Issue by WhiteCrafter** [Mithion/Mana-And-Artifice#163]
when i picked willager with crystalize spell and transported it over long distance, it bugged, didnt loose job, and started waking one direction instantly. i had to get them back on their village and then break all job blocks.

**Comment by Mechalith** [comment]
I think this might be a general issue with villagers ATM, because I had the same problem using other methods of relocating a villager. (Mob capture tool from Industrial Foregoing, quantum capture tool from another mod I'm forgetting, etc.)

**Comment by Mithion** [comment]
That was my thought too (good timing; was just reading through issues lol) - but I wasn't sure if other mods did it.  It's good to confirm.

What would probably make sense is for Mojang to put in some kind of distance check for villagers and if they go too far from the job block they lose the profession.

I'm going to close this as a vanilla issue.
