### ISSUE TITLE
Staves/wands infused with spells by the player lose the spell

### ISSUE THREAD

**Issue by facufierro** [Mithion/Mana-And-Artifice#165]
Tested on version 1.3.0.2, staves infused by the player lose their spell. Fresh install, only Mana and Artifice and JEI.
Just to be sure tried them with an older version and they work fine ( 1.2.1.9).
The problem seems to be the new icon interface, when i try to sneak+right click the staff is blank (no spell) it sends "Error setting spell data values; serverside validation failed".
Staves made in version 1.2.1.9 are not broken on 1.3.0.2 though.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release!

**Comment by Mithion** [comment]
1.3.0.3 fixed this issue
