### ISSUE TITLE
Constructs can't break blocks in claimed chunks (FTBEssentials chunks)

### ISSUE THREAD

**Issue by jaket376** [Mithion/Mana-And-Artifice#166]
Constructs cannot break blocks within chunks claimed via FTB Essentials. For example, if wanting to make a tree farm using the constructs, you have to unclaim the chunk in order to allow for harvesting of trees. This doesn't occur on plants such as wheat however, as I have a wheat farm which works fine with constructs, so it is only actual blocks that they cannot break.

I am playing on the latest version of ATM 6 where I have encountered this issue, and absolutely am loving the mod besides this small issue.

**Comment by Mithion** [comment]
This has been resolved in later versions.
