### ISSUE TITLE
Conflict Between "End Remastered" and M&A Blink Spell Ritual

### ISSUE THREAD

**Issue by Astrolegium** [Mithion/Mana-And-Artifice#167]
While it is likely on the side of the other mod, and I am not using it in my mod pack in favor of this mod, I have found that having the mod "End Remastered" installed prevents a player from placing an Eye of Ender on the "Ritual of Arcana" when attempting to create a spell with the "Blink" component. 

It is very likely that the other mod is changing the default Eye of Ender to a mod specific one, or adding an alternate behavior when right clicked on a block. I am not actually interested in a fix for the issue (or I would be bringing this to the attention of the other authors), but I am reporting this here as I feel it is worth bringing to your attention so that you are aware of the issue if others report similar problems in the future.

MC/Forge Version: 1.16.5-forge-36.0.21
Mana and Artifice Version: mana-and-artifice-1.3.0.1
End Remastered Version: EndRemastered-R352

**Comment by facufierro** [comment]
A workaround for this is to put the ender aye in the off-hand slot.

**Comment by Mithion** [comment]
If another mod is changing basic vanilla functionality, it's up to them to fix it.
