### ISSUE TITLE
Griefing with Nethergate

### ISSUE THREAD

**Issue by Krutontar** [Mithion/Mana-And-Artifice#168]
I just tried Nethergate on somebody via Smite and it crashed the server I was on.  Just Smite+Nethergate, no modifiers.
Version 1.2.1.9
Forge 36.0.21
Pack ATM 6 1.5.2

Funny story, back in 1.6.4 in Ars Magica 2, I tried putting Nether Intervention as a projectile and it crashed then also.

**Comment by Mithion** [comment]
At least I'm consistent :P

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
