### ISSUE TITLE
Generator Errors with terraforge

### ISSUE THREAD

**Issue by BentiGorlich** [Mithion/Mana-And-Artifice#169]
I use terraforge for my world gen (it is just beautiful) and I get the warning that structures from Mana and Artifice will not be generated due to missing generation settings:
> [TerraForged/]: Structure [mana-and-artifice:council_library] does not have any generation settings registered for it so it cannot be generated!
[TerraForged/]: Structure [mana-and-artifice:fairy_glade] does not have any generation settings registered for it so it cannot be generated!
[TerraForged/]: Structure [mana-and-artifice:potion_hut] does not have any generation settings registered for it so it cannot be generated!
[TerraForged/]: Structure [mana-and-artifice:ritual_circle_desert] does not have any generation settings registered for it so it cannot be generated!
[TerraForged/]: Structure [mana-and-artifice:ritual_circle_forest] does not have any generation settings registered for it so it cannot be generated!
[TerraForged/]: Structure [mana-and-artifice:ritual_circle_tundra] does not have any generation settings registered for it so it cannot be generated!
[TerraForged/]: Structure [mana-and-artifice:wistful_runesmith] does not have any generation settings registered for it so it cannot be generated!

Versions:
- Minecraft: 1.16.5
- Forge: 36.0.14
- Mana and Artifice: 1.3.0.2
- Terraforge: 0.2.8

**Comment by Liamdude** [comment]
This person also reported the issue to Terraforged, and they outlined how their generation works. The issue here could be something along the lines of not specifying in which biomes that structures should spawn and that generation settings may not be specified. More info at https://github.com/TerraForged/tracker/issues/74
