### ISSUE TITLE
[Bug] chalk persistence/placement still wonky

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#17]
**Description:**
chalk can be placed on chests, trapped chests, barrels and enderchests
when placed on chests, trapped chests and barrels, given items and the below container is opened, the chalk deletes itself, taking its contents with it
chalk doesnt break when enderchest is opened
if chalk is placed on a normal solid block and given items, and that block is removed, chalk deletes itself with its contents

**Comment by Mithion** [comment]
1.0.2-pre1 fixed this issue by making chalk runes non-placeable on any block that is not a solid opaque cube.

Also changed chalk to drop contained items when it is removed due to the block underneath it being changed to an invalid one or destroyed.
