### ISSUE TITLE
Broken codex arcana

### ISSUE THREAD

**Issue by AnonimiAngels** [Mithion/Mana-And-Artifice#170]
My codex arcana didnt showing any recipe or guide

**Comment by AnonimiAngels** [comment]
mod list
ArcaneFundamentals-alpha-5.2
cagedmobs-1.16.4-1.2.6
Cucumber-1.16.4-4.1.8
curios-forge-1.16.5-4.0.4.0
Cyclic-1.16.5-1.1.8
geckolib-forge-1.16.5-3.0.14
jei-1.16.4-7.6.1.71
mana-and-artifice-1.3.0.2
MysticalAgriculture-1.16.4-4.1.5
SimpleStorageNetwork-1.16.5-1.3.2

**Comment by Mithion** [comment]
Going to track this in #174
