### ISSUE TITLE
armor causes crash when breaking

### ISSUE THREAD

**Issue by Zatzou** [Mithion/Mana-And-Artifice#171]
So a player on a server I moderate has recently been having issues logging in as wheneve he logs in the server crashes. This appears to happen due to this mod attempting to call a method in `net.minecraft.util.ColorHelper` which doesn't exist.

What appears to happen is that every time the affected player logs on an arrow hits them causing the armor to take damage which inturn crashes the game.

Reading the crash logs from the server it appears that this issue is caused because `com.ma.items.armor.DyeableMageArmor.damageItem` calls `com.ma.items.armor.BrokenMageArmor.convertFrom` which calls `com.ma.items.armor.DyeableMageArmor.func_200886_f` which then finally crashes the server by calling the missing method.

I am not sure if this is caused due to the item being dyed or why this happens but it happens and I haven't been able to troubleshoot further than this. If I get more info on this case I will post about it here.

The server where this happens is running All the mods 6 1.5.3b. I have attached some of the crash reports and logs from the server to this issue.
[crash-2021-03-02_01.48.10-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6069427/crash-2021-03-02_01.48.10-server.txt)
[crash-2021-03-02_01.39.55-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6069435/crash-2021-03-02_01.39.55-server.txt)
[server log.txt](https://github.com/Mithion/Mana-And-Artifice/files/6069459/server.log.txt)

**Comment by Zatzou** [comment]
So I have gotten some more information on this case at this point. I know that the armor in question wasn't dyed or colored specially.

With more testing done now this seems to happen when the armor breaks and the set tries to repair itself. Another person I was testing with could trigger this crash using some other methods but the crash basically happened when the set breaks.

**Comment by Mithion** [comment]
I have fixed this in dev, it will go out with the next release!

**Comment by Mithion** [comment]
1.3.0.3 fixed this issue
