### ISSUE TITLE
Ritual of forgotten Lore wont activate

### ISSUE THREAD

**Issue by Emokeks** [Mithion/Mana-And-Artifice#172]
Hi, the ritual wont work because it cant find the bookshleves around it.
It says there are not enought bookshelves around, even with 20 bookshelves around it

**Comment by Mithion** [comment]
Chances are you're using quark bookshelves - either add them to the tagged list of accepted books in the mod using a datapack or ensure you're crafting vanilla bookshelves.

**Comment by Emokeks** [comment]
The mod didnt accept bookshelves other than the vanilla log used ones
