### ISSUE TITLE
Can't craft diamond construct parts at manaweaving altar

### ISSUE THREAD

**Issue by BigRigAssassin** [Mithion/Mana-And-Artifice#173]
I'm trying to complete tier 3 tasks and I need to make a construct with 3 diamond or iron parts.  I want to do diamond.  I have found a few diamond parts but need one more, yet I cannot make them.  I follow the recipe in the Codex Arcana and nothing happens.  This example is just a head, I couldn't make any other parts out of diamond.  I can make wood, iron and gold...I did not try obsidian.

![image](https://user-images.githubusercontent.com/12226031/110184036-06bcd500-7dc5-11eb-9663-8ec895b3fcd0.png)

![image](https://user-images.githubusercontent.com/12226031/110184049-0fada680-7dc5-11eb-8043-3594e5e5a3c7.png)

**Comment by Mithion** [comment]
Tier 3 requires gold or iron, diamond is Tier 5.
