### ISSUE TITLE
No text shows up when codex is opened

### ISSUE THREAD

**Issue by Kingbubing** [Mithion/Mana-And-Artifice#174]
I've installed and uninstalled different mods yet still get the same result. 
----Mod list:
architectury
cursios
ftb-gui-library
geckolib
Hwyla
jei
mana-and-artifice
u_team_core
useful_backpacks
wailaHarvestability

![nit](https://user-images.githubusercontent.com/80139150/110192626-cd03c280-7df4-11eb-90c1-bb501e7ffc58.PNG)

**Comment by Mithion** [comment]
Someone else was having this issue; it was due to language settings - what language are you playing the mod in?
Their fix was switching the language to en_GB - not saying to play all your game in this but wondering if the same works for you?

**Comment by Mithion** [comment]
Closing for no response.
