### ISSUE TITLE
[1.16.5] Inventory Items Lighting Wrong when next to constructs

### ISSUE THREAD

**Issue by HenryMaxler** [Mithion/Mana-And-Artifice#175]
Whenever viewing construct pieces in JEI or in Vanilla Minecraft, the other blocks in the inventory next to them change how they look, to look like the light is coming from the bottom of the block.  Using
curios-forge-1.16.5-4.0.4.0.jar
geckolib-forge-1.16.5-3.0.15.jar
mana-and-artifice-1.3.0.2.jar
forge-36.0.46
![image](https://user-images.githubusercontent.com/75149748/110232835-07dd2780-7ed5-11eb-8e87-5d505d150f0d.png)

**Comment by HenryMaxler** [comment]
Book of Rote also does this, but only when it is in specific slots, or viewed in JEI

**Comment by Mithion** [comment]
I've got a fix for this in 1.3.0.3, which is in alpha.

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
