### ISSUE TITLE
 Staff of the Pilgrim breaking sneaking

### ISSUE THREAD

**Issue by LeSalux** [Mithion/Mana-And-Artifice#177]
After I use the Staff of the Pilgrim then unequip it I am no longer able to move while sneaking. I do have 100 mods installed and it might be a conflict with another mod, but I noticed it prevented me from moving while crouching after the Pilgrim effect finishes. The glitch stops if I exit and reload the world.

**Comment by Mithion** [comment]
This isn't happening in my dev environment with just M&A - if you do an instance with just M&A on your end does it still happen?

**Comment by LeSalux** [comment]
With only M&A the issue does not happen - if you want the mod list I can
send it.
