### ISSUE TITLE
Ticking Entity Crash on server

### ISSUE THREAD

**Issue by desmandias** [Mithion/Mana-And-Artifice#179]
https://pastebin.com/pFiy551X

Something to do with the mage armor, I think? It's causing the player to crash the server when they attempt to log on, and it crashed them before. Do i need to reset their player data? I think they were decently far in the mod

**Comment by Mithion** [comment]
I've got a fix for this in 1.3.0.3, which is in alpha.

**Comment by desmandias** [comment]
Gotcha! Is there anything I can do about it now, though? Or will my player data be wiped?

**Comment by Mithion** [comment]
The fix shouldn't affect your player data, no.

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
