### ISSUE TITLE
Crash on Creeper Blowing Up Runeforge

### ISSUE THREAD

**Issue by jamesipod** [Mithion/Mana-And-Artifice#180]
https://pastebin.com/HRDCRFL4

Creepers blowing up Runeforges crash both server and client. Forge 36.0.42, Mana and Artifice 1.3.0.2

**Comment by Mithion** [comment]
Well that's fun.  Will get that fixed up for next version.

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
