### ISSUE TITLE
Constructs crashing the game after giving a command

### ISSUE THREAD

**Issue by Ablmo45** [Mithion/Mana-And-Artifice#183]
Whenever i try and give a construct a command to move or do anything it crashes the game and it says that following the command was what caused it in the crash log. I'm playing on All The Mods 6 so I don't know if that has anything to do with it.
[crash-2021-03-11_00.26.06-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6120661/crash-2021-03-11_00.26.06-server.txt)

**Comment by Mithion** [comment]
I'll look into it and get it fixed up.

**Comment by Mithion** [comment]
Resolved in 1.3.0.4
