### ISSUE TITLE
Villager trading  does not change no matter how many times I try to break its work block

### ISSUE THREAD

**Issue by Elyeroel** [Mithion/Mana-And-Artifice#184]
I am trying to create a mending villager but the trades are stuck only in emeralds and bookshelves. I tried it in a flat world to redo the same method and the results are the same. When I uninstalled Mana and Artifice, the trades and trades rolling works fine.

**Comment by Elyeroel** [comment]
How do you edit the config so the Librarian trades will return to vanilla trades?

**Comment by Mithion** [comment]
That is a config option in mana-and-artifice-general.toml, set modifyVillagerTrades to false
