### ISSUE TITLE
Manaweaving Table does not input symbols consecutively.

### ISSUE THREAD

**Issue by NextPorcupine** [Mithion/Mana-And-Artifice#185]
I'm trying to create a rune for Aura of Mining, but when trying to input square->triange->inverted triangle->square to the mana weaving table, it instead adds the second square to the second position, leaving it as square->square->triangle->inverted triangle.

**Comment by Mithion** [comment]
That's likely a visual bug; the old altar was bad for that - if you're drawing them in the right order, they'll go into the table in the right order.

To confirm though, can you let me know which version of the mod you're using?

**Comment by BlazingDragon87** [comment]
This issue seems to also affect the mana crystal crafting, I have not noticed this issue with others recipes yet.

Mod Version: 1.3.0.2
Mod pack: All the mods 6 1.5.4

**Comment by Eric4bz** [comment]
Can confirm something is definitely up with it. 
I'm on the 1.3.0.2 version and no matter what I try, it won't let me craft a mana crystal. Older recipes like the mana crystal fragment has worked, but more advanced items stubbornly refuse to work.

**Comment by Mithion** [comment]
I have 1.3.0.6 in beta on CurseForge, try that one and see if you're still having trouble

**Comment by GeorgeRandall** [comment]
I'm running 1.3.0.6 and I couldn't get anything with more than 3 symbols to work in the alter either. I ran into it with Book of Alteration, but I also reproduced it with Mana Crystal and Aura of Mining after finding this thread. I finally solved it by breaking the Mana weaving Table and placing it down again. All 3 of the recipes now work.

**Comment by Mithion** [comment]
So the issue seems to be that the table doesn't sync existing patterns when loaded causing them to be invisible and take up slots.  They're still there and functional but they don't render.  Right clicking with a manaweaving wand a few times should clear them out without the need to remove the table.
