### ISSUE TITLE
[1.16.5] Server crash after updating Mana and Artifice

### ISSUE THREAD

**Issue by JellyCreeperOfficial** [Mithion/Mana-And-Artifice#186]
After updating Mana and Artifice from 1.3.0.2 -> 1.3.0.5 getting crash (Player cant login to server until I rollback server) from Botania Spectator when looking at the Manaweaving altar. Crash Report here: https://pastebin.com/1ZSVvFwC

**Comment by Mithion** [comment]
1.3.0.6 is up on CurseForge, which fixes this issue.

**Comment by Mithion** [comment]
This is fixed in 1.3.0.6:
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3244357
