### ISSUE TITLE
HUD Go black when open Codex Arcana witn shaders.

### ISSUE THREAD

**Issue by Arzueel** [Mithion/Mana-And-Artifice#188]
Playing on my own server with this mod and shaders. When I open Codex Arcana HUD breaks according to shader: fonts and item icons dissapear from the game until fully restart (ProjectLUMA shaders) or fonts and items go completly black (SEUS PTGI E12). 
Mana and Artifice - 1.3.0.2
Optifine - HD G7\G8 Pre6

**Comment by Arzueel** [comment]
Does not work on mod v. 1.3.0.5 either.

**Comment by Mithion** [comment]
Optifine/Shaders are not supported.
