### ISSUE TITLE
Persistent Crashing after killing pixies with "fire".

### ISSUE THREAD

**Issue by optmisticnihilist** [Mithion/Mana-And-Artifice#190]
I say fire as I have only had this happen twice, once with a Mana And Artifice fire projectile spell and previously using an Chemical Thrower from Immersive Engineer Chemical Thrower spraying lava. Melee kills are fine. When this crash occurs, the game will crash every time I try to re-enter the world. The temp fix for both times was changing my position in the level.dat file to somewhere else. Afterwards, I am able to return to the location of the crash.

Crash logs from the fire projectile spell event (I'll have to do some digging for the chemical thrower logs). 
[crash-2021-03-18_15.44.46-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/6167399/crash-2021-03-18_15.44.46-client.txt)

[crash-2021-03-18_15.40.43-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/6167363/crash-2021-03-18_15.40.43-client.txt)

**Comment by Mithion** [comment]
Does this happen without Better End installed?  It seems to be related to a mixin they're using.

**Comment by optmisticnihilist** [comment]
It didn't crash after half a dozen pixies sprayed with lava with Better End disabled and crashed with just one bolt with Better End re-enable. For self-improvement I'm curious on why Better End is involved with the crash since I'm in not in The End (From testing I agree that Better End is involved but no idea why/how). Also curious on if/how that can be determined by the crash log.

**Comment by optmisticnihilist** [comment]
I'm getting the same crashes with just melee attacks with or without Better End Disabled if have or try to add to my inventory, the spectral glasses from evilcraft for seeing vengeance spirits.


[crash-2021-03-19_16.19.56-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/6174093/crash-2021-03-19_16.19.56-client.txt)

**Comment by optmisticnihilist** [comment]
The reply from EvilCraft. I wouldn't call this a high priority as the crash can be prevented by blacklisting pixie from generating a Vengeance Spirit.


********
 It doesn't look like this is something that can be fixed on my end.
The Mana and Artifice doesn't seem to be open-source, so I can't check why calling their renderer is breaking things.

I recommend following up with the mod author in Mithion/Mana-And-Artifice#190.
This code may be relevant to mention: https://github.com/CyclopsMC/EvilCraft/blob/master-1.16/src/main/java/org/cyclops/evilcraft/client/render/entity/RenderVengeanceSpirit.java

If there's something that needs to be changed on my end, please let me know!

**Comment by Mithion** [comment]
Yeah seems its due to the pixies rendering as the radiant sparkles.  I'm planning on changing their renderer anyway in the future (low priority though) so will see if that resolves the issue.

**Comment by Mithion** [comment]
This was resolved with the new pixie renderer
