### ISSUE TITLE
Occulus Not Registering Certain Actions for Progression

### ISSUE THREAD

**Issue by nekhs** [Mithion/Mana-And-Artifice#191]
On a server, the occulus is not registering certain actions (mostly crafting actions) have been performed, making it impossible to tier up without commands.

For example, in tier 1 it doesn't recognize crafting the manaweaving altar or crafting the inscription table. In tier 2, it isn't recognizing the unfired rune plates I've crafted.

**Comment by Mithion** [comment]
Hi there,

Sounds like you used a mod-added crafting table that isn't firing the appropriate crafting events (which this mod needs to track progression).  Can you confirm that the issue persists if you use a vanilla workbench?

**Comment by nekhs** [comment]
Oh! I'll ... actually check that. I think I've been using crafting table on a stick / advanced crafting table on a stick, and I think for this latest one I was using the cyclic workbench. 

- Yep! A vanilla workbench - even with Fast Workbench installed, which was a Concern for me - worked. Thanks for clearing that up!
