### ISSUE TITLE
[1.16.5] Server crash (factionTargetHelpPredicate -> NoSuchElementException)

### ISSUE THREAD

**Issue by iarspider** [Mithion/Mana-And-Artifice#193]
My ATM6 server has crashed twice with the same error: https://gist.github.com/iarspider/bc7427b11587812f90af1b3a783957bf

Mana and Artifice: 1.3.0.5
Forge: 1.16.5-36.1.0

**Comment by Mithion** [comment]
Hi there,

This should be fixed in 1.3.0.6:
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3244357
