### ISSUE TITLE
Auctoro Manaweave Registers as Capistro when drawn

### ISSUE THREAD

**Issue by nekhs** [Mithion/Mana-And-Artifice#198]
Every time I draw Auctoro at the manaweaving altar it registers Capistro, which is a problem since drawing Capistro also draws Capistro, The, uh, downward facing fish-looking ones. This is making it impossible to make a book of alteration - at least by manually drawing the rune. I haven't tried the automated option because, frankly, I don't actually understand it yet, haha.

And hey! I actually checked that I'm on the current beta and using the right methods this time!

**Comment by Mithion** [comment]
Hey there,

That's a known issue that happens when you manaweave facing north.  Face a different direction and you should be fine.

**Comment by nekhs** [comment]
.... You know now that you mention it. That is the direction I was facing. Sorry! I'll check known issues more thoroughly next time.

**Comment by Mithion** [comment]
It's a weird one.  Haven't been able to nail it down yet, but I think it has something to do with rotation wrapping from -180 to 180 on the north axis.

**Comment by nekhs** [comment]
Yeah, I wouldn't even know where to start on that issue. For now I'll just move my manaweaving altar lol. Thanks for the swift reply!

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the 1.4.0.0 release.
