### ISSUE TITLE
[Bug] spellcrafting logic (ritual of arcana)

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#20]
**Description:**
the resulting spell from a ritual of arcana activation is determined by the spell scroll currently in the central chalk
this means if you take a really cheap spell scroll, stick it into the ritual to craft it, then replace it with a really expensive spell right before activation, it'll craft the really expensive spell instead, using only the resources from the cheap spell

**Reproduce:**
1.) get a cheap spell like touch dig
2.) place into ritual of arcana and wait for reagent requirements to appear
3.) put all the required materials into the ritual
4.) remove cheap spell scroll
5.) swap it for an expensive scroll like bolt ice damage with lots of modifier upgrades
6.) activate ritual of arcana
7.) the required manaweave symbols will be for the previous cheap spell
8.) resulting spell will be the really expensive high complexity one
9.) profit

**Comment by Mithion** [comment]
I have a rework in mind for rituals handling reagents that will solve this issue.

**Comment by Mithion** [comment]
Rituals now lock reagents in place preventing the item from being changed.
