### ISSUE TITLE
[1.16.5-1.3.0.6] Wistful Runesmith replaces terrain blocks instead of being flush with terrain

### ISSUE THREAD

**Issue by TelepathicGrunt** [Mithion/Mana-And-Artifice#203]
Picture below shows what I mean. The nbt file probably just needs some Structure Void blocks places all along the outside of the building so that it does not replace terrain anymore.
![image](https://user-images.githubusercontent.com/40846040/112665030-fed6da80-8e30-11eb-93d0-b14e26c8d6f3.png)

**Comment by Mithion** [comment]
Structure gen has been improved in later versions.
