### ISSUE TITLE
Players, mobs, items, chests, and some other blocks turning into just a color.

### ISSUE THREAD

**Issue by Rainevlair** [Mithion/Mana-And-Artifice#206]
I was initially using version 1.2.1.9. When I made the touch dig spell and used it, all the mobs, all my items in my inventory, the chests, and some other random blocks were just a shade of green. As I moved around the world it would change colors. So I updated to 1.3.0.6 and I was experiencing the same problem. So I made a new world and it started out fine but then I had the same problem once I first made and used the projectile dig spell.

**Comment by VirtualGaming1** [comment]
just got the same exact issue and wound this render error is the with the problem.

Could not find uniform named InSize in the specified shader program.

**Comment by VirtualGaming1** [comment]
hay @Rainevlair just want to know what MC version you are using and forge version?

**Comment by Mithion** [comment]
Woah, weird.  I really do wonder if there's a better hook for me to render the HUD than along with the hotbar though, maybe there's one that also works but is less messy with the GL state.

Glad you found the conflict!

**Comment by VirtualGaming1** [comment]
@Mithion yea no problem i was noticing it when i was going in and out of the building I made. I am not 100% sure if it is shader from minecraft but it dose effect if there is an open sky above the player but part of it could be shader is that you can see the mobs skin when they get hurt (the red glow). it only effect on some blocks like chest, bed, and small part of some blocks from the mod.

maybe see if you can change something on the item and maybe make is as a model. i can do some testing for you if you need it. and i did notice my users of my modpack about the bug that we found

**Comment by VirtualGaming1** [comment]
![image](https://user-images.githubusercontent.com/20447403/113493370-52d26680-94a4-11eb-957b-1f2feb7c4e87.png)
![image](https://user-images.githubusercontent.com/20447403/113493372-57971a80-94a4-11eb-8e51-9458c0b8488f.png)
![image](https://user-images.githubusercontent.com/20447403/113493378-5ebe2880-94a4-11eb-991c-9dec60bf322a.png)
![image](https://user-images.githubusercontent.com/20447403/113493383-6b428100-94a4-11eb-8e61-1f440f710d57.png)

here is some pics if it is able to help you

**Comment by FrancisVX** [comment]
I had the same issue and for me the conflict was Xaero's World Map (not Xaero's Minimap). Couldn't find any workaround so I just had to remove it for now.

**Comment by D0ub1eZer0** [comment]
Fixed that without deleting Xaero's maps! Problem is really with Xaero's Minimap HUD overlay. Go to the last page of ingame Xaero's Map settings and change "Overlay render level" setting.

![Снимок экрана 2021-04-13 121635](https://user-images.githubusercontent.com/82442664/114528977-2d86ea80-9c52-11eb-9586-1ed8b3ca039b.png)

**Comment by VirtualGaming1** [comment]
I can conferm that last message fixed it. @Rainevlair or @Mithion should add to the title or a tag for mod compact issue with Xaero's Minimap and up to you guys if this is close or stay open

**Comment by Mithion** [comment]
Tagged as other mod issue and closing.
