### ISSUE TITLE
Pedestal deletes items on them when broken.

### ISSUE THREAD

**Issue by llneo** [Mithion/Mana-And-Artifice#207]
Not sure if its intentional but i discovered today that when breaking a pedestal that has an item on it, instead of dropping the item from its inventory, the item is just deleted instead. Happened three times thanks to excavation.

**Comment by llneo** [comment]
For the record i am running Direwolf20 1.16 1.7.0 modpack on a server, and i was able to replicate the issue with other items.

**Comment by Mithion** [comment]
Hey sorry it took me a bit to get back to you!

First, are you running the latest version (1.3.0.6)? I've fixed similar issues in recent updates.

If so, or if you update and it's still happening, how are you breaking the pedestal? (tool, spell, other mod thing, etc).

Thanks!

**Comment by llneo** [comment]
Sorry for the delay in reply. I just pulled it up and the modpack currently uses version 1.3.0.2, so sounds like i just need to wait for the pack update and until dont break pedestals with stuff on them =D. Thanks for the info and again sorry for the delayed reply.
