### ISSUE TITLE
Manaweave Altar Infuses with no symbols given

### ISSUE THREAD

**Issue by Apotherix** [Mithion/Mana-And-Artifice#208]
The Manaweave Altar currently just completes any infusion for the materials given without making me draw the manaweaving symbols for any recipes

Change of altar doesn't help
Relogging / Relaunching the pack doesn't help

For clarification, It's through the TNP Limitless 3 pack as well as on a server.

**Comment by Mithion** [comment]
I've heard of this one before but haven't been able to replicate it.

When you say "Change of Altar" do you mean breaking and replacing it?  Moving it to another location?

**Comment by Apotherix** [comment]
Change of altar was meant both by breaking and replacing as well as moving it to another location. as well as trying a completely different altar altogether. A Restart of the server fixed the issue. And i'm not sure what could have caused it
