### ISSUE TITLE
Animated Construct not chopping trees

### ISSUE THREAD

**Issue by xTobyPlayZ** [Mithion/Mana-And-Artifice#209]
I have set up an Animated Construct with an axe arm to chop trees in a certain area. I have previewed it's chopping area by placing one marker in my offhand and the other in my hand and the trees are within the area. Can't figure out for the life of me why it's not working!

I am following along with direwolf20 playing the Direwolf20 1.16 v1.7.0. Followed his setup exactly, no luck.
![one](https://user-images.githubusercontent.com/40534430/113464419-02014480-9489-11eb-82ea-b2edc6dde0bc.PNG)
![two](https://user-images.githubusercontent.com/40534430/113464422-03327180-9489-11eb-9c75-994187d2e30a.PNG)

**Comment by Mithion** [comment]
Hey there!  Can you please confirm you're running Mana and Artifice v1.3.0.6?

It's listed as beta on CurseForge but it does fix some issues related to constructs.

As for the logic, make sure the runes of marking encompass the lowest log of the tree.

**Comment by xTobyPlayZ** [comment]
I replaced my current version of MaA (v1.3.0.2) with v1.3.0.6 and made sure that my marking was set to the lowest block of the tree. The construct is still not behaving the way it should :(

**Comment by Mithion** [comment]
Sorry it took so long to answer, got really busy with work.
I imagine you've long since moved on but if you ever get back to it; hold both runes one in each hand to see the bounding box and screenshot that - also can use a diagnostics rod to see what the construct is thinking.

**Comment by Mithion** [comment]
Closing for no response.
