### ISSUE TITLE
Chrono Anchor asking for reagents to cast

### ISSUE THREAD

**Issue by ChuckMorris** [Mithion/Mana-And-Artifice#210]
The chrono anchor spell when casted, it appears in the chat that some reagents are missing in order to cast the spell, but none are listed in the codex arcana, I've tried having multiple items to cast it and using different shapes, but so far none have worked. Idk if this is a bug or there really are some requiered reagents (which would make sense as it is a get out of hell card) thanks in advance, and great mod, reallly love it <3

**Comment by LiSirNo** [comment]
On earlier versions it was clock. Try if it works, I doubt it changed

**Comment by ChuckMorris** [comment]
It works, idk how did I not think of that, thanks a lot.
