### ISSUE TITLE
Mana and Artifice spawns pixies in the ATM6 Mining Dimension

### ISSUE THREAD

**Issue by tanyan-tanyan** [Mithion/Mana-And-Artifice#211]
Hello, it appears that the ATM6 Mining Dimension is set to disable mob spawn entirely, however pixies can still spawn underground and often uncontrollably if given enough space.

I submitted a similar issue report to another mod in the ATM6 modpack which has the exact same issue with their mod. When I asked about it on the ATM6 server, a dev said the following:

![Discord_gg9FJaJZTQ](https://user-images.githubusercontent.com/68793071/113588397-02841180-9628-11eb-931f-632fe95e6266.png)

**Comment by Mithion** [comment]
How is ATM6 blocking spawns in the mining dimension?  I'm not doing anything special, just registering them into biome types for normal spawning, so if there's anything different I need to do I'm open to it.

"it's a bug cause we block it" may be true, it may not be, but it's not all that helpful of an answer from ATM6.  More information would be helpful.

**Comment by Mithion** [comment]
Closing for no response.

**Comment by tanyan-tanyan** [comment]
Hi, this discussion about the same problem might be of help:
https://github.com/baileyholl/Ars-Nouveau/issues/207
