### ISSUE TITLE
just wondering how the M&A registery works??

### ISSUE THREAD

**Issue by VirtualGaming1** [Mithion/Mana-And-Artifice#212]
I am asking this because I have been getting stuck on loading with Bus Handlers Registered 

19:44:51.368 com.ma.ManaAndArtifice modloading-worker-1 M&A -> Mod Event Bus Handlers Registered

and the only work around is to keep on restarting the client untill it pass that part?

EDIT:
This is the first line that always come once it pass the point.

19:52:35.905 com.ma.ManaAndArtifice Render thread Finished registering registries!

**Comment by Mithion** [comment]
Just basic Forge stuff.  Not doing anything out of the ordinary.

Try removing everything but M&A, Curios, and Geckolib and see if the issue persists.  If it loads, add the mods back in one at a time until you find the one that is conflicting.

**Comment by VirtualGaming1** [comment]
just a replay and will close this but I am starting to think this is FML side some how. right now i am using 36.1.0 first and now 36.1.1 and it freezed at client construction phase.
