### ISSUE TITLE
Wizard Council isn't an available entity to /kill or /summon

### ISSUE THREAD

**Issue by Shadicity** [Mithion/Mana-And-Artifice#213]
The Wizard council members apparently aren't their own entity, so they can't be targeted with the /kill command or summoned in if you want to use them.  Given how witch hunters don't attack them, I'm guessing they're the same entity, but I have no idea how to specify that, nor how much longer it would take to do it in commands, so it would be nice to have it as its own entity!

**Comment by Shadicity** [comment]
Spawn eggs would be nice but that's not an issue, so I'm putting it down here instead

**Comment by Mithion** [comment]
This won't be added.

The council functionality requires specific conditions which the mod enforces, summoning them out of turn could cause instability.

They're on a despawn timer so they'll auto remove as well.
