### ISSUE TITLE
Is there an 'official' way for modpack creators to edit codex arcana content?

### ISSUE THREAD

**Issue by TochaFh** [Mithion/Mana-And-Artifice#215]
I'm creating a 1.16.5 magic modpack where I'm changing many mod recipes (through kubejs and datapacks) so they use items and process from different mods in a cool and reasonable way. Example: I changed the _eidolon's enchanted_ash_ recipe (bone in furnace) to: _mana-and-artifice's bone_ash_ on _botania_'s mana pool!
_JEI_ shows all the recipes changes (of course), but I'm having trouble with some mods guide books (not only Codex arcana) that show the original recipes in images and text. 
My problem is: I changed the vinteum dust recipe so it can only be obtained by milling vinteum ore in the _Create_'s millstone (or crushing wheel), **but... there's this page in Codex arcana:**
![image](https://user-images.githubusercontent.com/62609161/114092090-dd91d780-988f-11eb-9309-55f24abfbcb2.png)
And I plan to change some more recipes...

It would be cool if there's a simple way to edit the content of this page...
I did some research and I found this: [Adding a Codex Entry](https://manaandartifice.com/api-docs/), which I think is useless to me because I'm not a mod maker, I mean, I could try to make a mod because I know C# that is very similar to java, **but anyway**, it doesn't seem like there is a way to edit the codex, just to add content...

If there's a simple way to edit the Codex and I didn't find, please let me know. But if not, I suggest creating a way to edit the Codex through datapacks, which would be easy for both mod and modpack creators!

**Comment by TochaFh** [comment]
You could adapt the already existent entries json system to add and overwrite and make a way to register them in the config file or automatic!

**Comment by bryceio** [comment]
I believe you can overwrite the codex entries using resource packs.

**Comment by Mithion** [comment]
There is already a folder in the same spot as the codex called "pack_adds" or something similar - you can make a separate version of the codex in there and they will be merged (including translations).  Entries in pack_adds will overwrite the main codex file if they have the same key.
