### ISSUE TITLE
Missing textures when using texture pack

### ISSUE THREAD

**Issue by Esseit** [Mithion/Mana-And-Artifice#217]
This is by no means a major issue, but when using certain texture packs and resource packs many textures for the mod seem to get lost or confused. By this i mean textures for the spell/grimoire books as well as any and all possible spell icons the player could choose appearing blank or a mixture of different textures provided by the pack. Ive also noticed while testing which ones worked and which didn't that the more you change packs, even packs that once worked would lose the icons and textures. F3+T does nothing to help the issue sadly. Ill leave a list of all the packs i personally used in case it is helpful.

-Dark renaissance
-Mythic
-New Default
-Overgrowth
-dokucraft
-invictus

All were found on curse forge for 1.16.5 and used with optifine (no shaders). Hope this helps!

**Comment by Mithion** [comment]
Optifine is the cause of that.

**Comment by Mithion** [comment]
Weirdly, some people have reported turning shaders on helping; but anyway OF breaks too many things with rendering for me to support it.
