### ISSUE TITLE
[Suggestion] Automate Rituals

### ISSUE THREAD

**Issue by DistantDig** [Mithion/Mana-And-Artifice#221]
Automating rituals would be a great addition in my opinion. Automating day/night rituals or mote rituals would be a great addition. I also tried playing around with create and rituals, and having other entities activate the rituals would accomplish this. I would love to see this feature!

**Comment by Mithion** [comment]
You can get pretty close with constructs, but it is something that's on my list.

**Comment by Mithion** [comment]
Decided I don't intend to allow rituals to be automated.
