### ISSUE TITLE
[Suggestion] Using Wands At Any Level

### ISSUE THREAD

**Issue by DistantDig** [Mithion/Mana-And-Artifice#222]
I liked how the spells on wands were level locked, at first. But when playing on a server with my friends I found that no one could use wands unless they progressed in the mod, even if one person already discovered the spell. I think that it would be neat to be able to create wands that unexperienced players could use, since I feel that wands really have no other purpose currently. Also, allowing constructs to use wands could open up a whole new side of automation, such as more permanent sigils or auto-mining.

**Comment by Mithion** [comment]
Not sure what you mean by wands - the structure loot (aka the staves/wands with charges) should be useable by anyone.  But crafted spells you need to progress in order to use.

**Comment by Mithion** [comment]
Looted spell staves can now be used by anyone, even if they haven't unlocked magic.
