### ISSUE TITLE
Codex Arcana  - ATM6 - 1.16.5

### ISSUE THREAD

**Issue by tyroneey** [Mithion/Mana-And-Artifice#223]
Opening the Codex Arcana is causing a glitch where all my items disappear... they are still there. I can see them in my hand as I scroll, but not in the GUI. When I escape and save to the main screen the words are missing off the menu as well.
![unknown](https://user-images.githubusercontent.com/83046326/115801490-bcea7700-a391-11eb-8a89-bca11443f06b.png)

**Comment by ianlavr** [comment]
I think it would be better to report this bug to ATM6 team

**Comment by Mithion** [comment]
This is a common bug related to Optifine, which is not supported.
