### ISSUE TITLE
XP Silktouch dupe

### ISSUE THREAD

**Issue by youngpetar1** [Mithion/Mana-And-Artifice#224]
When you break an ore like coal with a breakspell while having the silktouch ring on, you will get xp as if you broke it normally and get the silktouched ore. You can constantly break the ore over and over and you will get xp.

**Comment by spdkils** [comment]
Silktouch also straight up destroys certain blocks... For example a chest than can hold it's NBT data like crate from cyclic. POOF gone, and all items in it.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with 1.4.0.0
