### ISSUE TITLE
Brooms can pick items from IE's conveyor belts

### ISSUE THREAD

**Issue by LeoBeliik** [Mithion/Mana-And-Artifice#226]
M&A 1.3.0.6
Forge 36.1.6

Both brooms can take items directly from immersive engineers' conveyor belts.
IE adds a tag to the items in belts to prevent this ("PreventRemoteMovement")

**Comment by Mithion** [comment]
Is this tag in the entities' persistent NBT data or in a capability?  Happy to add it, just need to know where to look.

**Comment by LeoBeliik** [comment]
it is a tag in the entities' persistent NBT data.

**Comment by Mithion** [comment]
That's perfect, I'll add a check for it - thanks!

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the release of 1.4.0.0
