### ISSUE TITLE
Cantrip book

### ISSUE THREAD

**Issue by Macdonald1018** [Mithion/Mana-And-Artifice#227]
So I dont see a recipe for the cantrip book in the codex arcana and when I try to input all of the items into the manaweaving table as well as the square and circle, it doesnt create it. Also when I look up Cantrip book in JEI its like it doesnt exist.

**Comment by melbellrocks** [comment]
Open your manaweaver's wand and the cantrips are in there.  You can see how in the tooltip for the wand.

**Comment by Mithion** [comment]
Correct, the cantrip book was merged into the manaweaver wand in 1.3.0.6
