### ISSUE TITLE
Low-importance thing with flowers

### ISSUE THREAD

**Issue by CCheek** [Mithion/Mana-And-Artifice#23]
You can only place each of the plants (tarma root and wakebloom included) on grass, instead of what they would normally be on.

**Comment by Dragon5mith** [comment]
wakebloom can be placed on water, you just need to click on the side of a block next to (and above) the water.

**Comment by Mithion** [comment]
Flower block placement logic has been expanded; flowers can only be placed as follows:

Desert Nova on sand/red sand/podzol/coarse dirt/terracotta
Tarma Root on stone/grass/dirt
Wakebloom on water
Cerublossom and Aum follow normal flower placement rules
