### ISSUE TITLE
Entities and Items turn green when Mana HUD is active

### ISSUE THREAD

**Issue by 1mphuls3** [Mithion/Mana-And-Artifice#231]
I'm using the modpack TNP Limitless 3, there are a ton of mods and I'm not sure what causes it, everything is green only when the mana HUD is active when I disable it with the book it goes back to normal
![2021-05-04_16 45 22](https://user-images.githubusercontent.com/83678985/117082864-32423a00-acf8-11eb-8d30-397469341d94.png)

**Comment by JolllyJester** [comment]
I also have Have had this bug. Seems to happen when you spam cast a spell. Your input on disabling the HUD really helped! thanks.

**Comment by dacendale** [comment]
I also have this issue. Using Optifine and using any shader (including the internal one) suppresses the problem.

**Comment by Mithion** [comment]
It's also been suggested that it's a conflict with minimap mods as well, setting the render layer can help.

**Comment by JolllyJester** [comment]
How would one set that?

**Comment by 1mphuls3** [comment]
I just tested it, disabling Xaero's map and enabling the ftb chunks map fixed it.

**Comment by VirtualGaming1** [comment]
issue with map like this issue that is closed now:
#206

**Comment by SteamDoge9000** [comment]
this is issue is back, im using complimentery shaders adn everytings works fine, but I noticed with the currrent modpack I have that now if I enter creative mode while the mana bar renders, this will cause what was seen to happen again, and even vanish and reapear dependining on the pitch of the players head, this issue and visual errors cease when you go back into survival mode or disable the GUI Mana bar render alltoghether

**Comment by SteamDoge9000** [comment]
ill post a log on this happening if this issue is reopened

**Comment by SteamDoge9000** [comment]
snapshots:

no mana bar
![image](https://user-images.githubusercontent.com/38770780/139519088-31bcf6f9-22b0-4dec-8644-0c7e8114f0e6.png)


Mana bar renders!

![image](https://user-images.githubusercontent.com/38770780/139519098-45921808-aafb-4dee-8b27-7d12f1c1c902.png)
![image](https://user-images.githubusercontent.com/38770780/139519103-c4729043-ebb0-404e-955a-5f31d80963d0.png)
![image](https://user-images.githubusercontent.com/38770780/139519139-949d94da-181a-4dc4-862c-0a80870422dc.png)

Shaders present: Yes; Complimentary wtih complimentery mode on

Issue is non existent if your in survival however for some odd reason

![image](https://user-images.githubusercontent.com/38770780/139519201-859cd553-1b68-456a-a2a3-82de81ea54d5.png)
