### ISSUE TITLE
Ritual needed items not appearing

### ISSUE THREAD

**Issue by Bilhalva1** [Mithion/Mana-And-Artifice#233]
i put the Purified Vinteum Dust in the middle and it just turns purple, i tried to change the settings but nothing works

**Comment by Mithion** [comment]
What are your graphics settings on?
Do you have particles disabled?
Are you running latest version 1.3.0.6?

**Comment by Bilhalva1** [comment]
everything 
nope
yup

**Comment by AmongThem** [comment]
Hey, I believe the issue might be with the Forgery mod (forgery-1.3.4.jar) with the Cracking Spawn Eggs enabled in the Tweaks section. If you turn that off, rituals will work again. Sorry if this doesn't help you but I came across this similar issue too and wanted to disclose my solution. Hope this helps!

**Comment by Mithion** [comment]
That was confirmed to be the issue, thanks!
