### ISSUE TITLE
[1.16.5] Mod conflict LOTR grass crashes the server when grow spell used.

### ISSUE THREAD

**Issue by ProsperCraft** [Mithion/Mana-And-Artifice#234]
Dedicated server crash when bonemeal applied to LOTR grass.
https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed

Vanilla bonemeal doesn't crash the server.

Modpack - https://www.curseforge.com/minecraft/modpacks/towncraft

Crash report-
https://gist.githubusercontent.com/ProsperCraft/68bd44c24645029df94f952374c617cb/raw/d4574a40c7ace071cc223e7df31a0af13039afcf/gistfile1.txt

Debug log- 
https://gist.githubusercontent.com/ProsperCraft/b111486d329053d6ba37d00047d6cdee/raw/00b13f076404b10550ecb72a628ca85fa366ae7d/gistfile1.txt

**Comment by Mithion** [comment]
Hey sorry it took me so long to get back to you on this!
I'll take a look and see if I can fix the issue and make grow work fully, otherwise I can add some code to at least prevent the crash from happening.

**Comment by Mithion** [comment]
Closing as 1.16.5 is no longer supported.
