### ISSUE TITLE
Multiplayer server crashed when player casting sigil and rift is no longer online

### ISSUE THREAD

**Issue by Mikevandee** [Mithion/Mana-And-Artifice#236]
We are playing mod pack(all the mods to the sky) with this mod. And if I'm reading the crash report correctly mana-and-artifice seems to be the cause.

Steps for reproducing the bug:

1. player A places sigil on ground with rift.
2. player A goes offline
3. player B walks on top of sigil

Here are the crash reports:
[crash-2021-05-09_19.00.22-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6448068/crash-2021-05-09_19.00.22-server.txt)

**Comment by Mithion** [comment]
Hey sorry it took me so long to get back to you on this!

I'll make sure I get this all fixed up for next release.

**Comment by Mithion** [comment]
This has been fixed in dev, and will go out with version 14.0.0.
