### ISSUE TITLE
Ritual kit description should say Ctrl-Click to open the kit

### ISSUE THREAD

**Issue by abadger** [Mithion/Mana-And-Artifice#238]
mana-and-artifice: 1.3.0.6
mod pack: Direwolf20-1.16 v1.9.0

The Codex entry for ritual kits reads:
> Sneak right click on empty space to open the bag

It should read:

> Control right click on empty space to open the bag

Sneak right click attempts to set the ritual when it is clicked on an existing layout or place the ritual when on an empty space.

**Comment by Mithion** [comment]
Got it, thank you!  I'll fix up the translation.

**Comment by Mithion** [comment]
This has been fixed in dev, and will go out with version 14.0.0.
