### ISSUE TITLE
My mana bar vanished

### ISSUE THREAD

**Issue by TheRealAirShock** [Mithion/Mana-And-Artifice#239]
Something in the server was broken so i went in game mode to quikly fix it after this i realized that i had no more mana bar.
I cant figure out how to get it back is it couse i quikly did something with making golems? or spells?

**Comment by Mithion** [comment]
Hey sorry it took me so long to get back to you on this!
There are tabs at the bottom of the Codex that change how the HUD works - you likely clicked one by mistake and changed the UI to "never show" or "only show while holding something that consumes mana".
