### ISSUE TITLE
Constructs voiding items. Possibly when attempting to put an invalid item into a rune scribing table.

### ISSUE THREAD

**Issue by abadger** [Mithion/Mana-And-Artifice#241]
mana-and-artifice: 1.3.0.6
mod pack: Direwolf20-1.16 v1.9.0

This may be a regression of: https://github.com/Mithion/Mana-And-Artifice/issues/176 but I suspect it's a different bug.

I have a construct built for rune forging.  It has a gold smart head, wooden basic torso and legs, wooden hammer and wooden grabber arms.  Eight air aspects.

It is set to run with the following lodestone commands:
* take item from chest1.  (No filter, first item in chest is a stack of two [fired] rune patterns.)
* place on top of rune scribing table
* scribe rune (Pattern: construct rod)
* take from rune scribing table (no filter)
* place on anvil
* take item from chest1 (filtered: super heated purified vintium ingot.  A stack of two of these is in the second position of chest1)
* place on anvil
* forge rune
* take item from anvil (no filter)
* place item in chest2

chest2 is a double chest.  The chest has four filled rows and two empty rows.  I'm unsure if the marker is associated with the "full" half of the chest or the "partially filled" half of the chest but I suspect it's the full half.

The construct will go through the steps until it gets to placing items in chest2.  At that point, it fails to put the pattern in the chest.  Visually, it looks like it continues to hold onto it.  The construct then runs over to chest1 to pick up the next rune pattern. The construct fails to pick up the next blank pattern (because it already has the construct rod in its grabber hand).   Then it runs over to the runescribing table and places the rod into the top of the rune scribing table.  I believe this is where the rod is voided.  The construct proceeds along the commands specified in the lodestone but ends up making a further mess of things because it didn't scribe the pattern at the beginning of the process.  I think it ends up picking up the raw ingredients at various unintended steps and then eventually voiding each of them in the rune scribing table.

I'll attach a screenshot of the construct diagnostics window showing the first set of failures to where the initial rod is voided.

![2021-05-12_14 11 49](https://user-images.githubusercontent.com/209242/118045664-114b9b80-b32d-11eb-9958-0e8f5f4bbc8e.png)

**Comment by Mithion** [comment]
This is a great error report, thanks!  Has everything I need to recreate the circumstance and fix the issue.  I wish everyone was so thorough 😄 

I'll do what I can to get this fixed up for the next version!

**Comment by abadger** [comment]
Thanks @Mithion! I know how frustrating getting a non-reproducible bug is so I do my best when I'm the reporting end :-)

**Comment by Mithion** [comment]
This was resolved in 1.4.0.4 (Alpha on Curseforge)
