### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Arsonance** [Mithion/Mana-And-Artifice#243]
It involved the Cauterize spell, and Fireshield, I know that much
[crash-2021-05-16_18.14.21-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6489806/crash-2021-05-16_18.14.21-server.txt)

**Comment by Mithion** [comment]
This will be a tricky one as it seems to be related to Astral Sorcery and Botania's mixins as well as M&A - I'll see what I can do.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
