### ISSUE TITLE
warding candle

### ISSUE THREAD

**Issue by jokerace86** [Mithion/Mana-And-Artifice#244]
warding candle and forge conflicting on atm6 server
![Screenshot_20210522-024833_Chrome](https://user-images.githubusercontent.com/80618446/119217754-5351ab80-baaa-11eb-949f-be9e25673421.jpg)

**Comment by Mithion** [comment]
from the end:
"This is not an M&A bug, this is a Forge Issue"

Forge shouldn't be throwing this event if the entity is null, or they should tag the field as @Nullable.
That event indicates that M&A is allowing the event through to prevent a crash, but it means that a mob spawn may have slipped through the warding candle's protection.
