### ISSUE TITLE
JEI is visible in the Codex Arcana

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#245]
![image](https://user-images.githubusercontent.com/15698722/119505645-c9684380-bd32-11eb-8242-23ed37d50ba2.png)

Using mana-and-artifice-1.3.0.6

**Comment by Mithion** [comment]
I only recently learned you can toggle JEI off for specific UIs so yeah definitely I'll be fixing that up.  Thanks!

**Comment by Mithion** [comment]
This has been fixed.

**Comment by SteamDoge9000** [comment]
@Mithion yeah, I would like to say that but I just came across this with the current version that was released, I think you might have forgoten about the overlay produced by the Occulus
![image](https://user-images.githubusercontent.com/38770780/147841820-1e0940b9-a297-4be6-9372-dc15634d1406.png)
