### ISSUE TITLE
Arcane Furnace recipes should use the Runeforge as its catalyst in JEI

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#247]
![image](https://user-images.githubusercontent.com/15698722/119507450-78f1e580-bd34-11eb-96ec-4e557f4abffd.png)

Basically it should show the Runeforge on the left, like it does for most things from other mods:
![image](https://user-images.githubusercontent.com/15698722/119507593-94f58700-bd34-11eb-970e-9339fc4395a8.png)

This should be done for the other MaA things as well.

**Comment by Mithion** [comment]
Not sure how I would go about doing that but I will look up how to do so and get it done!

**Comment by Mithion** [comment]
This has been completed.
