### ISSUE TITLE
[Request] Tooltips for the reagents in the Inscription Table

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#248]
![image](https://user-images.githubusercontent.com/15698722/119513828-2ca9a400-bd3a-11eb-81f4-faf20dabf2d4.png)

I have no idea what this is, item tooltips would be very much appreciated

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/119516045-0553d680-bd3c-11eb-994d-57da31254283.png)

Oh this works actually! Adding tooltips to the Table would still be nice, but now it's way less major of an issue

**Comment by Mithion** [comment]
Because that right click thing exists, I'm actually going to remove the items from the inscription table.

It has all kinds of other issues, such as no tooltips, it can overflow over the bottom of the UI (and scrolling UIs are *evil*), and I think it causes more confusion than it prevents.
