### ISSUE TITLE
The Codex Arcana mentions a "cantrip book," but I can't find it in JEI or the creative menu

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#249]
![image](https://user-images.githubusercontent.com/15698722/119522340-7e096180-bd41-11eb-8741-3b49edb7730e.png)

**Comment by Mithion** [comment]
This is a known issue; it's actually been fixed in dev.
The Manaweaver Wand and the Cantrip Book were merged in 1.3.0.6 but I forgot to update the codex accordingly.  Look to the tooltip on the Manaweaving wand to access the Cantrip Book's functionality.

**Comment by aaronhowser1** [comment]
When I hold control and then right-click the Manaweaver's Wand, it uses up a stream of Mana as if I were drawing something.

https://user-images.githubusercontent.com/15698722/119525270-f5d88b80-bd43-11eb-9a2a-9abcfe8bac1f.mp4

The GUI for that also isn't very clear, I don't know what I'm supposed to be doing in it. There's three slots, and I can change the shape in each, but I don't know what to do with it.

**Comment by Mithion** [comment]
It's on my list to improve that UI to be more clear, and I've already fixed the manaweave start when you're opening the GUI.

**Comment by Mithion** [comment]
The layout is like this:

Tier 1 | Tier 3
Tier 2 | Tier 4
Tier 3 | Tier 5

The cantrips are:

Ignite      | Custom Spell 1
Dispel     | Custom Spell 2
Grimoire | Custom Spell 3

**Comment by aaronhowser1** [comment]
So you get to choose what combination of shapes makes the cantrip?

![image](https://user-images.githubusercontent.com/15698722/119527032-8cf21300-bd45-11eb-8606-d2ad831a67c9.png)
I tried setting fire to just be 2 circles, but when I make two circles in succession nothing happens.

https://user-images.githubusercontent.com/15698722/119527364-e0646100-bd45-11eb-9f1f-68b9d6ff2ae0.mp4

**Comment by Mithion** [comment]
The square merged with the circle - left click a floating shape with the wand to remove it (and get some of the mana back too).
I fixed the render issue where they don't render the patterns on top of each other properly in dev.

You can also use Manaweave in a Jar or Projectors to do the patterns more easily.  I have another large scale improvement to the recognition engine in the works which should make it *way* more accurate.

You did set the pattern correctly though, and if you do 2 circles it will work and try to set fire to the block you're targeting (short range, like 4 blocks).

**Comment by Mithion** [comment]
Closing as fixed in dev as I'm cleaning up my remaining to-do list.
