### ISSUE TITLE
More small flower issues

### ISSUE THREAD

**Issue by BinaryEnigma01** [Mithion/Mana-And-Artifice#25]
All of the flowers are rendered in hand as `BlockItems` when they should be `Items`

Also, wakeblooms are not destroyable by passing through them with boats (or bubble boats), this may be intended, and if not, maybe too much effort to implement for about 3 people to notice

**Comment by Mithion** [comment]
Flower rendering has been fixed, and wakebloom are now removed when colliding with a player in a boat.
