### ISSUE TITLE
Include the required tier in the tooltip or recipe

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#250]
If I need something that needs, say, Infused Thread, but I'm only level 1, I wouldn't know I can't craft it until it doesn't work.

It should say somewhere here, or in the item's tooltip what level you have to be before you can craft it
![image](https://user-images.githubusercontent.com/15698722/119524061-e86ed180-bd42-11eb-8ed2-ffaaffb810d7.png)

**Comment by Mithion** [comment]
Agreed; been thinking about that for a while.  Actually considering trying to hide it from JEI until you're the requisite tier, but a warning on the JEI recipe wouldn't be a bad idea either.

**Comment by aaronhowser1** [comment]
I'd argue against hiding them, since then it might cause confusion on if the mod updated and removed those items and the video you're watching is outdated (like the cantrip book) or if you just aren't at a high enough tier to see it

**Comment by Mithion** [comment]
The manaweaving wand thing is a bug; not intended to be the norm so I'm not too worried about that.  Better tooltips and correct codex can mitigate that concern.

A point in favour of hiding them is that's what the Codex already does; it only shows you things for your tier.

**Comment by Mithion** [comment]
This has been completed.
