### ISSUE TITLE
The HUD page doesn't explain how the HUD actually works

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#251]
![image](https://user-images.githubusercontent.com/15698722/119526593-23720480-bd45-11eb-86a9-4d349e73efc9.png)

Took me a hot second, but I figured out the bottom bar is your progress towards next magic level, but what's the difference between the two bigger blue bars? Why is there a smaller, lighter blue bar on top of the darker one, and why does it stop before the end?

**Comment by Mithion** [comment]
It's estimated mana consumption of the current spell :)

**Comment by aaronhowser1** [comment]
🤦 yeah that makes sense lol

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the 1.4.0.0 release.
