### ISSUE TITLE
[Request] A way to instantly turn a spell recipe into a spell for creative mode

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#252]
If I'm just testing spell stuff in creative mode, I don't really want to keep making the same ritual over and over again (fun as it is)

**Comment by Mithion** [comment]
Making spells in the inscription table is instant if you're in creative.

You can also use the Book of Rote to test more complex spells in creative as it has (almost) everything unlocked by default if you're in creative mode.

For creative testing, do a **/setTier 5** and then for faction-specific things you can use **/setFaction** to change between the factions.

**Comment by aaronhowser1** [comment]
The inscription table makes spell recipes, not spells. You have to do the ritual to make it into a spell every time.

**Comment by aaronhowser1** [comment]
Wait, nevermind. I have the dumb.
