### ISSUE TITLE
When you close the book, it forgets what chapter you were in

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#253]
![image](https://user-images.githubusercontent.com/15698722/119538399-b2384e80-bd50-11eb-8f4c-abc0664c4c83.png)
If I right click from here, I go to the Artifice chapter, which is good.

But if I go back to that page, then escape to close the book, then open it, I go back to the same page (which is good), but right click sends me to Basics

**Comment by Mithion** [comment]
Resolved in later versions of the mod.
