### ISSUE TITLE
It's hard to make an informed decision on which faction to join, since you can't see descriptions of what they give you until you've chosen

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#254]
A tier 2 mage who's about to enter tier 3 has to choose a faction. This is a hard decision, and one you can only make once.

They can check the Occulus and see the names and textures of items that each faction unlocks, but they can't actually read what they do. You can't know what the Unguent of Seeing is, so you don't know if it's better than the Bracelet of Trickery or Emberglow Bracelet, for instance.

Maybe hovering over items in the Occulus could show a brief description of what they do?

**Comment by aaronhowser1** [comment]
Sorry for making so many issues all at once by the way! I'm making quests for them, and I'm having a blast learning the mod

My progress so far
![image](https://user-images.githubusercontent.com/15698722/119548637-07c62880-bd5c-11eb-8fa7-f97fe0d61d79.png)

**Comment by Mithion** [comment]
Wow, that looks awesome!  What mod is making the quests?

I've been thinking that you've been flying through it *ha-ha*
I don't mind the posts at all.  I appreciate the help in making the mod the best it can be.

If you like, we also have a very active Discord server where you can toss ideas around (if you aren't there already)!
http://discord.gg/4nJEU4X

**Comment by aaronhowser1** [comment]
The quest mod is FTB Quests. I'll definitely be hopping on the server too, I'm having a lot of fun with the mod

**Comment by Mithion** [comment]
The codex has been rewritten to be much more clear now.
