### ISSUE TITLE
Server crash ConfiguredFeature not being registered

### ISSUE THREAD

**Issue by ProsperCraft** [Mithion/Mana-And-Artifice#256]
mana-and-artifice-1.3.0.6
Modpack- [TownCraft TWO for 1.16.5](https://www.curseforge.com/minecraft/modpacks/towncraft)

Server debug log with extra stuff from not enough crashes-
https://gist.githubus0ercontent.com/ProsperCraft/42aed323afab9a9b88fcdc78cafa4d2e/raw/9634295bc0bcb90743b1cd90faf23c0853d2e2b4/gistfile1.txt

Crashes we were getting before getting that nice debug log-
https://gist.githubusercontent.com/ProsperCraft/c13134fd1ac820a590794e349ab504c6/raw/e2f52219b36957b69f6ea8306380e8035a361f5b/gistfile1.txt

Another crash in a different biome-
https://gist.githubusercontent.com/ProsperCraft/deca14ce23e856dc0fed156231f0d518/raw/de532077b7a5f32e3c2031fc43eb28e9a17acf06/gistfile1.txt

Reply from LOTR mod author when reported there-

`Lars Ludwich (big floppa): Yep, looks like a bug in mana-and-artifice, trying to generate that cerublossom and aum flower patch. It's telling that the same crash occurs trying to generate in both lotr:old_forest in M-E (lotr mod) and minecraft:forest in the overworld (vanilla). The crash is coming via the FlowersFeature class, which indicates that something is going wrong in a flower worldgen feature, matching the debug JSON printout of the configured feature.
Note that the Not Enough Crashes Report is complaining about the ConfiguredFeature not being registered (i.e. the flowers) not the biome.`

**Comment by Mithion** [comment]
Great, thanks!  I'll take a look and see what I can do.

**Comment by ProsperCraft** [comment]
Here is another CME server crash, hope it helps.- https://gist.github.com/ProsperCraft/51e184e999c54072a612e1b43e2ec7a2
