### ISSUE TITLE
Lodestar GUI is way too high in low resolution / small window

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#258]
![image](https://user-images.githubusercontent.com/15698722/119667340-d1d88100-bdfb-11eb-9f5f-e81fb1a7c8ba.png)

**Comment by Mithion** [comment]
What size resolution is this?

**Comment by aaronhowser1** [comment]
The window (or at least a screenshot of it, idk how to count otherwise) is 856x512

**Comment by Mithion** [comment]
Fixed in dev for next release.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
