### ISSUE TITLE
Construct can't get to block right next to it

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#259]
![image](https://user-images.githubusercontent.com/15698722/119667456-ee74b900-bdfb-11eb-97c5-a38143bc18d7.png)

This is the area it tries to chop trees in

It's basically just alternating between these two

https://user-images.githubusercontent.com/15698722/119667589-0a785a80-bdfc-11eb-9eab-10f5ba2e4735.mp4

(also, shouldnt it just say it once? is it trying to make a message every tick or something)

![image](https://user-images.githubusercontent.com/15698722/119667523-fd5b6b80-bdfb-11eb-9b02-5fa7af06e0d5.png)

It is very slowly making progress, somehow. It hasn't moved at all.
![image](https://user-images.githubusercontent.com/15698722/119667750-30056400-bdfc-11eb-9751-ca8d34a7d7c6.png)

**Comment by Mithion** [comment]
I have this issue fixed in dev

**Comment by Mithion** [comment]
This has been fixed in dev, and will go out with version 14.0.0.
