### ISSUE TITLE
Cant use touch break on redstone because it just activates the block

### ISSUE THREAD

**Issue by wink28** [Mithion/Mana-And-Artifice#26]
![Untitled](https://user-images.githubusercontent.com/66880550/84600134-44e42400-ae45-11ea-9bbc-5ea5e8c4c98c.png)

**Comment by Mithion** [comment]
It's intentional, to prevent spells from triggering when trying to open a chest.
Sneak+activate to force the spell to bypass block activation.

It's the same with a bow, for instance.
