### ISSUE TITLE
[Request] Recipe compatibility expansions.

### ISSUE THREAD

**Issue by bryceio** [Mithion/Mana-And-Artifice#260]
I've noticed quite a few recipes in the mod that could have their materials expanded into tags rather than specific items without hindering the balance of any of the recipes. Using tags in these cases will not only expand some of the vanilla materials usable within the mod, but also provide a cleaner avenue for compatibility with items from other mods. I went through and made a datapack of all the recipes that I noticed that could benefit from this, which I have attatched here as well as sent in the modpacks channel on Discord.
[MACompatPack.zip](https://github.com/Mithion/Mana-And-Artifice/files/6546866/MACompatPack.zip)

While having this as a datapack is nice, I believe it would be better as a part of the mod's base data rather than requiring an additional file.

**Comment by Mithion** [comment]
Thanks!  I'll take a look through and see.

**Comment by Mithion** [comment]
These have been applied - thanks!
