### ISSUE TITLE
Chimerite Crystals are weirdly dark

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#261]
![image](https://user-images.githubusercontent.com/15698722/119673044-ae640500-be00-11eb-8f3a-2ee2f3339d97.png)

**Comment by Mithion** [comment]
They don't appear to be any darker than the table next to them...it looks fine to me.
What are you expecting, that they emit light or something?

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/119705982-027de200-be1f-11eb-8ab8-5c07017b76b4.png)

The white crystal looks more like a black or grey crystal.
![image](https://user-images.githubusercontent.com/15698722/119706152-3b1dbb80-be1f-11eb-9d45-dc1945a53903.png)
The one on the left is White, the one on the right is Gray

![image](https://user-images.githubusercontent.com/15698722/119706254-58528a00-be1f-11eb-8531-f1bf20a57afd.png)
This doesn't look like white to black, it looks like gray to black to vantablack
