### ISSUE TITLE
[Request] Enchantment Descriptions support

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#263]
The mod [Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions) adds tooltips and JEI pages for enchantments, dynamically generated using the lang key `enchantment.[modid].[enchantment].desc`

![image](https://user-images.githubusercontent.com/15698722/119677667-85de0a00-be04-11eb-9982-070d31ca8286.png)

**Comment by Mithion** [comment]
These have been added in 1.5.1.5.
