### ISSUE TITLE
[Request] Spawn eggs for mobs

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#265]
I could use /summon, but I don't know which entities are actual mobs and which are like, ritual things. 
![image](https://user-images.githubusercontent.com/15698722/119704467-4d96f580-be1d-11eb-9379-40bdba4fc13c.png)
I feel like I shouldn't spawn half of these

**Comment by Mithion** [comment]
Faction mobs need additional parameters set on them to function properly that spawn eggs don't provide; this will lead to far more bug reports from people who don't know what they're doing.
