### ISSUE TITLE
Having the mana HUD up makes everything blue/green and transparent 

### ISSUE THREAD

**Issue by IzzyWasBusy** [Mithion/Mana-And-Artifice#267]
Depending on where I'm standing and what direction I am facing when I have my mana HUD enabled it makes my game blue/green tinted or makes all text and items transparent.

**Comment by Mithion** [comment]
There's an issue with Optifine and/or minimap mods.  Remove Optifine as it isn't supported, but with minimap mods there are some options that can help.

I don't use minimap mods personally, so this is all secondhand:
- Disable internal shaders
- Change the render layer in the minimap options

I'm working on a fix for minimap conflicts. but I have no intention of supporting Optifine (though the fix may also work with it, I don't guarantee it).

**Comment by Mithion** [comment]
Closing this as a duplicate issue.
