### ISSUE TITLE
TODOS os itens perdem a textura

### ISSUE THREAD

**Issue by iangg123** [Mithion/Mana-And-Artifice#268]
Todos os itens perdem a textura ao usar o "fling". Todos eles ficam com a cor verde.
![20210527_155623](https://user-images.githubusercontent.com/84933490/119881829-1bac8e80-bf04-11eb-8432-289cec567869.jpg)

**Comment by TochaFh** [comment]
@Mithion, in English: "All items lose texture when using 'fling'. They become green."
@iangg123, Antes de tudo, verifique se o mana-and-artifice e os outros mods estão atualizados em suas últimas versões e veja se o bug ainda acontece com os mods atualizados (e avise aqui o resultado). Se o bug permanecer, disponibilize a lista de mods do seu modpack aqui e procure se tem algo relacionado a esse bug (algum aviso de "error" ou "exception") nos logs do jogo (e também avise aqui se achar algo). Dessa forma fica mais fácil de encontrar o causador do bug! Obs: não sou desenvolvedor desse mod, mas sei que os devs precisam dessas informações.

**Comment by TochaFh** [comment]
@iangg123 esse bug ja foi discutido aqui: #231

**Comment by iangg123** [comment]
@TochaFh valeu pela resposta cara, eu não tinha ideia do que tinha acontecido, então fui verificando os mods um por um, até encontrar oq causava o problema. No meu caso era o xaeros world map, assim que eu tirei ele, resolveu o problema. Mas, obrigado pela ajuda.
