### ISSUE TITLE
The book doesn't say how to get the Brimstone Boat

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#269]
![image](https://user-images.githubusercontent.com/15698722/119884517-560f2f00-bef6-11eb-97d5-747b34ca0e7c.png)

The page doesn't say how to get it

![image](https://user-images.githubusercontent.com/15698722/119884539-5e676a00-bef6-11eb-97d2-83a685ea43aa.png)

The Brimstone Charm page says that it's used to make the Boat, but doesn't say what you actually do with it. Apparently you aren't just supposed to right-click the Boat with the Charm.

**Comment by Mithion** [comment]
This has been fixed in dev, and will go out with version 14.0.0.
