### ISSUE TITLE
[bug] enchantments

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#27]
enchantments aren't limited to the items that they are usable on.  A diamond chestplate was enchantable with power 5, and I couldn't enchant a bow with power 5. the hammering went successfully, but the enchantment didn't happen.

will add comments with more issues found.

**Comment by Dragon5mith** [comment]
bows appear completely unenchantable at the runic anvil

**Comment by Dragon5mith** [comment]
the sharpness enchant doesn't have the proper surrounding chalk items in the codex. (or something else is wrong)

**Comment by Dragon5mith** [comment]
not my testing, but these items seem to void enchants attempted on them.
![enchanting voids](https://user-images.githubusercontent.com/8917961/84607579-103f8f00-ae7c-11ea-8f65-b38ff9160a15.png)

**Comment by Dragon5mith** [comment]
efficiency requires purified vinteum, which can't be placed on metal runes

**Comment by ace10102** [comment]
channeling can be applied to tridents, bows, crossbows, fishing rods, and books

**Comment by Dragon5mith** [comment]
unbreaking 1: successfully enchanted
![unbreaking1success](https://user-images.githubusercontent.com/8917961/84611885-05d9c100-ae8d-11ea-97fb-687dd5348b93.png)
items which get the hammering, but not the enchantment:
![unbreaking1eat](https://user-images.githubusercontent.com/8917961/84611865-01150d00-ae8d-11ea-811b-8ba8ef45cbec.png)

**Comment by Dragon5mith** [comment]
sweeping edge; clarity issue between smooth and regular quartz
1: works on irregulars (bow, crossbow, fishing rod, book, trident)
2&3: irregulars eat them

Smite:
1: works on irregulars
2-4: don't work on irregulars
5: doesn't work on runic anvil: mislabled blaze powder in file

silk touch: works on all

**Comment by Mithion** [comment]
Runic anvil now properly checks to ensure that the enchantment can be applied to the given items.  It also will eject invalid items instead of consuming them.
Sharpness recipe (and many others) were corrected.
