### ISSUE TITLE
Ritual Kit will not function

### ISSUE THREAD

**Issue by livieloo** [Mithion/Mana-And-Artifice#270]
I only just recently started using this mod and I'm having an issue with the ritual kit on a server with some friends. When I have a ritual set and activated, the kit does not bind to the ritual even with the items inside the kit. It worked for the Ritual of Aurora, because I specifically knew to conduct it at night, but the Ritual of Arcana does not bind to the kit. Is there a certain process for using the ritual kit that is not specified?

**Comment by sniggyfigbat** [comment]
I'm having similar issues; I can't get the Ritual of the Searing Inferno to bind. I'm fairly confident I'm doing it right, as I'm doing exactly what's shown in [this video](https://www.youtube.com/watch?v=e8AgWbQW5eY&t=1412s), and I've tried a bunch of variations.

Also on a server, M&A 1.3.0.6, forge 36.1.24.

**Comment by bryceio** [comment]
> I only just recently started using this mod and I'm having an issue with the ritual kit on a server with some friends. When I have a ritual set and activated, the kit does not bind to the ritual even with the items inside the kit. It worked for the Ritual of Aurora, because I specifically knew to conduct it at night, but the Ritual of Arcana does not bind to the kit. Is there a certain process for using the ritual kit that is not specified?

The Ritual of Arcana cannot be placed into a ritual kit due to its dynamic nature.

**Comment by bryceio** [comment]
> I'm having similar issues; I can't get the Ritual of the Searing Inferno to bind. I'm fairly confident I'm doing it right, as I'm doing exactly what's shown in [this video](https://www.youtube.com/watch?v=e8AgWbQW5eY&t=1412s), and I've tried a bunch of variations.
> 
> Also on a server, M&A 1.3.0.6, forge 36.1.24.

Are you performing the ritual in the nether?

**Comment by sniggyfigbat** [comment]
> > I'm having similar issues; I can't get the Ritual of the Searing Inferno to bind. I'm fairly confident I'm doing it right, as I'm doing exactly what's shown in [this video](https://www.youtube.com/watch?v=e8AgWbQW5eY&t=1412s), and I've tried a bunch of variations.
> > Also on a server, M&A 1.3.0.6, forge 36.1.24.
> 
> Are you performing the ritual in the nether?

Yes, and it works perfectly when drawn by hand. It's just the ritual kit that doesn't seem to work.

**Comment by Mithion** [comment]
Ritual kits have been improved and will go out in 1.4.0.0.
