### ISSUE TITLE
ring of enderman functionality

### ISSUE THREAD

**Issue by datnameis** [Mithion/Mana-And-Artifice#272]
I'm not sure if this is just a lack of information on proper usage or an actual bug but the ring of enderman does not double blink spell distance as advertised, and does not offer any block targeting mechanics. The section in the book says something about the shapes used to cast it but is very unclear about how it works.

**Comment by Mithion** [comment]
If you use something like bolt or projectile blink and target a block, it will attempt to blink you on top of that block with the ring equipped.  Teleporting this way will allow you to go twice the range that's set on the spell.
