### ISSUE TITLE
Request: Beehive Construct Interactions

### ISSUE THREAD

**Issue by Sn0wShepherd** [Mithion/Mana-And-Artifice#273]
Can you add Smoke Hive and Scrape Hive to the Lodestar?

Apparently it's another independent subroutine.  :(  

I couldn't get activate block to work with it.

Thank you for an AMAZING MOD!

If you need music or SFX work done, let me know!

I am the creator of Sn0wZone resource pack and musician for TolkienCraft 2 and 3, and a lot more.  I love the Minecraft community.  I been sick a LONG time, so, it's taking me a lot of effort to get Sn0wZone updated to 1.16.x.

**Comment by Mithion** [comment]
This has been added in dev and will go out with the next release (1.18.1)
