### ISSUE TITLE
Manaweave wand flickers right-click + vanishes if you right-click on an active ritual's runes

### ISSUE THREAD

**Issue by ArtOfCombat** [Mithion/Mana-And-Artifice#274]
The manaweave wand won't let me hold right-click, and vanished twice during a ritual while tracing patterns. It spams right-click as I hold the button, whether I use my trackpad or mouse, an issue I've never had before, and vanished twice over - probably because I accidentally hovered over the center rune as it right-click spammed.

**Comment by ArtOfCombat** [comment]
I figured out the flickering - I was running out of mana. However, that means if you run out of mana while hovering over a ritual, your wand vanishes.

**Comment by Mithion** [comment]
Rituals voiding items is a known issue and has been reported so I'm going to close this as a duplicate.
