### ISSUE TITLE
Watching server bug/Ticking entity bug

### ISSUE THREAD

**Issue by asdfghjkl403622** [Mithion/Mana-And-Artifice#275]
[crash-2021-06-05_03.15.02-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6603297/crash-2021-06-05_03.15.02-server.txt)
I have been trying to debug this bug for about a week now, and despite enabling the "remove arroring entities" and "remove erroring tile entities" settings it did not go away. this bug only seems to occur when loading certain chunks with lots of items in them, or new chunks in the end. Then, after believeing it to be a ram issue, I moved the serevr over to a computer where I could supply 15GB of ram only to be met with this new error when I tried to teleport using a ritual: 
[crash-2021-06-05_21.56.42-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6603307/crash-2021-06-05_21.56.42-server.txt)
I am lost and I hope it's just a setting I can change.

**Comment by Mithion** [comment]
Looks like there's a ritual entity that has lost its caster reference and is assuming it will have it, which will crash on load.
I've put in an additional check which will fix this in 1.4.0.0 when it releases, and will simply cause the ritual to fail and despawn.

In the meantime, if you can pinpoint the location of the erroneous ritual entity, you can remove it with a world editor.
