### ISSUE TITLE
[Request] A dimension or biome blacklist for enemy faction raids

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#276]
![image](https://user-images.githubusercontent.com/15698722/120919791-044a6f80-c681-11eb-9fa9-b0abae639af8.png)

This dimension is for schools, small interactive areas for learning parts of mods. This one specifically is for spatial storage from AE2.

Schools are kind of non-canon, nothing outside of the school interacts with the school, and nothing inside the school interacts with outside the school.

I just got attacked by a bunch of Spellbreakers and Witch Hunters in the school. And, while _absolutely hilarious_, that's not a great thing to happen. A way to disable this (**only in the schools**, or wherever else a pack dev wants to be safe) would be greatly appreciated.

**Comment by Mithion** [comment]
Individual enemies can now be blacklisted by dimension in the entities config file.
