### ISSUE TITLE
Runes like arcane, air, earth not working

### ISSUE THREAD

**Issue by Octo-chan** [Mithion/Mana-And-Artifice#277]
So I don't know If I'm being just dumb, but me and my brother play on a server and we can't make these 3 runes, we tried other and some work, for example the aura or defense rune patterns work, but not these 3, I don't know how many work/don't since we only tried these 5, Is It just us being dumb, or do they not work?
![2021-06-06_13 51 46](https://user-images.githubusercontent.com/80170719/120924751-7056c300-c6d5-11eb-96ae-82d7b6f13104.png)

**Comment by Th1med** [comment]
same here
