### ISSUE TITLE
Sildurs Shaders Incompatibility

### ISSUE THREAD

**Issue by Desanguin8ed** [Mithion/Mana-And-Artifice#278]
When I use my shaders and the HUD showing my mana comes up, everything goes blank. Items in my inventory don't render, chat goes blank. When I turned off the Shaders, it fixed.

**Comment by Desanguin8ed** [comment]
Update: it's the same for Chocapic.

**Comment by Mithion** [comment]
Shaders are not currently supported.  There are other issues with this same information so going to close as duplicate.
