### ISSUE TITLE
manaweave enchant

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#28]
the manaweaving portion of enchanting allows enchanting/enchanted runes (and probably regular items) in the recipe

**Comment by Mithion** [comment]
Not sure I want to change this.  Should be up to the player to choose what to use, enchanted or no.

Will change to exclude damaged items though.

**Comment by Mithion** [comment]
Manaweave recipes no longer allow damaged or enchanted items to be used for crafting.
As much as I like having a use for the enchanted things you may not need anymore, after some thought I agree that it wasn't the best to do.
