### ISSUE TITLE
Server crash when trying to place a new sigil

### ISSUE THREAD

**Issue by JayDay1O1** [Mithion/Mana-And-Artifice#281]
The server crashed and I cannot rejoin when I placed a sigil and was a bit away from others I had placed. I would have been at the limit on how many you can have at a time.

[crash-2021-06-09_17.46.14-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6627133/crash-2021-06-09_17.46.14-server.txt)

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the 1.4.0.0 release.
