### ISSUE TITLE
Weak Armor

### ISSUE THREAD

**Issue by Sleeclow** [Mithion/Mana-And-Artifice#282]
The set bonus from the mage armor is very nice, however using it in a mod pack is pretty much impossible, even with protection enchantment it barely blocks any damage. Would be really cool (I think) if this mod had an upgraded armor version for end game, or even if the mage robes just got an armor buff from the start as they are currently incredibly weak, and not worth the trade off.

**Comment by Mithion** [comment]
This is intentional.  Mage armor is intended to either be supplemented with buffing spells or to be used when standing back slinging spells and not being the direct target of damage.

It's very good situationally, but isn't meant to be a "be-all-and-end-all" kind of armor.
