### ISSUE TITLE
Everything except static blocks turns gray when holding a spell or Manaweaver's wand

### ISSUE THREAD

**Issue by Acefreezies** [Mithion/Mana-And-Artifice#283]
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 6_10_2021 6_07_16 PM](https://user-images.githubusercontent.com/79808108/121603449-c9489300-ca16-11eb-8b08-7ee37077c0ac.png)
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 6_10_2021 6_07_26 PM](https://user-images.githubusercontent.com/79808108/121603454-cb125680-ca16-11eb-900f-b81bcf4bfa30.png)

**Comment by Mithion** [comment]
This is a known incompatibility with minimap mods and/or optifine.

Optifine isn't supported, but if it's the minimap I've heard turning on internal shaders can work, or setting the minimaps render layer to a different value.  Depends on the minimap mod which options it has.
