### ISSUE TITLE
Construct won't scribe rune

### ISSUE THREAD

**Issue by DulfyMans** [Mithion/Mana-And-Artifice#285]
I have all the rune markings in their proper positions in the Lodestar (side marked = up for the runescribing tables), and my construct has a hammer arm. But, when it takes a blank rune pattern to the table, it doesn't do anything. It sits the pattern down and picks it back up, and attempts to perform the rest of its tasks.  I don't know what's wrong.

**Comment by Mithion** [comment]
Did you put the pattern in the lodestar scribe task?

**Comment by Mithion** [comment]
Also are you a high enough tier to make the rune?

**Comment by DulfyMans** [comment]
Yup, I put the pattern in the lodestar, and I'm high enough tier. I’m Tier 3 and it’s a rune of marking.

**Comment by Mithion** [comment]
Have you tried using a diagnostics rod on it?  What does it say?

**Comment by DulfyMans** [comment]
I haven’t tried that. Yesterday I ended up getting frustrated and started my own singleplayer world 😅

**Comment by Mithion** [comment]
Closing for no response.
