### ISSUE TITLE
Construct can't harvest when doing other things

### ISSUE THREAD

**Issue by Sazukii** [Mithion/Mana-And-Artifice#286]
My construct won't move when i am trying this rotation.

When i try this, with all the coords, it won't move at all. Not even harvesting or butchering when it's necessary. 
![image](https://user-images.githubusercontent.com/32707420/121825129-16479600-ccb1-11eb-9bbf-7cda9fdafc4d.png)

BUT when i remove the butcher coords, it starts to harvest as a maniac...
Same goes for butchering.

So i am wondering, if there is a incompatibility with butchering and harvesting?

My construct.
![image](https://user-images.githubusercontent.com/32707420/121825219-73dbe280-ccb1-11eb-9263-03804fe80d42.png)
Full rotation:
![image](https://user-images.githubusercontent.com/32707420/121825057-a76a3d00-ccb0-11eb-92f0-5cfa60159e2c.png)
Harvesting:
![image](https://user-images.githubusercontent.com/32707420/121825064-b0f3a500-ccb0-11eb-895f-551691ba36f0.png)
Butchering:
![image](https://user-images.githubusercontent.com/32707420/121825071-c668cf00-ccb0-11eb-81d1-f1ad7ef99942.png)

Running on:
MC: 1.16.5
CurseForge: ATM6 1.5.10b
Modpack: mana-and-artifice-1.3.0.6.jar

**Comment by Mithion** [comment]
Have you tried using a diagnostics rod on it?  What does it say?

Harvest is supposed to require a blade arm.

**Comment by Sazukii** [comment]
This is what its saying, but when i rotate the Harverst with the butcher => remove the butcher coords, it starts to work. Even with an Arm / Axe...

![image](https://user-images.githubusercontent.com/32707420/121825512-29f3fc00-ccb3-11eb-85da-7937c73b26c8.png)

**Comment by Sazukii** [comment]
It even says that it is capatible with planting.

![image](https://user-images.githubusercontent.com/32707420/121825583-8bb46600-ccb3-11eb-9884-01823e9af511.png)

**Comment by Mithion** [comment]
ok that may be a bug on its own, but it saying it needs to be able to harvest indicates that it's missing a capability (granted by the parts it has).

Does adding a blade arm solve the strangeness?

**Comment by Mithion** [comment]
Planting and harvesting are two separate capabilities, planting is grabber arms, harvesting is blade arms, so that part looks fine to me.

**Comment by Sazukii** [comment]
Not quite sure how to edit constructs yet.

**Comment by Mithion** [comment]
Use a control rod, right click the construct then right click the workbench...it'll return to the bench where you can replace parts and then re summon it.

**Comment by Sazukii** [comment]
Will try

**Comment by Sazukii** [comment]
I think it's working fine right now. Thanks alot.
Is there a way to see which arm does what, what all the capatibilities do and which arm you need for it?

**Comment by Mithion** [comment]
Np, glad it's working.

In the codex, the entries for the tasks tell you what capabilities they need, if any.

**Comment by Sazukii** [comment]
Thanks! Loving the mod so far! c:

**Comment by Mithion** [comment]
Glad to hear it :D
I'm going to close this as resolved.
