### ISSUE TITLE
A unknown entity generated server crash

### ISSUE THREAD

**Issue by NineRiver7** [Mithion/Mana-And-Artifice#287]
[crash-2021-06-13_13.01.19-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/6646457/crash-2021-06-13_13.01.19-server.txt)

**Comment by Mithion** [comment]
This issue is with Dungeons Arise; they should be checking for null in their EntityPlaceEvent handler (in the constructor the Entity is tagged as @Nullable).
