### ISSUE TITLE
Crashed when using Nethergate on a Mana and Artifice entity.

### ISSUE THREAD

**Issue by Desanguin8ed** [Mithion/Mana-And-Artifice#288]
14.06 10:01:28 [Server] Server thread/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 61c59e50-a959-484a-bdc7-10419e3ca1f7
14.06 10:01:28 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
14.06 10:01:28 [Server] INFO net.minecraft.crash.ReportedException: Ticking entity
14.06 10:01:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
14.06 10:01:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
14.06 10:01:28 [Server] INFO Caused by: java.lang.NullPointerException
14.06 10:01:28 [Server] INFO at com.ma.spells.components.ComponentNethergate.ApplyEffect(ComponentNethergate.java:44) ~[mana-and-artifice:1.3.0.6] {re:classloading}
14.06 10:01:28 [Server] INFO at com.ma.spells.SpellCaster.lambda$ApplyComponents$2(SpellCaster.java:264) ~[mana-and-artifice:1.3.0.6] {re:classloading}
14.06 10:01:28 [Server] INFO at com.ma.spells.crafting.SpellRecipe.iterateComponents(SpellRecipe.java:176) ~[mana-and-artifice:1.3.0.6] {re:classloading}
14.06 10:01:28 [Server] INFO at com.ma.spells.SpellCaster.ApplyComponents(SpellCaster.java:250) ~[mana-and-artifice:1.3.0.6] {re:classloading}
14.06 10:01:28 [Server] INFO at com.ma.entities.sorcery.targeting.EntitySpellProjectile.applyEffect(EntitySpellProjectile.java:257) ~[mana-and-artifice:1.3.0.6] {re:classloading,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at com.ma.entities.sorcery.targeting.EntitySpellProjectile.entityHit(EntitySpellProjectile.java:171) ~[mana-and-artifice:1.3.0.6] {re:classloading,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at com.ma.entities.sorcery.targeting.EntitySpellProjectile.func_213868_a(EntitySpellProjectile.java:362) ~[mana-and-artifice:1.3.0.6] {re:classloading,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at com.ma.entities.sorcery.targeting.EntitySpellProjectile.onHit(EntitySpellProjectile.java:266) ~[mana-and-artifice:1.3.0.6] {re:classloading,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at com.ma.entities.sorcery.targeting.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:413) ~[mana-and-artifice:1.3.0.6] {re:classloading,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 10:01:28 [Server] INFO ... 5 more

**Comment by Mithion** [comment]
This has been fixed in dev and will come out with 1.4.0.0 when it releases.
