### ISSUE TITLE
Can't use the mana inside a Mana Crystal Fragment/Mana Gem

### ISSUE THREAD

**Issue by DragonSorcererX** [Mithion/Mana-And-Artifice#289]
I filled a Mana Crystal Fragment with my mana but I don't know how to use that mana to fuel my spells, I tried upgrading it to a Mana Gem and I still couldn't use it, I tried it on both Infusion Mode and Supplement Mode, I also tried holding it on my off hand. What am I doing wrong?

**Comment by Mithion** [comment]
This is a known issue that has been fixed in dev to go out with 1.4.0.0.
Mana crystals currently will not refund mana to the player, but will work for supplying curios and armor and the like.
