### ISSUE TITLE
mending enchantment

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#29]
the manaweave enchanting portion for mending says to use an earth rune, and it works. The anvil portion says it needs to be an arcane rune, which can't be made into mending.
![2020-06-14_17 25 02](https://user-images.githubusercontent.com/8917961/84604429-0ad64a80-ae64-11ea-9214-dfb1395bf5b4.png)

**Comment by Mithion** [comment]
This has been corrected in 1.0.2-pre1.  The runeforge now uses the earth rune as well.
