### ISSUE TITLE
Using Cheap Spell Rituals for expensive spell crafting.

### ISSUE THREAD

**Issue by Bruinbird** [Mithion/Mana-And-Artifice#290]
I'm playing this mod in a modpack with a few friends, and because I don't understand much about the mod, I was making a cheap spell, and then figured out I should make a more expensive one, to get the components rote. However when I swapped the spell recipe in the center (in a ready ritual, all items were there), it activated the ritual, instead of changing the requirements of the ritual, which I thought it would do. 
Not necessary to the bug but my guess on what's going on
I think this happens because the ritual only reads the fact that it has a "spell recipe" in the center, and doesn't ever check if the requirements of the spell match those of the ritual, so it goes through with it and makes the spell anyway, because it reads it wrong.

**Comment by Mithion** [comment]
This has been fixed in dev, and will go out with version 14.0.0.
