### ISSUE TITLE
Runeforge recipe conflicts

### ISSUE THREAD

**Issue by sirben99** [Mithion/Mana-And-Artifice#292]
Hey!

I noticed that Runeforge can work as a furnace, campfire and a blastfurnace causes issues with other mods installed. Mainly the ones that add furnace recipies, like Quark. In Quark, you can smelt bone to bone meal. In Mana and Artifice you can smelt bone to bone ash. Having both installed causes you to get bone meal instead of bone ash, which means you cannot get bone ash at all.
Luckily Quark is nice enough to have options to disable this, but other mods that do this might not, which could cause potential soft locking and progression blocking.

My sugsections are: 

1. Disable Runeforge working as a furnace, campfire and a blastfurnace
2. Only allow vanilla/Mana and Artifice recipes to work on it
3. Prioritize Mana and Artifice items as a outcome (Instead of bone meal youll get bone ash)

If you have better way of handeling it go for it by all means! 

Ben

**Comment by Mithion** [comment]
3 is what it's supposed to do; I'll need to double check to make sure that it actually is.

**Comment by Elfinlocks** [comment]
> 3 is what it's supposed to do; I'll need to double check to make sure that it actually is.

It is currently not - for example, quark's bone to bonemeal furnace recipe overrides it in the Runeforge. In addition, the Arcane Compound recipe seems to not work at all - placing Arcane Compound into the forge to make Arcane Ash provides no animation at all, as if the recipe doesn't exist.

**Comment by Mithion** [comment]
The latter there may be an issue with FastSuite; it's been proven to mess with M&A recipes somehow.

**Comment by Mithion** [comment]
The Runeforge now prioritizes its own recipes before any other, then falls through to other recipes if no runeforging recipe is found.  This should resolve any conflicts such as these.
