### ISSUE TITLE
Bug In Mana And Artifice

### ISSUE THREAD

**Issue by Xeno100** [Mithion/Mana-And-Artifice#296]
My Brother and Me were going to play this together but when we did the set magic level command on him he had this weird x ray sort of thing and He was on laptop please fix this thank you

**Comment by Mithion** [comment]
This bug report provides no contextual information, screenshots, version information, logs, or anything relevant.
I'm going to close this.  Please re-open a new issue following the issue templates I just uploaded:
https://github.com/Mithion/Mana-And-Artifice/issues/new/choose

Once you've provided the appropriate context, I'll be happy to look into it.
