### ISSUE TITLE
[enhancement] enchanting

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#30]
allow more of the regular anvil abilities to the runic anvil, such as:
1. adding multiple enchantments on the same item
2. increasing enchantment levels with a second of the same type (rune ring has the higher level items)
3. repair an item. Runes could hold a hammer, iron (between one bar and an anvil, depending on amount of durability being repaired), an earth rune, and anything else that strikes your fancy.

**Comment by ace10102** [comment]
i also have a suggestion:
if you put an item and enchanted rune on the runic anvil, the metal rune symbols should display required reagents for the chosen enchantment above them like the rituals do

**Comment by Mithion** [comment]
Items 1 and 2 have been added - 3 won't be, as I don't want to completely remove the need for vanilla anvils.

Ghost items for enchanting is a good idea, but should have been its own separate thread.  Closing this an opening as a new one.
