### ISSUE TITLE
Constructs don't pluck chickens

### ISSUE THREAD

**Issue by Zarvera** [Mithion/Mana-And-Artifice#301]
Construct keeps reporting  that there're no targets for shearing when i place him in a coop with chickens.
Unless the requirements for "plucking" are somehow different from the ones for shearing, this seems to be a bug. And in either case there's a small issue with the Codex being uninformative on parts requirements for Commands. 

**Steps to reproduce**
- Assemble wooden Construct with a Grabber and Blade arms
- Mark the working area with marking runes
- Place chickens in the working area with the Construct
- Place Lodestar with "Shear\Pluck" command and marking runes that defined the area
- Smack construct with a Diagnostic Rod and read his report, he does nothing

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.4
 - Forge Version  36.1.16

**Comment by Mithion** [comment]
Not having this issue in 1.4.0.8; can you post a screenshot of your setup and mapped area?

**Comment by Mithion** [comment]
Closing for no response.
