### ISSUE TITLE
Manaweaving Patterns are too hard to obtain

### ISSUE THREAD

**Issue by Zarvera** [Mithion/Mana-And-Artifice#302]
**Is your feature request related to a problem? Please describe.**
Is there a particular, mm,  sadistic reason as to why simple pattern like Quadratum are lvl. 5 Villager trade? Or why patterns are seemingly trade-only at all? I've just spent a good hour trying to craft the Mana Crystal and i've only managed 4 fragments yet, the Altar just refuses to recognise my poor squiggly quadrants. 
Mana Projector thus fails as what seems to be a helping tool for a gimmicky crafting table, as securing a Villager and amassing stacks of Emeralds to level him up and then wonder what to do with a double chest of useless pattern papers one bought to level him up is a Herculean task and whole fueature needs a review i think.

**Describe the solution you'd like**
Some simpler way to make pattern papers for Mana Projector for those who struggle with manual Manaweaving would be extremely nice. 
And in light of that Manaweaver Villager would need a review too, as it stands his stock doesn't seems to be well thought out.

**Comment by Mithion** [comment]
Ritual of the Wandering Wizard is what you're looking for.
Have a stack of Vinteum Ingots on hand when you summon him.

**Comment by Zarvera** [comment]
I see, thanks! Would help throwing a fat hint somewhere around Projector's entry though. I would never even bothered with the trader by myself. 
Or a JEI\JER entry for said wizards trades, as it only shows Manaweaver's trades

**Comment by Mithion** [comment]
Good idea - I'll be sure to do so, at least for the codex :)
JEI might take some more work to do, but maybe it's doable?
