### ISSUE TITLE
Bound Sword changes into Bound Shield

### ISSUE THREAD

**Issue by ClownyTheClown** [Mithion/Mana-And-Artifice#303]
**Describe the bug**
Bound sword (Flame Damage + Damage Modifier) changes into my other spell, Bound shield (Entangle)
It only works for me somehow? I have my bound shield on left hand and when my mana runs out the sword I'm holding disappears and turns into the shield. My friend tried it and it didn't turn the sword into a shield and didn't desummon the sword and the shield but remained at near 1 mana.

Unfortunately there's no crash log or errors.
**To Reproduce**
1. Get item Bound Sword
2. Use with bound shield on left hand, drain mana so that theyre suppose to turn back into the spell

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.5]
 - Forge Version [e.g. 36.1.32]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.
Has:
-Optifine
-Alexmobs
-Astral Sorcery
-Origins forge port
-Hallzmine Plus
-Simple Network Storage
-Botania, Mythic Botania
-Useful backpack
-Biomes you'll go

**Comment by Mithion** [comment]
This was fixed in 1.4.0.8
