### ISSUE TITLE
Nether spawns overpower curated biome mob list

### ISSUE THREAD

**Issue by Linguardium** [Mithion/Mana-And-Artifice#304]
**Describe the bug**
Nether spawn weights overpower enderman spawns in warped forest
Warped forests are designed to be effectively mob-free except for Endermen. Imps and Wraiths seem to have a standard mob spawn weight which is higher than the enderman spawn weight, leading to effectively replacing endermen with imps and wraiths in warped forests.

**To Reproduce**
load game
visit warped forest in nether

alternatively, tp above nether ceiling in warped forest and build a platform for spawning

**Expected behavior**
platform/forest should have effectively only endermen (occasional other mob is fine, but the design of the biome is broken due to this mod)

**Version Information (please complete the following information):**
 - Mod Version: 1.3.0.6
 - Forge Version 36.1.31
 - Modpack: ATM6

**Additional context**
If spawn weights cant be adjusted appropriately, a biome blacklist config would be desirable

**Comment by legitswitch** [comment]
Having the same issue on FTB University 1.16. The problem makes finding ender pearls much harder than it should be. The InControl mod seems like a good workaround in the meantime, but it does require some config set up.

**Comment by Mithion** [comment]
All entities now have configurable spawn weights per dimension, and per biome.
