### ISSUE TITLE
[Suggestion] Mystical Agriculture Compatibility

### ISSUE THREAD

**Issue by Joey736n** [Mithion/Mana-And-Artifice#305]
After building a construct, and setting it up to farm Mystical Agriculture crops, we soon realized that it was unable to harvest them. Allowing constructs to harvest and plant Mystical Agriculture crops would be a great help, and give the constructs a wider range of usage.

**Comment by Mithion** [comment]
1.4.0.8 added some additional compatibility; but there is also a tag list of plants/harvestables.  We're working on expanded compatibility in the Discord server, so feel free to pop by and lend a hand.
