### ISSUE TITLE
Crashing and a bug

### ISSUE THREAD

**Issue by Eggflames** [Mithion/Mana-And-Artifice#306]
Game crashes if you try to see vellum's uses (with jei)
also, sometimes the book that lets you change modifiers (book of alternation or something like that) occationally doesn't show the wheel

![image](https://user-images.githubusercontent.com/87441902/125666992-d760cb92-3faa-4e50-bb81-07296457eb08.png)

 - Mod Version: mana-and-artifice-1.3.0.6
 - Forge Version: 36.1.0
 
 
![image](https://user-images.githubusercontent.com/87441902/125667642-5e223915-35df-4484-8bf9-45da5d868a33.png)

**Comment by VirtualGaming1** [comment]
it will help the dev if he can see the full crash log. if it pop up again press "View Crash Report" copy and paste into here.

**Comment by Mithion** [comment]
I'll also suggest updating to beta 1.4.0.8, which fixes several bugs and has no issues I'm aware of with JEI.
