### ISSUE TITLE
Game Crashing 

### ISSUE THREAD

**Issue by helix19667** [Mithion/Mana-And-Artifice#307]
Whenever mobs kill me, my frames suddenly drop and my game crashes when the respawn screen appears.
**To Reproduce**
Enter combat with any mob and die. 
![Screenshot (83)](https://user-images.githubusercontent.com/87464644/125738657-c9605243-8605-4f1a-b4ef-f32b20f22c4e.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.4.07
 - Forge Version 1.16.5-4.0.5.2

**Additional context**
Also running the "just enough  items" mod with this mod.
Version: 1.16.5-7.7.0.106

**Comment by Mithion** [comment]
This was fixed in beta 1.4.0.8
