### ISSUE TITLE
[Request] Recipe Compatibility

### ISSUE THREAD

**Issue by Elfinlocks** [Mithion/Mana-And-Artifice#308]
Most recipes in Mana and Artifice which incorporate vanilla items are NOT tagged, meaning that recipes use the items minecraft:stone, or minecraft:glass, instead of the tags forge:stone, or forge:glass/colorless for example. This makes the mod a massive pain to implement for modpack devs. Alternatively, please make the mod open source, so that we can at least do datapacks through KubeJS or OpenLoader.

**Comment by Mithion** [comment]
Several additional tags for recipes were added in 1.4.0.8, greatly expanding compatibility.  We continually work on this in the Discord server, so feel free to pop by to add an additional hand to it!
