### ISSUE TITLE
Ritual of Sanctum invocation

### ISSUE THREAD

**Issue by AmrakSekushi** [Mithion/Mana-And-Artifice#309]
**Describe the bug**
The Ritual's building shows blocks up until a point then the ghost outlines stops showing, For one allied with the Wizard Council.

**To Reproduce**
1. Complete the Ritual of Sanctum Invocation
2. Begin building the faction building
3. Eventually the ghost blocks will stop appearing.

**Expected behavior**
The ghost blocks to continue appearing to guide me through the construction of the faction sanctum.

**Screenshots**
http://prntscr.com/1c2405a
http://prntscr.com/1c245ob
http://prntscr.com/1c24a5p
http://prntscr.com/1c24f1t

**Version Information (please complete the following information):**
Mana and Artifice version 1.4.0.7
 - Forge Version 36.1.25
EDIT
This also happens on Mana And Artifice version 1.4.0.8 and Forge Version 36.1.61

**Comment by Mithion** [comment]
In your inventory there's a button to toggle between full structure and layer-by-layer mode.  You're likely missing a block on the current layer, but I can't see one in the screenshots - I've built about 10 sanctums trying to replicate this and have had no luck.

Does toggling the structure to full show the rest?

**Comment by Mithion** [comment]
Closing for no response.
