### ISSUE TITLE
Crash (Ticking Entity)

### ISSUE THREAD

**Issue by Traverse-Joe** [Mithion/Mana-And-Artifice#310]
**Doing Mana Crystal Recipe caused the server to freeze then crash**
It looks like something is causing a ticking entity

**Version Information (please complete the following information):**
 - Mod Version: [1.4.0.8]
 - Forge Version [1.16.5-36.1.66]

**Additional context**
https://pastebin.com/L8LhrmA1

**Comment by Mithion** [comment]
This has been fixed in dev for the next release.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
