### ISSUE TITLE
Most assets turning blue or green

### ISSUE THREAD

**Issue by GeneralKenobii** [Mithion/Mana-And-Artifice#311]
**Describe the bug**
Whenever I make a self fling spell, I use it a few times and then most assets turn blue or green. The colour changes sometimes but overall its unplayable.

**To Reproduce**
1. Make a self fling spell on an inscription table
2. Use it a few times
3. Everything turns blue or green

**Expected behavior**
It shouldn't do this

**Screenshots**
![unknown](https://user-images.githubusercontent.com/67180537/126874026-efb7f208-bb95-494b-b22d-f0f0b78e83cf.png)

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.3.0.6]
 - Forge Version [e.g. 36.1.32]

**Additional context**
Using Valhelsia 3 on 1.16.5, not sure if it just isn't compatible but it's really annoying

**Comment by Mithion** [comment]
This is an incompatibility with Optifine / Xaero's minimap.  Optifine isn't supported, Xaero's I'm trying to fix.
