### ISSUE TITLE
Automation falls apart as soon as i walk away a bit

### ISSUE THREAD

**Issue by Zarvera** [Mithion/Mana-And-Artifice#312]
**Describe the bug**
There seems to be a problem somewhere though i'm not entirely sure where exactly.
I've made and instructed Construct to craft mindnumbing amount of Gilded Blackstone on the Manaweaving Altar. He pulls Blackstones and gold from chest, shoves them down the Altar, activates Projector sitting by a Mana Crystal, then pulls Gilded Blackstones out and back into the chest.
Everything works absolutely perfectly for any amount of cycles until i walk a few chunks away. The distance is not too far to unload chunks and there is a chunkloader anyway so it should not be a problem. When i return, nothing is being crafted, Altar is filled with items, manaweave symbols, and Projector seems to be empty. 
Clearly something stops functioning as soon as i'm sufficiently far away regardless of chunkloading.

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.8
 - Forge Version36.1.32

**Additional context**
I *feel* like it's most probably Mana Crystal not supplying Projector with mana when player is away. 
What do you think?

**Comment by Mithion** [comment]
Its possible.  What are you using as a chunkloader?  Need to try and replicate this.

**Comment by Mithion** [comment]
Closing for no response.
