### ISSUE TITLE
Blink spell can take you below bedrock

### ISSUE THREAD

**Issue by abadger** [Mithion/Mana-And-Artifice#313]
**Describe the bug**
A blink spell (with maximum range) can take you below bedrock, where you then die in the void.

**To Reproduce**
1. Create a blink spell with maximum range.
2. Dig down to bedrock
3. While standing on bedrock and looking down, cast your blink spell'
4. You appear below the bedrock layer, falling into the void.

**Expected behavior**

Blink will not teleport you through bedrock.  (Or perhaps, blink will not teleport you lower than y=0 (in case being able to use blink to go above the bedrock ceiling in the nether is desirable)

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: mana-and-artifice-1.4.0.7
 - Forge Version 36.1.23

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Added a check for blink that won't let you go below Y: 1.
Fixed for next release.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
