### ISSUE TITLE
Working with PlayerEx and RelicEx that would effect Magic/spells stuff...

### ISSUE THREAD

**Issue by VirtualGaming1** [Mithion/Mana-And-Artifice#314]
So this is the one that would work better with PlayerEx and RelicEx and dose have stats that deal with "Magic" and this would great option to work with.

The things this could effect could be the MP storage or Spell strength or any thing you could thing that would effect from stats.

This is good for my RPG style modpack as well and this mod is the main magic mod as well. and only (that I know of so far) Magic Crafting mod.

**Comment by Mithion** [comment]
PlayerEx has moved away from Forge over to Fabric, so this won't be possible.
