### ISSUE TITLE
Ticking Entity Crash with Pyromancer

### ISSUE THREAD

**Issue by Dandas52** [Mithion/Mana-And-Artifice#315]
**Describe the bug**
Shooting fireballs at certain mobs with Pyromancer installed causes a ticking entity crash. 

**To Reproduce**
1. Download Mana and Artifice and Pyromancer. 
2. Use fireball on (currently confirmed to crash - Wither, Wizard Council Enforcer)

**Expected behavior**
The fireball damages the entity without issue, 

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.8
 - Forge Version 36.1.32

Crash log attached below:
https://pastebin.com/MMpqw8Nc

**Comment by Mithion** [comment]
Logs indicate the issue lies with Pyromancer.
