### ISSUE TITLE
Broom getting erased upon pickup

### ISSUE THREAD

**Issue by Zarvera** [Mithion/Mana-And-Artifice#316]
**Describe the bug**
Seems to be another one where something breaks entirely as soon as it gets far away enough.
Basically Broom stops functioning if gets too far away from it's inventory it was bound to (pushed or simply walks there because an item was there but you picked it up yourself) and loses LoS to it's inventory. After it stops in such a manner picking it up with shift-r-click erases the Broom altogether from the world and doesn't returns it as an item.

**Version Information (please complete the following information):**
 - Mod Version:  1.4.0.8
 - Forge Version  36.1.32

**Comment by Mithion** [comment]
It does drop as an item, but for some reason is invisible.  Walking around the area a little bit causes it to be picked up.

**Comment by Mithion** [comment]
This has been fixed.
