### ISSUE TITLE
[Suggestion] comparators

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#32]
it'd be cool if we could take comparator output from like pedestals or chalk runes or the manaweave projector 
you probably already have some ideas for redstone interaction but i just wanted to specifically draw attention to comparators because they dont get enough love

**Comment by Mithion** [comment]
How would such an interaction work?  There are a lot of other features on the go too, so want to make sure there's an actual use case.

**Comment by ace10102** [comment]
i was thinking runes / pedestal would simply output redstone if containing an itemstack and do nothing when empty
projector could output signal strength proportional to how full of mana it is, that or, no signal if not full, signal when full

**Comment by Mithion** [comment]
Easy enough.  Projector already accepts redstone signal to trigger emitting too.

**Comment by Mithion** [comment]
Comparator support has been added in 1.0.2-pre1 for the following blocks:

Chalk runes: outputs full power to comparators when an item is in it
Pedestals: outputs full power to comparators when an item is in it
Manaweave Projector: outputs power relative to how full it is (0 -> 15)
Inscription Table: outputs power while a spell is being crafted.
