### ISSUE TITLE
Faction Rituals Are not Working

### ISSUE THREAD

**Issue by steynraphael** [Mithion/Mana-And-Artifice#321]
**Describe the bug**
When I attempt to do a faction-joining ritual (all chalked out, components in the right place) while having no faction I get a message saying "This ritual is not for your faction. They will not answer your call."

**To Reproduce**
1. Set up Ritual of Fairie Courts (or other faction-joining ritual)
2. Be tier three with magic level 45
3. Activate ritual with purified vinteum dust

**Expected behavior**
The fairy would be summoned so that I could join the faction.

**Screenshots**
![image](https://user-images.githubusercontent.com/19765337/128300183-f693979d-eb7a-4f29-81ce-c64bff273fb3.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.4.06
 - Forge Version 36.1.0

**Additional context**
No other mods that were not required for Mana and Artfice

**Comment by Mithion** [comment]
You join a faction moving from T2 -> T3.  
You cannot change factions at higher tiers; the ritual will fail with this message.
