### ISSUE TITLE
Dynamic Trees Compatibility

### ISSUE THREAD

**Issue by grayscale420** [Mithion/Mana-And-Artifice#322]
Oak Fell doesn't (at least seems that it doesn't) work with Dynamic Trees.

**Describe the solution you'd like**
Chop tree.

**Describe alternatives you've considered**
Remove the tree

**Additional context**
Really don't know if this would cause any issues. Just a minor annoyance, really.

**Comment by Hequinoxe** [comment]
What happened to me: when I used oak fell on a tree produced by dynamic tree, the tree broke but there was nothing (no loot)

**Comment by Mithion** [comment]
Dynamic Trees must be changing something that's messing with the detection of trees.  It looks for log blocks and leaf blocks right now.  If those aren't found it won't do anything.

**Comment by Mithion** [comment]
Resolved in later issues of the mod.
