### ISSUE TITLE
Pilgrim's Path conflict

### ISSUE THREAD

**Issue by mahenderson2010** [Mithion/Mana-And-Artifice#323]
I'm playing in ATM6 right now and have been using the Staff of the Pilgrim for most of the game. I noticed that when I try to apply a Speed affect (either spell or Aura of Running will do) one or the other will not work depending on which was applied first. The jump boost from the Aura of Jumping doesn't affect it and neither do any step assist things I've tried. Only the Speed buff. Thank you for you time and the fun mod!

**Comment by Mithion** [comment]
Pilgrim doesn't stack with Speed as of 1.4.0.8 (not applying the effect at all if speed is present; and vice versa for the aura).  Since it's that effect that does the step assist and the jump, that'll be the root cause of the issue.

It was too much of a speed increase with both.
