### ISSUE TITLE
Ore doubling not working

### ISSUE THREAD

**Issue by CursedKing** [Mithion/Mana-And-Artifice#324]
When you use the chimerite yellow/red/orange near/next to a runeforge it doesn't double ore's. Tested with modded (All the mods 6) and normal iron ore neither of which got doubled by the chimerite crystal on a pedestal nearby

**Comment by Mithion** [comment]
Just tested on 1.4.0.8 and it's working fine.  Chances are you don't have the setup correct.
Can you post a screenshot?

**Comment by CursedKing** [comment]
![image](https://user-images.githubusercontent.com/81441620/129486484-913e8ded-59c4-4a83-a264-448b8a2288ec.png)

**Comment by Mithion** [comment]
That's an incorrect setup.  I can understand though, the codex isn't completely clear on it.  I've improved the verbiage and added a picture for next release to help!

Essentially the pedestals need to be on the left and right of the forges:
[P][F][P]

You can set it up that two forges share a crystal in the middle, like so:
[P][F][P][F][P]

When it's working you'll see additional fire around the crystals.

Sorry for the confusion!
