### ISSUE TITLE
Brazier has a missing texture?

### ISSUE THREAD

**Issue by BlueYoshi68** [Mithion/Mana-And-Artifice#327]
**Describe the bug**
The brazier...has a missing texture, that's about it.

**To Reproduce**
Just look at a brazier? Possibly an optifine compatability bug.

**Expected behavior**
It...to look normal.

**Screenshots**
https://i.imgur.com/WcL9vhN.png
yep

**Version Information (please complete the following information):**
 - Mod Version: 1.3.0.6
 - Forge Version 1.16.5 - 36.2.0

**Comment by Mithion** [comment]
Optifine is not supported.  There is a pseudo workaround here, but I in no way offer support for it nor guarantee it will work.  However, reports are that people have had success.  YMMV.
https://github.com/Mithion/Mana-And-Artifice/issues/158#issuecomment-780137524
