### ISSUE TITLE
[bug] Crash with LootBeams installed

### ISSUE THREAD

**Issue by Mrbysco** [Mithion/Mana-And-Artifice#329]
**Describe the bug**
When a Runescribing Recipe is dropped on the floor and LootBeams tries to render it's name/tooltip it crashes.

**To Reproduce**
1. Install LootBeams
2. Drop a Runescribing Recipe on the floor
3. See the game crash

**Expected behavior**
Lootbeams rendering a beam on top of the dropped item with the Runescribing recipe name and pattern displayed.

**Screenshots**
(not applicable)

**Version Information (please complete the following information):**
 - Mod Version: 1.3.0.6
 - Forge Version 36.2.0

**Additional context**
Lootbeams version: 1.16.5-release-aug2021

[Pastebin of Crashlog](https://pastebin.com/YCWS81eh)
Also reported the issue to LootBeams here https://github.com/shiroroku/LootBeams/issues/4

**Comment by Mithion** [comment]
Resolved in 1.5.1.5.
