### ISSUE TITLE
Crash: Using spell "Self - Crafting Table" and crafting with a nearly full inventory will crash the Server under certain conditions

### ISSUE THREAD

**Issue by MixKCet** [Mithion/Mana-And-Artifice#330]
This happens fairly reliably and is the single biggest source for crashes on our server. To set up the constraints, have a full or nearly full inventory and try to craft a lot of an item using the summoned crafting bench interface. This may be an odd interaction with JEI going on here as well.

The server then lags out, and recieves thousands of the message below. Honestly, it tickles my "infinite loop" senses. The crash report isn't helpful because it then generically times out.

`Sep 04 01:49:18 ip-172-31-3-37.ap-southeast-2.compute.internal java[15660]: [01:49:18] [Server thread/ERROR] [minecraft/ServerRecipePlacer]: Can't find any space for item in the inventory
Sep 04 01:49:18 ip-172-31-3-37.ap-southeast-2.compute.internal java[15660]: [01:49:18] [Server thread/ERROR] [minecraft/ServerRecipePlacer]: Can't find any space for item in the inventory
Sep 04 01:49:18 ip-172-31-3-37.ap-southeast-2.compute.internal java[15660]: [01:49:18] [Server thread/ERROR] [minecraft/ServerRecipePlacer]: Can't find any space for item in the inventory
Sep 04 01:49:18 ip-172-31-3-37.ap-southeast-2.compute.internal java[15660]: [01:49:18] [Server thread/ERROR] [minecraft/ServerRecipePlacer]: Can't find any space for item in the inventory
Sep 04 01:49:18 ip-172-31-3-37.ap-southeast-2.compute.internal java[15660]: [01:49:18] [Server thread/ERROR] [minecraft/ServerRecipePlacer]: Can't find any space for item in the inventory
Sep 04 01:49:18 ip-172-31-3-37.ap-southeast-2.compute.internal java[15660]: [01:49:18] [Server thread/ERROR] [minecraft/ServerRecipePlacer]: Can't find any space for item in the inventory
Sep 04 01:49:18 ip-172-31-3-37.ap-southeast-2.compute.internal java[15660]: [01:49:18] [Server thread/ERROR] [minecraft/ServerRecipePlacer]: Can't find any space for item in the inventory`

**Comment by Mithion** [comment]
Were you using the recipe book to place a recipe in the table?

**Comment by Mithion** [comment]
This has been resolved.
