### ISSUE TITLE
Crash on death - possibly due to pinned ritual recipe

### ISSUE THREAD

**Issue by Chraelix** [Mithion/Mana-And-Artifice#332]
Playing on FTB University 1.16, multiplayer; consistent crashes encountered after dying with the ritual for a water mote pinned. Not entirely sure it's the pinned recipe causing the problems, or if it's the only thing causing problems, but it's my best guess at this point. After initially dying, I've been unable to load in to the server at all as the game crashes before I get a chance to respawn. Most recent crash log attached:

[crash-2021-09-05_20.03.09-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/7113064/crash-2021-09-05_20.03.09-client.txt)

**Comment by Mithion** [comment]
Confirmed, and fixed in dev for next update.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
