### ISSUE TITLE
[Crash] Book of Mote

### ISSUE THREAD

**Issue by DevScyu** [Mithion/Mana-And-Artifice#333]
**Describe the bug**
When you open the book of mote and press the button at the top, the client crashes.

**To Reproduce**
1. Open book of mote
2. Press button at the top
3. Crash

**Expected behavior**
Not crash

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.0] 1.4.0.8 (beta)
 - Forge Version [e.g. 36.1.32] 1.16.5 36.2.4

**Additional context**
Using the modpack [TNP Limitless 3](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3)
https://hastebin.com/joqidulalo.rb

**Comment by Mithion** [comment]
Confirmed, fixed in dev for next update.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
