### ISSUE TITLE
More Runescribing Automation

### ISSUE THREAD

**Issue by m00nwtchr** [Mithion/Mana-And-Artifice#334]
**Is your feature request related to a problem? Please describe.**
I'm just wondering if there's a way to change which pattern the Lodestar is set to craft automatically, instead of e.g. having additional Lodestars for each runescribing pattern, and if there isn't i'd love for that to be possible.

**Describe the solution you'd like**
One potential way would be to allow external stuff to interact with the Lodestar inventory, then stuff like ComputerCraft turtles could grab and place stuff in the particular slot that corresponds to the pattern in the runescribing action

**Describe alternatives you've considered**
Idk

**Comment by Mithion** [comment]
A construct "overhaul" is planned soon which will give some much needed love to constructs, how they interact with things, and the lodestar in general.  I'll keep this in mind when I'm working on it.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).  There are several new options for interacting with blocks/items/inventories for constructs and it should be a lot better.
