### ISSUE TITLE
[crash] ritual of locating

### ISSUE THREAD

**Issue by Petrisis** [Mithion/Mana-And-Artifice#336]
**Describe the bug**
My Server got killed by watchdog while a player started ritual of locating. its in a crash loop as long as this chunk is loaded.
Server console output: "Failed to parse UUID for ritual caster. Giving up and completing the ritual anyway, but some effects may not apply! "

**To Reproduce**
1. play m&a inside the modpack [Crashed on Gyrnolia](https://www.curseforge.com/minecraft/modpacks/crashed-on-gyrnolia)
2. generate a world with quark_realistic setting
3. locate with m&a a "valhesia:desert_house"
4. start the ritual and the server will be shut down by a ticks taking to long

**Expected behavior**
The ritual should just work as its defined and not crash. 

**Version Information (please complete the following information):**
 - Mod Version: 1.3.0.6
 - Modpack Version: [0.7.5](https://www.curseforge.com/minecraft/modpacks/crashed-on-gyrnolia/files/3454548)
 - Forge Version 36.2.2

**Additional context**
i'm concerned that this could be a forge/valhelsia problem with some structure generation not working properly or /locate command doing stuff. 

[server crash report](https://gist.github.com/Petrisis/61fca017b4d36256043b8d779255ede5)

**Comment by Mithion** [comment]
The ritual uses the same code as the vanilla /locate command, calling out to the base minecraft world class - in the instances where it hangs, so too would vanilla.

As such, this isn't a bug with M&A, but with vanilla MC itself.
