### ISSUE TITLE
Add Apotheosis Towers to Thaumaturgic Link System

### ISSUE THREAD

**Issue by Veggetossj** [Mithion/Mana-And-Artifice#337]
**Is your feature request related to a problem? Please describe.**
I was unable to locate the Link for the Apotheosis towers in the UI of the Wandering Wizard that sells Thaumaturgic Links.

**Describe the solution you'd like**
For a Thaumaturgic Link, linked to Apotheosis Towers, to be added to the Wandering Wizard's Shop.

**Describe alternatives you've considered**
So far I can't think of alternatives to locate these towers, yet discovering the existance of Thaumaturgic Links i though i could find them more easely.

**Additional context**
From Apotheosis' Github, these towers are features not structures.

**Comment by Mithion** [comment]
Only structures and biomes are supported.
