### ISSUE TITLE
Bug: Crash to Desktop whenever Mana & Artifice is installed alongside Spoiled.

### ISSUE THREAD

**Issue by Ws60** [Mithion/Mana-And-Artifice#338]
**Describe the bug**
Crash to Desktop occurs whenever a Runic Inscription table from Mana and Artifice is loaded while the Spoiled mod is also installed. Narrowed down to only an incompatibility issue between these two as no other mods in my pack conflict reproduce the issue. Not sure if its due to Spoiled or Man & Artifice, have reported issue to both parties as a result.

**To Reproduce**
1. Either place down a table or load chunk with Runic Inscription table already placed.
2. Wait a few seconds to crash.
3. Crash.

**Expected behavior**
Not to crash to desktop after a few seconds. 

**Version Information (please complete the following information):**
 - Mana and Artifice: 1.4.0.08
 - GeckoLib: 3.0.46
 - CuriosAPI: 4.0.5.3 
 - Forge: 36.2.0

**Additional context**
Mod was downloaded and installed directly from Curseforge, no shady third party sites.
https://pastebin.com/pf97yrez

**Comment by Mithion** [comment]
It's calling getSlotsForFace, which from what I can see, the runescribing table shouldn't crash there (there's nothing that I can see that would throw a NullPointerException like in the crash report).

Still, I added a null check on the one parameter that should eliminate any chance of that error happening again.
