### ISSUE TITLE
[Bug] assorted codex issues (enchanting edition)

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#34]
**Description:**
**1.)** mending enchantment; the manaweave enchant for the rune requires and produces an earth rune with mending. runic anvil recipe requires an arcane rune with mending, it also doesnt seem to want to apply to anything regardless of whether the earth rune or arcane rune is used
![image](https://user-images.githubusercontent.com/33331567/84609347-ab3c6700-ae84-11ea-9846-06b6aac472f6.png)

**2.)** loyalty enchantment; loyalty's manaweave enchanting recipe doesnt display required shapes for any of the 3 levels
![image](https://user-images.githubusercontent.com/33331567/84609543-61a04c00-ae85-11ea-90f0-a89937d6d264.png)

**3.)** blast protection enchantment; doesnt show the runic anvil recipe for any of the levels
![image](https://user-images.githubusercontent.com/33331567/84609580-901e2700-ae85-11ea-9c09-684d7079952c.png)

**4.)** flame enchantment: doesnt display a runic anvil recipe tab
![image](https://user-images.githubusercontent.com/33331567/84609729-0fabf600-ae86-11ea-87c4-06c74e27827b.png)

**5.)** looting enchantment; few things messed up, first, it lists the manaweave enchant tabs as looting 1, looting 2, looting 1. the last two tabs (looting 2, and looting 3 thats labeled as looting 1) dont have the manaweave patterns required listed
![image](https://user-images.githubusercontent.com/33331567/84609856-8fd25b80-ae86-11ea-8275-bec54f28a45e.png)
![image](https://user-images.githubusercontent.com/33331567/84609872-9a8cf080-ae86-11ea-91c4-687d41e15268.png)
![image](https://user-images.githubusercontent.com/33331567/84609879-a1b3fe80-ae86-11ea-97bf-0effe0b350b7.png)
![image](https://user-images.githubusercontent.com/33331567/84609902-ba241900-ae86-11ea-9bf0-b7622c59bc79.png)
![image](https://user-images.githubusercontent.com/33331567/84609913-c27c5400-ae86-11ea-818f-68fc40b6b184.png)

**6.)** punch, efficiency & bane of arthropods enchantments; recipes require placing purified vinteum dust on runes, which cant be done (aware that broom can bypass this limitation)

**Comment by ace10102** [comment]
the recipes for enchanting sharpness have "mana-and-artifice:[sword type]" instead of "minecraft:[sword type]" so it spits items off of the anvil and doesnt display the swords in the codex recipe

**Comment by ace10102** [comment]
in mending's runic anvil recipe "minecraft:dragons_breath" should be "minecraft:dragon_breath"
doesnt change that manaweaving gives you a mending earth rune and the anvil recipe requires a mending arcane rune

**Comment by ace10102** [comment]
riptide 3 anvil recipe requires 9 items, there are only 8 ritual runes

**Comment by ace10102** [comment]
codex doesnt display entry for curse of vanishing despite having manaweaving and anvil recipes

**Comment by ace10102** [comment]
blaze powder in the smite 5 recipe is listed as "mana-and-artifice:blaze_powder" instead of "minecraft:blaze_powder",

**Comment by ace10102** [comment]
quick charge enchants level 2&3 anvil recipes have "minecraft:vinteum_dust" instead of "mana-and-artifice:vinteum_dust"

**Comment by Mithion** [comment]
Corrected all issues listed, with the exception of the punch enchant.  That requires arcane ash, not purified vinteum.  Adding tooltip support to the recipes will help alleviate that confusion.
