### ISSUE TITLE
When I put my magic in the magic book, the magic disappeared

### ISSUE THREAD

**Issue by krody2333** [Mithion/Mana-And-Artifice#341]
**Describe the bug**

**To Reproduce**
1. Get item 'spell_book' 'spell'
2. put spell in spell_book
3. Have magic level '2'
4. disappeared

**Expected behavior**
1.I opened a server without other mods and plugins
2.I don't know how to stop the explosion from destroy the block 

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.8]
 - Forge Version [e.g. 36.1.32]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Incomplete report.
