### ISSUE TITLE
Not compatible with any shaders.

### ISSUE THREAD

**Issue by Dandekiller** [Mithion/Mana-And-Artifice#342]
**Describe the bug**
When using shaders alongside this mod it causes either the text in the GUI's to become invisible, black, or purple. Sometimes the colors change when going to different option menus.

**To Reproduce**
1. Get item 'codex arcana'
2. Use it.
3. then enable any shader, for example "project Luma", " Sildurs Vibrant shaders High or extreme" or "Kuda-shaders" 

**Expected behavior**
To work, so that I can use this mod without disabling my shaders.

**Screenshots**
If applicable, add screenshots t
<img width="402" alt="p1" src="https://user-images.githubusercontent.com/14092361/137163542-84bfcecd-e680-4134-9713-482ca6fd1a7c.png">
<img width="905" alt="P2" src="https://user-images.githubusercontent.com/14092361/137163549-9b60a180-a404-4723-84aa-d4ac844e0e0b.png">
<img width="1177" alt="P3" src="https://user-images.githubusercontent.com/14092361/137163556-5f6e26bf-d637-4e84-a94e-8a1a8b264d9f.png">
<img width="1534" alt="p4" src="https://user-images.githubusercontent.com/14092361/137163592-4745a22e-8a85-43c2-8bdf-2d7951137be0.png">
<img width="590" alt="P5" src="https://user-images.githubusercontent.com/14092361/137163985-d22ace5a-c059-4380-aa6c-06de57807fa3.png">

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.8
 - Forge Version 36.2.8
 - Minecraft Version 1.16.5

**Additional context**
When having the shaders on, but not opening the book the items on the bar are visible, and minimap mop waypoint texts are also displayed properly. However, when the book is open nothing is visible when it is related to GUI or text. Some shader packs have text but every time I open the option window the color changes.

EDIT:

Added crash log:
[crash-2021-10-13_17.31.18-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/7339574/crash-2021-10-13_17.31.18-client.txt)

**Comment by SteamDoge9000** [comment]
while this seems to be the case with you, It seems that complementary shaders are not causing any issues if you use these setting on th
[ComplementaryShaders_v4.2.1.zip.txt](https://github.com/Mithion/Mana-And-Artifice/files/7356564/ComplementaryShaders_v4.2.1.zip.txt)
em

**Comment by Mithion** [comment]
Optifine is not supported.

**Comment by SteamDoge9000** [comment]
ok I did some testing and found out the cause of that issue if shaders are present

idk if its the case without them off but when you go into creative with them on an any UI from mana and artfice render, it will break things,
this issue however does not presist with shaders if your in survival

**Comment by SteamDoge9000** [comment]
my conclustion is that the Ui and shaders are clashing in some way that is breaking other overlays

**Comment by SteamDoge9000** [comment]
to reproduce, do the same as before, make sure you have you UI set to render when you hold a magic item from this mod and go into creative to whitness the breaking, but notice after you no longer have an item that causes the mana ui to render that the issue goes away

do the same process in survival mode with shaderd and you will notice the same issue does not presist, meanig this is a creative only issue to some regard

**Comment by SteamDoge9000** [comment]
refrence proof pictures, 

survial with the UI showing and no issues while in survival with it rendering
![image](https://user-images.githubusercontent.com/38770780/140252699-1038bdea-20d2-4e2c-8fab-abd87e6121f9.png)

same image as before but going into creative
![image](https://user-images.githubusercontent.com/38770780/140252736-eaf2d58e-adab-4a21-9037-c419184f2f51.png)

same is as the previous one but no longer holding the item that renders the fancy UI
![image](https://user-images.githubusercontent.com/38770780/140252788-a1798bda-bd60-4f47-bccd-4a3dbbb31e18.png)

**Comment by SteamDoge9000** [comment]
idk what this guy was using, but when I use Complimentary shaders with optifine g7, this issue only exist in the following conditions:

* one of the Fancy UI renders (mana bar or pinned recipie)
* You are in creative mode

**Comment by Mrpinkybugsheep** [comment]
bruh i got same error, also not sure if its connected, but everytime i reset minecraft game gets on african idk why, weird mana and artifice stuff
