### ISSUE TITLE
Unfocus search bars

### ISSUE THREAD

**Issue by LeoBeliik** [Mithion/Mana-And-Artifice#344]
**Is your feature request related to a problem? Please describe.**
In the new alpha (1.5.0.0) the new searchbars in the guis (Inscription Table,  Book of Rote, etc) are focused by default.

**Describe the solution you'd like**
I'd like them not to be focused when open, so the gui could be closed with the *open inventory key* (E by default).
I also noticed that clicking outside the searchbar does not unfocus them, it will be nice if that happened.

**Comment by Mithion** [comment]
Esc will close the GUI.  The search bars forcing focus is intentional.  This happens with vanilla UIs as well, for example the creative search screen.
