### ISSUE TITLE
A friendly note on some renders [adjustment fix on the new manaweaver projector]

### ISSUE THREAD

**Issue by SteamDoge9000** [Mithion/Mana-And-Artifice#345]
I like the new manaweaver projector and wand but I noticed something with the shaders im using, its a bit darker than it should be

now Ik this dosent support shaters but Complimentery [a BSL fork] aims to make it as compatabale as possable with other mods

and one thing I noticed was this
![image](https://user-images.githubusercontent.com/38770780/139519298-b89835f4-885c-4975-a023-bbf387e4ec3d.png)

even though the projection is struggling on the manaprojector, the one on the alter is still rendering effecivly, so I guess you can say im asking if you could do whatever you did to render the symbols on the alter to the projector to fix this lill issue

**Comment by SteamDoge9000** [comment]
also a side note: ik that what im going to say next is unlikey going to be fixed but I also noticed the shapes go dark when at night, though it seems this issue is fine with a shader lightsource next to ti
![image](https://user-images.githubusercontent.com/38770780/139519479-51517b3a-4767-46b7-a3ca-b7f02cb86dda.png)
![image](https://user-images.githubusercontent.com/38770780/139519495-81e91a61-ae58-40f6-a7e6-2cf719dd1cc9.png)

**Comment by SteamDoge9000** [comment]
by doing one more test, I have come to the conclusion, when shaders are present and you enter creative and any UI renders from this mod, things will break, though it will not if your in survival

**Comment by Mithion** [comment]
Shaders are not supported at this time.

**Comment by SteamDoge9000** [comment]
idk what report it was, but their was a creative render error with shaders, idk if it was because I removed something or the resent updates, but the UI elements breaking while mana and artificie UI renders happen while in creavie mode with shaders on is no longer happening

just thought I should let you know :3
