### ISSUE TITLE
Felled oak only breaks one block

### ISSUE THREAD

**Issue by Esseit** [Mithion/Mana-And-Artifice#346]
**Describe the bug**
When using felled oak through touch, it only breaks a single log near the clicked log instead of the entire tree. 

**To Reproduce**
1. Create the felled oak spell, cast through touch
2. Use on any tree at any point, from top to bottom
4. Only one block will break per cast

**Expected behavior**
The entire tree should break and fall to the ground

**Version Information (please complete the following information):**
 - Mod Version: 1.5.05
 - Forge Version 36.2.8

**Additional context**
Unsure if this only happens when cast via touch or if its through all applicable cast methods.

**Comment by KovakinGaming** [comment]
Apparently there is a similar bug with the  Spell: Touch - Break where it does not drain mana or give experience unless wearing a ring, not sure if it's any ring from the mod or specific ones.

**Comment by Mithion** [comment]
Fixed in 1.5.0.8
