### ISSUE TITLE
Emanation + Arcane Damage no visual effekt

### ISSUE THREAD

**Issue by MagicdragonI** [Mithion/Mana-And-Artifice#347]
**Describe the bug**
The spell emanation + arcane damage has no visual effekt. The spell is invisible. The spell is other than that working.

**To Reproduce**
1. Create the emanation + arcane damage spell
2. Use the spell
3. The spell is invisable

**Expected behavior**
A visual effekt to show where the spell is.

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.5
 - Forge Version 36.2.8

**Additional context**
Other arcane spells have an visual effekt. This is the only spell that i found that as not visual effekt.

**Comment by Mithion** [comment]
Fixed in 1.5.0.9
