### ISSUE TITLE
Specific Village Structure causes crash.

### ISSUE THREAD

**Issue by KovakinGaming** [Mithion/Mana-And-Artifice#348]
**Describe the bug**
Upon generating a village with one of possibly a few different structure IDs the game crashes in single player and while open to LAN.

**To Reproduce**
Create a new world, locate a village (with or without cheats) and generate it. If this doesn't cause the game to crash, go about 600-1k blocks and repeat.

**Expected behavior**
Village should generate without causing a game crash.

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.5
 - Forge Version 36.2.8

**Additional context**
Latest Crash: https://pastebin.com/NuysRzUx
Crash logs with all mods enabled:
- https://pastebin.com/PjZxMAXb
- https://pastebin.com/1xrms8bX

**Comment by Trapcast-Dan** [comment]
Update: Continues to crash with mod version 1.5.0.6

**Comment by Liamdude** [comment]
I just experienced this crash as well. Was walking toward I village that I knew existed, and the game crashed while generating the village. Currently on 1.5.0.6.

**Comment by KovakinGaming** [comment]
This issue has been fixed as of 1.5.0.7 and occurred due to villages generating with a runeforge.
