### ISSUE TITLE
[Request] Old school raiding

### ISSUE THREAD

**Issue by LiSirNo** [Mithion/Mana-And-Artifice#349]
Hello, Please don't be annoyed by this request I am aware why you changed this to way it is now.

But I would be really happy if you would add at least toggle in config to enable old raiding system (from portal, based on yours tier, regardless if you are using other fractions items or not) It felt more organic to me and with warding candles in play it just added some RPG feeling to my experience that current system is missing. 

Don't force any change if it would cause unnecessary workload I am having blast with this mod anyway :)

**Comment by Mithion** [comment]
Not high on the list right now, but I'll get to it if I can for you.

**Comment by Mithion** [comment]
This config has been added in 1.5.1.5.
