### ISSUE TITLE
Server Kick When Removing Equipped Spellweaver Armor

### ISSUE THREAD

**Issue by AetheriMC** [Mithion/Mana-And-Artifice#350]
**Describe the bug**
Attempting to remove any of the spellweaver armor pieces while they are equipped causes the server to kick the player with a "connection lost" message. This does not happen when moving the pieces around in your inventory before equipping them. Additionally, after reconnecting, thrown/removed pieces can be manipulated as normal, with the kick only occurring again once the pieces have been equipped and an attempt is made to remove them.

**To Reproduce**
1. Equip any of the spellweaver pieces
2. Attempt to remove the pieces through shift + left click or left click
3. Kick

**Expected behavior**
The player should be able to remove the armor pieces without the kick.

**Screenshots**
Not applicable.

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.6
 - Forge Version: 1.16.5-forge-36.2.0

**Comment by Mithion** [comment]
Fixed in 1.5.0.9
