### ISSUE TITLE
Game Freeze on leaving or approaching visible Eldrin Wellspring

### ISSUE THREAD

**Issue by Shadowfire86** [Mithion/Mana-And-Artifice#351]
**Describe the bug**
When approaching or leaving an area with a visible Eldrin Wellspring (either via Unguent or having the multiblock built) my game locks up and I have to force close it.

**To Reproduce**
1. Use Unguent of Seeing (Forget name of item), or have the multiblock built on a wellspring
2. get close enough for wellspring to load, or leave the area
3. Game locks up

**Expected behavior**
Expect at most some frame rate drop when loading or unloading the wellspring

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.6
 - Forge Version 36.2.8

**Additional context**
started to a lesser extent in the previous version

**Comment by Shadowfire86** [comment]
Had an experienced FTB member look through the crash log on one of the rare actual crashes. Apparently it has to do with World Gen of Rune Forges. Will attach lo
[crash-2021-10-31_15.17.44-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/7449940/crash-2021-10-31_15.17.44-server.txt)
g.

**Comment by Mithion** [comment]
Fixed in 1.5.0.8
