### ISSUE TITLE
Recipes don't show that you need to be in a faction

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#352]
![image](https://user-images.githubusercontent.com/15698722/139608582-22cc9697-f02a-4173-92fb-b48f510221a0.png)
![image](https://user-images.githubusercontent.com/15698722/139608594-17b4944b-ce88-43ab-921d-3a36e1f7b65c.png)
![image](https://user-images.githubusercontent.com/15698722/139608603-a858725d-0429-4d6d-98a5-1c7278e6f958.png)

Only the Occulus shows that it needs you to be in the faction

**Comment by aaronhowser1** [comment]
Maybe the tooltip could have `Faction: ` the same way it has tier?

**Comment by Mithion** [comment]
All recipes now show the faction icon.  Good idea!
