### ISSUE TITLE
The book doesn't explain how to actually *use* Eldrin Flight

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#353]
From just faffing around with it in creative, you go to a Wellspring and cast the spell and it sends you to a random other Wellspring?

**Comment by aaronhowser1** [comment]
Wait it works anywhere. So shouldn't it say it lets you travel *to* them, rather than *between* them? Since you don't have to be at one to use it.

**Comment by Mithion** [comment]
Fixed in 1.5.0.9
