### ISSUE TITLE
The intended (as far as I can tell) way of finding Wellsprings isn't very good

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#354]
Wellsprings are fairly rare. I'm flying around in creative mode using both of the Unguents and I haven't actually stumbled across one yet. Using the Book of Rote to cast Eldrin Flight is the only way I can actually find them.

![image](https://user-images.githubusercontent.com/15698722/139612526-fffdc91c-f3b3-46d4-b9e2-ebdf7d93aa48.png)
You have to be *close* to a Wellspring to see it, about 125 blocks. The Unguents last 60 seconds. You walk about 4 blocks a second. You can walk about 300 blocks in the time a single Unguent lasts. You almost definitely will not find a Wellspring in that time.

**Comment by Mithion** [comment]
Agree.  I have another solution in mind, but it's going to take longer than this patch allows.
For now I increased the duration to 10 minutes (1.5.0.9).

**Comment by aaronhowser1** [comment]
I like the animation the Eldrin Flight spell has, with the wisps pointing you at them. Maybe a weaker version of that? Like, it works in pulses instead of having a constant stream. Color coding would also be nice.

**Comment by aaronhowser1** [comment]
The Eldrin Sight Unguent is still only 3 minutes

**Comment by Mithion** [comment]
This was fixed in 1.5.1.1
