### ISSUE TITLE
Occulus progression not showing

### ISSUE THREAD

**Issue by Ptituf** [Mithion/Mana-And-Artifice#355]
**Describe the bug**
Progression occulus not showing

**To Reproduce**
Crafted manaweaver on (crafting table tinker) , crafted inscription table (on rftool crafter)
**Expected behavior**
Expected a green ligne and progression

**Screenshots**
![hyhyhy](https://user-images.githubusercontent.com/28937889/139662642-67bb1cc6-9aa6-49d8-af63-b9657a633735.PNG)

**Version Information (please complete the following information):**
 - modpack : Direwolf20 1.16 v 1.11.0
 - Forge Version : 1.16.5  36.2.2
 - mod version mana and artifices : 1.4.0.8

**Comment by Mithion** [comment]
Try using a vanilla crafting table.  Some modded ones don't post the necessary events that this mod needs in order to be notified that an item was crafted.
