### ISSUE TITLE
Crash in village

### ISSUE THREAD

**Issue by sirben99** [Mithion/Mana-And-Artifice#356]
**Describe the bug**
When going to a village the game crashes

**To Reproduce**
1. Go to world
2. /locate village
3. Teleport
4. Crash

**Expected behavior**
No crash

**Version Information**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.8
 - Mana and Artifice: 1.5.0.6
 - Curious: 4.0.5.3
 - Geckolib: 3.0.45
 - Server: No
 - Other mods: No

**Additional context**

Crashlog:
https://pastebin.com/ZQQS0AqE

Log:
https://pastebin.com/cu9M9Gez

**Comment by ModernGamingWorld** [comment]
[crash-2021-11-01_19.43.21-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/7457060/crash-2021-11-01_19.43.21-server.txt)

Same crash as soon as a person logs near a village the server takes a big dump

**Comment by KovakinGaming** [comment]
This bug has been fixed as of M&A version 1.5.0.7, accessible on https://manaandartifice.com/releases/

**Comment by Rensik** [comment]
Known Issue: Fixed in Dev

**Comment by sirben99** [comment]
Issue seems to be fixed in 1.5.0.8. Closing issue
