### ISSUE TITLE
Server Crash When Wearing Spellweaver Armor & Taking Damage

### ISSUE THREAD

**Issue by AetheriMC** [Mithion/Mana-And-Artifice#357]
**Describe the bug**
The server crashes whenever taking damage while wearing Spellweaver armor.

**To Reproduce**
1. Equip Spellweaver Armor set
2. Be attacked (e.g. a stymphalian from Ice & Fire)
3. Crash

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.8
 - Forge Version 36.2.0

**Additional context**
Crash log: https://pastebin.com/baudsgrz

**Comment by Mithion** [comment]
Fixed in 1.5.0.9
