### ISSUE TITLE
Pillager Summon Crash

### ISSUE THREAD

**Issue by Kiwii12** [Mithion/Mana-And-Artifice#358]
**Describe the bug**
Pillager summon crashes the game or server when it targets an enemy.

**To Reproduce**
1. Get Spell parts Summon and Lightning damage
2. Fill Chrystal Phylactery full of pillager.
3. Summon pillager near enemy. (It won't target anything in creative.)
4. Crash.

**Expected behavior**
Either not being able to fill a Chrystal Phylactery with pillagers, or for the game not to crash.

Version Information:
 - Mod Version: 1.4.0.8
 - Forge Version: 36.2.4 
 
 Double checked with only mana and artifice:
 - Mod Version: 1.5.0.3
 - Forge Version: 36.2.0

**Comment by Mithion** [comment]
Fixed in 1.5.0.9 (both the crash and additional functionality for crossbow-wielding mobs such as pillagers)
