### ISSUE TITLE
Infinite Shears

### ISSUE THREAD

**Issue by NonFunPun** [Mithion/Mana-And-Artifice#359]
**Describe the bug**
I generated infinite shears in a manaweaving altar

**To Reproduce**
Create a spell with projectile shear
Target a manaweaving altar

**Expected behavior**
Probably nothing

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.9
 - Forge Version 36.2.9

**Additional context**
Shear also seems to open chests and other GUI's when targeted.

**Comment by Mithion** [comment]
This was fixed in 1.5.1.1
