### ISSUE TITLE
[bug] more enchantments

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#36]
projectile protection 4 gets hammered on the anvil and leaves projectile protection 3 on the enchanted item.

**Comment by Dragon5mith** [comment]
The runic anvil recipes for fire protection in the codex are labelled as fire aspect and don't work, due to the rune wanting fire aspect. They are pictured differently from fire aspect.

**Comment by Dragon5mith** [comment]
blast protection 3 in the runic anvil, I would not have guessed white concrete powder by the look, especially after using different quartz items in other enchantments. (related to the mouseover recommendation listed elsewhere)

**Comment by Mithion** [comment]
The runic anvil now correctly checks and upgrades enchantments, and will allow applying multiple enchantments to a single item if they are compatible.

Blast protection III is now set to tagged, allowing any concrete.
