### ISSUE TITLE
Make Book of Shifting Lands Respect Ritual Consume True/False Setting

### ISSUE THREAD

**Issue by AetheriMC** [Mithion/Mana-And-Artifice#360]
**Is your feature request related to a problem? Please describe.**
Not precisely. Essentially, for the purposes of custom server balance, I alter the ritual components within the mod file directly, either making a ritual require different items, or making a ritual consume items instead. In the case of rituals involving the Book of Shifting Lands, in spite of setting consume to true, the book as an item still falls to the ground after the ritual completes.

**Describe the solution you'd like**
I would like for the book to be consumed as part of the ritual if the ritual recipe is configured for it to do so. Preferably I would like for the aesthetic of the book floating to be unchanged, but for the book to not drop after the ritual completes.

**Describe alternatives you've considered**
None, other than accepting that as an admin, we cannot control this one minor aspect of M&A :)

**Comment by Mithion** [comment]
Fixed for 1.5.1.2; for Flat Lands, Earthen Steppes, and Yawning Chasm.
