### ISSUE TITLE
Spells ignore PVP enabled server config

### ISSUE THREAD

**Issue by JBurlison** [Mithion/Mana-And-Artifice#361]
**Describe the bug**
Spells are killing friends

**To Reproduce**
1. cast a damage spell on a player, it kills them

**Expected behavior**
Dont kill them if pvp is disabled on the server

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.8
 - Forge Version: forge-36.2.8

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Corrected as of 1.5.1.2.
If a spell contains any components tagged as "harmful" and server PvP is disabled, it will remove any players from the target list.
