### ISSUE TITLE
Dying to Ritual of the Burning Hells causes floating bug

### ISSUE THREAD

**Issue by jah83440** [Mithion/Mana-And-Artifice#362]
**Describe the bug**
Dying due to damage incurred from the Ritual of the Burning Hells causes a floating effect upon respawn. Leaving and rejoining the world corrects the effect.

**To Reproduce**
1. Get reagents for Ritual of the Burning Hells
2. Perform the ritual
3. Don't be fully prepared for the burning damage, and die
4. Respawn, and begin floating

**Expected behavior**
I expected to simply respawn as normal.

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.10
 - Forge Version 36.1.13

**Comment by Mithion** [comment]
Fixed in 1.5.1.2 - the mod will attempt to cleanly remove the lift effect if the player dies while it is applied.
