### ISSUE TITLE
Ticking Block Entity Crashing Bug (crash report indicates the Arcane Sentry as the source)

### ISSUE THREAD

**Issue by jah83440** [Mithion/Mana-And-Artifice#364]
**Describe the bug**
We are encountering a crashing bug that appears to involve the ticking in the Arcane Sentry. We aren't really sure what caused the error, as the Sentry has been placed for more than a day with no problems.

**To Reproduce**
1. Get item Arcane Sentry
2. Place the Sentry
3. Beyond that, not sure. There is a pastebin attached to this report.

**Expected behavior**
Expected normal non-crashing behavior from the mod at large and the sentry in particular.

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.10
 - Forge Version 36.1.13

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/
[Sztza9FS.txt](https://github.com/Mithion/Mana-And-Artifice/files/7516881/Sztza9FS.txt)
.

**Comment by x4dr** [comment]
can confirm, crash report https://pastebin.com/nqX30Cw1
might not be relevant, as it is from 1.5.0.9, but since the patchnotes didn't mention anything, it might help

Mod Version 1.5.0.9
Forge Version 1.16.5-forge-36.2.2

**Comment by Cerubois** [comment]
Confirming that this is still crashing in 1.5.0.10. Mod was working just fine until one of us tried placing an Arcane Sentry. Crashed shortly after and now crashes upon load.
We'll unfortunately have to remove this mod until a fix is figured out, as it's holding our save file hostage.

**Comment by Mithion** [comment]
This was fixed in 1.5.1.1
