### ISSUE TITLE
Client side crash when Witch hunter attacks witch 

### ISSUE THREAD

**Issue by Milka-byte** [Mithion/Mana-And-Artifice#366]
So I noticed that on my server  when a witch hunter attacks a witch and a player is close by the client for that player crashes. Other players that didnt see the Witch hunter animation stay in the game.

Just Spawn a witch and a witch hunter then you should see it.

I will post the error message and the mods I have down here. 
Maybe gecko lib is broken bcz some mods are not compatible

The log says that the animation is the problem but idk for sure

-Mod version:1.5.0.10
-forge-36.2.9

https://pastebin.com/ySHGg7D1

**Comment by drakray** [comment]
Got the same thing after updating Geckolib https://pastebin.com/Jz9xiUL4

**Comment by b52src** [comment]
same

**Comment by Milka-byte** [comment]
Yeh
so the newest version of gecko lib breaks stuff  so i just installed an older version
version: geckolib-forge-1.16.5-3.0.51.jar
and it works now and thx drakray for the confirmation that its geckolib

**Comment by Mithion** [comment]
Closing as issue with GeckoLib as per [this issue](https://github.com/bernie-g/geckolib/issues/197)
