### ISSUE TITLE
Crash when clicking "Name & Icon" on a rote spell that was just cleared due to being invalid

### ISSUE THREAD

**Issue by flarn2006** [Mithion/Mana-And-Artifice#367]
**Describe the bug**
You know how some spell combinations aren't valid, and when you add an invalid effect in the Book of Rote, the entire spell is cleared? I just had that happen to me, and noticed it had also cleared the name and icon. When I clicked the button to reconfigure the name and icon on that spell, the game crashed.
Note that I've only had this happen once so far, and I haven't (yet) tried to reproduce it. The steps in "To Reproduce" are what I did which caused the crash.

**To Reproduce**
1. In the Book of Rote, create Wall + Frost Damage + Fling.
2. Give the spell a name and icon, and then exit from the book.
3. Reopen the book UI, and select that spell again.
4. Add "Summon Workbench" as a third effect, and close the book.
5. Repeat step 3. Notice how the page has been cleared.
6. Click "Name & Icon" (or whatever the button says)
7. Observe that the game has crashed.

**Expected behavior**
Naturally, I would expect the icon/name selection UI to appear.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.8
 - Forge Version 1.16.5-forge-36.2.4

**Additional context**
Crash log: https://pastebin.com/ACsQxSMp

**Comment by Mithion** [comment]
Fixed in 1.5.0.0
