### ISSUE TITLE
Projectile spells not rendering properly/or at all

### ISSUE THREAD

**Issue by InsaniteaTV** [Mithion/Mana-And-Artifice#369]
1 of 2 things happens when i mean this, either 1. the glowing head of a projectile does not show or 2. the projectile itself, trail and all, does not show

**To Reproduce**
1. grab any spell with the projectile base part
2. Use it
3. Have optifine installed (?)

**Expected behavior**
I remember that there was a glowing head to projectile spells like light and others, and that there should be a tail for all of them

**Screenshots**
can't show what isnt there

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.10
 - Forge Version 36.2.0

**Additional context**
I have optifine installed and am running the mod on a server

**Comment by Mithion** [comment]
Optifine is not supported.
