### ISSUE TITLE
[enhancement] creative mode

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#37]
When in creative mode right clicking an item into runes, the mana altar, or the runic anvil should not consume the item in hand (like placing items or putting them in item frames).

**Comment by Mithion** [comment]
The following blocks no longer consume items when right clicked in creative mode as of 1.0.2-pre1:
Chalk Rune
Metal Ritual Rune
Pedestal
Runic Anvil
Runeforge
Manaweaving Altar
