### ISSUE TITLE
Unable to cancel SpellEvent

### ISSUE THREAD

**Issue by TheCosmicNebula** [Mithion/Mana-And-Artifice#370]
**Describe the bug**
I am developing a mod (Dimensional Pockets II) that has spaces for individual players. You're BLINK spell allows players to exit this space. I have tried for the last 2 hours to stop this behaviour, but cannot without completely disabling spells.

**To Reproduce**
1. Get spell 'BLINK'
2. Use inside a Pocket from Dimensional Pockets II.
3. It allows escape from the enclosed space.

**Expected behavior**
I should be able to disable this action, as I have done with 'ender_pearls', 'chorus_fruit' and other mod items.

**Version Information (please complete the following information):**
 - Mod Version: [1.5.0.110]
 - Forge Version [36.2.0]

**Additional context**
On another note, the API version on your site is out of date and broken, and I have found it impossible to add Mana and Artifice to my Eclipse Dev environment, even following proper ForgeGradle dependency format. I love your mod, but it breaks mine :(

**Comment by Mithion** [comment]
Sorry about that.  The latest API is posted on the Discord server: http://discord.gg/4nJEU4X
I've annotated the SpellCastEvent as @Cancelable in API 1.5.1.2.

**Comment by TheCosmicNebula** [comment]
Many thanks! I didn't realise you had a discord, as I would have looked there. Appreciate the help, and love the mod!
