### ISSUE TITLE
Spells that affect blocks should not be usable inside a chunk protected by other player (FTB Chunks)

### ISSUE THREAD

**Issue by sabinico** [Mithion/Mana-And-Artifice#371]
**Is your feature request related to a problem? Please describe.**
Some spells are capable of acting on blocks, for example, the effect of gravity.
These spells should not be able to be used in a chunk protected by another player.

**Describe the solution you'd like**
The mod could try to check if the chunk is protected before activating the effect of the spell.

**Describe alternatives you've considered**
I have thought about looking for another chunk protection mod that is compatible, but the one I currently use (FTB Chunks) is the best known and the one with the most compatibility with the rest of the mods.

**Additional context**
Last mana and artifice version running in Enigmatica6 custom modpack.

**Comment by Mithion** [comment]
Added destruction checks to Collapse and Earthsky as of 1.5.1.2
