### ISSUE TITLE
[Request] Kybindings for spells on hotbar

### ISSUE THREAD

**Issue by WhiteCrafter** [Mithion/Mana-And-Artifice#372]
In combat i often want to use different spells, but i fell its uncomfortable and slow to scrooll to 9th slot(or strech my finger) and then switch back to my main spell. Same goes with books as well. While ur chosing spell from book you cant really move(and that split second is really important in close combat pvp, although u can get better and faster with that, it would be nice if there was some keybinding for spells.

There could be multiple ways to do this:
1. By sellectyng keybinding, (Just like u do with icons and names)
and spell should only work if u have in hotbar. if u have multiple spell with same keybinding first ome on hotbar should be casted.
or closest one from active slot. (some little letters on the icons would be nice so player could instantly see what key does what).
2. there could be some special book(one for player like book of rote) and set up keybindings from mineqraft control settings. But downside of this option is that there is lack of vizualisation. Player wont be able to remember what spells did he put and in which.
3. By assigning keybinds to the hotbar slots instad of spells. keybinds would cast whatever spell is in corresponding slot. pluss is that this way u could activate default spells in spell book and rote. Player wouldnt need letter icons in the spell icon because keybinds would be constantly asinged to same hotbar slot and wouldnt be hard to remember( in the first example player would be setting different keybind for every different spell and its easy to mess up, in seccond example u could forget which spells was put in the book and in what order, here u would just need to look at hotbar). 

only downside is that there wouldnt be 9 keys free on the keyboard(since there is hight chance there would be other things using them), but in 3rd case(which i think is best) it ballances little bit. player would most likly set up  max 3 or 4 keybinds and still would have to use books. but quickly cast imortanf spells in combat.

it would feel like nice rpg with spell icons and keybinds for them<3
sorry for such long explanation, just really like this idea

**Comment by Mithion** [comment]
This goes against the design philosophy of the mod, which is minimal keybinds - the radial menu in spell books can allow easy switching between spells.

I'm looking into allowing movement while the radial menu is open, which may or may not happen.
Spells in can be put into the existing hotkey slots, and those could also be re-bound for PvP convenience.
