### ISSUE TITLE
Games crashing when loading creative tab for this mod

### ISSUE THREAD

**Issue by Nathannaters** [Mithion/Mana-And-Artifice#373]
I just got the mod and everytime i go to look through the items in the inventory or even with the JEI menu the game crashes. It gives me an exit code - 1 and i read some of the crash log and it reads something about a "constructs/construct_grabber_arm_left_iron" in the item being render details and im assuming this is whats crashing my game but im not sure and would like a little help.

**Comment by Mithion** [comment]
There is not remotely enough information here to look into it.  There's a bug posting guide/template, please follow it and re-submit.
