### ISSUE TITLE
Emberglow Bracelet discharges too quickly

### ISSUE THREAD

**Issue by grundyboy34** [Mithion/Mana-And-Artifice#375]
**Describe the bug**
The Emberglow Bracelet completely discharges in only around 3 seconds of being in lava.

**To Reproduce**
1. Equip charged Emberglow Bracelet
2. Jump into lava
3. Notice protection expires after around 3 seconds, often leaving you dead before you can get out of the lava.

**Expected behavior**
I'd expect such an artifact to provide longer protection, especially given the faction's theme and that you'll be spending a lot of time around lava pools in this faction.

**Version Information (please complete the following information):**
 - Mod Version: 1.5.0.10
 - Forge Version 36.2.8

**Comment by Mithion** [comment]
Clearly the solution is to stop jumping into lava :P

Jokes aside, I've buffed the bracelet's maximum charge in 1.5.1.2.
