### ISSUE TITLE
Issue Creating Spells with the Fossilize Effect

### ISSUE THREAD

**Issue by Evakyl** [Mithion/Mana-And-Artifice#378]
Attempting to create a spell with the Fossilize effect results in the ritual failing to start once all the materials are placed. Particles as if there is a material missing appear.
Cleaning up and re-setting up the ritual and remaking the scroll through the scribing table does not fix the issue. 
Changing the target or modifiers have no effect on the outcome, with each change still failing at starting the ritual. 
Faction and tier requirements have been met.
Other spells can still be created so long as Fossilize is not used.

**Comment by Mithion** [comment]
The fossilize recipe was fixed in 1.5.1.1
