### ISSUE TITLE
The ritual of the greater mote of magic doesn't work.

### ISSUE THREAD

**Issue by hitmanssilent** [Mithion/Mana-And-Artifice#379]
Thats it, it simple doesn't work.

**Comment by Mithion** [comment]
First, "it doesn't work" isn't a proper bug report.  There's a template for submitting bug reports, I suggest you use it.  Had you provided reasonable information I could have told you what you were doing wrong.

Second off, yes it does.  Tried it and it worked without issue.  If you would like assistance, come to the Discord server and ask, someone there can help you.

http://discord.gg/4nJEU4X
