### ISSUE TITLE
[Bug] on ritual kits not actually saving some rituals

### ISSUE THREAD

**Issue by ace10102** [Mithion/Mana-And-Artifice#38]
**Description:**
so far ive found that the ritual kit only successfully saves the eventide ritual when oriented north/south
and the ritual of ancient stone only saves when oriented this specific direction
![image](https://user-images.githubusercontent.com/33331567/85073740-51d87e80-b189-11ea-9d47-7004a0a199c3.png)
(top of screen is north)
it does say 'ritual pattern stored' in chat even if it doesnt 'actually' save, so its recognizing them, but it doesnt update the kit's tooltip and doesnt remove previously saved rituals from the kit
ill go test other rituals rn

**Comment by ace10102** [comment]
ritual of return only has two orientations and neither of them save

**Comment by Mithion** [comment]
This has been fixed in 1.0.4-pre2
