### ISSUE TITLE
Complexity changes but spell remains the same

### ISSUE THREAD

**Issue by VallenFrostweaver** [Mithion/Mana-And-Artifice#381]
Minecraft 1.16.5
Forge 36.2.2
M&A 1.5.0.8

I found a weird behavior when adjusting spells... when I increase/decrease something like speed or damage and then bring it back up/down to what it was before, the complexity is different (it costs more). BUT. If I max it and then go back up/down to where it was, it fixes it. See below for before and after screenshots
![1](https://user-images.githubusercontent.com/13642054/144632233-44582a82-7b5f-4ac2-996d-31d223e40070.png)
![2](https://user-images.githubusercontent.com/13642054/144632235-f1dcf635-0334-4791-b630-a0ab0c41e428.png)
.

**Comment by Mithion** [comment]
Long since resolved...kind of forgot about GitHub for a while and had notifications going to the wrong email.  Oops.
