### ISSUE TITLE
So i tried fixing a spell a friend made, it was applied to self and was felled oak, i tried the spell and it started draining my mana quickly, and even when i destroyed it, my mana kept dropping how do i fix this?

### ISSUE THREAD

**Issue by Blank655** [Mithion/Mana-And-Artifice#383]
**Describe the bug**

**To Reproduce**
1. Get item '...'
2. Use on '....'
3. Have magic level '....'

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.0]
 - Forge Version [e.g. 36.1.32]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Tried in 1.5.1.2, was unable to replicate this.  If it happens again, please save and upload your player.dat file and I can take a look.
I suggest updating to latest (1.5.1.2) when it comes out, as it fixes many bugs and has many gameplay improvements.
