### ISSUE TITLE
Grimoire Radial Menu Mapping

### ISSUE THREAD

**Issue by jah83440** [Mithion/Mana-And-Artifice#384]
**Describe the bug**
The expanded Grimoire and Faction Grimoire (and possibly spellbook, I don't know because I only have a grimoire) has a mapping error in its new 16-slot radial menu. The first 8 menu slots (in the radial menu, not the Grimoire GUI) are repeated for the next 8. For instance, If the first slot in the radial menu is a Projectile Fire Spell called Fire Bolt, the 9th slot will also be Projectile Fire Spell, both when blank or when holding a different spell.

**To Reproduce**
1. Get item Grimoire or Faction Grimoire
2. Place a spell in slot 1. Leave other slots blank for ease of observation.
3. Select slot 1 in the radial menu
4. Select slot 9 in the radial menu

**Expected behavior**
Expected regular behavior of expanded grimoire space.

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.1
 - Forge Version 36.1.13

**Comment by Mithion** [comment]
Fixed in 1.5.1.2 - good catch!
