### ISSUE TITLE
Ticking Entity Error: Fireballs

### ISSUE THREAD

**Issue by jah83440** [Mithion/Mana-And-Artifice#385]
**Describe the bug**
A crashing error occurs whenever a fireball from a Ghast, a Blaze, or a player collected fire charge strikes a player.

**To Reproduce**
Self-contained
1. Get items dispenser, lever, and fire charge
2. Place fire charge in dispenser, and activate dispenser with lever. Ensure launched fire charge strikes a player.
3. Observe crashing behavior

**Expected behavior**
I expected the Infernal Armor to protect me from the fire and explosive force of a fireball.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.2
 - Forge Version 36.2.20

**Additional context**
https://pastebin.com/1U2h9s67

**Comment by Paduber** [comment]
Same here, arrow triggers crash too

**Comment by Mithion** [comment]
Resolved in 1.5.1.3
