### ISSUE TITLE
Odd lighting effects

### ISSUE THREAD

**Issue by CodexArchive** [Mithion/Mana-And-Artifice#386]
**Describe the bug**
Some of the Mana and Artifice blocks become rather dark/shadowed when placed down in the world, even more pronounced when placed next to each other. Additionally, upon opening up the first Mana and Artifice item page in either  JEI or in the creative menu, it appears to invert the shading on any minecraft entities or item sprites in the player's inventory.

**To Reproduce**
Replicate included screenshots and the lighting should act as shown in said screenshots. (the walls are not required for the in-world shadowing to happen, it just helped make it more apparent)

**Expected behavior**
Proper shading for both items in inventory and placed blocks.

**Screenshots**
<img width="1440" alt="MnA dark blocks" src="https://user-images.githubusercontent.com/80467605/146003333-3364d12b-2a73-43a1-8df0-bff2123b1fc7.png">
<img width="1440" alt="MnA Shaded inventory" src="https://user-images.githubusercontent.com/80467605/146003341-0f6dc4ce-f802-418f-9ede-77b47a5195c7.png">
<img width="1440" alt="MnA shaded inventory 2" src="https://user-images.githubusercontent.com/80467605/146003350-1c7584ce-431c-4ee1-8cdd-1232fe63464b.png">

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.2
 - Forge Version 36.2.20
 - JEI version: 1.16.5-7.7.1.138

**Comment by Mithion** [comment]
Resolved in 1.5.1.3 - related to manaweave bottles.  For blocks, it's an ongoing, overarching, much larger process to remodel them and will not be tracked as part of this issue.
