### ISSUE TITLE
Projectile crash

### ISSUE THREAD

**Issue by CodexArchive** [Mithion/Mana-And-Artifice#387]
**Describe the bug**
When attacked by an enemy using projectiles (skeleton assassin, pillager, skeleton, etc.), it causes the game to crash

**To Reproduce**
1. Be in survival
2. Spawn an enemy that uses only projectile attacks
3. Game should crash upon enemy attacking you before projectile deals damage

**Expected behavior**
The enemy's projectile should do damage, not crash the game

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.2
 - Forge Version 1.16.5-36.2.20

**Comment by Keltas** [comment]
I was just about to report this as I've experienced the same issue when skeletons shot at me. I am attaching a crash log:
[crash-2021-12-14_21.43.57-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/7714942/crash-2021-12-14_21.43.57-server.txt)

**Comment by Mithion** [comment]
Resolved as part of 1.5.1.3
