### ISSUE TITLE
Suggestion: Broom compatible with Metal barrels mod

### ISSUE THREAD

**Issue by BreazyLantern** [Mithion/Mana-And-Artifice#388]
Can you add compatibility with the metal barrels mod for the broom and vortex broom? I'm playing with ver. 1.5.0.10. so sorry if I made this without knowing if that had been added or is already planned.

**Comment by Mithion** [comment]
Brooms look for an IItemHandler capability on a block, from the UP direction.  Any block that doesn't have it won't be compatible at this time.  This may be revisited at a future date, however.

**Comment by Mithion** [comment]
Resolved with later versions of the mod.
