### ISSUE TITLE
Runescribing Recipe crash when it's on the floor

### ISSUE THREAD

**Issue by Kzeroko** [Mithion/Mana-And-Artifice#389]
**Describe the bug**
When the rune scribing recipe is on the floor, it crashes the client, and the save is unavailable unless I uninstall this mod:(

**To Reproduce**
1. Get Item Rune scribing Recipe.
2. Throw it on the ground
3. crashes

**Expected behavior**
Not crashing

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.4]
 - Forge Version [e.g. 36.2.8]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.
[crash-2021-12-20_05.19.49-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/7742797/crash-2021-12-20_05.19.49-client.txt)

**Comment by Mithion** [comment]
This looks like a crash with LootBeams that displays additional information about items on the ground?  This doesn't happen with just M&A.

The only thing I can think of is that the world passed in is null (which shouldn't happen) or the world's recipe manager is null (which also shouldn't happen).

I put some extra checks in to look for those conditions, will go out in 1.5.1.5.
