### ISSUE TITLE
The Grimoires page has Manaweaver Wand recipes instead of the Grimoire

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#390]
![image](https://user-images.githubusercontent.com/15698722/146783890-45d7059e-ddcf-4d5c-9f41-f4ef706d5e6f.png)

This is mana-and-artifice-1.5.1.4

**Comment by Mithion** [comment]
That's because the wands show the cantrips menu which is how you get a grimoire.
