### ISSUE TITLE
Faction Grimoires are apparently unobtainable

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#391]
Faction Grimoires are not mentioned anywhere in the Codex Arcana, and they do not have a recipe in JEI.

This is on mana-and-artifice-1.5.1.4

**Comment by Mithion** [comment]
They're a cantrip, T4, which you are guided to by the progression task "cast a T4 cantrip".

**Comment by aaronhowser1** [comment]
So when you're in a faction, the normal Grimoire cantrip gives you the new special one instead?
