### ISSUE TITLE
Not able to make Vinteum Dust

### ISSUE THREAD

**Issue by Velajuel121** [Mithion/Mana-And-Artifice#392]
**Describe the bug**
I play the modpack enigmatica 6 on a server and we installed mana and artifice in addition. 
The problem is that there is no recipe to create vinteum dust. Beside that, there is no recipe to use the Vinteum Ore.
I tried it both Multiplayer and Singleplayer - same result

**To Reproduce**
I downloaded the Enigmatica modpack on CurseForge and added the mod through curseforge

**Expected behavior**
Well, i guess crafting vinteum dust

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: mana-and-artifice-1.5.0.10
 - Minecraft Version: 1.16.5

**Additional context**

**Comment by Mithion** [comment]
Enigmatica 6 uses FastSuite (or FastFurnace), which messes with M&A recipes.  Remove that and you should be good to go.
