### ISSUE TITLE
Wellspring wont give Energy

### ISSUE THREAD

**Issue by Ironigel** [Mithion/Mana-And-Artifice#393]
to put it short 

I build everything i need, i placed it, the beam is there, but i wont get any energy from it. (Air Wellspring) 

The first one is working fine

**Comment by ChrisLTheNerd** [comment]
That happened to me once, apparently it was just that I confused an unknown wellspring for an air one. So make sure it's actually an wind one.

One on the left is an unknown wellspring, the other on the right is a wind wellspring.
![2022-01-01_18 25 54](https://user-images.githubusercontent.com/50182206/147862196-4cc1e1cc-51e4-496f-b686-87d52214fe12.png)

**Comment by Mithion** [comment]
Wellsprings were improved in 1.5.1.5, and some bugs relating to this were fixed.
