### ISSUE TITLE
command: place item

### ISSUE THREAD

**Issue by kosnic** [Mithion/Mana-And-Artifice#394]
**Describe the bug**
put place item command twice in a row, but specifies two different container, and construct will ignore the second target and put two items in the same first container instead of two different.
**To Reproduce**
I tested this once on my server and once in my own game, both happened, so I suppose this needs no special moves to reproduce
both was wooden construct though
**Expected behavior**
Items will be put into two different container.
**pictures**
![JHMZR5)Z{WABKCKCPT07ILE](https://user-images.githubusercontent.com/96661243/147390261-85220e4b-0c15-4cb8-9f96-13112629ae35.png)
![E73AJ`OPUQ$SEC (0A@0BBU](https://user-images.githubusercontent.com/96661243/147390263-12715c84-391e-4d1f-9f69-4caadc873c67.png)
![E6@FC3FA(4K((NF3FZ3~`XF](https://user-images.githubusercontent.com/96661243/147390264-5e0dc9b0-a101-4d1f-8f94-882e00b991c7.png)
![KJ9}{UYWPB~T_`7{Z`BBHZQ](https://user-images.githubusercontent.com/96661243/147390265-bafedffa-a4a3-4539-af90-786e65805127.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.3
 - Forge Version 36.1.19

**Additional context**
it still happens with no other mod

**Comment by Mithion** [comment]
The place item task will empty the construct's inventory currently.  The next update is a large update for constructs.  It will still be a while, but there will be a way around this! :)
