### ISSUE TITLE
Eldrin conduits not dropping themselves on servers

### ISSUE THREAD

**Issue by TBone311xXx** [Mithion/Mana-And-Artifice#395]
**Describe the bug**
Eldrin conduits don't drop when broken on server

**To Reproduce**
1. Get item Eldrin conduit : wind
2. Break it
3. Have magic level 60
4. Doesn't drop the conduit

**Expected behavior**
should drop the conduit item

**Version Information (please complete the following information):**
 - Mod Version: [1.5.1.5]
 - Forge Version [36.2.21]

**Comment by TBone311xXx** [comment]
Seems to also be applying to Runeforges

**Comment by SangurianSoul** [comment]
Indeed. I was running into this issue specifically with the Runeforge last night. Though I haven't progressed far enough on the server to see if I'm having issues with the other blocks as well.

**Comment by SangurianSoul** [comment]
Okay yes, i am having issues with the Runeforge and the Inscription Table, so it is likely i am having issues with all the multiblocks as well

**Comment by Mithion** [comment]
How are you breaking the blocks?  With a tool?  Break spell?

**Comment by TBone311xXx** [comment]
Breaking it with the break spell drops the multiblocks, using any other tool including none, and silk touch, does not drop them

**Comment by Mithion** [comment]
Ok, I will investigate - thanks!

**Comment by Mithion** [comment]
Hi there- this should be resolved in 1.18.1, and the changes will be backported to 1.16.5 when it next updates.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).
