### ISSUE TITLE
Chimerite Sandstone Walls Not Connecting

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Mithion/Mana-And-Artifice#396]
**Describe the bug**
Chimerite Sandstone Walls don't connect

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
![2022-01-01_18 18 45](https://user-images.githubusercontent.com/50182206/147863316-f6618d32-ace7-4bbc-b59d-15117b220d13.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.5
 - Forge Version 36.2.20

**Additional context**
None

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).
