### ISSUE TITLE
[Suggestion] Make the redstone spell trigger emit a short pulse (like a button) rather than the long pulse it does now.

### ISSUE THREAD

**Issue by CheeseMan2400** [Mithion/Mana-And-Artifice#398]
I really like the redstone spell trigger but I find that the long pulse length can make it really difficult of even impossible to use in a lot of situations. If the pulse were the same as a button I think it could be a lot more versatile. 

Maybe there could even be a way to "upgrade" it to increase pulse length, possible by using redstone on it.

**Comment by Mithion** [comment]
Not a bad idea at all, thank you!
