### ISSUE TITLE
flower texture weirdness

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#4]
certain angles of looking at the wakebloom clip over itself and create black shapes over the water

an update, all am3 flowers have the clipping over themselves. One texture diagonal works fine while the other eliminates the item's texture behind it
![2020-06-13_01 16 32](https://user-images.githubusercontent.com/8917961/84560613-bae86e00-ad13-11ea-814f-e17b6db8236f.png)
![2020-06-13_01 19 07](https://user-images.githubusercontent.com/8917961/84560643-ecf9d000-ad13-11ea-97b1-7162fcc6876e.png)
![2020-06-13_01 19 16](https://user-images.githubusercontent.com/8917961/84560645-ee2afd00-ad13-11ea-913c-eebfa1d25418.png)

**Comment by Mithion** [comment]
Resolved in 1.0.1-pre1
