### ISSUE TITLE
[1.0.3-pre2] Respawn impossible

### ISSUE THREAD

**Issue by Edorior** [Mithion/Mana-And-Artifice#40]
In a world in creative world, i tried /kill to return to the spawn. After pushing the respawn button, nothing happen and errors appeared in the console window (i'm using MultiMC 5). I tried with a new world refreshly created and /kill produced the same bug. After removing the mob and reloading a world, the initialization loop forever at 97%. With another new world, /kill works correctly.
Here is a log of the bug after trying to respawn after a /kill : https://paste.ee/p/LmNvC

**Comment by Edorior** [comment]
Update: it happen also in survival mode, in a world started in creative

**Comment by BinaryEnigma01** [comment]
This happens with all deaths it seems, I'm using twitch with JEI, recommended forge version, survival, no cheats resulted in the same thing, no respawning at all

**Comment by Mithion** [comment]
This has been fixed in 1.0.4-pre2
