### ISSUE TITLE
Crystallize'd shulkers don't uncrystallize properly

### ISSUE THREAD

**Issue by TBone311xXx** [Mithion/Mana-And-Artifice#400]
**Describe the bug**
Crystalline caged Shulkers remember their position in the world and teleport back to that spot when uncaged, resulting in the inability to transport mobs as intended.

**To Reproduce**
1. Get item - Spell with Crystallize (and magnitude 4 if applicable)
2. Use on - Shulkers anywhere
3. Have magic level - 75
4. See error - none

**Expected behavior**
Shulkers should recognize where they were uncaged as their new location.

**Screenshots**
The spell used.
![image](https://user-images.githubusercontent.com/12605227/148516912-07d83c2c-b63a-4062-9720-68425b333926.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.5
 - Forge Version 36.2.21

**Additional context**
Playing on a Server.

**Comment by Mithion** [comment]
Crystallize saves/loads the entity directly including all relevant properties as if the world did.  
Interacting with that data or manipulating it would break abstraction - not going to fix this.

I will put it in the codex that some entities do not crystallize well and mention Shulkers.  It kind of makes sense given that they're in the end and do strange multidimensional things in vanilla that they'd simply be able to teleport home.
