### ISSUE TITLE
Purple Textures 

### ISSUE THREAD

**Issue by Asraell** [Mithion/Mana-And-Artifice#401]
Describe the bug
Hi, I'm using Mana and Artifice 1.5.1.5 for Minecraft 1.16.5, I don't have any texture pack or shaders on and yet I have purple Mana codex.

Screenshot
![2022-01-07_11 16 06](https://user-images.githubusercontent.com/97285800/148529174-969bca0c-e07b-482d-b895-7d55e13b70b7.png)

**Comment by Mithion** [comment]
Post full game logs please so I can investigate - thanks!

**Comment by Asraell** [comment]
Hi sorry for responding very late, it apparently is just smthg with resource packs and shaders. Sometimes reloading just do the trick and sometimes I have to disable the resource pack / shaders. Vanilla it works fine.

**Comment by Mithion** [comment]
Oh, okay - going to close this then.  Thanks!
