### ISSUE TITLE
Magician's Workbench breaking when mined

### ISSUE THREAD

**Issue by Crystlack** [Mithion/Mana-And-Artifice#402]
**Describe the bug**
Magician's workbench breaks instead of dropping when mined.

**To Reproduce**
1. Place Magician's Workbench
2. Mine it
3. 
**Expected behavior**
Expected to get the workbench back, but it just disappears instead

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.5]
 - Forge Version [e.g. 36.2.22]

**Comment by Mithion** [comment]
Hi there- this should be resolved in 1.18.1, and the changes will be backported to 1.16.5 when it next updates.

**Comment by Danekjovax** [comment]
I also find this issue with many other artifices like the runeforge, and all the of the wellspring artifices (Pillars/lens).

**Comment by Danekjovax** [comment]
No fix for 1.16.5?
