### ISSUE TITLE
Please Convert your .ogg files into Mono format instead of Stereo

### ISSUE THREAD

**Issue by Y3Z0N** [Mithion/Mana-And-Artifice#404]
You use Stereo Vorbis files which means the sound will appear even if a player is miles away from a sound event.
Solution convert all of your .ogg files into mono format thats how Minecraft does it and you should do it too.

**Comment by Mithion** [comment]
Oh that's why that happens...good to know.  Will do!

**Comment by Y3Z0N** [comment]
you re not alone this misstake is made by several devs :-)

**Comment by Mithion** [comment]
This has been completed in dev for next release (1.18.1)
