### ISSUE TITLE
Inscription table stops writing spell after rejoining world

### ISSUE THREAD

**Issue by Cyakat** [Mithion/Mana-And-Artifice#406]
**Describe the bug**

I was using the Inscription table to create a self recall spell and I had logged off in the middle of the table writing the spell. I later rejoined and the progress bar is stuck and won't move at all. I can't click the arrow to make a new spell with the original parts. I can make a new spell with different parts but the table won't tell me how much vellum and ink it needs to make. Breaking and replacing the table fixes the problem

**To Reproduce**
1. Create spell on inscription table on single player world
2. Exit out of the game
3. Rejoin game
4. See stuck progress bar

**Expected behavior**

When I rejoined the game I expected to see the progress bar continue to move from where it was when I left the game.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.5]
 - Forge Version [e.g. 36.2.22]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).
