### ISSUE TITLE
1.18.1 version game closes on ritual display

### ISSUE THREAD

**Issue by LoneWolf137** [Mithion/Mana-And-Artifice#408]
Describe the bug:
when you try to open the display for any ritual ( say layout ritual of the arcane for example) the game closes. all other displays (manaweaving, crafting ...) seam to work.

To Reproduce:
1. get the arcane compendium
2. open any ritual page
3. try to display the layout on the top right

Expected behavior:
the game closes. the world loads fine after, but you can´t display the rituals.
Also no crash report get created.

Version Information:
 - Mod Version: [1.7.0.1]
 - Forge Version [39.0.59]

**Comment by Mithion** [comment]
This is fixed in dev for 1.7.0.2
