### ISSUE TITLE
Eldrin Flight affinity preview?

### ISSUE THREAD

**Issue by Timelife** [Mithion/Mana-And-Artifice#409]
The description of the Eldrin flight spell states that you can see the affinity of the wellspring before traveling to it. But all I see are the white "path lines". Am I missing something?

**Comment by Mithion** [comment]
It only shows the affinity for captured eldrin wellsprings.

**Comment by Danekjovax** [comment]
I would find the ability of previewing affinities of nearby wellsprings as very convenient.

**Comment by Danekjovax** [comment]
> It only shows the affinity for captured eldrin wellsprings.

Ok, I have seen that, and that's ok.  I am wondering what the little spheres are, that appear near a wellspring?

**Comment by Mithion** [comment]
Not sure what you mean, can you provide a screenshot?

**Comment by Danekjovax** [comment]
Sure thing.  I'll send a screenshot or two tonight.
