### ISSUE TITLE
Hard Crash When Placing Inscription table.

### ISSUE THREAD

**Issue by addis2123** [Mithion/Mana-And-Artifice#410]
**Describe the bug**
The game crashes when placing down the inscription table. Additional note: I was able to reopen the world and the chunk containing the table would not load.

**To Reproduce**
1. Clean install of the mod using CurseForge
2. Create a new creative world
3. Place down the inscription table
4. See an error

**Expected behavior**
The inscription table is placable in the game.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [1.7.0.1]
 - Forge Version [39.0.59]

**Additional context**
https://www.toptal.com/developers/hastebin/bibilewore.properties/

**Comment by Oucori** [comment]
Got the same behavior.

**Version Information (please complete the following information):**
Mod Version: [1.7.0.1]
Forge Version [39.0.59]

**Comment by addis2123** [comment]
Managed to do some testing on other versions of forge. The following versions experience the issue.

39.0.59, 39.0.58, 39.0.57, 39.0.56.

Wondering if this is java and its latest update. Currently running java Version 8 Update 321.

**Comment by addis2123** [comment]
So after some more testing, The JDK 17.0.2 and the bundled in launcher java are producing the same issues. Java 1.8.0_321 is not compatible with the installation of MC I'm testing with.

**Comment by addis2123** [comment]
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.mna.blocks.tileentities.InscriptionTableTile.save(net.minecraft.nbt.CompoundTag)'
Exit Code: -1

Posting in case people are searching google for answers.

**Comment by Febilian** [comment]
Pretty sure this was due to breaking changes in recent Forge versions, some other mods have had issues with it as well and had to update.

**Comment by facepalmgamer** [comment]
turns out it's stable with forger version 39.0.44 (i checked all until I got this one and it worked), and if you remake the instance and move you're saving over you can save the world file. not sure of any other effects that might have so I recommend taking not of items and remaking the world and just spawning stuff in.

**Comment by Febilian** [comment]
That approach unfortunately doesn't work if playing with other mods that already require the newer Forge versions, but it is at least an option if none of your other mods want the newer Forge versions.

**Comment by Mithion** [comment]
This is fixed in dev for 1.7.0.2
