### ISSUE TITLE
Hard Crash when viewing any ritual

### ISSUE THREAD

**Issue by facepalmgamer** [Mithion/Mana-And-Artifice#411]
**Describe the bug**
whenever you click on a ritual (not the page but the recipe) the game hard crashes. I tested with earthen steps, aurora wandering wizard, and arcana. As soon as you click the ritual to view how to make it, the game crashes.

**To Reproduce**
1. open codex
2. go to the ritual page
3. click on a ritual
4. click the white ritual logo to view the recipe

**Expected behavior**
a pop up of how to set up the ritual

**Version Information (please complete the following information):**
 - Mod Version: 1.7.0.1
 - Forge Version:  39.0.59

**Additional context**
I first had this happen in server with other mods, here is that log: https://pastebin.com/7tabTHWd
tested in a new instance with no other mods here is that log: https://pastebin.com/Bq6hkqh7
didn't see anything in either but still thought I would send them in case I missed it.

**Comment by Mithion** [comment]
This is fixed in dev for 1.7.0.2
