### ISSUE TITLE
Inscription table corruption

### ISSUE THREAD

**Issue by facepalmgamer** [Mithion/Mana-And-Artifice#412]
**Describe the bug**
placing the inscription table crashes the game, and servers/ It corrupts any chunk it is placed in.

**To Reproduce**
1. load in the world
2. place inscription table

**Expected behavior**
be placed down and not corrupt the world.

**Screenshots**
![2022-01-24_00 48 56](https://user-images.githubusercontent.com/30478166/150730045-9e99ec4f-690c-44c7-880a-10078753ff1e.png)
![2022-01-24_00 49 11](https://user-images.githubusercontent.com/30478166/150730062-89e5aa2c-566a-4459-a63a-4fb0b4f62e1d.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.0.1
 - Forge Version: 39.0.59

**Additional context**
Here is the crash report from my test world with only Mana and Artifice: installed https://pastebin.com/hCxN3Vje
here is the crash report from my server where I have other mods installed: https://pastebin.com/AGGNPpHU
The screenshots are from the server, I was able to boot back in but the chunk was gone. as for my single-player test world (first 
Pastebin), it won't load again.

**Comment by AshtonSnapp** [comment]
Just experienced this bug. [I put my crash report on Pastebin](https://pastebin.com/9geVY8PW), however the crash report appears to be mostly similar to the one you provided aside from the system details portion and the fact that this just happened.

**Comment by facepalmgamer** [comment]
> Just experienced this bug. [I put my crash report on Pastebin](https://pastebin.com/9geVY8PW), however the crash report appears to be mostly similar to the one you provided aside from the system details portion and the fact that this just happened.

turns out it's stable with forger version 39.0.44 (i checked all until i got this one and it worked), and if you remake the instance and move you're saving over you can save the world file. not sure of any other effects that might have so I recommend taking not of items and remaking the world and just spawning stuff in

I'm also gonna close this issue because I see someone else posted this issue before me
