### ISSUE TITLE
Advancements triggering upon picking up any item in a new world

### ISSUE THREAD

**Issue by AshtonSnapp** [Mithion/Mana-And-Artifice#413]
**Describe the bug**
When starting a new world, picking up any item causes all Mana and Artifice related advancements to trigger at once.

**To Reproduce**
1. Create a new world.
2. Break and pick up an item.

**Expected behavior**
Advancements should not trigger until the correct item is picked up - not just any old item.

**Version Information (please complete the following information):**
 - Mod Version: 1.7.0.1
 - Forge Version 39.0.59

**Comment by Mithion** [comment]
This is fixed in dev for 1.7.0.2
