### ISSUE TITLE
Inscribe table

### ISSUE THREAD

**Issue by MaterialGorll** [Mithion/Mana-And-Artifice#414]
**Describe the bug**
When I place it down it crashes my game then sends me back to the launcher then when I try to load the world again it crashes again
**To Reproduce**
1. Get item '...'
2. Use on '....'
3. Have magic level '....'

**Expected behavior**
I don't know 
**Screenshots**
<img width="1440" alt="Screen Shot 2022-01-24 at 10 26 14 PM" src="https://user-images.githubusercontent.com/98375939/150917005-c9372abf-15ee-45f2-b3e2-a9065aeb4c54.png">  

<img width="1440" alt="Screen Shot 2022-01-24 at 10 26 41 PM" src="https://user-images.githubusercontent.com/98375939/150917029-33b5390f-a4d4-42b6-bb59-e729f6e1335d.png">

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.0]
 - Forge Version [e.g. 36.1.32]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
This is fixed in dev for 1.7.0.2
