### ISSUE TITLE
Apotheosis Incompatibility

### ISSUE THREAD

**Issue by facepalmgamer** [Mithion/Mana-And-Artifice#416]
**Describe the bug**
if you have Apotheosis 5.2.0 installed (earlier versions work fine) the game crashes whenever you view the codex (searching in the creative menu, opening it when it's in your inventory, etc...)

**To Reproduce**
1. install Apotheosis v 5.2
2. search codex in creative

**Expected behavior**
not hard crash

**Version Information (please complete the following information):**
 - Mod Version: 1.7.0.2
 - Forge Version 39.0.59 & 39.0.55

**Additional context**
here is the crash report Pastebin: https://pastebin.com/gtMRNxMk
It's a rendering issue so not sure whose fault it is, but thought I would put it here since it crashes on the codex and not one of their items

google search catcher:
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41720_()" because the return value of "net.minecraft.world.item.crafting.Recipe.m_8043_()" is null

**Comment by ModernGamingWorld** [comment]
The new update also Breaks JEI/REI from loading or working at all

**Comment by addis2123** [comment]
Same interaction here. Though this is probably going to be a low priority as it's an incompatibility issue and not a core mechanic break.
Apotheosis-1.18.1-5.2.0
mna-1.7.0.2
Forge Version 39.0.59

**Comment by Mithion** [comment]
Not like I specifically try to break JEI or anything.
I run it in my dev env and experienced no issues, but I'll see what I can do.

**Comment by Mithion** [comment]
It looks like Apotheosis might be returning null from getResultItem() in one or more of its recipes - which shouldn't be happening.
No function that returns an ItemStack should ever return null by convention; it should instead return ItemStack.EMPTY.

Regardless, I've added some checks in dev that should detect if this happens and just ignore those recipes.  These changes will go out with 1.7.0.3.

**Comment by Mithion** [comment]
This was fixed in 1.7.0.3, which is out now.
