### ISSUE TITLE
Wizard Council ritual causing persistent crash

### ISSUE THREAD

**Issue by Vhnori** [Mithion/Mana-And-Artifice#418]
**Describe the bug**
During the processes of summoning the Wizard Council via the ritual and right before it finished, my game crashed. Now every time I try and log into the server, the server crashes. 

**To Reproduce**
Steps to reproduce the behavior: Not sure seeing as the server keeps crashing when I try and log in
Edit: A friend of mine was able to log into the server just fine, and I was able to join after that without the server crashing. However upon retrying the ritual, the same exact crash happened, with the inclusion of him crashing to desktop as well, and the server went into a persistent crash phase every time we tried logging in. Restoring a recent backup is the only thing allowing us to continue.

**Expected behavior**
1. Be able to log into the server without a persistent crash
2. Complete tier 3 by using a faction summon ritual

**Version Information (please complete the following information):**
 - Mod Version: 1.7.0.2
 -  Forge Version [e.g. 36.0.43]

**Additional context**
This is done on the All The Mods 7 pack

**Comment by Mithion** [comment]
This was fixed in version 1.7.0.3, which is out now.
