### ISSUE TITLE
bonefeather charm progression and tier 5 armor bug

### ISSUE THREAD

**Issue by REEEEEEEEEEEEEEEEEEEK** [Mithion/Mana-And-Artifice#419]
The ritual to summon the wizard council is causing crashes, thus getting the player stuck in tier 2 if you don't ally with the other factions

Also, the bonefeather requirement to tier up in tier 1 is acting kinda funny, i completed the task and the game wouldn't let me progress to tier 2 when i tried to sleep, so I closed and re-opened my world and the task wasn't completed for some reason

Wearing the tier 5 council armor also crashes the game.

**Comment by Mithion** [comment]
The council issue was fixed in version 1.7.0.3, which is out now.
