### ISSUE TITLE
Codex Proof-reading

### ISSUE THREAD

**Issue by BinaryEnigma01** [Mithion/Mana-And-Artifice#42]
General stuff:
- The entries seem out of order, maybe in inverse order with the exception of chapter 1:
![Index](https://user-images.githubusercontent.com/21149088/85221306-c2aab100-b3aa-11ea-8c61-a1034e015e78.png)
*Manaweave Enchanting*, for example, starts off mentioning runes which have not been made (possibly because I spawned the codex in creative)

- Whenever there's an image, the first few words appear below it, this is fine but it would look better on the other page, maybe, also the bookmark thing in the top right sometimes obscures some letters:
![Manaweaving page 2](https://user-images.githubusercontent.com/21149088/85221845-233bed00-b3af-11ea-9be5-1ddf1d12f88d.png)

Small mistakes in the codex:
-  In *Mana and Regeneration* `as long as you have sufficient hunger` - hunger is the opposite of saturation despite everyone using them interchangeably in Minecraft, this can be fixed to `as long as you aren't starving` or `as long as you are well-fed`
- In *Manaweave Enchanting*, in the last paragraph: `All that's left now, is to ..` - the comma after now should be removed
- In *Manaweaving*: 
  - There's the age-old dilemma of not breaking the fourth wall while trying to teach the player controls, `While holding the right mouse button, draw the shape in the air` clashes with the rest of the text somewhat, maybe make it a side note on using: `and begin using it (hold the right mouse button), draw the shape in the air and stop using it to finalize the process`
  - In the middle of the second page: `an incorrectly pattern will do nothing` - likely meant to be `incorrectly drawn` or simply `incorrect`
- In *Runescribing*, `Take care not to make any mistakes when chiseling your pattern, as any mistakes will require starting over..` - Two things here, "chiseling" should be "chiselling" and "mistakes" is repeated too close together, this can be fixed by writing `Take care when chiselling your pattern, as any mistakes will require starting over.. `

Hope this doesn't bore ya too much, keep up the great work

**Comment by Mithion** [comment]
Just to clarify some of the points here:

1.) Currently the codex is simply in alphabetical order - I am templating in the ability to specify an order to the entries, as I agree they could be laid out better.  Creative/Survival has no impact on the layout of the codex.

2.) The text wrapping is the default, adding some padding/spacing would solve the issue.

3.) I fixed the codex wording based on your suggestions.  Thanks!

**Comment by Mithion** [comment]
As of 1.0.6-pre1 the codex ordering has been significantly improved.
