### ISSUE TITLE
Book of Alteration doesn't work and gives error

### ISSUE THREAD

**Issue by Hotaru251** [Mithion/Mana-And-Artifice#420]
Book Of Alteration doesn't work (and thus can't do ritual either)
Says to hold book & press Z and select modifier yet gives error when you do.

"error setting modifier couldnt, verify held item"

**To Reproduce**
open book of alteration's radial and select damage, speed, delay, range and it'll show the error

**Screenshots**
https://i.imgur.com/JfLoPy1.png

**Version Information (please complete the following information):**
 - Mod Version - mna-1.7.0.1.jar
 - Forge Version - 39.0.43

**Additional context**
Running the ATM7 modpack.

**Comment by xotwod333** [comment]
Same for me. Really like to have an answer to this
