### ISSUE TITLE
Crash with Ritual of Wizard Council

### ISSUE THREAD

**Issue by LuigiTP** [Mithion/Mana-And-Artifice#421]
**Describe the bug**
on a Multiplayer server the ritual to align with council crashed everyone around and the server
after a restart we were able to log back in without any trouble

**To Reproduce**
1. Perform the ritual
2.crash
**Expected behavior**
Cool animations and tier up

**Version Information (please complete the following information):**
 - Mod Version: [mna-1.7.0.2.]
 - Forge Version [39.0.59]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

Never used it but i thiink i got it
My crash report
https://pastebin.com/7pZ2PXaM

Player doing the ritual crash report
https://pastebin.com/1sFYha6v

**Comment by Mithion** [comment]
This was fixed in version 1.7.0.3,which is out now.
