### ISSUE TITLE
Game Crash when trying to look at Codex Ritual recipes (1.18.1, all the mods 7).

### ISSUE THREAD

**Issue by NemesisArtarian** [Mithion/Mana-And-Artifice#422]
When clicking on the recipe for any ritual in the codex, game crashes.

**To Reproduce**
1. Open ritual page
2. Click on Ritual
3. Crash.

**Expected behavior**
Recipe appears

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.0.1.jar
 - Forge Version: 39.0.43

**Comment by Mithion** [comment]
This was fixed in version 1.7.0.3 (compatibility issue with Apotheosis), which is out now.
