### ISSUE TITLE
[1.5.1.5] Wizard Chalk not enchantable?

### ISSUE THREAD

**Issue by Elfinlocks** [Mithion/Mana-And-Artifice#423]
**Describe the bug**
Wizard chalk says it may be enchanted with Unbreaking in JEI, and I have confirmed this by enchanting it with commands in a test world, but the enchantment cannot be applied via an Anvil through using an enchanted book.

**To Reproduce**
1. Get wizard chalk and any unbreaking book
2. Use in anvil
3. See error - occurs in creative mode as well as survival

**Expected behavior**
Wizard chalk should allow the enchantment or the entry removed from JEI.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/Elfinlocks/Astral_Engineering/issues/25)

**Version Information (please complete the following information):**
 - Mod Version: [1.5.1.5]
 - Forge Version [e.g. 36.2.22]

**Additional context**
N/A

**Comment by Vhnori** [comment]
Have you tried using the Runic Anvil that comes with this mod? Thats how Ive been enchanting all of my Mana and Artifice gear

**Comment by Danekjovax** [comment]
Is there's a tier requirement?  I'm currently tier 4.

**Comment by Danekjovax** [comment]
Ok, I see that Books aren't used on M&A tools... runescribing it is.

**Comment by Danekjovax** [comment]
IT worked with runescribing, but man is it so much more work and expensive than the vanilla alternative, just to make chalk last a little longer. ;2P ;2
![2022-01-29_17 48 39](https://user-images.githubusercontent.com/10191173/151680208-774690ff-606b-46af-ba4c-d000b0a04db3.png)
)

**Comment by Danekjovax** [comment]
I'll add that using the same level enchantment of a book works.  IT's coded to the tier you're at.  Tier 4 allows level 2 enchantments for the post part.
![2022-01-29_18 21 23](https://user-images.githubusercontent.com/10191173/151680844-b1c60f3d-a1d2-445f-b624-9f10f0f880ee.png)
![image](https://user-images.githubusercontent.com/10191173/151680840-9f7d90fd-7caf-49a9-a95f-84a6a273614e.png)
