### ISSUE TITLE
1.16.5: Witch Hunters can crash the game with some versions of GeckoLib

### ISSUE THREAD

**Issue by autumn-birds** [Mithion/Mana-And-Artifice#424]
**Describe the bug**
Encountering a Witch Hunter in Survival mode seems to repeatably crash the game, specifically with a rendering error of some sort.  It may also happen in Creative, but hasn't for me in my (admittedly brief) testing.

I initially thought this was a compatibility issue with Fairy Lights, but then I checked and it also happens with only M&A (the version Curseforge installs when using their client.)

**To Reproduce**
1. Create a blank Curseforge 1.16.5 Forge instance (or, presumably, otherwise create an installation of Forge with no mods in)
2. Install M&A (and dependencies, GeckoLib and Curious API. CF did this for me)
3. Launch the game
4. Create a new creative world, and use the Witch Hunter spawn egg to place a Witch Hunter into the world.
5. Switch into Survival mode, and attack the Witch Hunter if nothing immediately happens.

**Expected behavior**
IDK, but not a crash. The disposition of Witch Hunters towards players who deal damage to them is presumably not great, but I don't *think* it's supposed to cause reality to abruptly stop working. ;P

**Screenshots**
[dunno that this would help any]

**Version Information (please complete the following information):**
 - Mod Version: `mana-and-artifice-1.5.1.5.jar`; `curios-forge-1.16.5-4.0.5.3.jar`; `geckolib-forge-1.16.5-3.0.65.jar`
 - Forge Version: 36.2.20 (according to the Curse launcher)

**Additional context**
Crash log/report with only M&A installed: https://pastebin.com/jAzRGPad

**Comment by autumn-birds** [comment]
(Also, for context, I initially encountered this upon attempting to load into a completely new world, though I had many other mods installed in that case.)

**Comment by autumn-birds** [comment]
It seems like the game crashes right after the Witch Hunter tries to throw a potion at me. (I also get this result from attacking it in Creative and then switching to Survival.)

**Comment by MrQueeba** [comment]
I am also having this issue with the same versions listed above. My singleplayer world is creative and as soon as the chunk with the Witch Hunter loads in the game will crash.
Crash log: [https://pastebin.com/uy5jkLKB](url)

**Comment by autumn-birds** [comment]
Ooh. Can confirm: downgrading to geckolib 3.0.64 fixes this on my end.

(Also, is it just me, or is GeckoLib versioning a bit strange? I saw a .67 and a .66 when going to download it, apparently uploaded out of order... or something...)

Should we open a new issue with GeckoLib, assuming they have a repository to open issues on?

**Comment by Skathes** [comment]
getting the same error with Skeleton Assassins when they throw their Bolos, downgradeing Geckolib to 3.0.64 does not fix

**Comment by Ecifeal** [comment]
Hey there! I am having the same problem!
But instead of 1.16.5 , I am playing on the latest version of Minecraft [1.18.1] and the most recent version of geckolid [geckolib-1.18-forge-3.0.11]

IDK if it helps, but I'm using the latest AMD CPU with integrated graphics.
I can easily run the latest games, but yeah - an ''integrated gpu'' means that I don't have a ''real'' standalone GPU. 
Idk if this could cause the problem?

**Comment by SirOMGitsYOU** [comment]
> getting the same error with Skeleton Assassins when they throw their Bolos, downgradeing Geckolib to 3.0.64 does not fix
> 
> Seems its the EntitySkeletonAssassinBloloRenderer itself causeing it. but is same no such method error

Can also re-affirm downgrading to 3.0.64 does not resolve this encountered this crash today
[crash-2022-02-02_11.14.11-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/7988744/crash-2022-02-02_11.14.11-client.txt)
.

**Comment by AzureDoom** [comment]
This is due how Mana and Artifice uses Custom Keyframes for the Witch Hunter that worked around a bug that was patched in the newest version of Geckolib. I've already let the dev know and they will be patching this for the proper method. 1.18.1 was fixed for this already.

**Comment by Mithion** [comment]
This has been fixed in 1.16.5 with M&A's update 1.5.1.6
