### ISSUE TITLE
Shader bug with guide book

### ISSUE THREAD

**Issue by Lendoker** [Mithion/Mana-And-Artifice#426]
After I open guide book with any shader is on everything become black or just dissapears (Items in inventory, letters and everything in UI)

1. Get item Guide Book (The blue 3d book)
2. Open it while using any shader (Tested on MakeUp UltraFast, Nostalgia, BSL, sildrus vibrant shaders, and SEUS)
3. See everything becomes black or dissapears

**Screenshots**
![2022-01-30_18 33 16](https://user-images.githubusercontent.com/70807737/151708288-161997f3-03ad-411e-82d2-f8da2842e2df.png)
![2022-01-30_18 33 18](https://user-images.githubusercontent.com/70807737/151708852-1d7d6537-db8c-480e-8ad6-faf90d64c5f1.png)
![2022-01-30_18 45 16](https://user-images.githubusercontent.com/70807737/151708745-04442fa3-31bb-4ef6-ada0-47a37fbd09b1.png)
![2022-01-30_18 45 20](https://user-images.githubusercontent.com/70807737/151708746-c5081ae0-284d-4d80-b875-b2d18dc0c3d1.png)
4b6.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.5

**Comment by Lendoker** [comment]
Found a way to fix this, just disable gui in settings and everything will work ok (Mana in the left-top corner have to be hidden to bug don't reproduce)

**Comment by Mithion** [comment]
Shaders in 1.16 are not supported.
