### ISSUE TITLE
Client crashes when attempting to see rituals

### ISSUE THREAD

**Issue by clayper** [Mithion/Mana-And-Artifice#427]
When I open the codex of arcana and attempt to look at any of the chalk patterns, the client crashes. This occurs for both me and the other person on my server. I'm playing ATM7 running mna-1.7.0.1

**Comment by clayper** [comment]
Updated to mna-1.7.0.3 and it works fine now

**Comment by Mithion** [comment]
Correct, This was fixed in 1.7.0.3
