### ISSUE TITLE
Entity Skeleton Assassin Bolo make client crash

### ISSUE THREAD

**Issue by Gogo08190** [Mithion/Mana-And-Artifice#428]
**Describe the bug**
Entity Skeleton Assassin Bolo make client crash and there is no way to return to the map afterwards.

**To Reproduce**
1. Get item '...'
2. Use on '....'
3. Have magic level '....'

**Expected behavior**
When a Skeleton Assassin fights against another faction, the Skeleton Assassin Bolo entity crashes the client and there is no way to return to the map afterwards.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [1.5.1.5]
 - Forge Version [36.2.22]

**Additional context**
https://crashy.net/4dWftWaUt4pa0BJWli3o

**Comment by Mithion** [comment]
This was fixed in 1.5.1.6
