### ISSUE TITLE
Sanctums not working and registering for occulos (1.18.1)

### ISSUE THREAD

**Issue by LuigiTP** [Mithion/Mana-And-Artifice#429]
I have seen multiple variants of this bug for specific factions but in the server im in we tried all factions and so: the sanctum does not register for occulus progression it also appears to not give any buff (however the ritual does register)

1. Build your faction Sanctum at tier 3
2. Use occulus
3. see no change
4. even after completing the minimum amount of requirements if the sanctum is included in those it will not let you tier up (so its not a visual bug where the text remains red when it should be green)

**Expected behavior**
Occulus should show sanctum progression completed and sanctum itself should provide a buff when nearby

**Screenshots**
![image](https://user-images.githubusercontent.com/46649309/152558091-bcc7d0c3-5485-44be-b050-58f2871f38ab.png)
![image](https://user-images.githubusercontent.com/46649309/152558174-5e92201b-9a64-4c85-bd5a-2222bec2e5fe.png)
The only ritual i performed was arcana to make the spell and the sanctum 

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.0.3
 - Forge Version 39.0.64

**Comment by pabesuarez** [comment]
lol, 6 hours ago
just got the same issue and was looking to see if i was doing something wrong
built the fae sanctum and got no buffs nor occulus completion

**Comment by Mithion** [comment]
This issue was fixed with the release of the Artifice Update, but I forgot to close it.  Sorry!
