### ISSUE TITLE
1.16.5 runeforge and inscription table can't be harvested. 

### ISSUE THREAD

**Issue by BeerHuntor** [Mithion/Mana-And-Artifice#430]
**Describe the bug**
When trying to harvest the inscription table or runeforge using and axe or pickaxe, it disappears and breaks, instead of having the item be returned.  Playing AllTheMods6 modpack. 

**To Reproduce**
1. Place Item
2. Mine Item
3. Loss

**Expected behavior**
To return the item mined. 

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.5
 - Forge Version: 36.2.22

**Comment by Mithion** [comment]
A workaround for now is to use a break spell; as that will work properly.

**Comment by incfool** [comment]
Just FYI this also applies to wellspring refraction lenses. (1.16.5)

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).
