### ISSUE TITLE
About shader rendering errors

### ISSUE THREAD

**Issue by 615303619** [Mithion/Mana-And-Artifice#431]
**Describe the bug**
Errors when working with shaders

**To Reproduce**
1. Install OptiFine
2. Load any of the shaders
3. You will see many items incorrectly rendered in a black and purple grid

**Expected behavior**
Hopefully this will be fixed so that I can play the mod with shaders on.

**Screenshots**
![image](https://user-images.githubusercontent.com/71170887/152679766-dc665c14-c80d-4303-a3e1-143119599ac0.png)
![image](https://user-images.githubusercontent.com/71170887/152679803-9598d85f-f65d-42a3-823f-27b1ea2a49e4.png)

**Version Information (please complete the following information):**
 - Mod version: 1.5.1.5
 - Forge version 36.2.23

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.
Minecraft version: 1.16.5
Use OptiFine_1.16.5_HD_U_G8
Also, my sincerest greetings:)

**Comment by Mithion** [comment]
Optifine is not supported.
