### ISSUE TITLE
Crash when I join the world (1.16.5)

### ISSUE THREAD

**Issue by DoctorSigma** [Mithion/Mana-And-Artifice#434]
**Describe the bug**
Crash when I join the world

**To Reproduce**
1. Join to world
2. See eror

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.6
 - Forge Version 36.2.21

**Additional context**
https://pastebin.com/Hj4Cp9fE  - Crash report

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).
