### ISSUE TITLE
Classic raids not working

### ISSUE THREAD

**Issue by LiSirNo** [Mithion/Mana-And-Artifice#435]
I played for quite some time with classic raids enabled and regardless of having max tier mage I never get raided. To confirm issue I setup raidTierIncrease and raidBaselineIncrease to 0.90. After couple of days still no raid occurred. When testing I was for the most part on plains so there was plenty of place for raid to spawn

 - Mod Version: mana-and-artifice-1.5.1.5
 - Forge Version: 36.2.20

**Comment by Mithion** [comment]
Will check into it for next patch, sorry!

**Comment by Mithion** [comment]
Closing as 1.16.5 is no longer supported.
