### ISSUE TITLE
Dimension Blacklist doesn't do anything

### ISSUE THREAD

**Issue by Aeases** [Mithion/Mana-And-Artifice#436]
**Describe the bug**
Dimension Blacklist doesn't block spells in specific dimensions

**To Reproduce**
1. Open mna.spells.toml, I used vscode
2. Press Ctrl+Shift+L and select every value for "dimensionBlacklist = ""
3. Retype it so that it reads dimensionBlacklist = "dimensionmod:dimension,dimensionmod:dimension2" for example
4. Load up your game and travel to the specified dimension, spells can still be used

**Expected behavior**
If you blacklist a dimension spells shouldn't be able to be cast there
**Screenshots**
![image](https://user-images.githubusercontent.com/96164686/152834866-a2c4408d-0a62-41c3-b12e-9adc556b0fd8.png)

**Version Information (please complete the following information):**
 - Mod Version: [1.7.0.3]
 - Forge Version [39.0.64]
 - MC Version [1.18.1]

**Additional context**
ModList
(https://0bin.net/paste/cTKwhMZX#u3kKR9BVrn8v6iEvW-DrfaWILvz2xmrNwERvGBszAgt)

**Comment by Mithion** [comment]
Fixed in 1.7.0.4 - however I should point out that in mna.general.toml there is a global spellDimensionBlacklist option, so you don't need to change it for every component :)

Sorry for the inconvenience!
