### ISSUE TITLE
MC 1.16.15 M&A 1.5.1.6 Update to fix crash with Witchhunter did not work

### ISSUE THREAD

**Issue by SangurianSoul** [Mithion/Mana-And-Artifice#437]
**Describe the bug**
Game crashes on spawn of Witchhunter, with latest 1.16.5 version

**To Reproduce**
1. Log on to server
2. Wait for Witchunter to spawn
3. Crash

**Expected behavior**
To not crash?
**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.6
 - Forge Version 36.2.23

**Additional context**
We did not have this problem with the previous version. Only updated for bugfixes, and now there are problems.

[crash-2022-02-07_21.55.22-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/8024087/crash-2022-02-07_21.55.22-client.txt)

**Comment by Mithion** [comment]
Did you update Geckolib to its latest as well?  The older Geckolib won't work with the fix and will cause the crash.

**Comment by SangurianSoul** [comment]
Ahha, no we did not. Did not realize that updated a little while back. everything seems to work just fine now

**Comment by SangurianSoul** [comment]
With the updated Geckolib, everything seems to be working.

Sorry for the late reply

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mithion** [comment]
All good 👍
