### ISSUE TITLE
crash when looking at rituals

### ISSUE THREAD

**Issue by LuxDeos** [Mithion/Mana-And-Artifice#438]
when i use the codex arcana and try to look at how to do a ritual via the side tabs it crashes my game, i can look at recipes and the rune tablet inscriptions just not rituals. I've tried upping ram allocation and lowering graphics just incase its cause the game couldnt handle it though that didnt work

**Comment by Mithion** [comment]
Make sure you are running the latest version.  This was fixed recently.
Latest 1.18.1 is 1.7.0.3 (soon to be 1.7.0.4), and latest 1.16.5 is version 1.5.1.6.
