### ISSUE TITLE
Eldrin altar doesn’t work for making Greater Motes

### ISSUE THREAD

**Issue by BrokN1Z** [Mithion/Mana-And-Artifice#439]
**Describe the bug**
When trying to make a Greater Mote using the Eldrin Altar it does not work when right clicking the Altar.

**To Reproduce**
1. Set up the Eldrin Altar complete with Conduit.
2. Set it to make a Greater Mote.
3. Right click with a empty hand on the Altar to start recipe.
4. Right click picks up item instead of starting the recipe.

**Expected behavior**
When the Altar is clicked with a empty right hand the recipe for the Greater Motes should start.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [1.5.1.6]
 - Forge Version [e.g. 36.2.20]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Did you follow the structure for the altar?  In the multiblock page in the codex (where it lists the materials) there's an eye button - click it to show the required multiblock.

**Comment by pixel547** [comment]
> Вы следовали структуре алтаря? На странице с несколькими блоками в кодексе (где перечислены материалы) есть кнопка глаза - нажмите на нее, чтобы показать необходимый мультиблок.

Yes, I also click and nothing, although I built everything correctly according to the book, but still nothing happens, what to do?

**Comment by alphaNumeric01** [comment]
I can confirm. Followed the structure preview in the codex and got it ok’d before attempting to craft the greater motes. I also experimented with various conduit locations and referred to MischiefOfMice’s tutorial and modpack play through to make sure I was following all the steps correctly. Placing the lesser mote in the center or placing the mote on the outside pedestals and right clicking the center with an empty hand did not start the craft.

**Comment by Gogo08190** [comment]
Same problem : https://www.toptal.com/developers/hastebin/uzakeyuqov.properties

**Comment by Mithion** [comment]
Resolved with the release of M&A 1.5.1.7 for Minecraft 1.16.5 and with M&A 1.7.0.5 for Minecraft 1.18.1.
Sorry folks.
