### ISSUE TITLE
1.18.1 - Tinkers Golden Travelers Armor issue

### ISSUE THREAD

**Issue by Benjamboo** [Mithion/Mana-And-Artifice#441]
**Describe the bug**
Interaction with Tinkers Construct Travellers Gear with the "Golden" trait.
This trait is supposed to make Piglins passive and not hostile, but when Mana and Artifice is installed this doesn't seem to work.
After over an hour of testing my modpack this only seems to happen when Mana and Artifice is installed. (Not GeckoLib).

**To Reproduce**
Have Travelers gear and add golden trait to it via the Tinkers construct anvil (using 3 gold ingots).
Go to the Nether and be attacked by Piglins.

**Expected behavior**
Piglins should be passive, as if wearing golden armor.

**Screenshots**
Screenshot of hostile Piglin with Mana and Artifice Installed  
![2022-02-16_12 44 06](https://user-images.githubusercontent.com/68694038/154191862-b7aa87c0-b1fd-4165-b9ce-92987cfc4428.png)

Screenshot with M&A Disabled.
![2022-02-16_14 44 41](https://user-images.githubusercontent.com/68694038/154192360-da91165c-8b7c-40be-b8d8-faa9e4c4c9b5.png)

**Version Information **
 - Forge - 39.0.79
 - Mana And Artifice - 1.7.0.4
 - Tinkers Construct - 3.4.1.46
 - Geckolib - 3.0.11
 - CuriosAPI - 5.0.6.1
 - Mantle - 1.8.31

**Comment by Benjamboo** [comment]
Ticket in the Tinkers Construct github.
https://github.com/SlimeKnights/TinkersConstruct/issues/4756

**Comment by Mithion** [comment]
I think this is an M&A issue, there are other issues with gold armor and piglins as well as a result of M&A interaction.  I'll need to fix this.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
