### ISSUE TITLE
Wandering Wizard invisible when summoned during rain or night

### ISSUE THREAD

**Issue by benediktwerner** [Mithion/Mana-And-Artifice#450]
When summoning a Wandering Wizard, it sometimes turns invisible after a second. From some testing, it seems to happen when it's night or raining. At first, I thought he was just going away really quickly since there also was an accompanying sound when it happened and it's also right at the time when the portal vanishes but using Eldrin Sight Unguent I can actually see him and I can also still interact with him just fine. He also doesn't become visible again when setting the time back to day.

I'm almost wondering if this is some intended feature like he's hiding in the night? But if it is, it really should be hinted at in the book on the page about the Wandering Wizard ritual since it's very confusing and feels like a bug.

**Version Information:**
 - Mod Version: 1.5.1.7
 - Forge Version: 36.2.20

**Additional context**
Happens in single- and multiplayer. Not sure if that's relevant but I'm running a custom modpack with a few other mods. Details: https://pastebin.com/rj2P1cVg

**Comment by Mithion** [comment]
That's intentional, he casts invisibility on himself in order to protect himself.  Similar to how wandering traders drink invisibility potions.

**Comment by benediktwerner** [comment]
Hm, I guess that makes some sense. But it really is quite confusing, especially with him appearing for a very short time and then instantly disappearing again without any obvious casting effect and also around the same time the portal closes. It confused both me and my brother for quite a while until I randomly figured out he's invisible. I think at least a note about this behavior in the book would help a lot.
