### ISSUE TITLE
Wellspring energy can't be shared between players

### ISSUE THREAD

**Issue by benediktwerner** [Mithion/Mana-And-Artifice#451]
I'm playing this mod together with my brother and it's pretty inconvenient that we can't share wellspring energy. For most other things, we can always use the stuff that the other one built but in this case, the energy is tied to the player so only the person that built the wellspring capture thingy actually gets it.

It seems that there's a config to make it shared between the faction but we're playing different factions so this doesn't really help us.

Ofc, we could each find enough wellsprings for all the stuff we need but that feels pretty tedious and against the point of playing cooperatively. There already is a fair amount of stuff that we have to do twice but for the most part that's expected and makes sense (and actually not having to do 100% of the tasks to advance the tier and having different factions helps a lot in reducing the overlap and also exploring more of the different stuff in the mod). But finding a dozen or so wellsprings twice is kinda too much.

For now, we've just had one person take all the wellsprings and do all the crafting and for the faction armor we just set the values for the other person via the command (btw, thanks a lot for the great commands to test stuff) but it would be much nicer if we could, for example, share the wellsprings if we're in the same scoreboard team. Maybe as a config option.

Still, just wanted to add: This mod is awesome! Definitely, the one we played with and used the most out of the pack.

**Comment by Mithion** [comment]
Yeah tbh I hadn't really considered that.

There are some better ways to mitigate this in the update, but I don't think it's quite there yet.  It'll still need more work before I'll consider it good enough to close this.

**Comment by LTHCTheMaster** [comment]
> scoreboard team.

@benediktwerner did youn consider vanilla teams or ftbteams ?

I've the same problem of wellspring energy on a server with a friend, and on another server by the past with another friend.
- On current server we finally crafted a lot of motes and used the table that allow you to burn coal to have enough of each wellspring, on this server we are using <b>ftbteams</b>
- On the other server, before we know the block that was mentioned above, we used commands, on this server it was the <b>vanilla teams system</b>

**Comment by Mithion** [comment]
The new wellspring rework resolves this issue.
