### ISSUE TITLE
Client crashes when interacting with Wandering Wizard on a server

### ISSUE THREAD

**Issue by benediktwerner** [Mithion/Mana-And-Artifice#455]
When interacting with a Wandering Wizard while playing on a server, the whole Minecraft client very frequently crashes. Out of maybe 15 attempts over multiple days and from two different people, it only didn't crash 3 times. All the other times, it immediately crashed after right-clicking on the Wizard the first time to open the trade GUI. Also, even when it worked, it still crashed after closing the GUI and trying again.

I've been using this mod exclusively on a server but doing some testing in a single-player world, it seems to work fine there.

Worth noting though that nothing happens to the server. It doesn't even log anything. Only the client crashes.

**Version Information:**
- Mod Version: 1.5.1.7
- Forge Version: 36.2.20

**Additional context**
I'm using a custom mod pack with a few more mods, see also the crash report: https://pastebin.com/uCpXC4cX

Also, I've found this in the logs right before the crash a few times:
```
[main/WARN]: GUI did not draw the dark background layer behind itself, this may result in display issues: com.ma.gui.entity.GuiWanderingWizard
```

I believe this was always at the times when it didn't crash immediately though. Right before I closed the GUI and tried again.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).
