### ISSUE TITLE
Can't rote Nethergate component

### ISSUE THREAD

**Issue by Andargus** [Mithion/Mana-And-Artifice#456]
**Describe the bug**
Can't rote nethergate spell in oculus.   I've tried making nethergate a self, projectile, and touch with none of them working.  I have casted the touch and projectile spells freely hitting no entity's, while hitting passive mobs, and while hitting aggressive mobs.  None have worked to even start roting nethergate.  *edit:  So I just found out other people on the server I am playing on can rote those spells, while I still can't.  The server just updated to the most recent version, however I still can't seems to rote any of them.  Not sure if it's only server side or a rare one off glitch.

**To Reproduce**
1. Get item 'nether gate spell (any type)'
2. Use on 'self/world/friendly mob/ and hostile mob'
3. Have magic level '75'

**Expected behavior**
Being able to rote nether gate like all other spells

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.6]
 - Forge Version [e.g. 36.2.26]

**Comment by Mithion** [comment]
So I'm having a hard time replicating this issue - it's roting fine for me in singleplayer, multiplayer, cross faction, everything.
The spell system had some low level changes as part of the Artifice Update and I'm hoping that resolved it.

The changes will go out with the next release (1.18.1).
