### ISSUE TITLE
Pairing with Optifine guts guis [1.0.4 pre2] [Optifine ver HD_U_G1 pre30]

### ISSUE THREAD

**Issue by Brickmastercat** [Mithion/Mana-And-Artifice#46]
When Mana & Artifice and Optifine are both installed, all items in inventories, the player model in the inventory, and all text in all menus are invisible. Outside of guis, everything is either invisible, or pitch black, depending on the object. (Though I can't tell what is what because it's all invisible and/or pitch black) 
(This is without any other mods installed, forge ver 31.2.27)
![2020-06-28_22 02 05](https://user-images.githubusercontent.com/14264854/85974838-5ff97c80-b98b-11ea-9b68-a96de2b111fa.png)
![2020-06-28_22 05 01](https://user-images.githubusercontent.com/14264854/85974861-6f78c580-b98b-11ea-9dbc-cbbd83951589.png)

**Comment by Mithion** [comment]
Prealpha is not concerned with inter-mod compatibility.

**Comment by Brickmastercat** [comment]
I figured as much, but thought it might be worth noting for when you do get to that stage
