### ISSUE TITLE
Tier 4 manaweaving on tier 2 spell.

### ISSUE THREAD

**Issue by Lendoker** [Mithion/Mana-And-Artifice#463]
**Describe the bug**
I tried to make Bind Wounds spell, but when I was doing it, appeared tier 4 pattern

**To Reproduce**
1. Make spell Bind Wounds/Touch
2. Try arcana ritual with it
3. The third pattern will be tier 4 pattern

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.7

**Comment by Mithion** [comment]
Duplicate of #444 , but thank you for letting me know!  I'm going to track it there.
