### ISSUE TITLE
[1.18.1] Log Spam "Error executing lodestar sub task, trying to recover." 

### ISSUE THREAD

**Issue by aerialspring** [Mithion/Mana-And-Artifice#464]
**Describe the bug**
Getting the following log spam in the server console:
`[02:07:48] [Server thread/ERROR]: java.lang.ClassCastException: class me.thonk.croptopia.items.CropItem cannot be cast to class net.minecraft.world.item.BlockItem (me.thonk.croptopia.items.CropItem is in module croptopia@1.8.1 of loader 'TRANSFORMER' @4df7d9ee; net.minecraft.world.item.BlockItem is in module minecraft@1.18.1 of loader 'TRANSFORMER' @4df7d9ee)
[02:07:48] [Server thread/ERROR]: Error executing lodestar sub task, trying to recover.`

We have two active lodestars on the server, in chunkloaded areas. One of them had run out of seeds and was just sitting there doing nothing. The other was actively planting/harvesting croptopia plants. When giving that lodestar a redstone signal to turn it off, log spam stopped.

I didn't see any errors in the tasking in the lodestar and the construct wasn't giving any error messages, so I'm not sure what was causing it at all. Here's what he has in the lodestar:

> Harvest (with two markers covering planting area) > Grab item from container (no item indicated) > Plant crops (markers covering same space) > Wait 5 seconds

I thought maybe it was because he didn't have a seed identified in the 'grab' step, so I put one in there, and restarted Lodestar, but the same messages came up in the console. 

The other lodestar appears to be working just fine, doing the same functions, except for the wait, but with Ars Nouveau's manabloom seeds. Removing the wait step did not resolve the issue. Thinking it may be an interaction with Croptopia?

There doesn't appear to be any affect on server or game performance, and the construct is functioning as expected. 

**To Reproduce**
1. Set up construct
2. Setup lodestar with Harvest > Grab (croptopia seed) > Plant
3. Watch console - see error.

**Expected behavior**
I wouldn't expect to see the messages repeating over and over in the console.

**Screenshots**
https://ibb.co/72gSZZJ

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.0] mna-1.7.0.5
 - Forge Version [e.g. 36.1.32] 39.1.0
 - Croptopia 1.18-FORGE-1.8.1
 - MC 1.18.1

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.
![2022-03-09 22_09_04-Akliz Command Center - Console](https://user-images.githubusercontent.com/10717721/157581578-b686b7da-4aed-43c0-989a-492c7215fd35.png)

**Comment by HammerDave** [comment]
More info on what leads to this behavior:
The get item from chest task has an empty filter.
The chest has an item in the 1st slot that isn't a seed.
The construct tries to plant the non-seed item.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1) - thanks!
