### ISSUE TITLE
Cannot convert resonating dust into Ender Pearl (bad recipe?)

### ISSUE THREAD

**Issue by clubpetey** [Mithion/Mana-And-Artifice#465]
**Describe the bug**
Trying to convert resonating dust into ender pearls, JEI shows a "Crushing" recipe for the grindstone and construct table but neither work.  You cannot place the dust in the grindstone or the construct table.  I think these recipes might be reversed, as it would make more sense to crush an ender pearl into dust.  But then is there a way to go back from dust to pearl?

**To Reproduce**
1. Take some resonating dust
2. Attempt to place in Grindstone
3. you cannot

**Expected behavior**
Either the dust should go in the grindstone and produce a pearl or the recipe should be removed.  If the latter, a recipe for converting dust to pearls should be added, if this is an intended feature.

**Screenshots**
n/a

**Version Information (please complete the following information):**
 - Mod Version: 1.7.0.5
 - Forge Version 39.1.0

**Additional context**
n/a

**Comment by Mithion** [comment]
hey there- this is an art issue, it's actually a construct "crush" task recipe.  We're working to fix it for the next update, but you have to assign a crush task to a construct using a Lodestar.  The construct must be holding the dust (from a "Take Item" command), and it will use the grindstone to crush the dust into a pearl.

Sorry for the confusion!

**Comment by clubpetey** [comment]
Ah, that makes sense.  I will await the update then.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1) - thanks!  Much clearer texture now:

![crushing](https://user-images.githubusercontent.com/2482373/166696469-e1d15d96-b494-41e5-9968-375b7aaf5c6c.png)
!
