### ISSUE TITLE
Sigil Shape crashes the game.

### ISSUE THREAD

**Issue by manaphoenix** [Mithion/Mana-And-Artifice#466]
**Describe the bug**
When using the sigil shape, attempting to activate the sigil in any method will crash the game.

**To Reproduce**
1. Create a spell using the sigil shape, components/upgrades don't matter.
2. Place the sigil.
3. activate the sigil by any means
4. crash.

**Expected behavior**
see "Describe the bug"

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.0.5
 - Forge Version 39.1.2

**Additional context**
I have two, one is from me placing it, and punching it. the other is spawning a zombie and having it walk across it.
https://pastebin.com/Z89ZwZTU
https://pastebin.com/5GQVx2DC

if anything else needed lmk :D

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1) - thanks!
