### ISSUE TITLE
Cannot create Self - Eldrin Flight spell

### ISSUE THREAD

**Issue by clubpetey** [Mithion/Mana-And-Artifice#467]
**Describe the bug**
I have a recipe for Self - Eldrin Flight.  I set the ritual of Arcana to turn it into a spell, and while the runes go purple and the needed reagents show up, clicking on the center a second time does not start the ritual.  Instead the floating "hints" go away, there are "sparkles" around the whole area, but nothing happens

**To Reproduce**
1. Create Spell Recipe Self + Eldrin Flight at Inscription table
2. setup runes for Ritual of Arcana
3. right-click center square with purified dust
4. place down spell recipe and required items
5. right click center block of ritual again
6.  Nothing happens!

**Expected behavior**
Ritual should begin, and ask me to draw the necessary manaweave symbols

**Screenshots**
screenshots below

**Version Information (please complete the following information):**
 - Mod Version: 1.7.0.5
 - Forge Version 39.1.0

**Additional context**
I have not tried other spells.  I will setup a different spell and see if the same problem occurs.  But I have sucessfully made spells in the past.  Both in survival and in creative

![2022-03-17_17 20 31](https://user-images.githubusercontent.com/2221486/158915405-bf4fc4ca-d4ea-4768-aa96-7831f53c7f2f.png)
![2022-03-17_17 20 48](https://user-images.githubusercontent.com/2221486/158915407-d535da8b-c697-46d8-af3e-d408bb82c713.png)
![2022-03-17_17 21 02](https://user-images.githubusercontent.com/2221486/158915409-1f1aea78-7d24-45ec-b641-3d8930492760.png)
![2022-03-17_17 21 41](https://user-images.githubusercontent.com/2221486/158915410-3c0559a3-6590-4a40-8074-4dc2ec7df89c.png)
![2022-03-17_17 21 46](https://user-images.githubusercontent.com/2221486/158915403-4dc99bed-2e4f-456e-8ad3-5788c04ceb8a.png)

**Comment by clubpetey** [comment]
Update: I just successfully completed the ritual of Arcana to make the spell "Self - Slowfall".  So this issues seems connected to Eldrin Flight,  I am currently Tier 4 and aligned with the Council.

**Comment by Mithion** [comment]
In your last screenshot, you are still missing a string (far right)
