### ISSUE TITLE
Rituals eating components

### ISSUE THREAD

**Issue by flame-controller** [Mithion/Mana-And-Artifice#47]
When I use a ritual kit in creative and place the required components in the desired places nothing happens, and when I go into survival and do the same things, it consumes the component but nothing happens. this may go further than this, but this is what happened to me

**Comment by Mithion** [comment]
Which ritual is stored in the kit when this happens?

**Comment by flame-controller** [comment]
Ritual of arcana

**Comment by flame-controller** [comment]
this also fixed when I didn't use the kit

**Comment by Mithion** [comment]
Ritual of Arcana was never intended to be kitted - functionality has been added in 1.0.5-pre1 to allow rituals to be flagged as un-kittable.
