### ISSUE TITLE
Ender Disc doesn't teleport from other dimensions

### ISSUE THREAD

**Issue by akira439** [Mithion/Mana-And-Artifice#471]
**Describe the bug**
Ender disc doesn't teleport from other dimensions (only within the overworld)

**To Reproduce**
1. Take the disc and set a combination of glyphs
2. Going from overworld to any other dimension
3. Choosing a destination in the disk
4. An animation of Ender's particles is played, and nothing happens

**Expected behavior**
In theory, I should have teleported to the destination with the correct combination of glyphs, as does the return ritual itself (and through dimensions), but again this doesn't happen

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.29 (1.16.5)

**Comment by Mithion** [comment]
Intentional.

**Comment by Mithion** [comment]
I should add - use rituals of return/gate to go cross dimensional

**Comment by TheAgentFlash** [comment]
So I'm guessing there's no plans to allow the disc to go across dimensions if for example, you had an appropriate world charm in your offhand?
