### ISSUE TITLE
Spelling Errors in Codex Arcana

### ISSUE THREAD

**Issue by HenryMaxler** [Mithion/Mana-And-Artifice#472]
**Describe the bug**
I was reading the Codex Arcana and noticed a few spelling mistakes
In Flowers... Wakebloom it says "They carry a surprising amoung of water" instead of amount of water
In Manaweaving it has "Mana Resevoir" in the title and in the section, but it should be "Mana Reservoir"

**Version Information:**
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.33

**Comment by HenryMaxler** [comment]
In the Animated Constructs: Wood Section it says "They are buoyant and light, meaning **the** help constructs to float and move more quickly."  Should say "They are buoyant and light, meaning _they_ help constructs to float and move more quickly."

**Comment by Mithion** [comment]
These were corrected in the codex rewrite - thanks!
This has been fixed in dev for next release (1.18.1).
