### ISSUE TITLE
Wellspring energy not increasing

### ISSUE THREAD

**Issue by redstoneking3** [Mithion/Mana-And-Artifice#473]
the Eldrin Wellspring energy is not going up in occulus

**To Reproduce**
1. Place refraction lens and build the multiblock
2. watch the cool particles which I assume mean its working.

**Expected behavior**
to see the energy go up from 9.2 in the occulus after afking for an hour

**Screenshots**
![2022-03-25_14 27 54](https://user-images.githubusercontent.com/87288129/160205325-84a3bd6a-f35f-4c2e-9091-7f9b3bb44fd4.png)

![2022-03-25_14 40 10](https://user-images.githubusercontent.com/87288129/160205332-4bd843d3-2425-4339-9ca9-6805c17b22ce.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.31

**Additional context**
Mod list:
https://pastebin.com/VYZr6pxR

**Comment by Mithion** [comment]
This has been fixed in dev for next release (1.18.1).
