### ISSUE TITLE
Eldrin Alter Use Server Crash

### ISSUE THREAD

**Issue by nefola** [Mithion/Mana-And-Artifice#474]
**Describe the bug**
When attempting to craft in an eldrin alter the server I was playing on crashed. Loading of that alter after server restart would cause additional crashes. Server is running about 50 other mods. A list of mods in additional content.

**To Reproduce**
1. Place items for crafting greater mote of air incomplete eldrin alter.
2. Have needed wellsping energy
3. Use chimerite wand on the eldrin alter.
4. Error Occurred

**Expected behavior**
Greater mote of air should be crafted. 

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.7
 - Forge Version [e.g. 36.2.8]

**Additional context**
https://pastebin.com/SqgiNQdb

**Comment by Mithion** [comment]
This has been fixed in dev for next release (1.18.1).
