### ISSUE TITLE
1.18.1 Piglins no longer passive when wearing golden armour

### ISSUE THREAD

**Issue by MUDAHMUDAH** [Mithion/Mana-And-Artifice#482]
**Describe the bug**
piglins no longer become passive/neutral when wearing golden armour

**To Reproduce**
Steps to reproduce the behaviour:
1. equip golden armour
2. enter nether and find/spawn a piglin
3. piglin becomes hostile and attacks player (as shown in attached screenshot)

**Expected behavior**
when wearing golden armour a piglin is suppose to be passive/neutral unless directly attacked

**Version Information:**
 - Mod Version: [1.7.05]
 - Forge Version [39.0.59]
 - Curios version: [1.18.1-5.0.6
 - geckolib version: [1.18-forge-3.0.11]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.
![2022-04-04_21 55 14](https://user-images.githubusercontent.com/102999164/161631507-a68dd9d4-9f9e-4629-95c4-65efac63ad86.png)

**Comment by Mithion** [comment]
This *should* be fixed in 1.7.2.2 (1.18.2) - please let me know if it is still happening for you.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
