### ISSUE TITLE
Top half of Runeforge doesn't take hopper inputs

### ISSUE THREAD

**Issue by Emeraldspiders** [Mithion/Mana-And-Artifice#486]
**Describe the bug**
Title. Bottom half works just fine, but for ore doubling it becomes a pain in the ass to automate when you have the pedestals above the hoppers that feed into the runeforges

**To Reproduce**
Place Runeforge, Places hopper pointing into the top half of the runeforge, put any item (including non smeltables, runeforge can still hold them), see item remain in hopper

**Expected behavior**
Hopper points into top half of runeforge, runeforge takes item from hopper

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.7
 - Forge Version 1.16.5, 36.2.20

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Corrected in dev for next release (1.18.1).
