### ISSUE TITLE
bug after using Arcane Codex

### ISSUE THREAD

**Issue by vapayt** [Mithion/Mana-And-Artifice#487]
i used Arcane codex and now every item and text (except gui) is dark and barely visible

1. get Arcane Codex (find somewhere or get in creative mod)
2. right-click with that in hands

i don't know about mod much, but i expect to just "read" it

![2022-05-10_18 28 48](https://user-images.githubusercontent.com/105302632/167666302-c2941f0a-1d3c-42a6-82bf-9187988bc6cf.png)
![2022-05-10_18 28 39](https://user-images.githubusercontent.com/105302632/167666305-f6645f14-a7ba-48ea-9a27-8165e0abc7c4.png)
![2022-05-10_18 27 42](https://user-images.githubusercontent.com/105302632/167666311-52930292-f841-4ba8-bbf2-0df82b522607.png)
![2022-05-10_18 27 37](https://user-images.githubusercontent.com/105302632/167666314-5b01aa9f-c1ec-45bb-a749-fbc36bae436f.png)
![2022-05-10_18 27 29](https://user-images.githubusercontent.com/105302632/167666318-f47a0393-af51-44d7-9252-0e480d2d1553.png)

 - Mod Version: 1.5.1.7
 - Forge Version 36.2.34 (1.16.5)

maybe it is because i've set too little amount of ram for 80+ mods? (but if i set more then my pc is gonna prob. crash)

**Comment by vapayt** [comment]
nah, optifine issues

**Comment by Mithion** [comment]
That'll do it - the Artifice Update for 1.18.1 has re-done a lot of the gui/hud stuff so should be *better* with things like this.  I still don't guarantee compatibility, but it might be worth a shot once the update is out.
