### ISSUE TITLE
Can't complete any of the crafting relating quests in tier 1 of the oculus

### ISSUE THREAD

**Issue by UnorthodoxDroid** [Mithion/Mana-And-Artifice#489]
I can't do any of the 3 oculus quests that include crafting for some reason, I've done all the other ones, but I can't seem to do these. I'm thinking it could be because I crafted the items before I could access the oculus, but I've crafted them multiple times after, and it still won't check off. I've tried re-logging and stuff too, but it doesn't seem to work.
I'm on the newest beta version of FTB Direwolf20 1.16

**Comment by Mithion** [comment]
You're likely using modded crafting tables.

Not all of them raise the OnItemCrafted event.  I'd let the mod authors know so that interop and compatibility can be improved, but in any case using a vanilla crafting table will work.
