### ISSUE TITLE
Reagents on runes get consumed when runeforging runes

### ISSUE THREAD

**Issue by Mourdida** [Mithion/Mana-And-Artifice#49]
Reagents placed around the runic anvil as for enchanting get consumed after finishing runeforging anything. 
This happens both with Metal and Chalk runes, but not with Pedestals.
Any reagent can be consumed, independently of the combination of reagents used.
The attached screenshot shows the position of the consumed reagents (on empty runes) after runesmithing, while the remaining reagents were left untouched : https://user-images.githubusercontent.com/68054483/87022117-53202880-c1d6-11ea-80e4-53ec5456022f.png

How to reproduce : 
- place a Runic Anvil and Runes (Chalk or Metal) around it as in the screenshot. The issue also applies with fewer runes.
- start any craft with the Runesmith's Hammer (for example rune pattern + superheated vinteum ingot)
- the last hammer hit consumes the reagents placed in the position of reagents when enchanting with the runic anvil

**Comment by Mithion** [comment]
This has been resolved in 1.0.5-pre3
