### ISSUE TITLE
Cannot put magic broom into manaweaving altar.

### ISSUE THREAD

**Issue by spectrumTF** [Mithion/Mana-And-Artifice#492]
Upon trying to put the broom into the altar it instead gets placed as an entity.

To Reproduce Steps to reproduce the behavior:
1. Take a magic broom
2. Right-click the altar
3. It instead gets placed in the world as an entity
Happens both with other mods and standalone(Curious,Geckolib,MNA)
Expected behavior: Broom goes into the altar as a crafting ingredient.

Screenshot:
![2022-05-17_23 26 01](https://user-images.githubusercontent.com/69161725/168904123-2feb762f-17c0-4f27-a5db-29e325606dba.png)

Version Information:
Mod Version: 1.5.1.7
Forge Version: 36.2.35

**Comment by Mithion** [comment]
This is already fixed in later versions.  However you can get around this by using a hopper, or another broom to insert the item.
