### ISSUE TITLE
Wellsprings do not remain visible after prism is complete, also do not convert Unknown wellsprings to lens type

### ISSUE THREAD

**Issue by GamerGuyRocks** [Mithion/Mana-And-Artifice#496]
Capture an eldrin wellspring by building the prism. wait or use commands to clear sight effects from unguent. I have that config setting enabled to make all wellsprings affinity neutral until a lens is used on them, but now that doesn't work.

With sight effects:
![2022-05-21_21 58 53](https://user-images.githubusercontent.com/102276631/169685044-2a0abb5e-fd46-4ae9-8732-f6c50bce771f.png)

Without sight effects
![2022-05-21_21 59 12](https://user-images.githubusercontent.com/102276631/169685048-816671c8-0a49-48a1-b00f-d21d20449d1f.png)

This is on the latest release.

**Comment by Mithion** [comment]
What you say "latest" what specific version is that?
