### ISSUE TITLE
1.18.2 crash after attune compass to biome from "Oh The Biomes You'll  Go"

### ISSUE THREAD

**Issue by CubeTwo** [Mithion/Mana-And-Artifice#497]
Describe the bug
After attune compass to biome from "Oh The Biomes You'll  Go" game world crashes

To Reproduce
Steps to reproduce the behaviour:
start ritual to find biome from Oh The Biomes You'll  Go
Expected behavior
after 1t crash that cant find biome, next crashes from entity ticking

Version Information:

    Mod Version: [1.7.2.1]
    Forge Version [40.1.22]
    Curios version: [curios-forge-1.18.2-5.0.7.0]
    geckolib version: [geckolib-1.18-forge-3.0.18]

Additional context
https://pastebin.com/UPEeY8CJ
https://pastebin.com/yZLkaxS4

**Comment by Its-Adra** [comment]
Same issue happened to me when trying to use the same ritual to go to a Biomes o' Plenty biome.
The biome in question was Mystic Grove
The link was found from a pregen structure. 

Link to the crash report:
https://pastebin.com/KPgyW15j

**Comment by Squantoscout** [comment]
I had the same thing happen with a vanilla biome (warm ocean), so i don't think its Biomes o' plenty that's the problem

**Comment by TheAgentFlash** [comment]
It's probably an oversight in the code when updating to minecraft 1.18.2 because biomes use "/locatebiome" now instead of the "/locate" that structures use.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
