### ISSUE TITLE
Digging rituals don't use the 1.18 bedrock depth

### ISSUE THREAD

**Issue by Crokoking** [Mithion/Mana-And-Artifice#498]
**Describe the bug**
The description of the Ritual of the Earthen Steppes and the Ritual of the Yawning Chasm both mention digging to bedrock. But they only seem to dig to around y=0 - so they don't handle the new 1.18 world height changes properly.

**To Reproduce**
1. Activate the Ritual of Yawning Chasm
2. Notice that the hole only goes down to around y=0

**Expected behavior**
The hole should go down all the way to y=-64 and only stop when it hits bedrock

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.1
 - Forge Version 40.1.0

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
