### ISSUE TITLE
1.18.2 Server crashing when using Ritual of locating

### ISSUE THREAD

**Issue by Whottech** [Mithion/Mana-And-Artifice#499]
Details - Forge 40.1.22 Modded
Mod Vers - mna-1.7.2.1.jar
Base Game Type - Skygrid

Morning,

Today on my pack a player tried using the "Ritual of Locating" and its now caused the chunks to error out.

https://pastebin.com/B43Ufrgp - console output

https://pastebin.com/A5KjJ5Rs - crash log (uploaded txt file too)

Has this been an issues before? Anyone had any luck fixing the affected area?

thanks,

Whoteva

[crash-2022-06-02_17.17.49-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/8828570/crash-2022-06-02_17.17.49-server.txt)

**Comment by Flash042501** [comment]
I got a similar crash on using that ritual, It worked once when I searched for a mansion, but crashed when I searched for a flower forest, just making sure, but does the ritual use the "/locatebiome" command when searching for a biome or does it still use "/locate"?

**Comment by groting** [comment]
Still crashes on newer version of M&A.

Details - Forge 40.1.15 Modded
Mod Vers - mna-1.7.2.2.jar

Trying to locate minecrfat:stronghold, maybe impact of YungsBetterStrongholds.

[crash-mna-1.7.2.2-locating-ritual.txt](https://github.com/Mithion/Mana-And-Artifice/files/8840084/crash-mna-1.7.2.2-locating-ritual.txt)

@Whottech, entity can be easily removed with NBTExplorer.

**Comment by Mithion** [comment]
This has been fixed and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
