### ISSUE TITLE
runic anvil recipe bug?

### ISSUE THREAD

**Issue by Dragon5mith** [Mithion/Mana-And-Artifice#5]
Chipped and damaged anvils aren't viable for crafting the runic anvil. If you want to keep this on purpose I'd recommend leaving a message in the codex that only an "untouched anvil" is usable.
![2020-06-13_01 52 28](https://user-images.githubusercontent.com/8917961/84561281-15d09400-ad19-11ea-8417-ecbf8428eed0.png)

**Comment by Mithion** [comment]
The displayed recipe indicates an anvil, not a chipped one or a damaged one.  Planned enhancements for the codex are displaying the item name on hover and cycling through valid items.  Once these are implemented it should be clear through context clues.
