### ISSUE TITLE
Ritual of Clear Skies / of the Monsoon - Locked reagents

### ISSUE THREAD

**Issue by Mourdida** [Mithion/Mana-And-Artifice#50]
Performing a Ritual of Clear Skies or a Ritual of the Monsoon with reagents placed on Metal Runes will lock the possibility to place or remove reagents with a right-click afterwards. 
It is still possible to get the reagents by breaking the rune. 
The ritual can still be run without adding or removing reagents.
This does not seem to apply to other rituals (at least it worked fine with the Ritual of the Flat Lands, which btw still has the same reagents as in 1.0.4, contrary to changelog information?).
Tested in 1.0.5

Steps : 
- Perform the ritual (Clear Skies or Monsoon) : place metal runes, place reagents, and manaweave correctly
- After completing the ritual, you will not be able to remove a reagent by right-clicking with an empty hand or to add a reagent by right-clicking an empty rune

**Comment by Mithion** [comment]
This has been resolved in 1.0.5-pre3.
