### ISSUE TITLE
Crash with Rituals [1.18.2]

### ISSUE THREAD

**Issue by itsdinkd** [Mithion/Mana-And-Artifice#500]
**Describe the bug**
Player set up a ritual in dedicated server and now corrupted chunk to the point where everytime he joins the server crashes

**To Reproduce**
1.Will have player come and write this

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.0] 1.7.2.1
 - Forge Version [e.g. 36.1.32] 40.1.20

**Additional context**
https://pastebin.com/FmTHm5uU

**Comment by error224543** [comment]
Steps to recreate
1) Begin the ritual of locating from mana and artifice, grab the materials needed 
2)draw the runes and use a thaumaturge "savanna pattern" 
3)begin ritual and draw the require manaweave symbol
4) soon as animation begins and the items converge it should crash everything

**Comment by Mithion** [comment]
Sorry about that.

There's a forge config to remove erroring entities that cleans up the corrupted ritual and prevents the crash: world/serverconfigs/forge-server.toml removeErroringEntities=true (or something similar)

Aside from the workaround, This has been fixed and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
