### ISSUE TITLE
Broken Ingredients [1.18.2]

### ISSUE THREAD

**Issue by itsdinkd** [Mithion/Mana-And-Artifice#502]
These broken recipes are causing JEI to have long load times as shown in this latest.log

latest log; https://gist.github.com/Sebas-Re/d2550652b9e1b6cd83cb6ee4efe84e4a (check the time stamp from when jei was serializing to the first broken recipe from MNA. 6 minutes.]

broken recipes ; https://pastebin.com/KM1vXtnR

![image](https://user-images.githubusercontent.com/35115304/171972354-b11fc1d3-f863-4157-bd8b-da8e6071d8e8.png)
![image](https://user-images.githubusercontent.com/35115304/171972256-f818c27b-7397-4d09-9245-97dbb2aea0c7.png)

ver:
MNA: mna-1.7.2.1.jar
MC: 1.18.2
Forge: 40.1.20

**Comment by Mithion** [comment]
This has been fixed and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
