### ISSUE TITLE
Deepslate Diamond Ores not dropping Chimerite

### ISSUE THREAD

**Issue by TheAgentFlash** [Mithion/Mana-And-Artifice#503]
Deepslate Diamond Ores don't drop Chimerite

To reproduce:
Just break Deepslate diamond ore as a level 10 wizard or higher

Deepslate diamond ore should properly drop chimerite like normal diamond ore.

 - Mod Version: [1.7.2.1]
 - Forge Version [40.1.31]

I'm fairly sure this was caused by an oversight in porting to Minecraft 1.18.2. you probably want to check deepslate emerald and coal too.
(Looking at the issues listed on this github tells me this wasn't the only oversight)

**Comment by Mithion** [comment]
This has been fixed and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
