### ISSUE TITLE
Locating RItual still crashing [1.7.2.2 for 1.18.2]

### ISSUE THREAD

**Issue by itsdinkd** [Mithion/Mana-And-Artifice#504]
Looks like the ritual of locating is still crashing players of AQM3 even with the version of MNA that was released to fix the crash. 

I am told the player started a new world when I released the update to my modpack that included 1.7.2.2 so it wasn't a pre-existing ritual. it was the first time the player created a locate ritual in this new world on MNA 1.7.2.2

https://gist.github.com/itsdinkd/51d6780e371d850505bb1e5e4163094d

**Comment by Mithion** [comment]
This has been fixed and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
