### ISSUE TITLE
1.18.2 Pig spawner

### ISSUE THREAD

**Issue by LoneWolf137** [Mithion/Mana-And-Artifice#505]
**Describe the bug**
All spawner in faction structures are pig spawners

**To Reproduce**
enter faction structure
see pig spawner

**Expected behavior**
for some reason they are pig spawers
 i tried multiple reistalls, modpacks and worlds.

**Screenshots**
![2022-06-08_06 20 46](https://user-images.githubusercontent.com/42692808/172530907-9abf52a9-c858-466b-aaf4-3574410a8162.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.2
 

**Additional context**

**Comment by LoneWolf137** [comment]
Additionally i found a undead crypt buried and in the ocean,  a fairy glade cutting a mountain and a demon fortress on the nether roof.

**Comment by Mithion** [comment]
Structures are fun.

**Comment by Mithion** [comment]
Structures are fixed.
