### ISSUE TITLE
Searching for a Mana and Artifice wand in the AE2 wireless crafting terminal (possibly one that has a weaving altar set?) causes a crash

### ISSUE THREAD

**Issue by Iris-xii** [Mithion/Mana-And-Artifice#506]
**Describe the bug**
While holding a few Mna items in my inventory, and being surrounded by a few Mna blocks, I opened my wireless crafting grid to find that it caused a crash. Some notable items were a spell and a wand.
UPDATE: It actually happened while searching in AE2 with a wand from mna present in my ae2 system.

**To Reproduce**
Dump a Mna wand (possibly with a manaweaving altar set?) into AE2 and search for it.

**Expected behavior**
Not a crash

**Crash log**
https://gist.github.com/Iris-xii/d4de37acb2d366bda69bfcca2fd60508

**Version Information:**
 - mna-1.7.2.2.jar 
 - net.minecraftforge:40.1.31

**Update**
Appears to happen when I search for "m" in ae2. I suspect it is caused by a wand I tossed into my AE2 system. I'll try to get it out and see if that helps.

**Comment by Mithion** [comment]
My bad.  Sorry.
This has been fixed and will go out with the next release.

**Comment by Mithion** [comment]
Version 1.7.2.3 has been released, which resolves this issue.
