### ISSUE TITLE
[1.18.2] Dedicated server crash loop - Cannot invoke "net.minecraft.world.entity.Entity.m_6060_()" because "living"

### ISSUE THREAD

**Issue by ProsperCraft** [Mithion/Mana-And-Artifice#507]
**Describe the bug**
Dedicated sever for my TownCraft for 1.18.2 modpack crashed.

It is crashing again every time the area is loaded.

**To Reproduce**

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.2.2
 - Forge Version 1.18.2-40.1.47

**Additional context**
Here is the console at the time of the crash-
https://gist.githubusercontent.com/ProsperCraft/b78cc22ef1f585edafe08c36dbc1fa59/raw/7f8327f55ade859462362896bb8a528b0a379e00/gistfile1.txt
Here is the crashlog-
https://gist.githubusercontent.com/ProsperCraft/253c4b4dcb2b95888f27f97db0096437/raw/703cb064cf32fbb67adbfaefd7c425ca75e63f40/gistfile1.txt
Second crash-
https://gist.githubusercontent.com/ProsperCraft/db85d0727b9d11fa8399316471b0ab37/raw/99c0d9410e41a378cac1295e9bd49bfd60f41f41/gistfile1.txt

**Comment by ProsperCraft** [comment]
Here is another crash with forge, Mana and all of the other mods updated-

https://gist.githubusercontent.com/ProsperCraft/4981b9d95258703b05f9c3c46f031b9b/raw/0544b11703e73bae1dc65877fd2f101b5082d440/gistfile1.txt

**Comment by ProsperCraft** [comment]
I don't understand, is the entity not saved in the region? I was able to get a /kill @e[type=mna:animated_construct] while the chunk was loading on login, and it still crashed, then I moved the region file out of the way, and it still crashed?

**Comment by Mithion** [comment]
This was fixed in 1.7.2.3 (1.7.2.5 is latest)
