### ISSUE TITLE
Ritual of the Yawning Chasm & Ritual of the Earthen Steppes Doesn't Dig Down to Bedrock (mna 1.7.2.2 - 1.18.2)

### ISSUE THREAD

**Issue by Diamond22110** [Mithion/Mana-And-Artifice#508]
**Describe the bug**
When doing the Ritual of the Yawning Chasm and the Ritual of the Earthen Steppes, the codex arcana mentions them both digging their respective holes down to bedrock, but will instead end around the pre-deepslate bedrock level. In other words, they stop digging their holes at around y2 - y15 as opposed to continuing to burrow down through the deepslate to actually reach bedrock. 

**To Reproduce**
1. Perform either ritual (Yawning Chasm or Earthen Steppes)
2. The hole being dug out will only reach down to about y2 - y15 as opposed to reaching the actual bedrock layer in Minecraft 1.18.2.

**Expected behavior**
One would expect the rituals of the Yawning Chasm and the Earthen Steppes to reach down to the actual bedrock layer, past the deepslate levels of the game. 

**Screenshots**
![Screenshot (1078)](https://user-images.githubusercontent.com/107358889/173509740-4e743844-67a7-404d-ab41-9a16fda05317.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.2
 - Forge Version 40.1.47

**Additional context**
No additional context needed, issue is pretty straight forward. I personally don't know if this is intentional or not, but I just wanted to report it as it is either an issue that needs to be resolved, or it might be something to look into re-writing in the codex arcana if it is intentional for it to stop at deepslate.

**Comment by Mithion** [comment]
Changed in 1.7.2.5
