### ISSUE TITLE
Construct frame entries missing from codex

### ISSUE THREAD

**Issue by NormalCube** [Mithion/Mana-And-Artifice#509]
**Describe the bug**
All construct frame patterns are missing from the codex arcana; thus being highly annoying to craft even with jei (can't pin them).

**To Reproduce**
1. Get codex arcana
2. Using the search function or browsing through the pages, attempt to find entries related to construct frame patterns
3. Realize they don't exist

**Expected behavior**
They should appear just like any other rune patterns

**Screenshots**
![2022-06-14_12 58 21](https://user-images.githubusercontent.com/107472981/173563101-4843373f-53a4-421f-8938-1b777855457f.png)

**Version Information:**
 - Mod Version: 1.7.2.3
 - Forge Version 40.1.48

**Additional context**
No other mods were used, except the latest version of jei and the required dependencies

**Comment by Mithion** [comment]
Resolved in later versions of the mod
