### ISSUE TITLE
Arcane Crown not refreshing its Mana Boost II potion effect fast enough.

### ISSUE THREAD

**Issue by TheAgentFlash** [Mithion/Mana-And-Artifice#511]
I downloaded the new update and noticed my mana was regenerating then get thrown back to a set point at regular intervals, preventing it from maxing out. I noticed this "mana reset" was happening every time the Mana Boost II potion effect duration changed from 0 seconds to 4 seconds, and sure enough when I take the crown off, my max mana drops but the odd behavior ceases, leading me to believe that the crown's potion effect stops being applied for about 1 tick, therefore resetting my mana.

To reproduce simply wear an arcane crown and watch your mana jump backwards repeatedly.

The behavior I expected was that my mana would be allowed to cap out while wearing the crown.

 - Mod Version: [1.7.2.3]
 - Forge Version [40.1.31]

Update: I Just tried the crown again, and the behavior wasn't occurring this time, I know it was tied to the crown somehow, so i'm unsure of the exact cause.

**Comment by CallMeHubris** [comment]
I'm experiencing an identical bug but from a different source. I get the same rubber-banding effect on my mana bar when the mana regen buff is applied by a mana crystal. I just started getting this bug when I updated the mod (v1.7.2.8) but didn't encounter this issue on the previous version I was playing on (v1.7.2.6)

- Mod Version: [1.7.2.8]
- Forge Version: [40.1.60]
