### ISSUE TITLE
1.18.2 Crafting in Inventory Crash (Crafts Ritual)

### ISSUE THREAD

**Issue by EtherChicken** [Mithion/Mana-And-Artifice#512]
**Describe the bug**
After putting a Dandelion in the bottom right slot in the inventory crafting menu, it tried to create the Ritual of Locating (the physical item which has the ID "mna:rune_ritual_metal",  causing a "RitualContext getCollectedReagents called during check reagents stage." 4 times on the my server CMD tab. My server was completely fine and I am able to rejoin with the dandelions being dropped on the floor. no crash log created and logs show nothing from 11 minutes before and until the crash.

**To Reproduce**
Completely unable to reproduce, but I have been able to to get nothing to show up in the output slot one time by opening the Codex Arcana and going to the "Practitioners Patch: Glyph" then straight to the inventory and putting the dandelion in the bottom right slot. The nothing craft happened again randomly when waiting for the Youtube Video to render, and was able to fix it by putting the dandelion in a different slot, this is shown in the video.

**Expected behavior**
I expected to craft yellow dye from the dandelions.

**Screenshots**
[Image of Inventory Crafting Table Crash](https://cdn.discordapp.com/attachments/508128383180210176/986622166793609266/unknown.png)
I have a video showing the minute leading up to the crash and the only few reproductions I could get after 10-15 of testing.
https://youtu.be/YHvuvigBENY
**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.3
 - Forge Version 40.1.47

**Additional context**
I have played MnA since one of the very first alpha releases and have never seen this issue nor anything like it and I wish I could give more insight but I was on autopilot when I clicked to craft so by the time I realized something had happened the game crashed already. I apologize if this isn't an MnA issue but I wasn't actively using another mod at the time and it was an MnA item that appeared so I thought it might be.

**Comment by Mithion** [comment]
That log message is just a warning and can be safely ignored...the craft part is weird and I'll have to investigate.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
