### ISSUE TITLE
QoL Recomendation: Texture Adjustment regarding Thaumaturgic Link pages

### ISSUE THREAD

**Issue by Shibva** [Mithion/Mana-And-Artifice#514]
ima gonna skip all of this and get down to the chase

I love the retextures that are being done and the Thaumaturgic Links as well, yet I would like to suggest it and it's relatively simple (I hope but I may be wrong); adding color variations to the texture itself. What I mean by this is simple; The Link itself can locate structures and biomes (and other things I may not be aware of) and they have the same texture used; what if the color of the texture was different for each category of Thaumaturgic Links that exist; as in the ones regarding structure would be tinted pink (for the sake of an example) and structures remaining unaltered

The benefits of this would make locating certain links easier to identify just slightly by the color of the page/scroll/parchment of the item itself

**Comment by Mithion** [comment]
Good idea!

**Comment by Mithion** [comment]
This was completed with the most recent update of the mod.
