### ISSUE TITLE
1.16.5 Witch Hunter crash minecraft

### ISSUE THREAD

**Issue by Aleks3275** [Mithion/Mana-And-Artifice#517]
If you start fighting with Witch Hunter or Turn on shaders when Witch Hunter appears, Minecraft will crash

1. Spawn Witch Hunter
2. Start fighting with Witch Hunter
3. You get a crash log.

 - Mod Version: [1.5.1.7]
 - Forge Version [36.2.8]
Crash-log
https://www.toptal.com/developers/hastebin/qigibewefe.yaml

**Comment by Mithion** [comment]
Update GeckoLib, that's a fix for common issues regarding witch hunters.

**Comment by Come1LLF00** [comment]
Hello. For us updating geckolib didn't help.

* Mod version [1.5.1.7]
* Forge Version [36.2.34]
* Mana and Artifice [1.5.1.7]
* Tried GeckoLib [3.0.64, 3.0.80, 3.0.81]

Crash Report:
[crash-2022-07-17_13.39.11-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/9127440/crash-2022-07-17_13.39.11-client.txt)

**Comment by Come1LLF00** [comment]
> Hello. For us updating geckolib didn't help.
> 
> * Mod version [1.5.1.7]
> * Forge Version [36.2.34]
> * Mana and Artifice [1.5.1.7]
> * Tried GeckoLib [3.0.64, 3.0.80, 3.0.81]
> 
> Crash Report: [crash-2022-07-17_13.39.11-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/9127440/crash-2022-07-17_13.39.11-client.txt)

Solved by downgrading GeckoLib to 3.0.77. But `/summon mana-and-artifice:witch_hunter_trickshot` crashes anyway
