### ISSUE TITLE
Mastery Altar "Pips" reset when traveling through dimensions or relogging

### ISSUE THREAD

**Issue by TheAgentFlash** [Mithion/Mana-And-Artifice#519]
**Describe the bug**
The pips that indicate your level of mastery in the altar reset any time you go to another dimension or relog.

**To Reproduce**
1. Gain mastery in a component that you have rote
2. Go to another dimension or relog
3. Check the altar and see that the number of pips on your component are gone.

"Pips" in question:
<img width="78" alt="Capture3" src="https://user-images.githubusercontent.com/25333490/174624914-6352bf8b-5e48-4e96-a4c7-bf20e0c87453.PNG">

**Expected behavior**
To be able to reliably see my mastery levels for any given component, even if I relog or travel across dimensions.

**Version Information**
 - Mod Version: [1.7.2.3]
 - Forge Version [40.1.31]

**Additional context**
This does not appear to reset actual mastery levels of a component, as when I gain more mastery the chat message relays a percentage that is accurate to the number of times I had the altar level it up. It only resets the "pips"

**Comment by Mithion** [comment]
This was fixed in 1.7.2.5
