### ISSUE TITLE
translation submit question

### ISSUE THREAD

**Issue by TUsama** [Mithion/Mana-And-Artifice#52]
Hi, Mithion, I wonder If somebody wants to add a new lang file, can he just create a pull request on GitHub？

Looking forward to your reply.

**Comment by Mithion** [comment]
Hi!  Thanks for your interest in translating :)

With the current state of the mod, I'm not really doing translations yet as there's so much more to add and there is a ton that will change.  

I'm going to put information on translations into discord (https://discord.gg/RSBJzNC) when I'm ready for that to begin.  Likely, it will work as a PR through this repo at that point as you correctly guessed.
