### ISSUE TITLE
Arcane Crown Texture Broke

### ISSUE THREAD

**Issue by TheAgentFlash** [Mithion/Mana-And-Artifice#520]
**Describe the bug**
The majority of the arcane crown is now the purple and black placeholder texture.

**To Reproduce**
Look at Arcane Crown

**Expected behavior**
To see a proper texture that was seen before this update

**Screenshots**
![2022-06-21_04 58 26](https://user-images.githubusercontent.com/25333490/174760550-7012fb21-a67c-47f2-90f6-955b6f259a8a.png)

**Version Information**
 - Mod Version: [1.7.2.4]
 - Forge Version [40.1.31]

**Comment by Mithion** [comment]
Resolved in 1.7.2.6!
