### ISSUE TITLE
Translate permission

### ISSUE THREAD

**Issue by Pinkhai** [Mithion/Mana-And-Artifice#521]
**Is your feature request related to a problem? Please describe.**
I want to translate your mod into chinese I need a permission 

**Describe the solution you'd like**
I will handle this work in my summer vacation then I give the lang file to i18n. so every chinese player will understand how interesting your mod is

**Describe alternatives you've considered**
someone may cowork with me or complete it instead of me

**Additional context**
nothing

**Comment by Mithion** [comment]
go right ahead!
