### ISSUE TITLE
Channel type spells not being maintained

### ISSUE THREAD

**Issue by TheAgentFlash** [Mithion/Mana-And-Artifice#522]
**Describe the bug**
When I go  to channel a beam, emanation, or wrath shape spell, it doesn't maintain itself properly and instead cancels itself immediately and goes on cooldown.

**To Reproduce**
1. Craft a spell that requires you to hold down the button to cast, (e.g. Beam, Wrath, Emanation)
2. Try to cast it and have it go on cooldown when you try to.

**Expected behavior**
For the Channeling type spells to be cast properly.

**Version Information**
 - Mod Version: [1.7.2.4]
 - Forge Version [40.1.31]

**Comment by Mithion** [comment]
This was fixed in 1.7.2.5
