### ISSUE TITLE
[1.18.2] Concentration Spells and Summon Spell Bugs

### ISSUE THREAD

**Issue by Lonely-Android** [Mithion/Mana-And-Artifice#523]
**Describe the bug**
Concentration Spells: Cast and take mana, only play a split second of animations and then disappear with no effect
Summon Spells: With a full phylactery in a staff of summoning or not (in the offhand) will take mana and put spell on cooldown but claim that "The target is too powerful for this spell". I didn't think skeletons were too powerful to be attacked by any iron golem, or maybe that's just my phylactery one lol

**To Reproduce**
This is all on a server
Somehow it only bugs in survival mode, works fine in creative
Concentration: I used a break beam to see this. 
1. Make a break spell with the beam form.
2. See resulting bug

Summoning: As stated, phylactery with iron golem.
1. Make a summon spell with strength (that's what I used) 
2. Fill a phylactery with iron golem
3. Cast and see resulting bug

**Expected behavior**
Concentration: Spells to function properly
Summon: Mobs to spawn from the phylactery type as said in the spell description

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.7.2.4]
 - Forge Version [e.g. 40.1.52]

Thank you in advance for all your work! I love this mod even with the bugs lol

**Comment by Mithion** [comment]
The channeled spell bug was fixed in 1.7.2.5.

The summon thing is intentional; you need to increase the magnitude of the spell.  There's a health maximum.  You can increase it in the configs to allow for summoning of more powerful mobs :)
