### ISSUE TITLE
Spellbreaker causes severe fps drops

### ISSUE THREAD

**Issue by luo-2233** [Mithion/Mana-And-Artifice#524]
**Describe the bug**
When the view towards Spellbreaker, The game has experienced a severe fps drop.

**To Reproduce**
1. Look to Spellbreaker

**Expected behavior**
Hopefully no lag will occur as a result

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [1.7.2.4]
 - Forge Version [40.1.51]

**Additional context**
I added a lot of mods and I'm not sure if this is a compatibility issue, but and the game didn't crash.

**Comment by jojobmomo** [comment]
Same

**Comment by todor1705** [comment]
Me too

**Comment by Mithion** [comment]
Duplicate of #516 - tracking there.
