### ISSUE TITLE
Config option `modifyVillagerTrades` is not respected when set to `false`

### ISSUE THREAD

**Issue by StevenJBurns** [Mithion/Mana-And-Artifice#525]
**Describe the bug**
When the config option `modifyVillagerTrades` is set to `false`, the value is not respected

**To Reproduce**
1. Set the `modifyVillagerTrades` flag to `false` in `mna.general.toml` and restart the game
2. Attempt to "reset" an unbound librarian villager's trades by breaking and replacing the lectern work station
3. Note that enchanted book trades are never offered despite the config setting being set to `false`

**Expected behavior**
An unbound librarian villager should occasionally offer enchanted books after "resetting" the lectern work station

**Version Information (please complete the following information):**
 - Mod Version:  1.7.2.5
 - Forge Version:  40.1.54

**Comment by Mithion** [comment]
I'll make sure this is fixed for next version.

**Comment by Mithion** [comment]
Just released 1.7.2.6, this should resolve the issue - make sure you are also using the new config file placed in serverconfig (as the configs were moved there to solve a different issue).

Let me know if it's good for you!

**Comment by StevenJBurns** [comment]
Took a bit to find the `serverConfig `but it's now working as advertised.  Thanks again!
