### ISSUE TITLE
[1.18.2] Ranged Construct Arm Bug

### ISSUE THREAD

**Issue by Lonely-Android** [Mithion/Mana-And-Artifice#526]
**Describe the bug**
Mana Cannon Arms do not work (though I know the spell arms don't according to the Codex)

**To Reproduce**
Make Construct with mana cannon arms and mana tank torso
Animate it
Put hostile mob in range
See it sit there while the diagnostic says it recognizes the hostile

**Expected behavior**
Mana cannon shoots like a player is using it

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.7.2.5]
 - Forge Version [e.g. 40.1.52]
 
Thanks again!

**Comment by Lonely-Android** [comment]
I did, noticed it was mentioned in the codex. Diag menu said it had mana.

**Comment by Mithion** [comment]
Okay, what other parts are on the construct?  I'll build the same one and see if I can replicate the issue.  I know on the battlechicken server I was using a mana cannon arm on a construct and it worked fine, so it might be something to do with other parts.

**Comment by Lonely-Android** [comment]
Construct assembled as follows:
Gold smart head
Gold mana torso
Diamond left shield
Diamond right mana cannon
Gold rocket legs

Hope this help!

**Comment by Dimmondback** [comment]
Issue still persists in version 1.7.2.8.

**Comment by Dimmondback** [comment]
Performed additional testing in creative world:
This setup works fine:
Obsidian Basic Head
Obsidian Mana Torso (fully charged from mana crystal)
Obsidian Basic Legs
Obsidian Right Mana Cannon
Obsidian Left Grabber Arm

I tested out with the shield arm and depending on which hand is the mana cannon, the golem prefers the left-handed attack more. (Ex: If the mana cannon is the left hand, the golem prefers to ranged attack but if the shield is in the left hand, the golem prefers to shield bash).

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
