### ISSUE TITLE
Bugfixes for 1.16 still coming? Particularly #395

### ISSUE THREAD

**Issue by SangurianSoul** [Mithion/Mana-And-Artifice#528]
M&A 1.16.5 Is still heavily used by the community as I'm sure you are aware.

I am also aware that a huge update to 1.18 happened recently that will not be backported. I completely understand with that scope of work.

But I was wondering if there are bugfixes still coming to 1.16? I have a large server that is constantly running into the issue with breaking multiblock things, they break entirely without dropping. Things such as the Runeforge, Inscription Table, Runic Torch, ETC. Conduits also have a problem.

**Comment by abadger** [comment]
This one as well: https://github.com/Mithion/Mana-And-Artifice/issues/444 (AFAICS, bind wounds is the only spell that gets you to 35 spell complexity which is one of the oculus requirements to leave tier 2)

**Comment by SangurianSoul** [comment]
Oh, awesome.

Very happy to hear, this mod is just the best.

**Comment by Mithion** [comment]
Eventually, if I have time, but I will admit older versions aren't my priority at the moment.  I will need to come up with a plan to address this properly though.

**Comment by Mithion** [comment]
Closing as 1.16.5 is no longer supported.
