### ISSUE TITLE
Transitory Tunnel recipe is broken in 1.0.5-pre3

### ISSUE THREAD

**Issue by Mourdida** [Mithion/Mana-And-Artifice#53]
The recipe shown in the Codex Arcana misses an entry for the second ingredient (see [screenshot](https://user-images.githubusercontent.com/68054483/88569629-fb3d4a80-d03a-11ea-9dcc-d555c8c3c304.png)).
The recipe doesn't work with or without the second ingredient (an Ender Focus).

I looked into the code for this recipe (mana-and-artifice/recipes/manaweaving/transitory_tunnel.json) and the second ingredient is incorrectly written : "minecraft:enchantment_focus_ender" instead of "mana_and_artifice:enchantment_focus_ender", which should be easy to fix.

**Comment by Mithion** [comment]
My baf, I've fixed the recipe for the next version.  thanks for pointing it out!
