### ISSUE TITLE
Vinteum Manaweaver's wand not work [1.16.5]

### ISSUE THREAD

**Issue by CobaxVarrier** [Mithion/Mana-And-Artifice#530]
I took the Manaweaver's wand and when I used in the manaweaving altar the speel not appear and the wand stop to cast durability and mana, i create a new world in creative and I used the wand again and worked, but a back to my survival world again and happen the same thing

**Comment by Mithion** [comment]
Make sure you have enough mana to complete the weave, and that you've unlocked magic by reading the codex at least once.

There is a priority of notifications for manaweaves so it's possible that the patterns are being pulled into a nearby pedestal or manaweaving altar.

**Comment by aaaaa777** [comment]
I have this issue too, and I already read the codex, I have 800 mana, and I'm in the middle of nowhere
