### ISSUE TITLE
Sleeping Does not advance Occulus

### ISSUE THREAD

**Issue by Zakkapcsos** [Mithion/Mana-And-Artifice#531]
Me and my brother are playing on a local world where we have a couple of random mods installed, including morpheus (Sleep vote system) and when he tries to sleep, it doesn't advance the Occulus, im the host and hes the one having issues (I have not messed with the mod myself), id assume this was a Morpheus issue but it also resets his crafted items progress everytime he rejoins (Inscription table, Manaweaving wand, and the manaweaving altar)

**To Reproduce**
1: Craft item (Appear green)
2: sleep (Sleep no work :< )
3: Reload login ( Green gone)
4: repeat (Definition of insanity)

Mod Version is 1.5.1.7

**Comment by Mithion** [comment]
LAN worlds work strangely and differently, I recommend running a small local server instead.  It's almost the identical setup and will remove a lot of weirdness that LAN worlds seem to create.
