### ISSUE TITLE
Shift clicking items out of a pouch into a full inventory occasionally deletes them.

### ISSUE THREAD

**Issue by Lonemind** [Mithion/Mana-And-Artifice#532]
**Describe the bug**
When the players inventory is full and they try to shift-click items from the Practitioner's Pouch into their inventory the items are occasionally deleted if the players inventory doesn't already have the items to be moved.

**To Reproduce**
1. Fill your inventory with an item, sticks for instance.
2. Open a Practitioner's Pouch with a stack of items in it, planks for instance.
3. Shift-click the planks to move them into the players inventory.
4. Watch as part of the stack is deleted, or, if the item doesn't stack, is lost forever.

**Expected behavior**
Items should not move from the pouch if there is no room in the player's inventory.

**Screenshots**
[Video](https://imgur.com/a/PpLeE4F)

**Version Information (please complete the following information):**
 - mna-1.7.2.5
 - Forge Version 40.1.60

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
