### ISSUE TITLE
I can not make cantrips except for 2 chunks [1.16.5]

### ISSUE THREAD

**Issue by aaaaa777** [Mithion/Mana-And-Artifice#533]
I can draw the symbols in the air, it consomes mana but when I stop clicking, nothing happens, when I was tier 1, it had some that made a message saying that I can not make this cantrip now, but now, I am tier 2 and nothing happens, but in two chunks that I was staying, I could do everything normal

**To Reproduce**
1. Get item 'wand'
2. Draw a cantrip
Nothing happens

**Expected behavior**
No clue.

**Screenshots**
![image](https://user-images.githubusercontent.com/51868857/179642044-41e35310-7864-47d1-ac32-01cfb89cae03.png)
![image](https://user-images.githubusercontent.com/51868857/179642154-1f21c247-82af-4fa2-831a-e4f48c3b05c7.png)

**Version Information (please complete the following information):**
 - Minecraft Version {1.16.5}
 - Mod Version: [1.5.1.7]
 - Forge Version [Dont know]

**Additional context**
I am using mods: RPG HUD/Epic Knights/Alex's mobs/Apotheosis/architectury/blood magic/bookshelf/brutal bosses/citadel/curios/dynamic surroundings/Epic fights/exotic birds/ forge branders spawner/ geckolib/ guide api/hwyla/JEI/Journey map/jumpboat/kobolds/mahou tsukai/Mana and artifice/mowzies mobs/orcz/ore excavation/patchouli/placebo/prefab/rubidium/shrines/the abyss/untamed wilds/vampirism

I played before with another mods, and the same thing happened, but it was in my home the chunks

**Comment by Mithion** [comment]
It's likely being pulled into the nearby manaweaving altar.
