### ISSUE TITLE
Construct commands

### ISSUE THREAD

**Issue by CubeTwo** [Mithion/Mana-And-Artifice#534]
**Describe the bug**
1. Command [Gather Items] sometimes dont work and if Construct gather items some items missing(deleted? see 1.1clip)
2. Command [Place Block at Position] dont see or dont using item that [rune:Marking] have selected (or its dont work on tree saplings?) and use random sapling
3. Command [Condititon: Is Block At Location] dont use tree saplings what in slot for condition and use random sapling see3.1. and / or dont using item that [rune:Marking] have selected (or its dont work on tree saplings?)
4. Command [Condition:Construct Has Item] dont work with specified tree saplings? and / or used with command [Place Block at Position]
**Screenshots**
1.1 https://clips.twitch.tv/RockyHonestClintVoHiYo-DjGV0RD39hZlr4SH
2.1 https://imgur.com/a/51O2QIF
3.1 https://imgur.com/a/qTPxUKy
**Version Information (please complete the following information):**
 - Mod Version: [1.7.2.6]
 - Forge Version [40.1.60]
 - 
 - my character tier 4 mage (council allied)
 - my construct was build with:
[Smart Gold Head]
[Gold Axe Right Arm]
[Iron Grabber Left Arm]
[Diamond Storage Torso]
[Iron Basic Legs]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
You don't need to loop the logic like that - the "chop wood" task (or any task) will loop back to the blue start node if the output isn't connected.  For example:

![image](https://user-images.githubusercontent.com/2482373/181310090-36a0d872-2832-44da-bf96-c215eb893b81.png)
This will chop trees, and if it successfully does so it will try to pickup items and deposit them into a chest.  Note that the red node on chop trees and both the nodes on deposit aren't connected to anything - that tells the construct to start the workflow again.

Looping them like you have will run into intelligence limits and cause the construct to become confused - this counter is reset whenever a workflow restart happens, so doing it the way I showed will help limit that.

I did a simple test setup to look for a jungle sapling at the given location.  If it does, it moves to green.  If it doesn't, it moves to red:
![image](https://user-images.githubusercontent.com/2482373/181310665-ae5d674a-fbb7-4844-ba48-e730a9164460.png)

It seems to be working fine for me.  Here's the logic:
![image](https://user-images.githubusercontent.com/2482373/181310754-42740e4e-3f35-418a-b632-d3b6341fdc15.png)

Did the same thing for "construct has item", and it's working fine too for jungle saplings:
![image](https://user-images.githubusercontent.com/2482373/181311090-238cecca-b8de-4f22-bd99-394d64acd623.png)
![image](https://user-images.githubusercontent.com/2482373/181311128-99746cdc-45d6-4bf2-a65f-d13f90b9d42b.png)

When telling constructs to place a block at a position, it needs to be targeted on empty air (not the block below, etc)

Point 1 is fixed for 1.7.2.7
