### ISSUE TITLE
Magic Brooms

### ISSUE THREAD

**Issue by CubeTwo** [Mithion/Mana-And-Artifice#535]
**Describe the bug**
1.magic broom sometimes stop working   see 1.1-1.3
2.magic broom dont work with barrels and chest from sophisticated storage mod (cannot place broom to chest \ barrel)
3.cannot place magic broom in [Manaweaving Altar] to craft ]Vortex Broom]. If you place hopper to Altar and put broom in hopper it place broom in Altar. see 1.5
4.[Vortex Broom] sometimes dont pickup items, after new item droped it works again. see 1.6
**To Reproduce**
1. Get item 'magic broom'
2. Use on 'hopper \ chest \ barrel' and wait?
3. Have magic level '5'

**Expected behavior**
after place magic broom it random stop working after it pickup some items, sometimes if you nodge or move broom by my player collision it work again, sometimes it stuck and dont work
**Screenshots**
1.1 https://clips.twitch.tv/BigBoredStingrayPMSTwin-54iZjUVDMfzhwQDS
1.2 https://clips.twitch.tv/TemperedDarkGooseOhMyDog-bL5kYLGwQuze1sXc
1.3 https://clips.twitch.tv/RudeManlyTriangleKappaWealth-of5l3HulVtI4a_xW
1.4 https://clips.twitch.tv/ColdBeautifulStingrayTwitchRPG-AsD9y-FRzFGyLdHU
1.5 https://clips.twitch.tv/DignifiedVastOysterEagleEye-VywysOSqv7jPZM3p
1.6 https://clips.twitch.tv/WiseBumblingBubbleteaGOWSkull-c1wiA1Ky5NkHyhz2

**Version Information (please complete the following information):**
Mod Version: [1.7.2.6]
Forge Version [40.1.60]

**Comment by Mithion** [comment]
1. MC pathing/AI is fun.  I made some tweaks to brooms so they can grab things from farther away; that should solve the issue.
2. Depends how they implement their storage.  Brooms currently only work with tiles that implement the Container interface.  For more advanced interactions, look into constructs.
3. - This is fixed for 1.7.2.7
4. Brooms have a line of sight predicate - meaning they need to be able to "see" the item on the ground.  If something is in the way, they won't be able to collect the item.  They also take time to deposit items, and once they start they won't pick up new items until they're done.
