### ISSUE TITLE
Releasing crystalized mobs by clicking on a wall will spawn them inside it

### ISSUE THREAD

**Issue by Grzesiu447** [Mithion/Mana-And-Artifice#536]
**Describe the bug**
Releasing crystalized mobs by clicking on a wall will spawn them inside it, killing them most of the times.

**To Reproduce**
1. Get item Crystalline cage
2. Use on the wall
3. Have magic level 'any'

**Expected behavior**
Mobs should spawn next to the wall you click on

**Screenshots**
![2022-07-23_18 07 01](https://user-images.githubusercontent.com/29795630/180613345-75d47c39-cb5a-4407-8d74-af2cfa39d788.png)

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.2.5.jar
 - Forge Version forge 1.18.2 40.1.54

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Changed and will go out in 1.7.2.7
