### ISSUE TITLE
Few quality of life improvements to Codex Arcana

### ISSUE THREAD

**Issue by Grzesiu447** [Mithion/Mana-And-Artifice#537]
**Is your feature request related to a problem? Please describe.**
1st: After you exit an entry in the book you go back to 1st page of that tab, which makes it really annoying to check new things afer you get to next tier.
2nd: It's annoying to look for new things in the Codex, after you get to next tier.

**Describe the solution you'd like**
1. Make it so after you exit an entry, you go back to the page the entry is on. A bookmark feature would be useful too.
2. Make it so tier of each entry is visible from the tab.

**Comment by Mithion** [comment]
Hey there,

The codex is being reworked with several new changes including bookmarks and better navigation.  Regarding point 2 though, that's what the occulus is for.

**Comment by Grzesiu447** [comment]
Yes, you can see what's new in Occulus, but you can't read about the new things inside it.
It'll be easier to look through new things when you don't exit the entry into the first page of the tab, but still it would be more convenient if entries were highlighted differently depending on the tier. Alternatively you could just highlight entries as "new" or "unread".
