### ISSUE TITLE
Crystal Phylactery can't be filled over (1/50)

### ISSUE THREAD

**Issue by Grzesiu447** [Mithion/Mana-And-Artifice#538]
**Describe the bug**
Crystal Phylactery can't be filled over (1/50).

**To Reproduce**
1. Get item Crystal Phylactery
2. Place in anywhere in inventory, kill mob (tested with vanilla sword)
3. Have magic level any

**Expected behavior**
Crystal Phylactery fills (1/50) for each kill

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.2.5.jar
 - Forge Version forge 1.18.2 40.1.54

**Comment by Mithion** [comment]
This is resolved in dev and will go out with 1.7.2.7
