### ISSUE TITLE
Crash when picking up Constructs via Carry On mod.

### ISSUE THREAD

**Issue by SheriffEllis** [Mithion/Mana-And-Artifice#539]
**Describe the bug**
When using the carry on mod to pick up a construct, and attempting to enter 3rd-person view, the client crashes.

**To Reproduce**
1. Create a wickerwood construct.
2. Pick it up using the carry on mod.
3. Press F5

**Expected behavior**
To enter 3rd-person mode without crashing.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mana and Artifice Version: 1.7.2.6
 - Forge Version: 40.1.68
 - Carry On Version: 1.18.2-1.17.0.8

**Additional context**
Crash report:
https://www.toptal.com/developers/hastebin/dezosuweko.properties

**Comment by Mithion** [comment]
I believe this is on GeckoLib's side and should be reported to them (make sure you're running latest version in case they've already fixed it) - if it turns out it's something I am doing, I'll reopen look into it then, but I'd like confirmation that it isn't something they're doing.
