### ISSUE TITLE
Manaweaver's Wand sound wont stop playing after mana runs out.

### ISSUE THREAD

**Issue by ProbablyGreen** [Mithion/Mana-And-Artifice#54]
When using the Manaweaver's Wand if you run out of mana you will immediately stop using the wand, however the sound effect associated with the wand's use will continue to play. It will not stop playing until you leave the game or use another item that is activated with a right click, such as firing a bow, drinking a potion, eating food, or using the Manaweaver's Wand again. Placing blocks did not stop the sound.

**Comment by Mithion** [comment]
This has been fixed in 1.0.6-pre1.
