### ISSUE TITLE
Crystal of Memories Gifting

### ISSUE THREAD

**Issue by Numilani** [Mithion/Mana-And-Artifice#541]
The Crystal of Memories artifact seems like an ideal candidate for a "symbiotic" item: a non-combat mage gives a CoM to a combat-heavy player, they go fill up the crystal with XP, then return the item to the mage in exchange for a favor. Unfortunately, the CoM is locked behind a Tier 2 restriction, preventing non-mages from using the item.

It would be ideal if the CoM were perhaps *crafting-locked* at Tier 2, but *usable* by anyone at any tier.

**Comment by Mithion** [comment]
Crystal of Memories has no such restrictions on use; it already works like you said.  Go hire your warrior!
