### ISSUE TITLE
NPE crash on opening Wandering Wizard GUI

### ISSUE THREAD

**Issue by UncleJaspie** [Mithion/Mana-And-Artifice#542]
**Describe the bug**
Game crashes when opening Wandering Wizard GUI

**To Reproduce**
Interact with Wandering Wizard

**Expected behavior**
No crash and GUI is able to open

**Screenshots**
none

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.7.2.6]
 - Forge Version [e.g. 40.1.60]

**Additional context**
`java.lang.NullPointerException: Cannot read field "_scrolling" because "this.list" is null
at com.mna.gui.entity.GuiWanderingWizard.m_7979_(GuiWanderingWizard.java:120) ~[mna-1.7.2.6.jar%23254!/:1.7.2.6] {re:classloading}`

**Comment by Mithion** [comment]
Can't replicate, but added a nullcheck that should fix the error from the excerpt you included.
Please provide full logs in the future, not just snippets; it really helps with debugging the issue fully.

Change will go out with 1.7.2.7.
