### ISSUE TITLE
[Feature] Allow enchantments on the Astro's Anachronous Anelace

### ISSUE THREAD

**Issue by Charismara** [Mithion/Mana-And-Artifice#543]
**Is your feature request related to a problem? Please describe.**
The Sword is cool but can't compete with enchanted tools 

**Describe the solution you'd like**
Allow enchantments on the Sword

**Additional context**
![image](https://user-images.githubusercontent.com/14293974/181722265-5238fe50-c186-4f75-9132-b5269373da44.png)

**Comment by Mithion** [comment]
It has spells instead of enchantments; that's the point.  Between transcription allowing rote spells and the 2 spell slots, it's a phenomenal weapon.
