### ISSUE TITLE
Decoy spell crashes server once in a while

### ISSUE THREAD

**Issue by flamehaze1427** [Mithion/Mana-And-Artifice#545]
Use decoy spell a few times and it will crash server with entity ticking.
[crash-2022-08-03_03.11.48-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/9249852/crash-2022-08-03_03.11.48-server.txt)

to reproduce use the spell decoy over and over till server crashes. Not tested on single player.

**Expected behavior**
make a copy of your self.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [1.7.8.2
 - Forge Version [e.g. 40.1.60]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
"at electrodynamics.common.event.PlayerHandler.compareArmor"

You'll need to report this to the Electro Dynamics folks.
