### ISSUE TITLE
Crash when trying to locate disabled / modded Structures with Rutal of Location

### ISSUE THREAD

**Issue by Charismara** [Mithion/Mana-And-Artifice#546]
**Describe the bug**
When trying to locate a vanilla Desert Pyramid with yungs better desert temples installed leads to a crash.

**To Reproduce**
1. Try to locate a Vanilla Desert Pyramid
2. wait until the server crashes

**Expected behavior**
A Message which says that no structure could be found or something like that

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.8
 - Forge Version: 40.1.68

**Additional context**
Crash Report: https://pastebin.com/ypL1MHvw

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
