### ISSUE TITLE
[BUG] Crash On Loading Into Server With Active Eldrin Altar Ritual

### ISSUE THREAD

**Issue by Dimmondback** [Mithion/Mana-And-Artifice#547]
**Describe the bug**
Dedicated servers will crash when a player loads back into the server while an Eldrin Altar ritual is active. (Keeping the ritual going can be done by having insufficient affinity while an Eldrin Conduit tries to supply affinity).

**To Reproduce**
0. Load up dedicated server with MNA latest (I used 1.7.2.8).
1. Prepare Eldrin Altar with Eldrin Conduit (I used fire) and ensure 0 affinity of Conduit type (fire in this case).
2. Ensure you have insufficient affinity and attempt to make Greater Mote (I tried fire).
3. With the ritual active, disconnect from the server.
4. Attempt to load back into the server and crash the server.

**Expected behavior**
The server does not crash and the player is able to load back in.

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.2.8
 - Forge Version: forge-40.1.52
 - Minecraft Version: 1.18.2

**Additional context**
Attaching crash report here:
[crash-2022-08-07_12.30.51-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/9277367/crash-2022-08-07_12.30.51-server.txt)

**Comment by kitsunekaze-93** [comment]
i am having the same issue, currently locked out of my minecraft world... latest backup is about a week ago...

i believe the problem is that it tries to check how much eldrin is needed to do the recipe, but the recipe is not set when loading. so where it is callign the method getPowerRequirements on the recipe, it needs to check if it HAS a recipe before calling it

`java.lang.NullPointerException: Cannot invoke "com.mna.recipes.eldrin.EldrinAltarRecipe.getPowerRequirements()" because the return value of "com.mna.blocks.tileentities.EldrinAltarTile.getCachedRecipe()" is null
	at com.mna.blocks.tileentities.EldrinAltarTile.tickLogic_consumePower(EldrinAltarTile.java:753) ~[mna-1.7.2.8.jar%2377!/:1.7.2.8]
	at com.mna.blocks.tileentities.EldrinAltarTile.Tick(EldrinAltarTile.java:228) ~[mna-1.7.2.8.jar%2377!/:1.7.2.8]
	at com.mna.blocks.artifice.EldrinAltarBlock.lambda$getTicker$0(EldrinAltarBlock.java:33) ~[mna-1.7.2.8.jar%2377!/:1.7.2.8]`

**Comment by Papaturts** [comment]
Samething happened to the server im on
[crash-2022-08-13_01.26.35-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/9330575/crash-2022-08-13_01.26.35-server.txt)

**Comment by greanthai420** [comment]
Can confirm. Same issue here.

**Comment by sandtechnology** [comment]
Have no idea why author still not handling this issue, but an fixed version for those two crash is here (You need to overwrite the original jar with zip contents here): 
[class-patch.zip](https://github.com/Mithion/Mana-And-Artifice/files/9739941/class-patch.zip)

**Comment by itsdinkd** [comment]
> 

im sure if you make a pull request he will accept, maybe.

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
