### ISSUE TITLE
[BUG] (Minor) Projectile Gust Does Nothing Without Modifiers

### ISSUE THREAD

**Issue by Dimmondback** [Mithion/Mana-And-Artifice#549]
**Describe the bug**
Upon creation, the Gust spell with Projectile shape has Radius 0 but magnitude 1, meaning it is not able to interact with the environment without adding the Radius modifier and increasing it to 1 or more.

**To Reproduce**
1. Create a spell with Gust component and Projectile shape
2. Open spell's details menu (CTRL+RMB)
3. See Radius is set to 0
4. Try to break grass, leaves, flowers, snow, etc with it and observe no environmental changes.

**Expected behavior**
Some environmental changes, even if it is a single block area (without the need for using Radius upgrade).

**Screenshots**
![image](https://user-images.githubusercontent.com/7410101/184070800-fe1a7cfc-b75e-4f10-bc82-a8a66318c21a.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.8
 - Forge Version: 40.1.52
 - Minecraft Version: 1.18.2

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
