### ISSUE TITLE
Crash during ritual

### ISSUE THREAD

**Issue by Schmille** [Mithion/Mana-And-Artifice#55]
The crash occurred shortly after starting the Ritual of Summoning.
I was using version 1.0.5-pre3 on a dedicated server.

Full log: [https://pastebin.com/5zB1uZ62](https://pastebin.com/5zB1uZ62)

**Comment by Mithion** [comment]
Can you confirm whether or not the player focus was attuned to a player?  Was the player online at the time?

**Comment by Schmille** [comment]
The player was online at the time and had tried to attune the focus to him, however the item description did not display the his name. It just said “Attuned to”.
The ritual starts up alright, but causes the crash if it is left running for 5 - 10 seconds or so.

**Comment by Mithion** [comment]
Thanks for the update - glad it worked that time around.

Player charms seem to need to be "attuned" twice before it actually sticks, not sure why yet.  I've fixed the crashing bug in version 1.0.6-pre1 with a non-attuned charm.  The ritual will simply fail to start in that instance.

**Comment by Mithion** [comment]
Player charms now properly attune when right clicked the first time - there is no need to do it twice.
This has been fixed in 1.0.6-pre1
