### ISSUE TITLE
Wellspring Deletion does not work.

### ISSUE THREAD

**Issue by QuantumZizo** [Mithion/Mana-And-Artifice#550]
**Describe the bug**
Trying to remove Wellsprings with /mna wellspring delete ~ ~ ~ results in an error message saying "Wellspring could not be deleted. Likely one doesn't exist at the specified location".

**To Reproduce**
1. Find a wellspring or create one using /mna wellspring create ~ ~ ~.
2. Stand inside the wellspring and use /mna wellspring delete ~ ~ ~.

**Expected behavior**
Expected the wellspring to be deleted without displaying error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/91835426/184453160-d07e4232-b866-463c-8169-662cd15e8f86.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.8
 - Forge Version: 40.1.73

**Additional context**
Other mods include Cracker's Witherstorm Mod, Curios API, GeckoLib, and JEI.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
