### ISSUE TITLE
Construct Mana-Weaving/ Auto-Manaweave projectors

### ISSUE THREAD

**Issue by CTH999** [Mithion/Mana-And-Artifice#552]
I have found it frustrating when I am binding spells to my hellfire staff. The runes are just repeats, and sure, I can use a manaweave projector, but that still is kinda slow, and not as neat. So, I have a solution!

So, my idea is to have it so constructs can do manaweaves. You could use a button that does something that a construct detects, and then it goes to do the manaweaving.

A simpler, but not as interesting option is to have manaweave projecters activate with redstone. But, then we can't have our constructs doing manaweaving!

**Comment by Mithion** [comment]
Manaweave bottles were the solution to this problem
