### ISSUE TITLE
Weird Server Log Issues

### ISSUE THREAD

**Issue by AzrouStone** [Mithion/Mana-And-Artifice#554]
**Describe the bug**
Basically as I run this on a server, the server repeatedly outputs a warning that a config file was changed/incorrect which on its own isn't too bad but eventually begins lagging my server and even prevents any input commands such as stopping the server.

**To Reproduce**
1. Put the mod into a server mod folder
2. Load the server and let it run
3. wait for about 5 to 30 minutes
4. See error spamming in server console/logs

**Expected behavior**
[Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file C:\serverconfig\mna-spells.toml is not correct. Correcting
[Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file C:\serverconfig\mna-spells.toml is not correct. Correcting
[Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file C:\serverconfig\mna-spells.toml is not correct. Correcting
...

**Version Information (please complete the following information):**
 - Mod Version: [mna-1.7.2.8]
 - Forge Version [forge-40.1.70]

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.9 for 1.20.1

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
