### ISSUE TITLE
ComputerCraft turtles annihilated by touch-break spell.

### ISSUE THREAD

**Issue by dan-1am** [Mithion/Mana-And-Artifice#555]
**Describe the bug**
Turtles and computers from ComputerCraft tweaked (CC: Tweaked) mod placed in world as blocks are destroyed by touch-break spell without producing corresponding item. ComputerCraft modem cables do not have this bug.

**To Reproduce**
1. Place turtle on the ground with right click.
2. Use spell "touch-break" on placed turtle (with shift to skip turtle interface).
3. Observe disappeared turtle, no item on the ground and your clear inventory.

**Expected behavior**
Turtle should appear on the ground or in your inventory as item.

**Screenshots**
Not needed.

**Version Information:**
 - Mana and artifice - 1.7.2.8 for minecraft 1.18.2
 - Forge Version - 40.1.57
 - CC: Tweaked - 1.100.9

**Additional context**
No other large mod installed. Here is full list:
cc-tweaked-1.18.2-1.100.9.jar
configured-1.5.3-1.18.2.jar
corpse-1.18.2-1.0.1.jar
curios-forge-1.18.2-5.0.7.1.jar
ferritecore-1.18-4.2.1-forge.jar
geckolib-forge-1.18-3.0.34.jar
jei-1.18.2-9.7.1.232.jar
lazydfu-1.0-1.18+forge.jar
mna-1.18-1.7.2.8.jar
rubidium-1.18.2-0.5.3a.jar
simpleplanes-1.18.2-4.13.4.jar
starlight-1.18.2-1.0.2+forge.546ae87.jar
Xaeros_Minimap_22.13.0_Forge_1.18.2.jar
XaerosWorldMap_1.26.2_Forge_1.18.2.jar

Edit: added "on the ground" in expected behavior.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.

**Comment by dan-1am** [comment]
I strongly support your decision. I, personally, have long forgotten about this issue and this game world. The risk of someone else encountering this bug in already old 1.18 version is low enough. As well as the bug's severity. New game versions are far more important. I want to use this opportunity to say: Thank you for your great mod!
