### ISSUE TITLE
Modifying Seer Stone charms crash the server/game while sentry is firing.

### ISSUE THREAD

**Issue by amoooooo** [Mithion/Mana-And-Artifice#556]
**Describe the bug**
Removing a whitelisted player charm from a seer stone while the sentry is targeting the player results in a crash

**To Reproduce**
Set up sentry,
Add player charm to whitelist
While shooting, remove charm

**Expected behavior**
Sentry stops targetting them.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.8
 - Forge Version 40.1.73

**Additional context**
https://hastebin.com/subovudivo.pl

**Comment by amoooooo** [comment]
update: this happens with elemental sentries even without modifying them they just randomly hang the server when the entity theyre targetting dies to another sentry.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
