### ISSUE TITLE
Breaking a manaweave cache with a break spell results in an additional set of loot

### ISSUE THREAD

**Issue by tdphillips** [Mithion/Mana-And-Artifice#557]
**Describe the bug**

**To Reproduce**
1. Have a wand and a break spell (touch + break)
2. Find a manaweave cache that you are at the correct level to open
3. Open the cache and loot everything out of it
4. Break the cache with your spell
4. See a new set of loot drop in-world

**Expected behavior**
As breaking a cache with a pickaxe seems to be a bit buggy, I suspect the block should not be broken with a break spell either.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.8
 - Forge Version 40.1.68

**Additional context**

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
