### ISSUE TITLE
[Suggestion] An idiomatic approach to storage

### ISSUE THREAD

**Issue by Shadowex3** [Mithion/Mana-And-Artifice#558]
**Is your feature request related to a problem? Please describe.**
By nature Minecraft and mods have a lot of stuff for players to make, store, and use. In particular progression often involves multi-step processes and multi-tiered recipes. In "Tech" mods this is mitigated by their being based around piping systems by default, and often including some kind of advanced inventory system long term (like RS or ID).

In "Magic" mods on the other hand gameplay revolves around lots of physical in-world actions by the player. MNA's Rituals, Ars Nouveau's Enchanting and Imbuing system, Botania's... Botania. So you need lots of specific things, in lots of specific places.

The problem is that RS, ID, and the rest just don't fit well and as far as I know there's no real magic-centric approach to mid and late game storage management. The point where chests start getting too crowded and Storage Drawers isn't sufficient (and reams your framerate).

**Describe the solution you'd like**
A thematically fitting system for centralized item management and storage with multiple access points. I think for MNA the most fitting would be a block or spell for opening searchable access to inventories in the room, and a block constructs can be assigned to for "ordering" items from remote locations. Higher tiered constructs could get more items at once, have more repositories assigned, handle simple intermediary steps like compacting/uncompacting (ingots vs blocks), etc.

If you wanted to go overboard you could even make a spell or ritual for in-the-wild and cross-dimensional summoning.

**Describe alternatives you've considered**
I've thought about an army of constructs but even leaving aside system resource usage and potential pathfinding issues (plus crowdedness) I don't think they way they work is suited to this. Plus that approach requires basically keeping enough duplicate everything on hand to have a supply wherever you might want it.

Storage Drawers works early on but it's always had performance issues and even using 4x4s you need a giant wall of them for each ONE item, plus like with chests it's still tied to a single physical point of access.

**Comment by Mithion** [comment]
Occultism handles this perfectly, and constructs can interact with its wormholes as well.
