### ISSUE TITLE
Issues with Spectral Elytra

### ISSUE THREAD

**Issue by Mourdida** [Mithion/Mana-And-Artifice#56]
1.0.5-pre3

1. Spectral Elytra can't be equipped similarly to other chestplates (or to vanilla Elytra) by right-clicking them in the hotbar, nor by shift-left-clicking Spectral Elytra in the inventory.

2. While flying with Spectral Elytra, mana decreases and increases irregularly.
2. While flying with Spectral Elytra, mana regeneration is not modified by Hunger/Saturation level.

3. During Creative flight, wearing Spectral Elytra decreases your speed while sneaking : sneaking while flying in Creative mode with Spectral Elytra makes your descending flight slower than without them.

I didn't know if I should have opened an issue for each of these points since they were short and easy to describe.

**Comment by Mithion** [comment]
The spectral elytra has been fixed in 1.0.7.1
