### ISSUE TITLE
Sided inventories don't seem to be working on runescribing table for patterns

### ISSUE THREAD

**Issue by djmcgill** [Mithion/Mana-And-Artifice#562]
**Describe the bug**
Apologies in advance if this is just a PEBKAC error. 

I'm trying to automate runscribing, and my construct just does not seem to be able to place a rune pattern into the slot on the runescribing table. The note on this in the codex says it should accept patterns from all sides.
However, when I try with the construct it always just says "I wasn't able to put Runescribing Recipe into the Runescribing Table. Sorry boss."
Additionally I can't do it with other mod automation, in this case LaserIO. It works fine with other items, putting the hammer, chisel, and blank runes into the right slots in the table no problem it's just the patterns that don't seem to insert into the table.

**To Reproduce**
1. Get a runescribing recipe, in this case it's just Rune Pattern: Fire
2. Put in chest
3. Create lodestar with "take item from container" with the marking rune specifying the chest and for the filter I just used a blacklist with some random other item. Now the construct has picked up the rune pattern.
4. Add "place item into container" next, specifying the runescribing table with the rune of marking. I've tried all sides.
5. Observe as the construct picks up the item, then stops. If you use the bell of bidding on diagnostics you see the above message
6. Try with other mod automation if you like, I tried vanilla hoppers too, nothing.

**Expected behavior**
The runescribing pattern should go into the top-right slot in the runscribing table

**Screenshots**
![image](https://user-images.githubusercontent.com/1290757/186547782-975ed1bc-2822-4634-bb7d-af3a4816a43f.png)
![image](https://user-images.githubusercontent.com/1290757/186547802-30ae8e14-1ca2-4ff8-baa2-b7b99c8e76bf.png)
![image](https://user-images.githubusercontent.com/1290757/186547848-2d7b034c-3eac-4a3b-954e-79908b424049.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.8
 - Pack: Magitech, Mana and artifice  3.1a
 - Forge Version: 40.1.73

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
