### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by 78codemonkey** [Mithion/Mana-And-Artifice#563]
**Is your feature request related to a problem? Please describe.**
pmmo/pmmo nbt, won't level magic nor is items restricted to magic level requirements

**Describe the solution you'd like**
add compat for pmmo or pmmo nbt :

**Describe alternatives you've considered**
is request for mana and artifice, magic level requirements on items, blocks and spells, mana bonus with wands, staffs, books, and worn, magic xp gain with work stations used, golem creation, spell creation, and spell/staff use

**Additional context**

**Comment by Mithion** [comment]
This would fall under the realm of an addon, for which M&A provides a feature-rich API.
