### ISSUE TITLE
[Suggestion] Add Deepslate Vinteum Ore and Raw Vinteum Ore

### ISSUE THREAD

**Issue by OnTarasMind** [Mithion/Mana-And-Artifice#564]
**Is your feature request related to a problem? Please describe.**
Only a minor one, but with recent updates to Minecraft, every ore no longer drops the block itself(silk touch notwithstanding), and Vinteum doesn't fit, making it feel a little off. Another small issue is that there's no deepslate variant for the ore, either.

**Describe the solution you'd like**
I'd personally like to see Raw Vinteum/something akin to it, since it is already an ore that is smelted.

**Describe alternatives you've considered**
Alternatively, the ore could just drop the dust, but I can imagine that probably won't happen.

**Additional context**
If wanted, I can provide textures for the deepslate ore and Raw Vinteum

Raw Vinteum

![image](https://user-images.githubusercontent.com/49374027/189308107-9a4bdbea-a435-4b46-8bca-262c40183d27.png)

Deepslate Vinteum Ore

![image](https://user-images.githubusercontent.com/49374027/189307507-fabedd03-153f-4578-b917-b359694e1b02.png)

Forgive me for the potentially poor textures, this isn't my usual style, since I usually work in the style of the Unity resource pack. These are primarily just to provide examples for how they could look.

**Comment by Mithion** [comment]
Raw ore has been added.
