### ISSUE TITLE
Adding own rituals

### ISSUE THREAD

**Issue by MrFobosYT** [Mithion/Mana-And-Artifice#565]
**Is your feature request related to a problem? Please describe.**
I am creating a mod pack for version 1.18.2. I saw that there are rituals in your mod and I tried to add my own, but he writes me an error (Could not find a registered handler for this ritual recipes)

**Describe the solution you'd like**
Can you tell me if it is possible to solve this problem without getting into the mod code ?

**Additional context**
![Capture2](https://user-images.githubusercontent.com/73641170/189474414-05d34ccc-c3bf-4f56-9af2-2fb80cb375a6.PNG) ![Capture](https://user-images.githubusercontent.com/73641170/189474415-b7ebc10d-abd1-4242-9de7-f7b1c0cbdad5.PNG)

**Comment by xiakkto** [comment]
1.16.5 is also unable to create its own rituals...

**Comment by Mithion** [comment]
Rituals require a handler to be registered through the API; or rather they used to.  This will be the case in 1.16.5, as it is not getting any further updates.

In 1.18.2, with the release of 2.0.x, rituals now have a "command" property you can set, which will run the command when the ritual completes.  This can replace a handler for simple things.  If you're using "createsItem" that is only for a gui representation for things like the codex and JEI.

An example:

{
    "type": "mna:ritual",
    "tier": 1,
    "pattern":
    [
        [ 0, 2, 0 ],
        [ 1,-1, 3 ],
        [ 0, 4, 0 ]
    ],
    "reagents":
    [
        "   ",
        "W W",
        "   "
    ],
    "keys":
    {
        "W": 
        { 
            "item": "wool",
            "optional": false,
            "consume": false
        }
    },
    "parameters":
    {
        "innerColor": "0xFFCC00",
        "outerColor": "0xFF8A00",
        "beamColor": "0xffd000"
    },
    "command": "time set noon"
}
