### ISSUE TITLE
[Suggestion] Making motes easier to create after obtaining them

### ISSUE THREAD

**Issue by ronondex2009** [Mithion/Mana-And-Artifice#566]
**Is your feature request related to a problem? Please describe.**
Many of the apparatus in Mana and Artifice require eldrin power to function, and some of the recipies require motes to craft, such as how a magic mote is used in the mana crystal recipe. These motes are often difficult and time consuming to create, needing special setups in order to function. For me, this wouldn't be much of a problem if the motes were only used occasionally.

**Describe the solution you'd like**
Once an eldrin wellspring is captured by a conduit, it should be possible to materialize the eldrin power _into_ a mote. Of course, this process should take more eldrin power than a fume filter could produce in order to prevent players from duplicating motes.

**Describe alternatives you've considered**
- "putting" affinity into a jar, once enough affinity is made, could be extracted as a mote via a ritual, table, etc.
- Trading for motes
- Condensing a large amount of a corresponding resource into a mote

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue with motes being craftable via the Eldrin Altar later on.
