### ISSUE TITLE
Example Dimension/Biome Blacklist For Spells

### ISSUE THREAD

**Issue by DistantDig** [Mithion/Mana-And-Artifice#567]
**Is your feature request related to a problem? Please describe.**
We've been trying to blacklist certain spells in certain biomes and dimensions, and we seem to be unable to get any of them to work. I saw in the change log that the way these blacklists work had recently changed, but there is no example or good explanation on how they work. I tried to reach out to the discord, twice, and both times I got no response.

**Describe the solution you'd like**
Perhaps in the config you can put an example for dimensions and biomes, since i cannot for the life of me figure it out.

**Additional context**
Specifically I've tried to put "minecraft:overworld" and it doesn't seem to work. I've also tried several biomes, specifically ocean biomes and those also don't work. An quick example for what to put in the config would be greatly appreciated.

**Comment by Mithion** [comment]
It's likely related to the configs resetting bug.

**Comment by Mithion** [comment]
The config resetting bug has been fixed in 3.0.0.9 (1.20.1).
A sample blacklist value for spells in the nether and end:

["minecraft:the_nether", "minecraft:the_end"]
