### ISSUE TITLE
Issues with warding

### ISSUE THREAD

**Issue by Mourdida** [Mithion/Mana-And-Artifice#57]
1.0.5-pre3
I know some of these issues have been discussed in Discord some time ago and warding is written as a work in progress in the in-game guide. However there are a few issues I wanted to raise :

1. Warded blocks can't be currently unwarded

1. Warded blocks can't be destroyed by the player who warded it ; however, explosions and fire destroy warded blocks, and warded falling blocks (Sand, Gravel...) are not warded anymore after falling.

1. Warding currently wards a block position (this may be a feature?) : warding a block, then destroying it (for ex. by fire) and placing a new block in the same position wards the new block. This doesn't sound normal to me.

1. Right-clicking a warded block with another block visually uses the item in the inventory (for example, if you have a block of dirt in your hand and you place it on a warded block, the Dirt will disappear from your inventory. This is only a visual bug : if you right-click somewhere else with the disappeared Dirt, it will still be placed, even if it seems to not be in your inventory).

1. Warding multiblocks (doors, beds...) causes weird behaviours, because only one block of the multiblock structure gets warded. For example, right-clicking a warded side of a door doesn't open the warded side but the non-warded side gets both open and closed at the same time. On the contrary, right-clicking the non-warded side opens/closes the whole door normally. Similarly, doors/beds can be destroyed by breaking the non-warded side, but if you break the warded side, the non-warded side is both there and broken. This is the most severe bug I have found with warding, and there may be other blocks with similar behaviours.

**Comment by Mithion** [comment]
Thanks for this list - warded blocks are very much incomplete as stated, but this will lead to some good test cases when I finish them off.

**Comment by Mithion** [comment]
Warding has been removed from the mod.
