### ISSUE TITLE
Tier 2 spell ritual is asking me for tier 3 manaweaving pattern

### ISSUE THREAD

**Issue by notchriss** [Mithion/Mana-And-Artifice#571]
**Describe the bug**
I'm trying to create a tier 2 spell (self + bind wounds, no modifiers), 35 complexity for the "craft 35 complexity spell" milestone, however the ritual is asking me to draw a tier 3 pattern that's not yet unlocked. 

**To Reproduce**
Craft a self + bind wounds, no modifiers spell using ritual of arcana while being in tier 2.

**Expected behavior**
a) self+bind wounds should be tier 3
b) hourglass pattern should be tier 2
c) self+bind wounds should not require hourglass pattern

**Screenshots**
![maa](https://user-images.githubusercontent.com/8706925/196959931-a0694e02-bc1f-4414-94cf-ee7263e61310.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.34

**Comment by Mithion** [comment]
This was fixed in M&A version 2.0.0.x
