### ISSUE TITLE
what does reedfeather charm do

### ISSUE THREAD

**Issue by chrisi1504** [Mithion/Mana-And-Artifice#572]
i need help finding out what the reedfeather talisman does (im playing on 1.18.2)

**Comment by chrisi1504** [comment]
![2022-10-22_16 45 46](https://user-images.githubusercontent.com/116447332/197345551-81ce113b-bc36-4987-a49f-1d0bba1060f8.png)

**Comment by Mithion** [comment]
Under "feather charms" it says that the reedfeather charm will prevent you from drowning by breaking and refilling your breath meter one time.
