### ISSUE TITLE
[1.18,2] Changing values in "serverconfig\mna-spells.toml" crashes the game on world startup

### ISSUE THREAD

**Issue by bogdano1** [Mithion/Mana-And-Artifice#573]
**Describe the bug**
   I have changed all DELAY values to allow a maximum of 30 and a step complexity of 0.1 in the file "mna-spells.toml" located in the serverconfig. Then, when I tried to load that world the game froze in place.
By removing the file, it loads again as it did before changing the values.

**To Reproduce**
1. Open the file saves\<insert world name here>\serverconfig\mna-spells.toml
2. Change all the "maximum = 3.0" for "maximum = 30.0" and "step_complexity = 0.5" for "step_complexity = 0.1" under ["mna:components/<some component>".DELAY]
3. Open Minecraft
4. Launch <insert world name here>
5. The game Freezes and won't load

**Expected behavior**
The world loads properly.

**Version Information (please complete the following information):**
 - Mod Version: [1.18.2 - 1.7.2.8]
 - Forge Version [40.1.84]

**Comment by bogdano1** [comment]
here is the file I used

https://drive.google.com/file/d/1evfB3fHNkYJQ1jPv5L3CPf-ymvu5mlgC/view?usp=sharing

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
