### ISSUE TITLE
[Bug] Crash on Placing Construct Pieces Onto Armor Stand With GeckoLib Update

### ISSUE THREAD

**Issue by DelviousCrafts** [Mithion/Mana-And-Artifice#575]
**Describe the bug**
Having a construct in the world, or placing construct pieces on an armor stand causes GeckoLib to create a rendering crash on single-player and server with GeckoLib's new update of the rendering via lazy value calculation. This was not an issue up to version GeckoLib 3.0.46. (also a rendering crash was created with just salmon loaded after an armor stand was placed, but that happened in a world with a lot of other mods installed and I'm not certain that's an M&A issue as it was never tested in a pure M&A test world like the constructs were. Adding it to the report just in case.) 

This does not occur placing any other items onto the armor stand. 

**To Reproduce**
1. Install or update GeckoLib to version 3.0.48+
2. Place down an armor stand.
3. Get a construct part of any kind
4. Right-click the construct part onto the armor stand to begin setting up a construct
5. Crash

**Expected behavior**
For you to be able to place construct pieces on the armor stand to make a construct without crashing.

**Screenshots**
N/A (also impossible due to immediate crash)

**Version Information (please complete the following information):**
 - Minecraft Version 1.18.2
 - Mod Version: 1.7.2.8
 - Forge Version 40.1.84
 - Curios API (forge) version 5.0.7.1
 - GeckoLib version 3.0.48+

**Additional context**
[Link](https://pastebin.com/iJ2AXR3C) to crash report on Pastebin

[Link](https://pastebin.com/EMXVSpcP) to latest.log file on pastebin

**Comment by DouglasJack** [comment]
I am also experiencing this issue, I had to restore to a previous backup as this prevented all players within render distance to crash.

**Comment by Keter01** [comment]
I'm having the same issue. If you're on a server you can kill the entity through the server console (the coordinates are displayed in the crash log). That way you don't need to restore a backup and potentially lose hours of work if the backup is old.

**Comment by Shibva** [comment]
its far more than that, the construct even EXISTING crashes the world, this is a critical bug and it was a result of a method being removed from what I can see

**Comment by Shibva** [comment]
https://github.com/bernie-g/geckolib/issues/324

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/200253995-d88ea647-70dc-430b-a585-0ac88acbc29d.png)


Im guessing something about this done it, whatever they did

**Comment by Thorandan** [comment]
https://discord.com/channels/398610095585624074/746849790515609780/1042432410735890442

**Comment by Shibva** [comment]
Sorry could you post that message in here

**Comment by LunafeyLazuli** [comment]
Same issue with my server as well

**Comment by LunafeyLazuli** [comment]
Does anyone have any updates about this crash?

**Comment by ghostnek0** [comment]
From what I kown the issue is still happening if just tried it this morning and still crashed

**Comment by drakray** [comment]
Using GeckoLib 57 and the new MNA 1.7.2.10 and I can put construct pieces on an armor stand without crashing, what versions are you using @ghostnek0 ?

**Comment by ghostnek0** [comment]
56 and MNA 1.7.2.8 might just need to update it my bad see if it works then hopefully

**Comment by TianchengWu4810-tamu** [comment]
Does the problem solved after updating?

**Comment by drakray** [comment]
> Does the problem solved after updating?

yes it does, at least I didn't crash since I updated

**Comment by DelviousCrafts** [comment]
Yes, this particular issue appears to be resolved. Thank you!

**Comment by ManlyManManly** [comment]
I fixed it by going to the mods file and deleting the entities
