### ISSUE TITLE
Wellspring Prism Multiblock Malfunction

### ISSUE THREAD

**Issue by Hyfro-Cyrup** [Mithion/Mana-And-Artifice#576]
I'm using mana-and-artifice-1.5.1.7 for Minecraft version 1.16.5. I am unable to construct a Wellspring prism to capture Eldrin Wellspring energy. What seems to be happening is that the stairs and slabs are not registering for multiblock structure completion, and as such the structure thinks it is incomplete. I tried both chimerite sandstone and chimerite stone. Pictures show before and after placing a stair. Note the structure stays at 58/70. 

1. Locate Eldrin Wellspring
2. Construct Wellspring Prism
3. Watch the stairs and slabs not add to progression. 
4. Witness wellspring not working

Expected behavior: 
The count should go up and the wellspring should be visible as the prism is complete. 

![2022-11-06_01 56 42](https://user-images.githubusercontent.com/108480855/200160441-f99cc98b-8124-4d81-a05c-f830a6f4a75f.png)
![2022-11-06_01 56 46](https://user-images.githubusercontent.com/108480855/200160455-aec78963-4d1d-4321-81a9-16db1edb59d5.png)
Extra picture to show it actually is a wellspring:
![2022-11-06_02 04 33](https://user-images.githubusercontent.com/108480855/200160578-0dc1f62d-c583-478c-9306-19968a19dc16.png)

Version Information: 
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.35

Modlist (though nothing should be interfering, I would think):
[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
[Immersive Engineering (by BluSunrize)](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[CaveBiomeAPI [Forge] (by blackgear27)](https://www.curseforge.com/minecraft/mc-mods/cavebiomeapi)
[Mana and Artifice (by AWildCanadianEh)](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[Pollen (by moonflowerteam)](https://www.curseforge.com/minecraft/mc-mods/pollen)
[Ore Excavation (by Funwayguy)](https://www.curseforge.com/minecraft/mc-mods/ore-excavation)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Drawers Tooltip (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/drawers-tooltip)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Comforts (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Pam's HarvestCraft 2 - Trees (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Puzzles Lib (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Visual Workbench (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Tinkers Construct (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Waila Harvestability (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/waila-harvestability)
[Sneaky Tree Growing [Forge] (by ConmineLP)](https://www.curseforge.com/minecraft/mc-mods/sneaky-tree-growing-forge)
[More Overlays Updated (by RiDGo8)](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated)
[Shield Parry (by Drullkus)](https://www.curseforge.com/minecraft/mc-mods/parry)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Pam's HarvestCraft 2 - Crops (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Mantle (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/mantle)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Caves & Cliffs Backport (by blackgear27)](https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Hwyla (by TehNut)](https://www.curseforge.com/minecraft/mc-mods/hwyla)
[Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended)

**Comment by Hyfro-Cyrup** [comment]
Update: recreated the issue in a bare-bones modpack

**Comment by Pitagoraaa** [comment]
I think this multi-block will only work with stair and slab, not "Chimerite Stone" or "Chimerite Sandstone", but only with "Arcane Stone" or "Arcane Sandstone". Please try and change the appropriate locations.

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
