### ISSUE TITLE
[1.16.5] Cannot activate Ritual of Arcana

### ISSUE THREAD

**Issue by SleekFreak** [Mithion/Mana-And-Artifice#579]
My Minecraft server runs version 1.5.1.6 and when I add the Purified Vinteum Dust to the Spell Recipe the animation does not occur, and the Purified Vinteum Dust is not consumed. I had assumed that it was a confliction with the mod pack that was also installed (specifically the [Shattered Ring mod pack on Forge](https://www.curseforge.com/minecraft/modpacks/shattered-ring)) however I don't think that there would be any problem with the mods, but I wanted to make sure that it wasn't the case. 

https://user-images.githubusercontent.com/93061463/201244070-2f72a9a2-75bf-4906-9b06-f26bde1beb2b.mp4

This is what happened in Creative Mode, I don't believe that being in Survival Mode would change the outcome, but I would try again if something was found.

This is an old version of the mod, so I'm not surprised if there are very specific issue that the developer does not want to work on at the moment with the current version being the main focus. I have seen one video addressing the specific version being played ([This overview by Lorthorn](https://www.youtube.com/watch?v=xEyUtDLi-CQ)) however it was not addressed in the video nor any of the comments talk about it. I am using this Github report before entering the Discord to ask about the problem but if this issue has been solved in a discord thread I'd be interested to join the Discord and read the solution. 

Thank you for your time and effort to anyone who has read this whole report, your work is extremely helpful.

**Comment by SleekFreak** [comment]
UPDATE: I did this with the mod alone with only the dependencies and it still didn't work. Is this an issue with 1.16.5?

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
