### ISSUE TITLE
Wooden Construct Basic Torso and Basic Legs incompability

### ISSUE THREAD

**Issue by Torfbisray** [Mithion/Mana-And-Artifice#584]
**Describe the bug**
When trying to craft the wooden legs, they have the same items as the torso.
But the manaweaving patterns match.
So that when trying to craft wooden basic legs a wooden basic torso is crafted beforehand.

They both have Adamas and then Quadratum, after which entering another Adamas to craft the legs is impossible.
since the manaweaving altar will apply the crafting recipe of the torso.

**To Reproduce**
1. Put the items 3 Wood and 2 Vinteum Dust into the Manaweaving altar
2. Cast the manaweaving patterns Adamas and Quadratum
3. Torso is beign created without option to craft legs with another Adamas instead

**Expected behavior**
The crafting recipes need to be adjusted so that the torso is beign crafted differently and the
recipes won't conflict. I suggest using a "Construct Frame: Torso" since they are available at that stage.

**Screenshots**
![Construct incompability](https://user-images.githubusercontent.com/97400591/204087802-ac4f6ead-15c7-4bd3-b58d-179c92725459.png)

**Version Information (please complete the following information):**
 - Mod Version: [1.7.2.8]
 - Forge Version [40.1.85]

Sorry if this bug is a duplicate, but I could not find this problem on either the discord or here on git. So sorry if I am beign blind.

**Comment by KaratekHD** [comment]
As a a workaround you can draw the pattern first and place the items in later.

**Comment by Torfbisray** [comment]
Thank you very much for the workaround!

**Comment by Mithion** [comment]
This was resolved with the release of version 2.0.x
