### ISSUE TITLE
Constructs will crash game.

### ISSUE THREAD

**Issue by Coderchris842** [Mithion/Mana-And-Artifice#585]
**Describe the bug**
I have a video of it that describes the bug clearly
**To Reproduce**
1. Get item 'Wickerwood head'
2. Use on 'Armor stand'

**Expected behavior**
The wickerwood head is placed on the armor stand

**Screenshots**
Screenshot

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.8
 - Forge Version 40.1.85

Video to big, heres a link to it in .zip.7z.zip form(I know it's weird how I compressed it).
https://drive.google.com/file/d/1HN68QxWbvAM_f-EaedTfV7xcImjeXaHP/view?usp=sharing

**Comment by Coderchris842** [comment]
https://drive.google.com/file/d/1HN68QxWbvAM_f-EaedTfV7xcImjeXaHP/view?usp=sharing

**Comment by Filijusanshu** [comment]
I have the same issue. Hope it get fix soon because I really enjoyed the mod from what I've seen.

**Comment by Seagoddess** [comment]
If you are wondering, the crash is a rendering issue caused by geckolib. Which has now caused our server to be in peril again due to it also being involved in occultism. Now we'll have to research anytime we want to place ANYTHING from either mod down.

**Comment by Shibva** [comment]
on another note, this issue is either a duplicate or an extension of #575

**Comment by Mithion** [comment]
Issue was on GeckoLib end, they updated and resolved it.
