### ISSUE TITLE
Rendering Block Entity crash

### ISSUE THREAD

**Issue by diablo7806** [Mithion/Mana-And-Artifice#588]
I've been playing a mod pack with Mana and Artifice for about a month or so, and out of nowhere, Minecraft crashes any time I load any MnA blocks within render distance. I've tried updating MnA in the mod pack to no avail.

Attached relevant section of the console log.
[Console Log.txt](https://github.com/Mithion/Mana-And-Artifice/files/10415762/Console.Log.txt)

**Comment by Mithion** [comment]
This was an issue with GeckoLib, they updated and resolved it.
