### ISSUE TITLE
Automation fails after chunk reload 1.18.2, Forge 40.1.80

### ISSUE THREAD

**Issue by Nihilhalla** [Mithion/Mana-And-Artifice#589]
**Describe the bug**
Possible duplicate of #312,
Issue is that automation constructs interacting with mod blocks seem to forget they can path to a target block after the chunk unloads.
Present workaround is to rebind construct to lodestar so as to refresh instructions.

**To Reproduce**
1. Make a construct, in my case with rocket legs
2. Tell the construct to interact with a block or path to a block as part of it's instructions.
3. Log off of server or otherwise unload chunk,
4. Reload chunk by logging back in/running back.
5. See that constructs are not functioning.

**Expected behavior**
Constructs simply restart lodestar instructions upon chunk reload, and continue automation.

**Screenshots**
None available at this time.

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.10
 - Forge Version 40.1.80

**Additional context**
Mod list is available at https://hastebin.com/sayafeseyi.rb

If you require additional information or log files please don't hesitate to message me, I'm also in your discord, Nihilhalla is the username.

**Comment by Mithion** [comment]
Later versions of the mod resolve this issue.
