### ISSUE TITLE
The Allfather's Will can be dropped

### ISSUE THREAD

**Issue by Red1004** [Mithion/Mana-And-Artifice#591]
So by dropping the will before the axe comes back, you can keep the will (does nothing)

1. Get Allfather's Axe
2. Throw the axe
3. Open inventory
4. Grab the will and throw it out of your inventory with mouse click
5. Wait for Allfather's Axe to return
6. Pick up the will that should now be on the ground

**Expected behavior**
I expected the Will to not be droppable, as it isn't through just Q

**Version Information:**
 - Mod Version: 1.7.2.10
 - Forge Version: 40.1.92

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
