### ISSUE TITLE
Crafting any items at normal crafting station not counting towards tier progress

### ISSUE THREAD

**Issue by cdaragorn** [Mithion/Mana-And-Artifice#592]
**Describe the bug**
The Occulus is not showing progress for some crafted items. I've already checked and made sure I used a standard Minecraft crafting table to create them but it has not counted basically anything that I have to craft as progress towards the next tier. Specifically crafting a delegation station, inscription table, practitioners pouch and manaweaving altar all failed to count for me.

**To Reproduce**
1. Craft any of the following items listed in description at standard crafting table when at tier 1
2. Check Occulus progress
3. That crafting item still shows red

**Expected behavior**
Item should show green showing you've accomplished that task

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.10
 - Forge Version 40.2.0

**Additional context**
We discovered that using Tinkers Construct crafting table actually worked and counted it just fine. For some reason in this version at least the standard minecraft crafting table doesn't count but TC's does.

**Comment by Mithion** [comment]
2.0.0.27 has released, which has the rework of progression resolving this issue.
