### ISSUE TITLE
[Bug][1.18.2][1.7.2.10]Unexpected interaction with Transitory Tunnel and offhanding blocks

### ISSUE THREAD

**Issue by Rosethorns** [Mithion/Mana-And-Artifice#594]
**Describe the bug**
When using the Transitory Tunnel and while the offhand slot is filled with a _placeable_ (like a block) the offhand _placeable_ is placed in the position of the right clicked tile. This appears as replacing the center block of the 3x3 area the tunnel creates, deleting the block that used to be in that position.

**To Reproduce**
1. Equip a block or other placeable to the offhand slot
2. Use the Transitory Tunnel item on a surface

**Expected behavior**
That the offhand item does not replace the block clicked when using the Transitory Tunnel

**Screenshots**
![image](https://user-images.githubusercontent.com/2171914/217945981-48b20015-979c-468d-bc5f-a68b58cc2936.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.10
 - Forge Version: 40.2.0

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
