### ISSUE TITLE
Entangle visual and sound effects sometimes overrule others in the same spell after upgrading to 50% cooldown reduction

### ISSUE THREAD

**Issue by MatalMoore** [Mithion/Mana-And-Artifice#595]
**Describe the bug**
After upgrading the Entangle spell effect to 50% cooldown reduction, its earth-element sound effects and visual effects overrule those of some other spell effects, such as Frost Damage and Fire Damage, but not Lightning Damage, in the same spell, but did not before upgrading. In particular the Beam spell shape will display as brown instead of the icy blue it did before. This seems to have a random chance of happening upon loading the Minecraft application. In my case I had also upgraded the Beam spell shape to 50% cooldown reduction, as well as the Frost Damage spell effect, and I did not test it at any point before upgrading Beam, Entangle, and Frost Damage to 50% cooldown reduction.

**To Reproduce**
1. Upgrade Entangle to 50% cooldown reduction with the Master's Dais
2. Create a spell with Entangle and another effect, such as Frost Damage (I used the Beam shape)
3. Cast the spell and observe the visual and sound effects of the spell
4. Close Minecraft
5. Open Minecraft from the launcher
6. Load back into the world
7. Cast the spell created in step 2 and observe the visual and sound effects of the spell
8. Repeat steps 4-7 if the visual and sound effects did not change (it can take a few times)

**Expected behavior**
A spell with the Beam shape and Entangle and Frost Damage effects should always have the visual and sound effects of Frost Damage
The same should apply for Fire Damage instead of Frost Damage

**Screenshots**
none

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.2.10
 - Forge Version: 1.18.2-forge-40.2.0

**Additional context**
Other mods:
ChickenDropFeathers-1.1-forge-1.18-38.0.17
CosmeticArmorReworked-1.18.2-v2a
curios-forge-1.18.2-5.0.7.1
FastLeafDecay-28
geckolib-forge-1.18-3.0.57
geckolib-quilt-1.18-3.0.46
gravestone-1.18.2-1.0.1
inventorysorter-1.18-19.0.0
ironchest-1.18.2-13.2.11
Jade-1.18.2-fabric-5.99.10
jei-1.18.2-9.7.1.255
journeymap-1.18.2-5.9.3-forge

**Comment by Mithion** [comment]
The mod picks the highest affinity - there was a bug in this that caused it not to, but that was fixed.
There is no rule that frost damage would override entangle; it's purely based on the affinity of the spell.
