### ISSUE TITLE
Going through the end portal (Back to the Overworld) resets all Mana and Artifice progress

### ISSUE THREAD

**Issue by Robonics** [Mithion/Mana-And-Artifice#596]
Jumping through the portal resets all Mana and Artifice progress. Tier, Level, Rote Spells, even the fact that I've read the codex. This has happened to both me and a friend under the same conditions.
Considering this is a pretty easy to encounter bug, and the fact that I didn't see any issues about makes me question if it's a compat issue, but to my knowledge none of the mods in my modlist affect the end itself, as YUNG's Better Strongholds only affects the overworld stronghold structures.

**Reproduce**
Have progress in mana and artifice, kill the Ender Dragon, then return to the Overworld

**Expected behavior**
Going through the portal does not wipe my progress

 - Minecraft Version: 1.16.5
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.34

<details>
<summary><h3>Modlist</h3></summary>
<ul>
<li>abnormals_core-1.16.5-3.3.1.jar</li>
<li>appleskin-forge-mc1.16.x-2.4.0.jar</li>
<li>BetterCaves-Forge-1.16.4-1.1.2.jar</li>
<li>BetterDungeons-1.16.4-1.2.1.jar</li>
<li>BetterMineshafts-Forge-1.16.4-2.0.4.jar</li>
<li>BetterStrongholds-1.16.4-1.2.1.jar</li>
<li>byg-1.3.6.jar</li>
<li>cameraoverhaul-1.0-1.16.4.jar</li>
<li>citadel-1.8.1-1.16.5.jar</li>
<li>ColdSweat-2.1.11.1.jar</li>
<li>curios-forge-1.16.5-4.0.8.2.jar</li>
<li>DynamicSurroundings-1.16.5-4.0.5.0.jar</li>
<li>FarmersDelight-1.16.5-0.6.0.jar</li>
<li>farmersrespite-1.16.5-1.1.jar</li>
<li>geckolib-forge-1.16.5-3.0.106.jar</li>
<li>gravestone-1.16.5-1.0.7.jar</li>
<li>iceandfire-2.1.11-1.16.5.jar</li>
<li>ImmersiveEngineering-1.16.5-5.1.0-148.jar</li>
<li>ImmersivePetroleum-1.16.5-3.4.0-13.jar</li>
<li>jei-1.16.5-7.7.1.153.jar</li>
<li>mana-and-artifice-1.5.1.7.jar</li>
<li>mowziesmobs-1.5.27.jar</li>
<li>mutantmore-1.16.5-1.0.1.jar</li>
<li>oculus-1.4.5.jar</li>
<li>rubidium-0.2.11.jar</li>
<li>selene-1.16.5-1.9.0.jar</li>
<li>SoundFilters-0.14_for_1.16.2.jar</li>
<li>supplementaries-1.16.5-0.18.5.jar</li>
<li>Xaeros_Minimap_23.1.0_Forge_1.16.5.jar</li>
<li>XaerosWorldMap_1.28.9_Forge_1.16.5.jar</li>
<li>YungsApi-1.16.4-Forge-13.jar</li>
<li>YungsBridges-Forge-1.16.4-1.0.1.jar</li>
<li>YungsExtras-Forge-1.16.4-1.0.jar</li>
</ul>
</details>

**Comment by Robonics** [comment]
I should add, this only happens when going though the return portal. It does not effect you when you die.

**Comment by Mithion** [comment]
There's a known issue with this happening with Mohist, wonder if that's the issue

**Comment by Robonics** [comment]
I've had this issue occur twice. Once one a Bisect hosted server, and once on an Aternos one. I'm not sure what they use behind the scenes for hosting.

**Comment by Mithion** [comment]
Closing as 1.16.5 is no longer supported.
