### ISSUE TITLE
[1.18.2]Hellfire Staff

### ISSUE THREAD

**Issue by Tigrex-Dai** [Mithion/Mana-And-Artifice#598]
**Describe the bug**
When using spell infusion table, an error message often occurs: 'Error setting spell data values; serverside validation failed'
Sometimes it works, but the mana cost is still bugged:
Mana cost showing in the UI of ctrl+right click is correct(half reduced from mastery) but showing in the UI of shift in the inventory is incorrect and it actually costs this much.

**To Reproduce**
1. Get item 'spell infusion table', 'hellfire staff' (I'm in demon faction)
2. Infuse spell 'electric arc' + 'fire damage'
3. Have magic level 71, and both spell cost half reduced

**Expected behavior**
The spell is correctly infused with correct mana cost without any error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/26639371/222933105-379662ba-9cce-4f98-8898-2abb8b9dd3ac.png)
![image](https://user-images.githubusercontent.com/26639371/222933128-1e9cc6ed-5f86-49e2-9d12-b4d0232d893a.png)
![image](https://user-images.githubusercontent.com/26639371/222933155-4b74ef02-0417-46ce-be75-5e436540bd1f.png)

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.10
 - Forge Version 40.2.0

**Comment by Mithion** [comment]
The Hellfire staff boosts damage and mana costs - the gui doesn't have that context, but the tooltip does.
