### ISSUE TITLE
Elemental Sentries will crash when attacking a player whose ID contains special characters

### ISSUE THREAD

**Issue by StarryNeverFall** [Mithion/Mana-And-Artifice#600]
Crash does not occur when Elemental Sentries locks a player, but when it attacks and causes damage.
Although player IDs with special characters are rare, if this problem occurs, players may no longer be able to enter the game. Because the bug will repeat when the player enters the game again.

 - Mod Version: 1.7.2.10
 - Forge Version 40.2.1

Complete crash-reports : [https://pastebin.ubuntu.com/p/xkVGGJswWq/](https://pastebin.ubuntu.com/p/xkVGGJswWq/)

**Comment by StarryNeverFall** [comment]
Not only players, but also some creatures can cause this problem when the game language is not English.
[https://pastebin.ubuntu.com/p/dT2N5YnkrF/](https://pastebin.ubuntu.com/p/dT2N5YnkrF/)

**Comment by StarryNeverFall** [comment]
After several tests, this problem will occur as long as it is used with Seer Stone.

**Comment by Mithion** [comment]
There was a bug with seer stones causing crashes when targeting players, though it has been fixed in 2.0.0.24
