### ISSUE TITLE
Incompatibility with Roughly Enough Resources - "Invalid player data"

### ISSUE THREAD

**Issue by unilock** [Mithion/Mana-And-Artifice#601]
**Describe the bug**
With Mana and Artifice and Roughly Enough Resources installed, trying to join a world results in an instant disconnect, with the error message "Invalid player data".

**To Reproduce**
1. Install Mana and Artifice and its dependencies
2. Install Roughly Enough Resources and its dependencies
3. Start Minecraft and create a new world

**Expected behavior**
The world loads.

**Screenshots**
<img width="260" alt="image" src="https://user-images.githubusercontent.com/11802133/223331264-b243d67a-9fd9-4dee-b3a7-05c1a955a647.png">
(it says "Back to Server List" regardless of whether you're joining a singleplayer or multiplayer world)

**Version Information**
- Minecraft: 1.18.2
- Forge: 40.2.0
- Mana and Artifice: [1.7.2.10](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/4285099)
- Roughly Enough Resources: ([this PR](https://github.com/theorbtwo/RoughlyEnoughResources/pull/69) cherry-picked into the [latest official 1.18.2 branch](https://github.com/theorbtwo/RoughlyEnoughResources/commit/6aa28b53e8dc10fc7f15f418804fd576664e93ea) - [here's a JAR](https://mega.nz/file/hg9T1BJZ#WUbKQ9IRgR3XJgs0HiEgFHAb4vVYyGotQms0Ql0rEho), but feel free to build it yourself if you don't trust me (i don't!))
- Roughly Enough Items: [8.3.590](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/4401133)
- REI Plugin Compatibilities: [8.0.46](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks/files/4402955)
- WMITAF: [2.4.0](https://www.curseforge.com/minecraft/mc-mods/wmitaf/files/3929241)
- Architectury API: [4.11.89](https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/4384391)
- Cloth Config API: [6.4.90](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3972426)
- Curios API: [5.0.9.0](https://www.curseforge.com/minecraft/mc-mods/curios/files/4418032)
- GeckoLib: [3.0.57](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/4181370)
- (convenience mods)
    - Better Mods Button: [3.2.3](https://www.curseforge.com/minecraft/mc-mods/better-mods-button/files/3963200)
    - Config Menus for Forge: [3.2.0](https://www.curseforge.com/minecraft/mc-mods/config-menus-forge/files/3671318)
    - Inventory Profiles Next: [1.9.2](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4370587)
    - Jade: [5.2.6](https://www.curseforge.com/minecraft/mc-mods/jade/files/4082408)
    - McMouser: [1.0.0](https://www.curseforge.com/minecraft/mc-mods/mcmouser/files/3561231) (yes i use a mac; what of it?)
    - Mouse Tweaks: [2.21](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/3578801)
    - Xaero's Minimap: [23.2.0](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/files/4418097)
    - Xareo's Worldmap: [1.29.2](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/files/4424632)
    - Kotlin for Forge: [3.10.0](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/4392674)
    - libIPN: [2.0.2](https://www.curseforge.com/minecraft/mc-mods/libipn/files/4370454)

**Additional context**
Relevant bit of `latest.log`, snipped from when creating a new world:
https://gist.github.com/unilock/bf563624fca626ca4af48d256f0298da

**Comment by unilock** [comment]
I """fixed""" this by mixing into Mana and Artifice's loot modifier registration class and completely disabling the loot functions breaking RER from ever being registered in the first place, then editing the mod's built-in datapack to replace all loot tables referencing those loot functions to contain only sticks.
Not an ideal solution IMO. But if you don't need mana caches, then I guess it's fine...?

https://github.com/unilock/MNA-Mixin/blob/main/src/main/java/net/unilock/mnamixin/mixin/GlobalLootModifiersMixin.java

**Comment by xAlicatt** [comment]
This is happening in 1.20.1 as well.

**Comment by unilock** [comment]
The issue is caused by MNA returning `LootItemFunctions.SET_CONTENTS` in the `getType()` method of each of its `LootItemConditionalFunction`s. It should be returning the result of `Registry.register(BuiltInRegistries.LOOT_FUNCTION_TYPE, RLoc.create(path), new LootItemFunctionType(serializer));` instead.

Here's a mod I made that *actually* fixes the issue: https://github.com/unilock/MNAMixin2

**Comment by xAlicatt** [comment]
> (By the way, I would recommend using EMI and EMI Loot instead of REI and RER. EMI has native support for JEI plugins when both recipe viewers are installed 🙂)

I'm trying EMI/Loot and getting the same error mentioning COFH Core and Sawmill now. Turning off Loot does not stop the error. 

I just swapped RER for JER and it's working fine. *shrug*

**Comment by aking4125** [comment]
There may be another conflicting mod in my modpack (Especially since we're using Sinytra connector). But it breaks EMI entirely with the (EMI waiting for server) message forever. 

> The issue is caused by MNA returning `LootItemFunctions.SET_CONTENTS` in the `getType()` method of each of its `LootItemConditionalFunction`s. It should be returning the result of `Registry.register(BuiltInRegistries.LOOT_FUNCTION_TYPE, RLoc.create(path), new LootItemFunctionType(serializer));` instead.
> 
> Here's a mod I made that _actually_ fixes the issue: https://github.com/unilock/MNAMixin2
> 
> (By the way, I would recommend using EMI and EMI Loot instead of REI and RER. EMI has native support for JEI plugins when both recipe viewers are installed 🙂)

I don't know how to use this mod. Attempting to build it via IntelliJ fails.

**Comment by unilock** [comment]
@xAlicatt
> I'm trying EMI/Loot and getting the same error mentioning COFH Core and Sawmill now. Turning off Loot does not stop the error.

That's strange; I have both of those mods running alongside EMI + EMI Loot just fine.  
Since the issue persists even without EMI Loot, I'm guessing there's a mod incompatibility somewhere else, but it's hard to say where without a crash log.

> I just swapped RER for JER and it's working fine. *shrug*

If I'm reading its code correctly, JER hardcodes the loot tables it supports to only those from vanilla Minecraft by default. ([source](https://github.com/way2muchnoise/JustEnoughResources/blob/705bbf05fea77b0b806f15bee0179662e5813697/Common/src/main/java/jeresources/util/LootTableHelper.java#L98))  
So it's not surprising that it works, given it doesn't touch M&A's loot tables at all :p

***

@aking4125

> There may be another conflicting mod in my modpack (Especially since we're using Sinytra connector). But it breaks EMI entirely with the (EMI waiting for server) message forever when installing MnA (1.20.1)

I also have EMI and M&A working together well, even with Sinytra Connector, so there's likely some other issue at play. But, again, it's hard to say what.

> I don't know how to use this mod. Attempting to build it via IntelliJ fails.

It should be as simple as
1. `git clone https://github.com/unilock/MNAMixin2.git`
2. `cd MNAMixin2`
3. `./gradlew build`

Alternatively you can download the latest build from the [workflow](https://github.com/unilock/MNAMixin2/actions) I just set up.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.

**Comment by unilock** [comment]
>  Note that this, and many more issues have been fixed in 1.20.1

It most certainly is not. You're still returning `LootItemFunctions.SET_CONTENTS` for `LootItemFunction#getType` in all of your `LootItemConditionalFunction`s, as of MNA 3.0.0.22.

**Comment by InvalidArgument3** [comment]
> The issue is caused by MNA returning `LootItemFunctions.SET_CONTENTS` in the `getType()` method of each of its `LootItemConditionalFunction`s. It should be returning the result of `Registry.register(BuiltInRegistries.LOOT_FUNCTION_TYPE, RLoc.create(path), new LootItemFunctionType(serializer));` instead.
> 
> Here's a mod I made that _actually_ fixes the issue: https://github.com/unilock/MNAMixin2
> 
> (By the way, I would recommend using EMI and EMI Loot instead of REI and RER. EMI has native support for JEI plugins when both recipe viewers are installed 🙂)

wanted to say thank you so much for making that, it solved an issue I had when assembling a 1.20.1 modpack - looks like it also conflicts with EMI Ores or whatever the more modern RER is. but your mixin solved it
