### ISSUE TITLE
Artifacts tab and whenever i search @mana and artifice in the recipe are in the bottom right my game automatically crashes

### ISSUE THREAD

**Issue by TrainingPurse1** [Mithion/Mana-And-Artifice#602]
**Describe the bug**
whenever me or my friend search up @mana in the recipe search area after we load into the game it automatically crashes our game and we tried lowering the mod to a lower version and it does not fix it.

idk how to reproduce it other then trying to search up mana in the recipe search box

**Expected behavior**
it happens every time without fail. all we did was download the mod so we could put it in the modpack. 
which is FTB direwolf20 1.18. we just added like 25-30 other mods to enhance the modpack.

steps to reproduce:
1. load up singleplayer world
2. open up creative inventroy
3. click arrows until you see mana and artifice: artifacts
4. click on it
5. crash
6. OR
7. press e to find recipe search area on your right
8. type in @man
9. game crashes.

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.10
 - Forge Version 40.1.84

**Additional context**
other then it happening every time without fail idk what the problem is at all. we tried downgrading the version of the mod cause for some other mods it seemed to work but it doesn't work at all for this one.

it also does not show up in the mods folder in the main menu under singleplayer and multiplayer. I scrolled through all of the mods and nothing resembling mana and artifice or as I keep seeing it throughout several files (mna). 

im very new to this kind of stuff and my friends dad mostly help fixed all of the bugs we had so far but even he did not have any clue on what was going on.

**Comment by Mithion** [comment]
This was fixed in 2.0.0.23!
