### ISSUE TITLE
Eldrin Altar hung state, server crash

### ISSUE THREAD

**Issue by biggayenergy** [Mithion/Mana-And-Artifice#603]
**Describe the bug**
Eldrin Altar fail/cancel not working

**To Reproduce**
1. Have 0 Fire Eldrin Energy
2. Be Tier 4.
3. Add 2 Blaze Powder & 1 Mote of Fire to the Eldrin altar to create a greater mote of Fire
4. The Recipe kicks off but fails due to lack of energy.
5. Add a Mote of Fire to the Eldrin... Furnace thingy?
6. The Eldrin Altar stays stuck in it's cinematic state & your mote slowly burns up giving a static 0 Fire energy while the eldrin altar takes it's energy.
7. Remove the reagents for the recipe
8. The Eldrin Altar is unaffected and continues to exist like it's going to make an item.
9. Upon reboot, the server crashes.

**Expected behavior**
The server to not crash & Eldrin Altar recipe to stop trying.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.2.10.jar
 - Forge Version 40.2.0

**Additional context**
https://pastebin.com/sMBV8UD1

**Comment by biggayenergy** [comment]
**Did further testing and noticed a few things:**
This only happens when I do not have the required Eldrin Energy for a recipe when I attempt to craft a recipe. The recipe gets stuck in a hung state. I can use /mna wellspring add <name> <element> <required energy> and then re-activate it and it will work successfully. If I try to do a recipe, do not have the energy, and then try to modify the recipe or take an item off a pillar, the server will crash.

I did notice that when I try to repeat a recipe by just rick-clicking with an empty hand, it will provide a "You do not have the required eldrin energy for this recipe" error message, and everything is fine. I think there might be something wrong with the pre-recipe eldrin energy check on a first-time craft.

**Comment by ArthurUFelix** [comment]
did u get any solution for this one? Happened the same thing in the server that i was playing and they just removed the mod other way no one could join anymore. Also i kinda do not understand how wellpsring energy works in numbers so idk if i had enough

**Comment by Mithion** [comment]
This issue has been fixed in later versions
