### ISSUE TITLE
Stone Fishing Arm Recipes Broken

### ISSUE THREAD

**Issue by christofferson** [Mithion/Mana-And-Artifice#606]
**Describe the bug**
Both stone fisher arm recipes ask for `minecraft:logs` instead of `forge:stone` , and the output for the left arm recipe is set to `mna:constructs/construct_fishing_rod_left_iron` instead of the stone variant.

**To Reproduce**
1. Check the recipes for the fisher arms in JEI

**Expected behavior**
Stone component recipes should be made of stone and result in stone components

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.10
 - Forge Version 40.2.0

**Comment by Mithion** [comment]
This was fixed in 2.0.0.23!
