### ISSUE TITLE
Elemental Senteries Crash Server When Set to Target Players

### ISSUE THREAD

**Issue by N0tRocketScience** [Mithion/Mana-And-Artifice#607]
We have been playing on a server with the mod for several months now and have discovered a big issue. When you place an elemental sentry and set it to target all players with an unattuned charm, when it fires at a player the game/server crashes (this happens regardless of the sentries damage type) 

Version Information:

    Mod Version: 1.7.2.10
    Forge Version 40.2.0

**Comment by Mithion** [comment]
This was fixed in 2.0.0.23!
