### ISSUE TITLE
1.18.2 (1.7.2.10) Null pointer exception with moving inventory and constructs

### ISSUE THREAD

**Issue by JagonArcur** [Mithion/Mana-And-Artifice#609]
Specific incidence and means of reproduction: Using create to move an inventory that a construct is checking for items causes this crash. Likely moving the inventory with any means will result in the same, but that is untested.

[crash-2023-04-28_11.56.21-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/11355395/crash-2023-04-28_11.56.21-server.txt)

**Comment by Mithion** [comment]
This was fixed in 2.0.0.23!
