### ISSUE TITLE
[1.16.5] Lantern Wraiths keep populating other dimensions and spawn in huge groups

### ISSUE THREAD

**Issue by sirben99** [Mithion/Mana-And-Artifice#610]
**Describe the bug**
Hey!

I have an issue where Lantern Wraiths are spawning in custom dimensions and they seem to spawn in abnormal groups. For example they spawn in the Dimensional Dungeons dungeon dimension and in the vanilla MC End dimension. 
As of the abnormal group amount, i havent seen other mobs spawn this freaquantly in groups of 2-4, like the Lantern Wraiths do.
I have posted screenshots of what i mean

**To Reproduce**
1. Download Mana and Artifice and Dimensional Dungeons mod
2. Launch the game
3. Create a portal to the Dimensional Dungeons dimension or The End
4. See that Lantern Wraiths are spawning there

**Expected behavior**
Lantern Wraiths should not spawn in other dimensions than theyr supposed to and the spawning should be adjusted

**Screenshots**
![2023-04-29_17 17 35](https://user-images.githubusercontent.com/32977052/235308136-eca41fa8-5fcc-4af0-ae17-ac3c8691b573.png)
![2023-04-29_17 15 02](https://user-images.githubusercontent.com/32977052/235308137-c05e298e-acb6-44ef-973f-f65facd01e29.png)

**Version Information**
 - Minecraft version: 1.16.5
 - Forge Version; 36.2.39
 - Mana and Artifice: mana-and-artifice-1.5.1.7
 - Dimensional Dungeons: dimdungeons-1.13.1
 - Geckolib: geckolib-forge-1.16.5-3.0.106
 - Curios: curios-forge-1.16.5-4.1.0.0

**Comment by Mithion** [comment]
1.16.5 is no longer supported, but this has been fixed in 2.0.0.23!
