### ISSUE TITLE
Moving the mouse over the base while drawing runes can cause crashes

### ISSUE THREAD

**Issue by lixiangdong122333** [Mithion/Mana-And-Artifice#612]
**Describe the bug**
Moving the mouse over the base while drawing runes can cause crashes

**To Reproduce**
1. Get item 'manaweaver_wand_advanced'
2. Use on 'Eldrin Altar', hold down the right cilck and move to the 'Pedestal', release the right cilck
3. Have magic level 'any'
4. See error : Service crash

**Expected behavior**
Service remains normal

**Screenshots**
<img width="1917" alt="Untitled" src="https://user-images.githubusercontent.com/25265669/236678432-9f569f8e-165a-4141-9b88-3b0e520bb027.png">

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.7]
 - Forge Version [e.g. 36.2.39]

**Additional context**
error log in : https://pastebin.com/ux9xnENg

**Comment by Mithion** [comment]
This was fixed in 2.0.0.23!
