### ISSUE TITLE
[1.18.2] IndexOutOfBoundsException from Manaweave Cache

### ISSUE THREAD

**Issue by CvoidWyvern** [Mithion/Mana-And-Artifice#613]
**Describe the bug**
Crash on loading specific chunks of a new world
https://mclo.gs/sQm1TkF

**To Reproduce**
Load new world, if not immediately crashing move to new chunks until crashing

**Expected behavior**
No errors with generation, or at least something to catch this log it

**Version Information (please complete the following information):**
 - Mod Version: mna-1.7.2.10
 - Forge Version 40.2.2

**Additional context**
Lots of worldgen mods in this pack listed in the log, most notably IDAS & Integrated Stronghold, BYG, Repurposed Structures, Terrablender, and Unearthed, also have Terratonic, Terralith, and Incendium datapacks included

Edit: Updated logs after removing some potential culprits
Crash log: https://mclo.gs/uwwj1zc
Full log starting game and generating new world: https://mclo.gs/x8ZJNLM

**Comment by Mithion** [comment]
This was fixed in 2.0.0.23!
