### ISSUE TITLE
Can't get tier 2 [1.16.5]

### ISSUE THREAD

**Issue by SmitisYT** [Mithion/Mana-And-Artifice#615]
![IMG-f539be0b5c90d48cf4d2c152dc3fbf72-V](https://github.com/Mithion/Mana-And-Artifice/assets/92750633/e665b3fe-f3b2-4e23-8aa0-9c992e3ab3f1)
I completed all the tasks to get tier 2, but when i did it, they all marked red and now i even cant complete them one more time

**Comment by Mithion** [comment]
Version 1.16.5 is no longer supported; but this has been fixed in newer versions!
