### ISSUE TITLE
[1.6.5] Can not excute ritual "Practitiones's Pouch" with coveyance patch   in nether or the end

### ISSUE THREAD

**Issue by Cacoalpano** [Mithion/Mana-And-Artifice#616]
Version Mana and Artifice: 1.5.1.7
Minecraft 1.6.5
I use **Practitiones's Pouch** to save ritual : 
-Ritual of Searing Inferno
-Ritual of endless void. 
In **Practitiones's Pouch**, i add a patch **coveyance**, 
In the this  **coveyance** patch , i connected  it to a chest in OVERWORLD. 
I loaded chunk to have this chest, when i try summon "Ritual of Searing Inferno" in nether  or "Ritual of endless void" in the end =>   it is not happen, it is not show log in GUI of user. 
I opened log in this case, i saw "java.lang.NullPointerException: null".

_java.lang.NullPointerException: null
	at com.ma.items.ritual.ItemPractitionersPouch.func_195939_a(ItemPractitionersPouch.java:884) ~[mana-and-artifice:1.5.1.7] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:651) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:ForgeHooksMixin,pl:mixin:APP:morecfm.mixins.json:ForgeHooksMixin,pl:mixin:A}._ 

I think in this case , if "Practitiones's Pouch" does not get item in chest in the world is different from the player's world  , please the  "Practitiones's Pouch"  only check item in "Practitiones's Pouch" , If it is not enough, you can show log "NOT ENOUGH ITEM".
Thanks you

**Comment by Mithion** [comment]
Version 1.16.5 is no longer supported; but this has been fixed in newer versions!
