### ISSUE TITLE
Projection rune working with specific apotheosis blocks or with vanilla books

### ISSUE THREAD

**Issue by LTHCTheMaster** [Mithion/Mana-And-Artifice#617]
**Is your feature request related to a problem? Please describe.**
I enjoy apotheosis and "libraries" block of this mod. Those blocks allow you to store a lot of enchantments from books. A lot of mods add disenchantment methods that give enchanted books, projection rune used in m&a's disenchantment method are not considered by those blocks

**Describe the solution you'd like**
Add compatibility between projection rune and apotheosis' libraries blocks

**Describe alternatives you've considered**
Enchant books with runic anvil and runes

**Additional context**

**Comment by Mithion** [comment]
There is now a config that allows a projection rune to enchant anything.
