### ISSUE TITLE
Game crashes when I use the bell of bidding

### ISSUE THREAD

**Issue by Berkvrl** [Mithion/Mana-And-Artifice#618]
When I right click or press z with the bell of bidding in my hand the game crashes immediately.
I'm using 1.18.2 forge 40.2.4, the latest version of mna(1.7.2.10) geckolib forge 3.0.57 and curios forge 5.0.7.1
I don't use any other mods other than those.

Here is the link to the crash report:
https://hastebin.com/share/zajarirido.perl

**Comment by Berkvrl** [comment]
I found out the reason why it happens in the com/mna/items/constructs there is a class file which has code for the bell of bidding.
In this code there are a bunch of commands such as FOLLOW or EAT. One of those commands is INTERACT and it is the one causing issues. In order to search for the icons of those commands the code picks the command name and turns them into lowercase variants. If your computer is using english than you have no problem but my pc has turkish language and in turkish i and ı are different letters so when INTERACT turns lowercase it becomes ınteract and because of that the interact.png file cannot be found.

**Comment by Mithion** [comment]
The issue you mention is unrelated, but I appreciate the effort!  Version 2.0.0.23 fixes this issue.

**Comment by Berkvrl** [comment]
Apparently it's not fixed I'm getting the same error even in the newest version
