### ISSUE TITLE
Unable to Enchant Using Multishot I Rune

### ISSUE THREAD

**Issue by AetheriMC** [Mithion/Mana-And-Artifice#620]
**Describe the bug**
I am unable to use the Multishot I enchantment rune to enchant an item, including Bows and the Eldritch Orb. I believe the issue is that the rune once crafted is not properly named. Indeed, the crafting recipe shows the Multishot I as the name of the rune with a Multishot I enchantment as the end result, but the crafted item is a Rune: Air with the multishot enchantment on it instead.

**To Reproduce**
1. Craft the Multishot I enchanting rune using the manaweaving station
2. Place the desired item to enchant on the runic anvil
3. Place the rune on the item on the runic anvil
4. Items will not accept the rune as a valid option for enchanting

**Expected behavior**
For the rune to be applied to the appropriate items so as to enchant those items with Multishot I.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.10
 - Forge Version: 1.18.2 - 40.2.4

**Comment by Mithion** [comment]
This was fixed in version 2.0.0.23!
