### ISSUE TITLE
Disable vinteum ore spawning

### ISSUE THREAD

**Issue by BlakeIsMyWaifu** [Mithion/Mana-And-Artifice#621]
**Is your feature request related to a problem? Please describe.**
I would like to disable all vinteum ore from spawning so that i could use [large ore deposits](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits) to create large deposits instead of lots of spread out veins

**Describe the solution you'd like**
In the config server config you can already change frequency but it's a minium of 2. I would like to a boolean to turn off vinteum natually spawning all together. This is a common feature in many other mods already and it would be nice have all ores in deposits together.

**Comment by Mithion** [comment]
This config was added in version 2.0.0.23!
