### ISSUE TITLE
Crash because of Eldrin Altar

### ISSUE THREAD

**Issue by Nico44YT** [Mithion/Mana-And-Artifice#622]
**Describe the bug**
The game/server crashes whenever someone tries to perform a manaweaving pattern on the eldrin altar.

**To Reproduce**
1. Get a manaweaving staff
2. Place a Eldrin Altar
3. Perform any pattern

**Expected behavior**
No crash when using Eldrin Altar

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.39

**Additional context**
Crash Log: https://pastebin.com/9asCi16N
Server Crash Log: https://pastebin.com/kNHdAmd0

**Comment by Mithion** [comment]
Version 2.0.0.23 resolves this issue.
