### ISSUE TITLE
Ritual of Arcana seems to start its effect and then immediately stop

### ISSUE THREAD

**Issue by polkakitty** [Mithion/Mana-And-Artifice#624]
I'm using ATLauncher, Minecraft 1.18.2, Forge 40.2.10, and Mana and Artifice 2.0.0.22 on Linux.  I originally encountered this problem on an instance of Minecraft with various other mods like Create, Botania, TerraForged, and Biomes O Plenty installed (it isn't a specific modpack; it's just some other mods that I thought looked good.)  However, I created another instance of Minecraft with Mana and Artifice, Curios, and Geckolib as the only mods installed, started a new world in creative mode, tried creating a spell, and the same thing still happened, so I don't believe the issue has anything to do with incompatibility with other mods.

I'm trying to use the Ritual of Arcana to create a new spell.  Drawing the runes on the ground, starting the ritual with Purified Vinteum Dust, putting the spell recipe in place, and putting the reagents for the spell in their indicated places all seem to work correctly.  However, when I try to activate the center rune again with Purified Vinteum Dust, the effects for the ritual do not appear.  All that happens is, the floating indicators showing which runes to place the items on disappear (the items themselves are still on the runes and can be picked up again; they should be consumed as part of the ritual, but it never gets to that point,) and some small points of light appear in the air and then fade away (the attached screenshot shows what this looks like.)

It looks as if some particles are being generated for one frame, possibly as part of the effects that should appear in the air, but then the ritual gets cut off somehow.

I wish I could tell you more about what's going on, but Mana and Artifice doesn't seem to be writing anything to Minecraft's latest.log while performing the Ritual of Arcana, and I wasn't able to find any log files that Mana and Artifice generated itself.

The weird part is, my first attempt to create a spell (with Touch and Break) succeeded, but I started encountering this problem on my second attempt to create a spell (with Touch and Splash,) and now, every attempt to create a new spell results in the ritual immediately stopping, even if it's another spell with only Touch and Break, and even if it's a separate world on a separate instance of Minecraft!

![ritualofarcana](https://github.com/Mithion/Mana-And-Artifice/assets/81491188/73f7b73d-147d-433c-afb9-5ed5a9ebdfa7)

**Comment by polkakitty** [comment]
After further testing, I've found that the Ritual of Arcana will fail in this way if either of two conditions is true:

- The spell recipe contains the Splash component.  There seems to be an issue with that particular component; in my survival world, I was able to successfully make another Touch/Break spell and a Touch/Light spell, but if I try to create a Touch/Splash spell, when I reach the point in the ritual where I activate the center rune with Purified Vinteum Dust for the second time, the ritual always fails to progress any further.

- You were in the Creative gamemode at the point when you created the spell recipe at the Inscription Table.  This seems to give you an item with most of the properties of a finished spell instead of a spell recipe (if you right-click with it, you can immediately assign it an icon and a name, and after doing so, you can use it as a spell, and instead of the icon for a spell recipe, it has the icon that's used for a spell when you first get it out of the Ritual of Arcana and you haven't assigned an icon to it yet.  The attached screenshot shows the difference; the item in slot 1 was created in creative mode, and the item in slot 2 was created in survival mode, using the same inscription table with only Touch and Break selected as components.)

Normally a finished spell cannot be substituted for a spell recipe in the Ritual of Arcana (if you try to use it as such, the spell will appear as an item on the center rune, but the reagents for the spell will not be displayed over the runes.)  However, if you take the item you get from creating a spell recipe at the Inscription Table in creative mode, and you use that for a spell recipe in the Ritual of Arcana, the reagents required for the spell will appear over the runes, and right-clicking them with an empty hand will put the appropriate items over the runes, but when you've placed the reagents and you activate the center rune with Purified Vinteum Dust for the second time, the rest of the effects for the ritual never appear.

So, in short, the real issue is that using the Inscription Table in creative mode gives you a bugged item that can be used as a finished spell, and can be used to display the required reagents for the Ritual of Arcana, but can't be used to complete the Ritual of Arcana.  I understand the utility of being able to create spells directly and skip the Ritual of Arcana when you're playing in creative mode (especially for you as the mod creator, since you'll need to test a lot of revisions to specific components,) but I think that maybe, when you're in creative mode, the Inscription Table should give you a choice between making a spell recipe and making a finished spell.

The Splash issue was the one I first encountered in my survival game, and then when trying to reproduce the problem in creative mode, I accidentally stumbled into the second issue.  Since I didn't realize there were two separate conditions that could make the ritual fail, I think that made my description of the problem more confusing than it could have been, and I apologize for that.

![spellrecipe](https://github.com/Mithion/Mana-And-Artifice/assets/81491188/9c607b9d-7923-4709-9a27-6c32d43867fc)

**Comment by Mithion** [comment]
The ritual not starting is due to a recipe error - it's invisible and so the ritual is literally waiting for an item it can't find.  I've fixed it in the next version, that's my bad (it is supposed to also include a water bottle).

The creative mode functionality is 100% intentional.  The inscription table just gives you the completed spell in creative mode, allowing you to skip the ritual of arcana entirely.
