### ISSUE TITLE
Mana and Artifice mobs never spawn

### ISSUE THREAD

**Issue by polkakitty** [Mithion/Mana-And-Artifice#625]
I'm using ATLauncher, Minecraft 1.18.2, Forge 40.2.10, and Mana and Artifice 2.0.0.22 on Linux.  I originally encountered this problem on an instance of Minecraft with various other mods like Create, Botania, TerraForged, and Biomes O Plenty installed (it isn't a specific modpack; it's just some other mods that I thought looked good.)  However, I created another instance of Minecraft with Mana and Artifice, Curios, and Geckolib as the only mods installed, started a new world in creative mode, went up in the air to be able to see a large area of terrain, and waited for a few in-game days, and I saw vanilla mobs spawn, but Mana and Artifice mobs never did, so I don't believe the issue has anything to do with incompatibility with other mods.

I started a world using Mana and Artifice v1.7.2.8 when that was the current version, and I remember seeing mobs like the Hulking Zombie and Mushroom Soldier spawn before I even found or read the Codex.  However, after starting a new world using version 2.0.0.22, I've played for 20 hours, established a base, and completed most of the goals to progress from tier 1 to tier 2, but I haven't seen a single Mana and Artifice mob.

I know the Codex says that the factions deploy more powerful troops near where powerful wizards exist, which implies that the strongest mobs should only appear after I've made progress through the mod.  But even in creative mode, with my tier set to 5, my level set to 50, and a faction chosen (I tested it with Fey,) no Mana and Artifice mobs ever seem to spawn at all.

**Comment by Mithion** [comment]
I had the spawn weights WAY too low in config (for reference, 8 for single mobs and 16 for wars - I've bumped that to 40 and 80 respectively.  So they *could* spawn, they just hardly ever did because they effectively had no chance to.

You can also change the weights of any mob, per biome, in mna-entities.toml

The "more powerful" just refers to how strong the mobs are; it doesn't affect their chance to spawn at all.
