### ISSUE TITLE
Ticking Entity Server Crash

### ISSUE THREAD

**Issue by WesleySnacks** [Mithion/Mana-And-Artifice#629]
**Describe the bug**
After summoning the pig dragon he launches approximately 2 chickens, they explode, and the server crashes.

**To Reproduce**
1. Summon Pig Dragon
2. Wait a few seconds for him to start attacking
3. Crash

**Expected behavior**
For no crash to happen

**Version Information (please complete the following information):**
 - Mod Version: 2.0.0.28
 - Forge Version 40.2.9

**Additional context**
Crash Log: https://pastebin.com/GkQpb9Pp

**Comment by Mithion** [comment]
This was resolved in the latest 1.18 update
