### ISSUE TITLE
Opening Codex Arcana reduce font size.

### ISSUE THREAD

**Issue by Sidnatum0** [Mithion/Mana-And-Artifice#63]
1.0.6-pre2
![2020-08-23_14 14 45](https://user-images.githubusercontent.com/55444707/90977474-761c5700-e54e-11ea-9090-69c852b132ce.png)
![2020-08-23_14 14 49](https://user-images.githubusercontent.com/55444707/90977478-787eb100-e54e-11ea-9221-6eb9786018c6.png)

**Comment by Mithion** [comment]
That's intentional.  The Codex forces a unicode font while it's open.  It will properly restore the font when closed if it wasn't already a unicode font.

(From 1.0.6-pre1 patch notes/General: - The codex now forces a unicode font)
