### ISSUE TITLE
[1.18.2] IndexOutOfBoundsException when loading Manaweave Cache

### ISSUE THREAD

**Issue by PerpetuallyEngineering** [Mithion/Mana-And-Artifice#631]
**Describe the bug**
Crash on loading world
https://mclo.gs/zAlObIz

**To Reproduce**
Load world, generate a problematic chunk

**Expected behavior**
Lack of crash

**Version Information (please complete the following information):**
 - Mod Version: mna-2.0.0.29
 - Forge Version 40.2.10

**Additional context**
Issue #613 appears very similar to the issue experienced.

**Comment by PerpetuallyEngineering** [comment]
Minor update. Working with a modpack I previously had working and switching in terraforged for world generation led to the same error above. Can turn on and off the crash by adding or removing terraforged.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
