### ISSUE TITLE
Telekinetic Retrieval Makes the Spell Nonfunctional

### ISSUE THREAD

**Issue by NotGoodAtGam** [Mithion/Mana-And-Artifice#632]
**Describe the bug**
Adding telekinetic retrieval to a spell makes it nonfunctional

**To Reproduce**
Add the enchantment to any wand or staff that has impulse, animus, or greater animus

**Expected behavior**
For the spell to be functional at least even without the enchantment

**Version Information (please complete the following information):**
 - Mod Version:  2.0.0.29
 - Forge Version: 40.2.0

**Additional context**
Playing on a server with very few mods. This bug actually causes the spell to completely stop working, pressing right click or ctrl clicking both do literally nothing without even moving your hand. The non enchanted versions of the spells work perfectly fine. I tested a few wands and staves with all 3 kinds of spell, and I tried projectile and self shapes for both. I tried this at both tier 3 and tier 4, in creative mode and survival. Did not test if disenchanting makes the spell functional again.

**Comment by NotGoodAtGam** [comment]
Update: tested again on 2.0.0.30 and the bug is still an issue. 
Disenchanting does revert the spell. 
It's also worth noting that the base version of Animus doesn't work with self cast on both versions of the mod, and it will act as if you're casting the spell but not use any mana like you have an invalid target, I'm not sure if this is intentional or not because Greater Animus still works with self cast even when using blocks, but the codex explains that self cast works for the spell which is why I'm putting it here.

**Comment by NotGoodAtGam** [comment]
Update 3: Still present on Version 2.0.0.31 after testing for posterity.

**Comment by Mithion** [comment]
Telekinetic retrieval is intended to go on the item you're launching.  The enchantment prevents right clicking to stop you from placing a block accidentally (for example an anvil) which would delete the enchantment.  Right now it is allowed on everything, but I may be able to make some changes.

**Comment by Mithion** [comment]
This was resolved in 3.0.0.11
