### ISSUE TITLE
Dig radius is oversized (1.18.2)

### ISSUE THREAD

**Issue by wuzzard** [Mithion/Mana-And-Artifice#633]
**Describe the bug**
I created a spell: projectile, break, radius.  When I set the radius to 2, it break 7x7x7 blocks, instead of the expected 5x5x5.  Note that when I set the radius to 1, it breaks 3x3x3 blocks, as expected.  

**To Reproduce**
1. Create spell with projectile, break, radius
2. Set radius to 2
3. Cast on a large, flat section of blocks
4. Observe the extra block of radius actually broken

**Expected behavior**
The spell should only break a 5x5x5 section, the initial block and a radius of two blocks along each axis.

**Screenshots**
NA

**Version Information (please complete the following information):**
 - Minecraft: 1.18.2
 - Mod Version: 2.0.0.30
 - Forge Version: 40.2.10

**Additional context**
NA

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
