### ISSUE TITLE
Soaked status stuck "on" ofter travel through gate on rainy day

### ISSUE THREAD

**Issue by wuzzard** [Mithion/Mana-And-Artifice#634]
**Describe the bug**
I have an MnA gate that goes to an underground hideout with not other exits or entrances.  When I teleport in, it takes the world a moment to load.  During that time, my MnA detects that it is raining and marks my character as "soaked".  The timer runs dowwn, but the status effect stays permanently until I either relog, or transition between inside and outside.

**To Reproduce**
1. Run the game on a system with a performance level such that  where teleporting into a new location, it takes a moment for the world to load (not sure if a powerful machine can avoid this)
2.  Make a gate to an underground location
3. Teleport, while not soaked, to the underground location, while it is raining at your destination
4. Observe the soaked status
5. Do not leave the underground area
6. Wait for the "soaked" status to time out
7. Note that the status icon never goes away

**Expected behavior**
Since I am underground, I expect to be dry.  It might be ideal for MnA to delay weather detection for a few seconds after a teleport, so the "soaked" status never triggers at all.  However, it would also be acceptable if it went away properly, by checking the environment when the timer expires.

**Screenshots**

**Version Information (please complete the following information):**
 - Minecraft: 1.18.2
 - Mod Version: 2.0.0.30
 - Forge Version: 40.2.10

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
