### ISSUE TITLE
Cantrip Triangle Problem

### ISSUE THREAD

**Issue by Ryuco** [Mithion/Mana-And-Artifice#635]
**Describe the bug**
for some reason the cantrips on my server refuse to work, no matter what symbol you draw or how well you articulate the design it always creates the triangle in the air.

**To Reproduce**
1. get Chimerite manaweavers wand.
2. Attempt to draw any symbol besides a triangle
3. Have magic level '1'
4. Watch as it magically becomes a triangle no matter what you draw

**Expected behavior**
I expected to be able to draw a / or a \ or even a square but instead always got triangle.

**Screenshots**
wouldnt really show the problem.

**Version Information (please complete the following information):**
 - Mod Version: 2.0.031
 - Forge Version 40.2.10

**Additional context**
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[Butcher's Delight Foods (by onuadan)](https://www.curseforge.com/minecraft/mc-mods/butchers-delight-foods)
[Ender Storage 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8)
[Vampires Need Umbrellas (by focamacho)](https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Biomancy (by Elenterius)](https://www.curseforge.com/minecraft/mc-mods/biomancy)
[Vampirism - Become a vampire! (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)
[AstikorCarts [Horse Carts] (by pau101)](https://www.curseforge.com/minecraft/mc-mods/astikorcarts)
[Realm RPG: Imps & Demons (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-imps-demons)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Potion Blender [Fabric/Forge] (by motivational_dragon)](https://www.curseforge.com/minecraft/mc-mods/potion-blender)
[Corn Delight[Forge] (by sz0999312)](https://www.curseforge.com/minecraft/mc-mods/corn-delight)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Weapons of Miracles - epic fight (by reascer)](https://www.curseforge.com/minecraft/mc-mods/weapons-of-miracles-epicfight)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Nock Enough Arrows (by itayfeder)](https://www.curseforge.com/minecraft/mc-mods/nock-enough-arrows)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Isle of Berk Addons (by JayZX535)](https://www.curseforge.com/minecraft/mc-mods/isle-of-berk-addons)
[Realm RPG: Dragon Wyrms (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-dragon-wyrms)
[Infernos - HTTYD (by RedgitReds)](https://www.curseforge.com/minecraft/mc-mods/infernos-httyd)
[GottschCore (by gottsch)](https://www.curseforge.com/minecraft/mc-mods/gottschcore)
[SecretRoomsMod (by AbrarSyed)](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Wandering Bags (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/wandering-bags)
[Create: Alloyed (by MythrilBagels)](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Fresh Animations (by Fresh__LX)](https://www.curseforge.com/minecraft/texture-packs/fresh-animations)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Create : Armory (by Chilllliii)](https://www.curseforge.com/minecraft/mc-mods/create-armory)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[[FORGE] soul like monsters: epic fight addon (by sunwoolove777)](https://www.curseforge.com/minecraft/mc-mods/soul-like-monsters-epic-fight-addon)
[CodeChicken Lib 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
[Mysterious Mountain Lib (by sz0999312)](https://www.curseforge.com/minecraft/mc-mods/mysterious-mountain-lib)
[Miner's Delight + (by soytutta)](https://www.curseforge.com/minecraft/mc-mods/miners-delight-plus)
[Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[[FORGE] soul like armors reworked (by sunwoolove777)](https://www.curseforge.com/minecraft/mc-mods/forge-soul-like-armors-reworked)
[Potion Flasks (by creamsicle42)](https://www.curseforge.com/minecraft/mc-mods/potion-flasks)
[Mo' Potions (by LDMGamingYT)](https://www.curseforge.com/minecraft/mc-mods/mo-potions)
[Dungeon Denizens (by gottsch)](https://www.curseforge.com/minecraft/mc-mods/dungeon-denizens)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Epic Samurai's - Ninja Expansion (by VPixelStudio)](https://www.curseforge.com/minecraft/mc-mods/epic-samurais)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[MCA Reborn [Fabric/Forge] (by jahx_senpoopie)](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)
[Awesome Dungeon Nether edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge)
[Infused Foods (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/infused-foods)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[TheDirtyStuff (Drugs) (by bogismok)](https://www.curseforge.com/minecraft/mc-mods/thedirtystuff)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Awesome Dungeon Ocean edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-edition-ocean-forge)
[Tarot Cards (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/tarot-cards)
[Crabber's Delight (by AlabasterLeking)](https://www.curseforge.com/minecraft/mc-mods/crabbers-delight)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Shipping (by PlayTics)](https://www.curseforge.com/minecraft/mc-mods/shipping)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Enemy Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/enemy-expansion)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Realm RPG: Fallen Adventurers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-fallen-adventurers)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Create Encased (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-encased)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Mowzie's Mobs (by bobmowzie)](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
[Isle of Berk (by GhanouCraft)](https://www.curseforge.com/minecraft/mc-mods/isleofberk)
[Vampirism Integrations (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Soul fire'd (by Crystal_Spider_)](https://www.curseforge.com/minecraft/mc-mods/soul-fired)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[ProjectE (by SinKillerJ)](https://www.curseforge.com/minecraft/mc-mods/projecte)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Construction Wand (by ThetaDev)](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
[StateObserver (by Favouriteless)](https://www.curseforge.com/minecraft/mc-mods/stateobserver)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Epic Fight (by maninthe_home)](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod)
[Rings of Ascension (Forge) (by focamacho)](https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
[Mana and Artifice (by AWildCanadianEh)](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Chest Cavity - Forge Port (by booneldanforever)](https://www.curseforge.com/minecraft/mc-mods/chest-cavity-forge-port)

**Comment by Mithion** [comment]
The Manaweaving Wand has a radial menu to select the pattern to draw if freeform is giving you problems.
