### ISSUE TITLE
[1.18.2] Client Crash due to Ticking Entity in The End

### ISSUE THREAD

**Issue by Thanjar** [Mithion/Mana-And-Artifice#636]
**Describe the bug**
Client crashes when approaching any mob from any faction while in the end but is not consistent. 

**To Reproduce**
1. Enter the End.
2. Approach group of faction mobs fighting each other.
3. chance to not crash, but soon or later guarantee crash.

**Expected behavior**
Be able to approach mobs from factions in the End.

**Version Information (please complete the following information):**
 - Mod Version: 2.0.0.31
 - Forge Version: 40.2.10

**Additional context**
Only happens to me and does not crash server.
Tried removing all items from inventory and placing them in a chest, crash still occurs.
Log: [Pastebin](https://pastebin.com/mW1RPFnw) (Do not worry about the long log, 80%~ of the log is the mod manifest)
To possibly make it easier, here is the words that I have seen the most in the crash log:
-LivingEntity
-Mixin
-Across all crash logs that I had repeating this crash, at line 15, it was always either a Pixie or "LivingWard".
Extra Notes:
-Using a Modified version of All the Mods 7 (this mod was added to modpack).
-If this matters: I belong to the Devils of the Nether and I'm at Tier 5.

**Comment by Thanjar** [comment]
Update: It can occur in the Overworld, but seems to be at a lower chance

**Comment by Thanjar** [comment]
Update: After many crashes, found out it also occurs with Chatterers, something that all this entities have in common is that they fly, not sure if that is the cause

**Comment by Thanjar** [comment]
Update: After many crashes, found out it also occurs with Chatterers, something that all these entities have in common is that they fly, not sure if that is the cause.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
