### ISSUE TITLE
Invalid Bell of Bidding Recipe

### ISSUE THREAD

**Issue by Sylis-V** [Mithion/Mana-And-Artifice#639]
**Describe the bug**
Viewing in JEI or attempting to craft the Bell of Bidding yields an invalid recipe.

**To Reproduce**
1. Open inventory
2. Left-click 'Bell of Bidding'
3. Behold, invalid tag.

or

1. Attempt standard crafting recipe of 
--         Silver      Carpet
Silver   String     Silver
Silver Iron Nug. Silver
2. Behold, no output.

**Expected behavior**
Successful craft of Bell of Bidding.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/95304381/5d60ac49-aa37-4b4f-b3af-a13a21515ea6)
![image](https://github.com/Mithion/Mana-And-Artifice/assets/95304381/1db08016-25ed-41ef-b6cb-c775ffd51825)

**Version Information (please complete the following information):**
 - Mod Version: 2.1.0.1
 - Forge Version 43.3.5

**Additional context**
This does use the 1.19 alpha release of MNA.
Modlist:
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Rechiseled: Create (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled-create)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Enigmatic Legacy (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy)
[Ars Artifice (by Jarva)](https://www.curseforge.com/minecraft/mc-mods/ars-artifice)
[mutil (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/mutil)
[Tarot Cards (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/tarot-cards)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Ars Elemental (by Alexth99)](https://www.curseforge.com/minecraft/mc-mods/ars-elemental)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Infusion Table (by jptrzy)](https://www.curseforge.com/minecraft/mc-mods/infusion-table)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Gateways to Eternity (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity)
[Spirit (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/spirit)
[YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Vitalize (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/vitalize)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
[Drawers Tooltip (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/drawers-tooltip)
[FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Building Gadgets (by Direwolf20)](https://www.curseforge.com/minecraft/mc-mods/building-gadgets)
[Occultism (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/occultism)
[Corn Delight[Forge] (by sz0999312)](https://www.curseforge.com/minecraft/mc-mods/corn-delight)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Magnesium/Rubidium Extras (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Dave's Potioneering (by SoterDave)](https://www.curseforge.com/minecraft/mc-mods/daves-potioneering)
[Delightful (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/delightful)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Mandala's GUI - Dark mode (by cesar_zorak)](https://www.curseforge.com/minecraft/texture-packs/mandalas-gui-dark-mode)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Mysterious Mountain Lib (by sz0999312)](https://www.curseforge.com/minecraft/mc-mods/mysterious-mountain-lib)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Rechiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[ConnectedTexturesMod (by tterrag1098)](https://www.curseforge.com/minecraft/mc-mods/ctm)
[Real Seasons (by Favouriteless)](https://www.curseforge.com/minecraft/mc-mods/real-seasons)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Enchanted Book Redesign (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/enchanted-book-redesign)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Potions Master (by thevortexFoxTopia)](https://www.curseforge.com/minecraft/mc-mods/potionsmaster)
[Hexerei (by JoeFoxe)](https://www.curseforge.com/minecraft/mc-mods/hexerei)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Tetra (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/tetra)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Reaper (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/reaper)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Mana and Artifice (by AWildCanadianEh)](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice)
[Too Many Glyphs (by derringercubed)](https://www.curseforge.com/minecraft/mc-mods/too-many-glyphs)
[Ars Ocultas (by mystchonky)](https://www.curseforge.com/minecraft/mc-mods/ars-ocultas)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Ars Creo (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-creo)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Modonomicon (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Wandering Bags (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/wandering-bags)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Magnesium/Rubidium Dynamic Lights (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Italian Delight (A Farmer's Delight Add-on) (by PuurpZ)](https://www.curseforge.com/minecraft/mc-mods/italian-delights-add-on-for-farmers-delight)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[Relics (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/relics-mod)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[Ars Armiger (by VykladeLapiet)](https://www.curseforge.com/minecraft/mc-mods/ars-armiger)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Jade Addons (Forge) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
[Tetranomicon (by syrikalis)](https://www.curseforge.com/minecraft/mc-mods/tetranomicon)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)

**Comment by BaltKallar** [comment]
same issue for anything using carpet in the recipe
