### ISSUE TITLE
[1.18.2] Nethergate destroying blocks

### ISSUE THREAD

**Issue by HEAAAG** [Mithion/Mana-And-Artifice#640]
**Describe the bug**
Nethergate spell deletes blocks from world

**To Reproduce**
1. Get spell nethergate.
2. Use when overworld/ nether location has surrounding blocks.
3. 3x3x3 area of blocks centered at player's head are destroyed.

**Expected behavior**
Teleportation to the overworld/ nether without destruction of blocks

**Screenshots**
Before Nethergate, all blocks present
![2023-11-15_15 17 19](https://github.com/Mithion/Mana-And-Artifice/assets/41999589/8b6cdc6d-7b37-41b7-8dbe-7d94c58d5549)

After Nethergate.
![2023-11-15_15 18 30](https://github.com/Mithion/Mana-And-Artifice/assets/41999589/ee0d0c72-5b55-4238-8388-df3e2f87e202)

**Version Information (please complete the following information):**
 - Mod Version: 2.0.0.31
 - Forge Version 40.2.5

**Comment by Mithion** [comment]
This issue was resolved with the latest 1.18.2 update
