### ISSUE TITLE
[1.19.2] The ritual of locating does not work.

### ISSUE THREAD

**Issue by Althraxion** [Mithion/Mana-And-Artifice#642]
**Describe the bug**
I was playing with mna in 1.19.2, and I attempted the ritual of locating. It said that it could not find the structure in a reasonable distance. I have tested with the vanilla ancient city and a datapack structure. Both times, /locate was able to find them relatively close.

**To Reproduce**
1. Perform ritual of locating on any structure.
2. /locate the same structure.
3. See error.

**Expected behavior**
I expected the ritual to give me a compass pointing to the structure.

**Screenshots**
![bug1](https://github.com/Mithion/Mana-And-Artifice/assets/107289759/86aea393-c19a-445c-ba66-cb55914fc83a)
![2023-12-02_12 02 40](https://github.com/Mithion/Mana-And-Artifice/assets/107289759/3c9329bc-13cf-47fb-bd37-c142b0ef5655)

**Version Information (please complete the following information):**
 - Mod Version: [1.19.2 - 2.1.0.4]
 - Forge Version [e.g. 43.3.5]

Extra Info:
It did not even spend time looking, just instantly popped up with did not find it, which is a problem, as in mna playthroughs I heavily rely on this ritual. It isn't technically gamebreaking, as it still gives you the advancement, just annoying.

**Comment by wetbrownsauce** [comment]
It works fine for me with only mana & artifice installed, but in my modpack it does not work. Are you using any other mods? Possibly a conflict?

**Comment by FoxMcloud5655** [comment]
Still happening on 1.20.1, very likely a mod conflict.  Would have to do further testing.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
