### ISSUE TITLE
Vinetum Ore Gen Cannot Be Disabled Using the Config

### ISSUE THREAD

**Issue by Lonemind** [Mithion/Mana-And-Artifice#644]
**Describe the bug**
It appears that the config options that have to do with disabling/configuring Vinteum Ore generation are ignored. Setting `generateVinteum` to false has no effect. Niether does changing the upper/mid/bottom region values. They appear to continue generating at default values.

**To Reproduce**
1. Change the values of generateVinteum, vinteumVeinYValueMidBottom, etc.
2. Load a new world
3. Find vinteum ore in places it should not be generating.

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 2.0.0.31]
 - Forge Version [40.2.14]

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
