### ISSUE TITLE
[1.19.2] After a certain amount of time, game crashes due to "StringIndexOutOfBoundsException"

### ISSUE THREAD

**Issue by Azreliax** [Mithion/Mana-And-Artifice#650]
**Describe the bug**
The game randomly crashes after a certain amount of time

**To Reproduce**
Unable to reproduce properly, but it seems to occur with random ticking entities, if you spend too much time in a few chunks for too long

**Expected behavior**
I expect the game to be running smoothly without any ticking entity errors. Entities that causes the crash are random. I read through the crash log myself and noticed that every entity may have a chance to cause the crash.

**Screenshots**
I can't provide any screenshots unfortunately

**Version Information (please complete the following information):**
 - Mod Version: [1.19.2-2.1.0.4-all]
 - Forge Version [1.19.2-forge-43.3.5]

**Additional context**
The crash log contains another mod that may have something to do with the cause of the crash. Its called "The End of Herobrine". But I'm not sure if this particular mod causes the crash, since the ticking entities only are Mana and Artifice mobs

Crash: https://pastebin.com/Rke2uUDS

**Comment by Mithion** [comment]
The issue is with The End of Herobrine, they'll need to check string bounds before substring calls.
