### ISSUE TITLE
In the Inscription Table, the paper cost image is vellum instead of paper

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#651]
**Describe the bug**

![image](https://github.com/Mithion/Mana-And-Artifice/assets/15698722/70f31dbd-b02f-4b89-8a6f-aa650170a54c)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.4-all
 - Forge Version 43.3.5

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
