### ISSUE TITLE
The page for Greater Animus is visible at tier 1

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#652]
**Describe the bug**

![image](https://github.com/Mithion/Mana-And-Artifice/assets/15698722/9ee40ac2-7a2b-4caf-97e6-1d1f10a726fc)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.4-all
 - Forge Version 43.3.5

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
