### ISSUE TITLE
"Required Reagents" is empty in the Inscription Table

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#653]
**Describe the bug**

![image](https://github.com/Mithion/Mana-And-Artifice/assets/15698722/0d1a5f0f-0298-48cd-8a8d-397c47a7485a)

![image](https://github.com/Mithion/Mana-And-Artifice/assets/15698722/d35ba061-196d-48ce-98be-6224f73e47e6)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.4-all
 - Forge Version 43.3.5

**Comment by aaronhowser1** [comment]
Mod list, in case this might be a mod incompatibility or something
https://gist.github.com/aaronhowser1/e869d0ea426dc2738f3c68c212b6b793

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
