### ISSUE TITLE
Incorrect coloring in the Ritual of the Earthen Steppes page

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#654]
**Describe the bug**

![image](https://github.com/Mithion/Mana-And-Artifice/assets/15698722/7c2b0920-5a10-4930-8d13-e58537bfc5c9)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.4-all
 - Forge Version 43.3.5

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
