### ISSUE TITLE
Construct mana cannon targeting bug

### ISSUE THREAD

**Issue by A1CSutehk** [Mithion/Mana-And-Artifice#656]
**Describe the bug**
Construct's with mana cannon arms will try to target player.

**To Reproduce**
1. Build a client with a mana cannon
2. engage hostile mob
3. be in close proximity of construct when it fires (1-6m)

**Expected behavior**
Construct's projectile should home in on target, however it will attempt to curve and hit player (though no damage will be done)
**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [mna-2.0.0.33.]
 - Forge Version [40.2.14]

**Additional context**
Construct will target enemies properly when player isn't within close distance.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
