### ISSUE TITLE
Game crashes with error java.lang.NullPointerException: Cannot read the array length because "patterns" is null

### ISSUE THREAD

**Issue by PiperTres** [Mithion/Mana-And-Artifice#657]
When trying to open the cantrips menu the game crashes

1. Get a wand
2. Try to open the Cantrips menu
3. Crash

Expected behavior:
Cantrips menu opens up 

Version Information:
 - Mod Version: 3.0.0.0
 - Forge Version 47.2.16

Tried changing keybinds, same result.
https://mclo.gs/MWC34vg
^ Crash log

**Comment by zendarsf** [comment]
i have same issue 
Mod Version: 3.0.0.2
Forge Version: 47.2.6

**Comment by Sudholz-Arne** [comment]
I ran into the same issue. Just finished testing through my mods on the Direwolf20 1.10 pack. The cause is the **[HammerLib](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)** mod, and at least in this modpack, the only mod requiring it is SolarFluxReborn.

**Comment by vdrake77** [comment]
A fix for the meantime is to use the default patterns; they're all assigned even if you can't use them

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
