### ISSUE TITLE
Tier I can't be completed.

### ISSUE THREAD

**Issue by Sidnatum0** [Mithion/Mana-And-Artifice#66]
Tier 1 spells cannot be crafted as components such as Infused Silk and Ritual Focus (lesser) are in tier 2.
Therefore, raising the level, as well as creating a spell with a complexity of 15, is impossible, also because the complexity of the existing components is not enough.
Also, in tier 1, there are no items that can be created in the altar.
1.0.6-pre2

**Comment by Mithion** [comment]
This has been fixed in 1.0.6-pre3
