### ISSUE TITLE
Minecraft crashes if you put construct parts on an armor stand

### ISSUE THREAD

**Issue by wiligl** [Mithion/Mana-And-Artifice#660]
**Describe the bug**
If you try to put construct parts on an armor stand, then the game crashes and you cannot join the world anymore.

**To Reproduce**
see above

**Expected behavior**
The game should not crash.

**Screenshots**
see bug report

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.0] mna-1.7.2.8.jar
 - Forge Version [e.g. 36.1.32]   40.1.92
 - run as modpack via Curseforge: Magic and Sorcery by Speshel_ (sorcerer modpack-1.1.zip)
 
![image](https://github.com/Mithion/Mana-And-Artifice/assets/8667566/e5693d72-93f2-4a13-a102-a69a90917c11)

**Additional context**
Bug report in PasteBin: https://paste.ee/p/UwBox

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
