### ISSUE TITLE
(1.16.5) 1.5.1.7 Book of Marks and Book of Phylacteries pink texture

### ISSUE THREAD

**Issue by WarriorG8** [Mithion/Mana-And-Artifice#661]
the 1.16.5 most recent version (1.5.1.7) are with the Book of Marks and Book of Phylacteries with a pink square texture, is that normal? A bug or just upcoming content? There will be updates to that version of the game?

![2023-12-31_17 36 55](https://github.com/Mithion/Mana-And-Artifice/assets/117954174/a8076440-90ed-47f3-b11f-ce083563a731)

PS: Now i'm having another trouble and i don't know why but when i break any mana and artifice block like runeforge or inscription table, it is destroyed and not dropped. (i've seen another people with same problem that was told being fixed, but isn't) Update: The blocks are dropping normally now and i didn't do anything. Up2: Runic anvil, Occulus, Runescribing table are dropping normally.  Pedestal are also not dropping.

Another question, i've made the ritual of locating to Swamp, but reaching the location it wasn't Swamp, the ritual of locating doesn't work if there is modded biomes?  i found the Tall Grasses biome from Exotic Critters instead of Swamp. i think it might be because i have updated the mod and the compass was broken, but i'm not sure, i'll try to do another compass.

The Codex will have  a page about the fourth faction? The Undead if i remember.

**Comment by WarriorG8** [comment]
> the 1.16.5 most recent version (1.5.1.7) are with the Book of Marks and Book of Phylacteries with a pink square texture, is that normal? A bug or just upcoming content? There will be updates to that version of the game?
> 
> ![2023-12-31_17 36 55](https://private-user-images.githubusercontent.com/117954174/293520770-a8076440-90ed-47f3-b11f-ce083563a731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTU5MTgsIm5iZiI6MTcwNDI1NTYxOCwicGF0aCI6Ii8xMTc5NTQxNzQvMjkzNTIwNzcwLWE4MDc2NDQwLTkwZWQtNDdmMy1iMTFmLWNlMDgzNTYzYTczMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwNDIwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWE4ZDI2ZWY1MDcxN2I0OTViNzAwZjlmYWRiNDkyNDc5ZmZkZGUxMDcyMWY4OTI2MDliMDE5ZDg4YjY4NzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JaCL0tPOEL1PjPVqOfmCiwSfhEXPShFjg5zaBpmDtJE)
> 
> PS: Now i'm having another trouble and i don't know why but when i break any mana and artifice block like runeforge or inscription table, it is destroyed and not dropped. (i've seen another people with same problem that was told being fixed, but isn't)

Another question, i've made the ritual of locating to Swamp, but reaching the location it wasn't Swamp, the ritual of locating doesn't work if there is modded biomes?  i found the Tall Grasses biome from Exotic Critters instead of Swamp. i thing it might be because i have updated the mod and the compass was broken, but i'm not sure, i'll try to do another compass.

**Comment by Mithion** [comment]
This has been resolved in a later version.  1.16.5 is no longer supported.
