### ISSUE TITLE
[1.19.2] Incompatible with "Shoulder Surfing Reloaded"

### ISSUE THREAD

**Issue by HendersonT** [Mithion/Mana-And-Artifice#664]
**Describe the bug**
If both Mana and Artifice and Shoulder surfing reloaded are loaded, the client will crash if the camera gets close to a block behind the player, triggering a "Pose stack not empty" crash. 

**To Reproduce**
1. Load Minecraft with only Mana and Artifice, Shoulder SUrfing Reloaded, and their dependencies. 
2. Go into third person
3. Get close to a block behind the player head, e.g. intersect the camera with a tree.
4. Game freezes and crashes.

**Expected behavior**
The game should not crash, the camera should shift to a first person perspective.

**Version Information (please complete the following information):**
 - Mod Version: Mana and Artifice [2.1.0.6]
 - Shoulder Surfing Reloaded [2.8.1]
 - Forge Version [43.3.7]

**Additional context**
Crash Report: https://pastebin.com/YiLWgzgQ

If Either mod is removed, the issue does not occur.

**Comment by HendersonT** [comment]
Reported on Shoulder Surfing Reloaded as well.

**Comment by Exopandora** [comment]
The bug has been resolved by Shoulder Surfing Reloaded. This issue can be closed.
