### ISSUE TITLE
[1.20.1] Practitioners pouch duplication bug

### ISSUE THREAD

**Issue by Synesthesia707** [Mithion/Mana-And-Artifice#665]
**Describe the bug**
Practitioners pouch duplicates items

*Steps to reproduce the behavior:
 Place stacked items in the pouch then drag them around, they will dupe. Must be a stacked item. 

*Version Information*
 - Mod Version: [3.0.0.2]
 - Forge Version [47.2.18]
 
**Additional context**
Bug is present with no other mods downloaded.

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.7
