### ISSUE TITLE
[1.20.1] Runic Malice Crash

### ISSUE THREAD

**Issue by Synesthesia707** [Mithion/Mana-And-Artifice#666]
**Describe the bug**
 Runic malice crashes client when placing runes inside.

**To Reproduce**
Place a rune inside a runic malice. 

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.2]
 - Forge Version [47.2.18]

**Additional context**
Bug is present with no other mods.

**Comment by Mithion** [comment]
This was added in version 3.0.0.8.
