### ISSUE TITLE
Bug with Iris

### ISSUE THREAD

**Issue by bugchungas** [Mithion/Mana-And-Artifice#667]
I added the mod to a mod pack that I'm playing and it won't open, when I delete it, it will open. I get the crash log: The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance

Im playing 1.19.2
Is there any simple fix to this without deleting Iris.

**Comment by Mithion** [comment]
Iris is fabric, M&A is Forge
