### ISSUE TITLE
"Enchant an item on a runic forge" achivment doesn't record in the Oculus

### ISSUE THREAD

**Issue by MasonReptiloid** [Mithion/Mana-And-Artifice#669]
**Describe the bug**
"Enchant an item on a runic forge" achivment doesn't record in the Oculus

**To Reproduce**
1. Advance to tier 3
2. Runforge and craft an enchantment rune (in my case Feather Fall 2)
3. Succesfully enchant an item
4. Look in the Oculus
5. Don't get the achivement 

**Expected behavior**
Geting the achivement in the Oculus

**Versions**
Mode version: 3.0.0.1
Minecraft version: 47.2.0

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.7
