### ISSUE TITLE
Crash: Probably some projectile collision (v. 1.0.6-pre7)

### ISSUE THREAD

**Issue by mikeThePlayer** [Mithion/Mana-And-Artifice#67]
Game crashed when an arrow (fired by skeleton) hit my casted spell in mid-air (it was a basic projectile shape with fire damage component).

I tested it once more and game crashed again. Last scene I was able to witness in game, was a deflected fire projectile moving behind me.
I did not test it with other mobs/weapons/real players trying to shoot at me.

Adding a crash log: https://pastebin.pl/view/efbcc781

MC: version 1.16.2
Forge: 33.0.22
Mana and Artifice: 1.0.6-pre7

**Comment by Mithion** [comment]
This has been fixed in 1.0.6-pre9.
