### ISSUE TITLE
Cloudstep Enchantment doesn't work 

### ISSUE THREAD

**Issue by MasonReptiloid** [Mithion/Mana-And-Artifice#670]
**Describe the bug**
Cloudstep enchantment can't be placed on an item. It can neither be placed on an item as a rune on a runeforge nor with a /enchant command.

**To Reproduce**
1. Get the Cloudstep I rune
2. Place a boots on a runeforge
3. Use the hammer to enchat boots with the rune
4. Fail
OR
1. Take boots in a hand 
2.  /enchant Player mna:cloudstep 1 
3. Fail

**Expected behavior**
Get boots with a Cloudstep I enchantment 

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.1
 - Forge Version 47.2.0

**Additional context**

**Comment by Deomyeon** [comment]
Useful alternative : Fix enchanted_book's NBT

1.  Obtain enchated_book
/give @a minecraft:enchanted_book{StoredEnchantments:[{id:"mna:cloudstep",lvl:3s}]}
 or
/data modify entity @e[type=minecraft:item, limit=1, sort=nearest] Item.tag.StoredEnchantments[0] set value {lvl: 3s, id:"mna:cloudstep"}

2. Enchant boots with anvil(minecraft:anvil)

[cloudstep only works for boots]

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.7
