### ISSUE TITLE
Magician's Workbench dupes items

### ISSUE THREAD

**Issue by MasonReptiloid** [Mithion/Mana-And-Artifice#671]
**Describe the bug**
Magician's Workbench dupes all items in crafts that it saves (you can just take them). Moreover usual crafting hotkeys like "Right Click+Shift" don't work
**To Reproduce**
1. Get Magician's Workbench
2. Craft something
3. Quit the table menu
4. Enter the Magician's Workbench again
5. Try to take an Item from a saved craft
6. Dupe the item

**Expected behavior**
Items are ghosted in saved craft, you can use the normal crafting hotkeys. 

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.1
 - Forge Version 47.2.0

**Additional context**

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.7
