### ISSUE TITLE
Disenchanting dosen't work

### ISSUE THREAD

**Issue by MasonReptiloid** [Mithion/Mana-And-Artifice#673]
**Describe the bug**
Menu of Disenchanting table is bugged and completly broken (see the screenshot) 

**To Reproduce**
Open disenchanting table 

**Expected behavior**
Working disenchanting table

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/155913347/0941215c-0e58-4bfa-93c5-a4bd43e1bf60)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.3
 - Forge Version: 47.2.0

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.7
