### ISSUE TITLE
1.20.1 - Dimension Blacklist resets on every launch

### ISSUE THREAD

**Issue by Aeases** [Mithion/Mana-And-Artifice#674]
**Describe the bug**
The dimension blacklist resets to containing no dimensions on every launch of the world.

**To Reproduce**
1. Set Dimension blacklist
2. Launch world

**Expected behavior**
the config file to maintain the dimensions set in the blacklist.

**Screenshots / Screencasts**

https://github.com/Mithion/Mana-And-Artifice/assets/96164686/d4b72ce5-270a-41c6-9e80-dcd6fcc2dd9b

**Version Information:**
 - Mod Version: [3.0.0.3]
 - Forge Version [47.2.19]

**Additional Info**
this could be related to #658

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.9
