### ISSUE TITLE
Warding Candle anti spawn failing with Exotic Critters mobs

### ISSUE THREAD

**Issue by WarriorG8** [Mithion/Mana-And-Artifice#675]
Warding Candle anti spawn and Explosion protection do not work properly with Exotic Critters Mod (1.16.5)

1. Install Mana and Artifice and Exotic Critters together
2. Craft and light a Warding Candle
3. Wait til the night

**Expected behavior**
With Warding Candle is expected to not spawn hostile mobs in protected areas and to not blow up blocks

 - Mod Version: [e.g. 1.5.1.7]
 - Forge Version [e.g. 36.2.34]

-Exotic Critters Version 1.16Experimental1.10

**Comment by Mithion** [comment]
This has been resolved in later versions; 1.16.5 is no longer supported.
