### ISSUE TITLE
[1.20.1] Dragon Survival Incompatibility

### ISSUE THREAD

**Issue by Zainyest** [Mithion/Mana-And-Artifice#677]
**Describe the bug**
Crash on selecting a dragon form with Dragon Survival and dependencies on 1.20.1.

**To Reproduce**
1. Install Dragon Survival 1.5.57, Curios API, GeckoLib 4, and Mana and Artifice on Forge 47.2.0.
2. Launch the game.
3. Start & load a world.
4. Select a dragon species, save and accept.
6. Render thread fatal error.

**Expected behavior**
Player model change to selected dragon.

**Version Information (please complete the following information):**
 - Mod Version:  3.0.0.4
 - Forge Version  47.2.0

**Additional context**
https://hastebin.com/share/ezurutesin.php

**Comment by eehunter** [comment]
I can confirm that I have had the same issue after adding M&A (as well as a couple of other mods) to a previously-stable-ish modpack that includes Dragon Survival. Disabling M&A in the launcher has prevented the crash.
Furthermore, a similar issue exists when M&A is installed on 1.18.2 with Better Invisibility present. Crouching while wearing the Bracelet of Trickery causes other players nearby to crash. I have not tested this particular issue without Epic Fight present, but removing Better Invisibility resolved it. I believe I should open a separate issue for what I have just described, knowing this is a recurring problem.

**Comment by Zainyest** [comment]
Hi, after trying to reproduce this error it seems it was fixed using the most recent versions of each mod for 1.20.1; probably safe to close for now.

Tested with:
-Curios API [5.7.0]
-Dragon Survival [1.5.57]
-Dragon Survival Compatability [1.1.5] (with and without)
-GeckoLib 4 [4.4.2]
-Mana and Artifice [3.0.0.9]
