### ISSUE TITLE
Misaligned Faction Armor Values

### ISSUE THREAD

**Issue by CodexArchive** [Mithion/Mana-And-Artifice#678]
**Describe the bug**
Not sure if this is a bug or intentional, but the armor stats of the demon and undead faction armors don't line up with the armor used to craft them. The demon armor has netherite armor stats but is created using diamond armor, and the undead armor has diamond armor stats but is created using netherite armor. The armor stats for the fey and council match appropriately with the armor used in crafting, so it seem like the undead and demon armor may have gotten each other's intended stats.

**To Reproduce**
Load up a world with MNA and compare the faction armor values (toughness, durability, etc.) with the armor used to craft them

**Expected behavior**
Demon armor should have diamond armor values and undead armor should have netherite armor values to align with the armor used in their crafting.

**Version Information (please complete the following information):**
 - Mod Version: 2.0.0.33 (1.18.2)
 - Forge Version 40.2.14

**Comment by Mithion** [comment]
This is intentional, as it's based on materials the faction would encounter.  The effects of the armor were also considered in their defensive bonus.  You can increase this using Aura of the Bulwark if desired.
