### ISSUE TITLE
Crash with Emanation Spell Effect and Nether Portal

### ISSUE THREAD

**Issue by ClownyTheClown** [Mithion/Mana-And-Artifice#679]
Crash Description:
Unsure, however seems to deal with a "spell_entity_emanation" entity that was located in a nether portal.
Constantly crashed server as soon as someone enters the nether near where the entity was.
Killing it with a repeating command block at spawn before friend joining stopped the crash.

Crash Report:
https://hastebin.com/share/duculeyemi.rust

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.4-all
 - Forge Version: 47.2.19

**Comment by Mithion** [comment]
Seems your paste was deleted, I am unable to view it.

**Comment by ClownyTheClown** [comment]
https://pastebin.com/8PxEs08H
Here's a new one

**Comment by Mithion** [comment]
Thanks!

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
