### ISSUE TITLE
Null Pointer Error

### ISSUE THREAD

**Issue by 8bitminerman** [Mithion/Mana-And-Artifice#680]
**Describe the bug**
A Null pointer error

**To Reproduce**
1. Have a construct with a mana cannon
2. have the construct shoot the mana cannon and have the shot hit an entity
3. Game Crash

**Expected behavior**
The game crashed

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.5]
 - Forge Version: [47.2.20]

**Additional context**
Crash log part 1
https://pastebin.com/4Kz9ZeE3
Crash log part 2
https://pastebin.com/3thEJDAP

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
