### ISSUE TITLE
[1.20.1] Datapacks' Hidden Entities Are Visible

### ISSUE THREAD

**Issue by Jawggy** [Mithion/Mana-And-Artifice#681]
Datapacks use entities like armor stands, villagers, etc that are supposed to be invisible/hidden, but with MnA installed, they become visible, ruining the visuals.

The tested datapacks are Stellarity, Nyctocosm, and Nevermore.

Nyctocosm examples:
- Armor stands visible while casting magic
- the mob Death Walker has a visible Giant entity
- Villagers and Armor Stands are visible in an activated Dias of Inculcation
- the Nightmare Serpent segments have visible Slime entities
etc.

Stellarity examples:
- With Stellarity, when opening an End portal, eyes of ender now rotate around the portal. The hidden Armor Stand entities are visible.
- (needs further confirmation) some custom textures don't work, like the Dragonblade.

 Nevermore examples:
 - Hidden mobs (husk, wandering traders, etc) are visible on custom mobs.
 
 I'm using over a 130 mods including performance enhancing mods, and I've tested them all; MnA ultimately seems to be the culprit. And idk if this info is useful, but I'm not using Sinyatra Connector.

**Comment by Mithion** [comment]
Probably has something to do with the camoflage code changes.

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
