### ISSUE TITLE
Inscription table doesn't look like it should when placed in world.

### ISSUE THREAD

**Issue by levicc00123** [Mithion/Mana-And-Artifice#682]
**Describe the bug**
![2024-01-17_14 46 42](https://github.com/Mithion/Mana-And-Artifice/assets/4361838/a0a1496b-2bb9-48b5-9621-6026c43cd098)

**To Reproduce**
1. Get inscription table
2. place in world

**Expected behavior**
The quill and paper on the inscription table shouldn't be glitched.

**Screenshots**

**Version Information (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Mana and Artifice: 3.0.0.6
 - Embeddium: 0.2.18
 - OS: OpenSUSE Tumbleweed 20240123
 - Kernel: 6.7.1-1
 - graphics card info (from lspci -nnk):
`0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Tiger Lake-LP GT2 [UHD Graphics G4] [8086:9a78] (rev 01)
        Subsystem: Dell Device [1028:0ab0]
       Kernel driver in use: i915
`

**Additional context**
From talking with the people on the discord, they thought the issue was embeddium, but disabling embeddium and it's addons didn't help any. My mod list can be found at https://gist.github.com/levicc00123/95b5282ce877c6603f3ebae5870a092c

**Comment by Mithion** [comment]
Doesn't happen with just M&A:
![image](https://github.com/Mithion/Mana-And-Artifice/assets/2482373/490e5c5c-839d-4f74-ad97-42073d371f9c)

You'll need to disable mods one half at a time (binary sort, more explanation can be given in Discord if needed) to find the cause of the issue.

**Comment by levicc00123** [comment]
Even with just M&A in the pack, the issue still persists, which makes me think it's a linux specific issue, which I'm guessing you know next to nothing about. Is there a debug build of M&A I could use to try and run down the issue?

**Comment by Mithion** [comment]
You'd guess wrong.  I was a Linux and Windows sysadmin for over 10 years, and I use it every day.  No there isn't a debug build.  

Do you have the Forge experimental lighting pipeline enabled?  Try toggling it.  Does it happen if you don't have any blocks beside the table?

**Comment by levicc00123** [comment]
I'm sorry I've taken so long to reply, I've been busy lately.

experimentalForgeLightPipelineEnabled = true causes java to dump it's memory. in a pack with just M&A.

[latest.log](https://github.com/Mithion/Mana-And-Artifice/files/14319949/latest.log)
[hs_err_pid7681.log](https://github.com/Mithion/Mana-And-Artifice/files/14319950/hs_err_pid7681.log)

**Comment by levicc00123** [comment]
The game loads on the second try, but no change to how the inscription table looks.

![2024-02-17_12 02 58](https://github.com/Mithion/Mana-And-Artifice/assets/4361838/c1e81c9e-df12-4a29-8677-d3a34a316479)

[latest.log](https://github.com/Mithion/Mana-And-Artifice/files/14319968/latest.log)

**Comment by Mithion** [comment]
Does this happen with other multipart models, such as the Master's Dais or the Runescribing Table?

**Comment by levicc00123** [comment]
Updating M&A to 3.0.0.9 causes a crash when trying to create or play a world, 

[crash-2024-02-21_21.02.35-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14368669/crash-2024-02-21_21.02.35-server.txt)
[latest.log](https://github.com/Mithion/Mana-And-Artifice/files/14368672/latest.log)

**Comment by levicc00123** [comment]
Starting fresh from a new instance allows me to joint a world with M&A 3.0.0.9 

![2024-02-21_21 27 22](https://github.com/Mithion/Mana-And-Artifice/assets/4361838/60c60a64-d788-44e9-9fc0-347a6b71f348)

![2024-02-21_21 37 15](https://github.com/Mithion/Mana-And-Artifice/assets/4361838/bf67731d-f4c1-498b-bf90-540a330293f6) (I don't remember if this has an in-world animation, figured I'd include it just in case.

![2024-02-21_21 43 21](https://github.com/Mithion/Mana-And-Artifice/assets/4361838/7a8d8325-7103-4e07-b937-a99963ab46e5)

[latest.log](https://github.com/Mithion/Mana-And-Artifice/files/14368895/latest.log)

**Comment by Mithion** [comment]
No matter what I try, this is not replicateable for me.  Tested on native Linux, Mac, Windows, all worked fine.  I'm calling this one a hardware / driver limitation, or something specific to your local instance.
