### ISSUE TITLE
[1.20.1] Infernal Armor does not render correctly: missing pieces, transparent, and pink.

### ISSUE THREAD

**Issue by IstasNix** [Mithion/Mana-And-Artifice#683]
**Describe the bug**
Infernal Armor does not appear to be rendering correctly. No mods other than MNA and prereqs (Geckolib).

**To Reproduce**
1. Get Infernal Armor.
2. Wear Infernal Armor.
3. Torso and boots don't seem to render at all, other pieces are bright pink?

**Expected behavior**
Torso and boots should definitely be rendering, and the textures aren't pink so I don't know why the armor is?

**Screenshots**
![MNAPinkDemons](https://github.com/Mithion/Mana-And-Artifice/assets/20792963/8ac97292-e0d5-49b1-a181-930fbfd5a297)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.6
 - Forge Version: 1.20.1-47.1.88

**Additional context**
Initially found in a modpack, but I have created a test environment with _only_ Mana and Artifice. The rendering issue persists.

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
