### ISSUE TITLE
It makes sense to note on the mod page that you need geckolib and Curios to run the game

### ISSUE THREAD

**Issue by murakumokazuma** [Mithion/Mana-And-Artifice#684]
Wondered why my game kept crashing on startup while trying to try out the mod, a friend ended up helping me find out that I needed Curios and geckolib to start the game. Would be great to add that as an east-to-see install requirement.

**Comment by Mithion** [comment]
It used to, though I'm still trying to get used to CurseForge's new dashboard.  I think I have it now.
