### ISSUE TITLE
[1.20.1] java.lang.IllegalStateException: Rendersystem called from wrong thread, higher tier Deathcap entities crash the game.

### ISSUE THREAD

**Issue by Captaincrikey001** [Mithion/Mana-And-Artifice#686]
Description:

The deathcap entities (especially the higher tiers with the burrowing attack) causes an exception in the tick loop, leading to a game crash and will sometimes continuously crash the game upon trying to log back into the world, effectively rendering the world unplayable if not backed up.

1. Spawn a tier 3 Deathcap entity (Via raid forcing.)
2. Let it perform the burrowing attack
3. Game will crash. Server cases may include insta crashing upon rejoining world.

Expected behavior:

Clean animation that jumps from the Deathcap's initial position to whereever its target is and not a crashing game or a ruined world.

Screenshots:

![image](https://github.com/Mithion/Mana-And-Artifice/assets/156194272/2db336e5-4cd8-42c9-b62f-f545901f565c)
![image](https://github.com/Mithion/Mana-And-Artifice/assets/156194272/ce60e646-c9ea-4577-8764-5f46bb322e9c)

Version Information:
 - Mod Version: 3.0.0.6
 - Forge Version: 47.2.19

https://pastebin.com/rv0ZXY8z

Additional information:

The problem mainly occurs with physics-mod-pro (Version 3.0.10) installed. We have 80+ other mods installed and out of them all, physics was the only one really doing anything. I don't know if that has something to do with a confliction issue or what, especially since I would never expect MNA to ever be compatible with Physics or vice-versa.

**Comment by Mithion** [comment]
Okay, I've gone through the entire render code for the Deathcap and it doesn't reference the RenderSystem class anywhere in the entity or the renderer.  

Thus, given that:

1. It doesn't happen with just M&A
2. It only happens with physics-mod-pro and it's explicitly referenced in the crash log:

at net.diebuddies.minecraft.ParticleSpawner.spawnServerBlockPhysicsParticle(ParticleSpawner.java:223) ~[physics-mod-pro-v164-forge-1.20.1.jar%23280!/:3.0.10] {re:mixin,re:classloading}

also mentioned there is Embeddium, but that's mixins and  they seem to be everywhere, I can confidently say that this is not an M&A bug.  If physics mod pro is doing some shenanigans with multi-threading, it'll be up to them to fix.
