### ISSUE TITLE
Shrink Works On Every Faction Except Fey And Is Infinite For Them

### ISSUE THREAD

**Issue by Voidpexx** [Mithion/Mana-And-Artifice#687]
**Describe the bug**
Shrink does not work on fey. but works on every other faction and has an infinite duration for them.

**To Reproduce**
1. Create a shrink spell with any shape
2. Set your faction to fey
3. Cast the spell to affect yourself
4. You will not shrink
5. Set your faction to any of the others
6. Cast the spell again
7. Receive the shrink status effect with an infinite duration

**Expected behavior**
Shrink should apply for the set duration to all factions except fey. And should be infinite on fey

**Version Information**
 - Mod Version: [1.20.1-3.0.0.6]
 - Forge Version [47.2.20]
 - GeckoLib [1.20.1-4.4.2]
 - Curios API [5.6.1+1.20.1]

**Additional context**
Nothing else is installed. Just MnA and its requirements

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.7
