### ISSUE TITLE
[1.19] Crash when casting the Manaweave Patterns at the 

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#688]
**Describe the bug**
[Crash report](https://gist.github.com/aaronhowser1/7f031391c34fc2ccc3ba142225c52f6b)

**To Reproduce**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/15698722/9825fc70-5586-402b-a47c-d8957b5a46fb)
I was at this stage and when I did my first pattern, it crashed. On restart, it doesn't crash.

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.6-all
 - Forge Version 43.3.5

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
