### ISSUE TITLE
[1.19] Killing the Fairy Queens gave me a broken Arcane Thesis

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#689]
**Describe the bug**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/15698722/a5ed78ed-d0f7-403f-a24f-3bae2e5a8843)

I made a new creative world and used commands to reach tier 5 and set faction to the Council. Then I teleported to the fairy tree place and summoned and killed the queens with strength 100 to make it faster. The Arcane Thesis I got is apparently broken.

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.6-all
 - Forge Version 43.3.5

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
