### ISSUE TITLE
[1.19] Wither Lich is impossible to kill, it just vanishes instead

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#690]
**Describe the bug**
Video linked

**To Reproduce**
1. Buff yourself to make it go faster
2. Spawn it either via commands or ritual
3. Kill it
4. Observe that it disappears

**Expected behavior**
For the boss fight to either continue or for it to drop its loot

**Screenshots**
Video file is too big for github but it's on the discord [here](https://discord.com/channels/398610095585624074/721815052478316626/1202380008761335849)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.6-all
 - Forge Version 43.3.5

**Comment by Mithion** [comment]
Boss dropped the loot every time I tried this.  How were you killing it?
