### ISSUE TITLE
Braclet of trickery does not make you invisible to players

### ISSUE THREAD

**Issue by Voidpexx** [Mithion/Mana-And-Artifice#691]
**Describe the bug**
Shifting with the bracelet of trickery disables your first person model and turns off mob detection but does not make you invisible, players can still see you, and if you go in third person you can see yourself

**To Reproduce**
1. Be a part of the fey faction
2. Acquire the bracelet of trickery
3. Charge the bracelet with a sufficient amount of mana
4. Equip the bracelet
5. Have a friend/alt connect to your world/server
6. Hold shift to activate the bracelet
7. Other players can see you and you are visible in F5

**Expected behavior**
Shifting with the bracelet equipped should make you invisible

**Version Information:**
 - Mod Version: 1.20.1-3.0.0.6
 - Forge Version: 47.2.20
 - Curios API Version: 5.6.1+1.20.1
 - GeckoLib Version: 1.20.1-4.4.2

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
