### ISSUE TITLE
[1.20.1] Failed to load model, no value present.

### ISSUE THREAD

**Issue by border999** [Mithion/Mana-And-Artifice#692]
**Describe the bug**
See title.

**Expected behavior**
Load model without issue.

**Screenshots**
![Screenshot 2024-02-02 115616](https://github.com/Mithion/Mana-And-Artifice/assets/11824584/fcc6cea7-cb83-4cc1-85fe-e4d9ade1ca44)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.6-all
 - Forge Version: 1.20.1-forge-47.2.20

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
