### ISSUE TITLE
[1.20.1] Disenchanter is causing anonymous crash

### ISSUE THREAD

**Issue by Captaincrikey001** [Mithion/Mana-And-Artifice#694]
Description:
This occurs whenever you put down a disenchanter and start it up. After around 1-6 minutes, the game will crash with no crash report, nor any warning whatsoever.

1. Place down a disenchanter.
2. Start it up and let it go.
3. Wait around 1-6 minutes.
4. The game will crash and not produce any crash.log.

Expected behavior:
The disenchanter, when started, should be awaiting eldrin power in order to complete and not thanos snap my game.

Screenshots:

![2024-02-05_07 01 56](https://github.com/Mithion/Mana-And-Artifice/assets/156194272/5b815ab1-8160-4fd5-932d-d10e8a896437)
![image](https://github.com/Mithion/Mana-And-Artifice/assets/156194272/4ab7d4f2-e8a8-4bfe-8083-ea48b39e734a)

Version Information:
 - Mod Version: [3.0.0.7]
 - Forge Version [47.2.19]

Additional context
Tried with and without other mods, and can confirm it's MNA only.

**Comment by Mithion** [comment]
Please post latest.log and debug.log; they may contain vital information to help me fix this bug faster.  They should exist even if a crash report isn't generated.

**Comment by Captaincrikey001** [comment]
[latest.log](https://github.com/Mithion/Mana-And-Artifice/files/14196422/latest.log)

[debug.log](https://github.com/Mithion/Mana-And-Artifice/files/14196426/debug.log)

**Comment by Mithion** [comment]
I should have been more clear; delete these files from your system, launch the game, make it crash, then post these files.
Is that what was done in this case?  If not, please post updated files as per these updated instructions. 

Thanks!

**Comment by Captaincrikey001** [comment]
Latest.log: https://hastebin.skyra.pw/undefined.swift

Debug Log: [debug.log](https://github.com/Mithion/Mana-And-Artifice/files/14203833/debug.log)

Okay sorry. Me is dumb dumb at times. XD Hope this helps.

**Comment by Mithion** [comment]
And after that log it crashed?

I don't see a single thing in the logs; not even a stack trace indicating a crash.  I ran MC just standing next to a Disenchanter that was running (waiting for power) for about 20 minutes and it didn't crash.  Tried first person, third person, looking at the block, not looking at the block, menu open, menu not open.

This, combined with a lack of a stack trace leads me to believe this issue isn't related to M&A.  As a next step I would recomment ensuring your JVM is up to date and that you have all of your latest drivers/system updates installed as well.  Same with Curios and GeckoLib, but I doubt they're the cause here either.

If you're on Windows and are more of a technical user, you can check the event log to see if maybe it has some additional information that might be helpful.

**Comment by Captaincrikey001** [comment]
I'll do it all, anyways. It'll take a while, but I'll let you know how it goes.

**Comment by Captaincrikey001** [comment]
So, I gave it some more tests, and I tried placing multiple Disenchanters down and having them all going at once.

The more that are placed down and activated, the faster the game crashes.

Trying it with one crashed my game within 2 mintues and 7 seconds.

Trying it with around 7 crashed my game in 25 seconds on the dot.

And to clarify, it's just the disenchanter. No other workstation from MNA is causing it.

**Comment by Captaincrikey001** [comment]
Fixed. All we had to do was change our Java Runtime from OpenJDK Platform to Oracle. 

Well, kinda fixed in that case I guess, but regardless, you can close now if you want.

**Comment by iUltimateLP** [comment]
Hey! My friend has recently encountered a similar issue and I assume it might be linked to this one, as the outcome is very similar, so asking @Mithion to reopen. We've identified the log file [`hs_err_pid18728.log`](https://hastebin.skyra.pw/obiwacuxuq.prolog).

Relevant is probably:
```
Current thread (0x000002474755c020):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=14784, stack(0x000000dc7c600000,0x000000dc7c700000)]


Current CompileTask:
C2: 317219 54860       4       com.mna.blocks.tileentities.wizard_lab.DisenchanterTile::spawnParticles (298 bytes)

Stack: [0x000000dc7c600000,0x000000dc7c700000],  sp=0x000000dc7c6fb8f0,  free space=1006k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x2be0a9]
V  [jvm.dll+0x21ba8b]
V  [jvm.dll+0x21944b]
V  [jvm.dll+0x1a56b6]
V  [jvm.dll+0x2291ea]
V  [jvm.dll+0x22724c]
V  [jvm.dll+0x7efd0c]
V  [jvm.dll+0x7ea13a]
V  [jvm.dll+0x67ad85]
C  [ucrtbase.dll+0x29363]
C  [KERNEL32.DLL+0x1257d]
C  [ntdll.dll+0x5aa58]


siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000000028
```

If more info is necessary, I'll be happy to provide! Thanks.
