### ISSUE TITLE
[1.20.1] Server crashes with newest Mana & Artifice Version

### ISSUE THREAD

**Issue by Kantharr** [Mithion/Mana-And-Artifice#695]
I recently updated the version of Mana & Artifice on my personal minecraft server to the newest (3.0.0.7) and the server now crashes with the following error message:

java.lang.NullPointerException: Cannot invoke "com.mna.api.faction.IFaction.getAlliedFactions()" because the return value of "com.mna.api.capabilities.IPlayerProgression.getAlliedFaction()" is null

We do have other mods installed like Xaero's Minimap, Xaero's Minimap & World Map - Waystones Compatibility [Forge], Waystones, Xaero's World Map, etc.

My friend that is accidentally causing the server to crash believes that it's an issue with his Council Sanctum that we made. If we revert the mod to the previous version (3.0.0.6) the crash would no longer occur. I do see in the detailed walkthrough of the error that it mentions the Circle of Power block which I'm guessing is related to the Council Sanctum. I personally haven't played the mod yet but my friend has been mainly playing that lol.

 - Mod Version: [3.0.0.7]
 - Forge Version [47.2.0]
 
Below is the full crash report:
[crash-2024-02-06_16.18.50-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14186878/crash-2024-02-06_16.18.50-server.txt)

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
