### ISSUE TITLE
[1.20.1] M&A + MrCrayfish's Gun Mod Crash

### ISSUE THREAD

**Issue by PSeaver** [Mithion/Mana-And-Artifice#697]
**Description**
Game crashes after shooting M&A mobs (Witch Hunter, Hulking Zombie, etc.) with guns from MrCrayfish's Gun Mod [Unofficial].

**To Reproduce**
1. Obtain a gun from MGM (rifle, shotgun, etc.)
2. Use the gun on M&A monsters.
3. Eventually, the game will freeze and crash as soon as a bullet hits a M&A mob. 

**Expected behavior**
I expected the M&A mobs to take damage and/or die when shot.

**Version Information:**
 - Mana and Artifice: 3.0.0.6
 - Geckolib: 4.4.2
 - Curios API: 5.6.1 + 1.20.1

 - Forge Version: 47.2.0

**Additional context**
Other Mods:
 - [MrCrayfish's Gun Mod [Unofficial]](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod-unofficial): 1.4.8
 - [Framework](https://www.curseforge.com/minecraft/mc-mods/framework): 0.6.16

The number of mobs that have to be attacked before the crash occurs seems to vary. When trying to reproduce this error myself, I have had it occur within attacking around 3 mobs. Other times, it has taken longer, but not more than a few minutes at most.

Crash report: https://pastebin.com/Swv7Wc6h

**Comment by PSeaver** [comment]
The crash also happens in the latest versions of both mods (MNA: 3.0.0.7, MGM: 1.4.10). Crash log here: https://pastebin.com/tcc2YyT8

**Comment by Mithion** [comment]
It's strange, it is attempting to get a value immediately after setting it, but getting null which shouldn't happen.
I refactored how this is handled so that it shouldn't crash anymore.  It'll go out with the next update.

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
