### ISSUE TITLE
Item renderer in custom Codex tabs need to move one pixel to the left

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#698]
**Describe the bug**
The item renderer for custom Codex category ribbons is one pixel off. It just needs a lil' scoot.

**To Reproduce**
Create a custom recipe category and open the codex.

**Expected behavior**

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/c9d37422-b103-4bf2-9a89-ef31de7d7448)

**Version Information (please complete the following information):**
 - MnA 3.0.0.7

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.
