### ISSUE TITLE
I translated your mod into Russian for version 1.19.2. can you add this translation to the mod?

### ISSUE THREAD

**Issue by Nikita-nikk** [Mithion/Mana-And-Artifice#699]
I made the translation and checked it works, maybe it's not correct, but everything seems to be fine.

[ru_ru.json](https://github.com/Mithion/Mana-And-Artifice/files/14221319/ru_ru.json)

**Comment by MangriMen** [comment]
Want it too

**Comment by Mithion** [comment]
Thank you!  I've added it to the resource files so it will be included with the next update of the mod.

**Comment by Mithion** [comment]
This was added in version 3.0.0.8.

**Comment by Mark2200** [comment]
will the guide book be translated?

**Comment by Rabbi-T-Rodjer** [comment]
> will the guide book be translated?

Yeah. This translation took a long time, and it's not very artistic, but it's understandable.
https://github.com/Mithion/Mana-And-Artifice/issues/850

**Comment by justGyga** [comment]
> > will the guide book be translated?
> 
> Yeah. This translation took a long time, and it's not very artistic, but it's understandable. #850

How to add your json in mod?
