### ISSUE TITLE
Vinteum Ore isn't smelted in the Blast Furnace.

### ISSUE THREAD

**Issue by deltaburst** [Mithion/Mana-And-Artifice#7]
Vinteum Ore isn't smelted in the Blast Furnace.
![image](https://user-images.githubusercontent.com/66882559/84575854-b9a45900-ad86-11ea-9d98-c09eba0ff0be.png)

**Comment by deltaburst** [comment]
Neither are vinteum-coated iron ingots.

**Comment by Mithion** [comment]
Resolved in 1.0.1-pre1
