### ISSUE TITLE
The guidebook problems after loading chinese language file

### ISSUE THREAD

**Issue by TUsama** [Mithion/Mana-And-Artifice#70]
At first, I used the resource pack to load the Chinese lang file, and I found something that should not happen.

1. 

~~the Basic section and the manaweaving section will show out on the same page, this will only happen every time you open the guidebook. But when you check out another page and then go back, it'll show this page normally.~~

2. the guidebook file seems cannot load dynamically. If you unload the Chinese translation pack, you need to restart the game to refresh what your guidebook show, even reenter your save the guidebook still show English, but the lang file can load dynamically.

3. ~~the section of artifice, constructs, enchantments don't show anything even I'm in tier 3. I double-check my file form, but I can't find anything different between your file form and my.~~

here is the Chinese translation pack. You can try to load it if you want to do some tests.

[am3.zip](https://github.com/Mithion/Mana-And-Artifice/files/5174173/am3.zip)

I found that I left a place which should be filled, so the guidebook produced the bugs. but the book still cannot load dynamically.

**Comment by TUsama** [comment]
I found two hard-code strings:

![image](https://user-images.githubusercontent.com/21279092/92318334-5b151100-f03d-11ea-8143-9f1e4bdf693e.png)

**Comment by Mithion** [comment]
it should be better in 1.0.7.1, but I'm not closing this issue at this point.  I'd say 1.0.7.1 progressed more towards a fix on this issue but likely hasn't fully fixed it yet.

**Comment by TUsama** [comment]
It's so weird, I have tried some ways to load the lang file, only one way that replaces the guidebook_en_us.json can work. I'm not sure the bug is about the loading problem or the name problem.

[am3.zip](https://github.com/Mithion/Mana-And-Artifice/files/5229109/am3.zip)

you can use this to test by yourself.

**Comment by Mithion** [comment]
The codex can now be translated and loads languages properly with all fallbacks.
