### ISSUE TITLE
[1.18.2] Construct activate block lodestar command makes the player interact with the block

### ISSUE THREAD

**Issue by Red1004** [Mithion/Mana-And-Artifice#700]
**Describe the bug**
When having a construct interact with a useable block, the game thinks that the player was the one that made the interaction and has the effects directed to the player. So if I were to have a construct interact with a chest, the chest UI would open up on my screen, or if I were to have it interact with a pedestal, it would pull the item from my hand instead of the constructs

**Steps to reproduce the behavior:**
1. make a construct
3. get a lodestar
4. set lodestar to activate a useable block (ie chest, furnace, crafting table)
5. bind construct to lodestar
6. wait for construct to act
7. see results

**Screenshots:**
Can't really do screenshots for this so I'll just do a video.
https://youtu.be/QfuCJxbAm90

**Expected behavior**
At least for the pedestals, I expected the construct to either grab the item from the pedestal, or place the item in it's hand on the pedestal.

**Version Information:**
 - Mod Version: 2.0.0.33
 - Forge Version: 40.2.17

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
