### ISSUE TITLE
Living wrad causes server crash

### ISSUE THREAD

**Issue by Halfisland** [Mithion/Mana-And-Artifice#701]
Living ward causes server crash.
No idea how this happened.

Minecraft Version:1.18.2
MNA Version:2.0.0.33

![OR_{L6R)GUN`$0XGQHE`_CW](https://github.com/Mithion/Mana-And-Artifice/assets/159912757/01cd2a8c-ffbf-4c10-9801-7863d09d7c57)

[crash-2024-02-13_19.31.59-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14261677/crash-2024-02-13_19.31.59-server.txt)

**Comment by Mithion** [comment]
Not an M&A issue - tested by spawning a Living Ward and dropping it in lava.
"Unhandled Damage" sounds like something some other mod is doing.
