### ISSUE TITLE
[1.20.1]There are some problems with aura enchantment .

### ISSUE THREAD

**Issue by Wandering-L-Cloud** [Mithion/Mana-And-Artifice#702]
First,  aura of the depths lead to crash of game when I touch water wearing chest armor with the enchantment.
Second, though it can show forge icon, aura of the depths can't be possessed by chest armors and Aura of jumping has the same condition. The icon will disappear and reappear with one tap after another. Maybe all aura enchantment have the same problem. What's more, if an aura enchantment has been possessed  by a chest armor,  maybe it will lead to crash when it produces effect, for example, the first problem.

**Screenshots**
![2024-02-15_22 38 54](https://github.com/Mithion/Mana-And-Artifice/assets/151632590/9404a680-5cae-4a9e-b9bf-0edb0781b9df)
![2024-02-15_22 38 57](https://github.com/Mithion/Mana-And-Artifice/assets/151632590/5c3e997a-ffd4-420a-a0e8-704dbce5559b)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.8]
 - Forge Version [47.2.20]

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.9
