### ISSUE TITLE
Constructs start their swimming animation in any water depth

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#703]
**Describe the bug**
A construct will start its swimming animation even when it's in _comically_ shallow water puddles.

**To Reproduce**
Place a water source a few blocks away from a construct and watch the animation start.

**Expected behavior**
I would expect the construct to get pushed by the fluid and remain standing.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/06275def-b5c6-4a4a-9688-2a657c90472a)

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.8]
 - Forge Version [e.g. 47.2.20]

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
