### ISSUE TITLE
Has Fluid Level parameter untranslated

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#704]
**Describe the bug**
The parameter description in the Has Fluid Level construct task is untranslated.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/e6f48bd0-0a89-4bc3-bb7d-bf68022dfce5)

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.8]

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
