### ISSUE TITLE
council island eldrin conduits

### ISSUE THREAD

**Issue by LoneWolf137** [Mithion/Mana-And-Artifice#705]
**Describe the bug**
the eldrin conduits dont place, they drop as items.  and the cathedral is waterlogged if it spawns near a river/the ocean. Dont know if there is anything you can do about the later, i dont know how structure generation works.

**To Reproduce**
1. load a world
2. go to coucil island

**Expected behavior**
they are placed as block, which would also look very nice. 

**Screenshots**
![2024-02-21_13 29 26](https://github.com/Mithion/Mana-And-Artifice/assets/42692808/85c3f206-094a-4da1-8c55-00b587cd230a)

**Version Information :**
- Forge: 47.2.0
 - mna: 3.0.0.9
- geckolib: 4.4.2
- curios: 5.7.0

i tested this with mna on its own (plus curios and geckolib, but do they even count?)

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
