### ISSUE TITLE
MnA 1.19.2 MnA Flowers Duplication Glitch (May be intended?)

### ISSUE THREAD

**Issue by SangurianSoul** [Mithion/Mana-And-Artifice#709]
**Describe the bug**
You may place any of of the flowers added by MnA into a flowerpot. Upon Right clicking, you receive another flower. This may be repeated as many times as you wish.

**To Reproduce**
1. Any Tier or Magic level.
2. put any MnA flower in flower pot.
3. right click for infinite flowers.

**Expected behavior**
Not having infinite duplicating flowers? Unless this is entirely intended...

**Version Information (please complete the following information):**
 - mna-forge-1.19.2-2.1.0.6-all
 - forge-1.19.2-43.3.5

**Comment by Mithion** [comment]
Resolved in 3.0.0.10 for 1.20

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
