### ISSUE TITLE
MnA 1.19.2 Runeforge doubling doubles vinteum ingots. (may be intended?)

### ISSUE THREAD

**Issue by SangurianSoul** [Mithion/Mana-And-Artifice#710]
**Describe the bug**
A runeforge with the appropriate chimerite crystal to perform ore doubling will double vinteum coated iron into 2 vinteum ingots. This can be further doubled by placing the vinteum ingots back in and getting double super-heated vinteum.

**To Reproduce**
Pretty much as explained above.
1. Runeforge with appropriate chimerite crystals on pedestals. I used red.
1. Place 1x vinteum coated iron ingot, once done, receive 2x vinteum ingots
3. Place 1x (or more) vinteum ingots in forge, once double, receive double the amount in super-heated vinteum ingots.

**Expected behavior**
Not having several stages of duplication? Unless this is entirely intended...

**Version Information (please complete the following information):**
 - mna-forge-1.19.2-2.1.0.6-all
 - forge-1.19.2-43.3.5

**Comment by Mithion** [comment]
This is intended functionality, yes - the Runeforge is a useful setup!
