### ISSUE TITLE
Eldrin alter crashes the server everytime a player join after restart of the server

### ISSUE THREAD

**Issue by Charcoal118** [Mithion/Mana-And-Artifice#711]
**Describe the bug**
I was hosting a multiplayer world with my friends with 75 mods in total. I stopped the server after everyone left and one person had just finished crafting something with the eldrin alter. When the next time I started up the server and I join, the server crashes.

**To Reproduce**
1. Get item 'eldrin alter'
2. Use in multiplayer
3. Restart the server
4. A player joins
5. Crashes

**Expected behavior**
It crashes as soon as I join.

**Screenshots**

**Version Information (please complete the following information):**
[minecraft version: 1.18.2]
[forge version: 40.2.14]

**Additional context**
 [crash-2024-02-25_17.23.02-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14395962/crash-2024-02-25_17.23.02-server.txt)

**Comment by norfaremc** [comment]
Confirmed, having the same issue in 1.19.2

**Comment by EtherChicken** [comment]
Having the same issue in 1.20.1, only happens if the altar is loaded in, i.e. being in the nether while altar is in overworld works fine, but as soon as you go back through a portal it crashes the server.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
