### ISSUE TITLE
Emitter using Enchantment now crashes local clients

### ISSUE THREAD

**Issue by biggayenergy** [Mithion/Mana-And-Artifice#712]
**Describe the bug**
When loading a chunk that has Emitters on them with the Enchantment type, the client crashes.

**To Reproduce**
1. Get to chunk where 5 emitters are active with enchantment type particle effect.
2. When the chunks load, client crashes

**Expected behavior**
The client should be able to handle it

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.9
 - Forge Version 47.2.0

**Additional context**
Crash Report https://pastebin.com/0ra7aexM

**Comment by Mithion** [comment]
Resolved in 3.0.0.10
