### ISSUE TITLE
You can get the Soaked effect while a spectator

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#713]
**Describe the bug**
While in spectator mode, fly through water and you get the Soaked effect and start dripping particles

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.19.2-2.1.0.6-all
 - Forge Version 43.3.8

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
