### ISSUE TITLE
A Strange record disk broken

### ISSUE THREAD

**Issue by Dan1ss1mo** [Mithion/Mana-And-Artifice#715]
**A Strange record disk doesn't work**
Inserting A Strange record disc in a jukebox in creative does nothing. Doing so in survival make the disk disappear

**To Reproduce**
1. Get you're self a jukebox
2. Get you're self A Strange record disc
3. Try to insert it in jukebox in any of those gamemodes
4. No music(and no disk) ;-(

**Expected behavior**
A lovely music to vibe with my construct friends

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.2], [3.0.0.5] & [3.0.0.9]
 - Forge Version [47.2.0]

**Additional context**
Really love this feature. The music is lovely and constructs dancing with it are adorable. ❤️

**Comment by Mithion** [comment]
Resolved in 3.0.0.10

**Comment by Dan1ss1mo** [comment]
thank you! 🎉
