### ISSUE TITLE
Ring of enderman bug

### ISSUE THREAD

**Issue by Dan1ss1mo** [Mithion/Mana-And-Artifice#717]
**Ring of enderman bug let you cast time stop**
Using ring of enderman causes several different issues
1) you either get this message
![image](https://github.com/Mithion/Mana-And-Artifice/assets/112878543/f3484175-2ccb-4471-8dfe-07ebab03ef83)
2) teleport on the same place as you were
or
3) server just dies (finally - permanent time stop)

**To Reproduce**
1. Get Ring of enderman
2. Get self blink spell with any range
3. Use it untill server dies

**Expected behavior**
Teleporting for doable the distance, ignoring enderman ring altered blink behaviour for self shape or spell just doing nothing and info popup about self shape not being compatible with the ring

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/112878543/8d780a47-1dad-49b6-ae43-49f763c83f0e)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.10]
 - Forge Version [47.2.0]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
This was resolved in 3.0.0.11
