### ISSUE TITLE
Incorrect slugs in T4 conduit recipes

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#718]
**Describe the bug**
Recipes for the T4 conduits are looking for, for example, "mna:lesser_conduit_water" instead of "mna:lesser_eldrin_conduit_water". T4 conduits are uncraftable.

**Bandaid**
[eldrin_conduit_recipe_fix.zip](https://github.com/Mithion/Mana-And-Artifice/files/14488595/eldrin_conduit_recipe_fix.zip)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.10

**Comment by Mithion** [comment]
This was resolved in 3.0.0.11
