### ISSUE TITLE
[1.20.1] Incompatibility with Immersive Portals using Sinytra Connector

### ISSUE THREAD

**Issue by SnackJunkie** [Mithion/Mana-And-Artifice#719]
**Describe the bug**
After travelling through an immersive portal, no spells can be cast until the game is reloaded

**To Reproduce**
1. Travel through an immersive portal (tested with nether portal)
2. Attempt to cast a spell

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.9
 - Forge Version 47.2.0

**Additional context**
Sinytra Connector: 1.0.0-beta.36+1.20.1
Forgified Fabric API: 0.92.0+1.11.1+1.20.1
Immersive Portals: 3.3.7
Curios API: 5.7.0+1.20.1
GeckoLib 4: 4.4.2

**Comment by SnackJunkie** [comment]
No errors or warnings are logged either when travelling through the portal or when attempting to cast a spell afterward

**Comment by SnackJunkie** [comment]
Just updated mods, confirmed issue still present.
Sinytra Connector: 1.0.0-beta.37+1.20.1
Forgified Fabric API: 0.92.0+1.11.3+1.20.1
Mana and Artifice: 3.0.0.10

**Comment by Mithion** [comment]
This will be related to Sinytra Connector or Forgified Fabric.  Essentially there's an event somewhere that re-sets up the capabilities that isn't being called.  This is on them to fix.
