### ISSUE TITLE
Tome of recipes visual bug

### ISSUE THREAD

**Issue by Dan1ss1mo** [Mithion/Mana-And-Artifice#720]
**No icons in Tome of recipes**
Reciped in Tome of recipes don't have any icons

**To Reproduce**
1. Get Tome of recipes
2. Add any recipe in it
3. observe

**Expected behavior**
Wish they would have them

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/112878543/5eb779ac-400f-44e9-8c26-da27f5e732a9)
(it's actually full of recipes)
**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.10]
 - Forge Version [e.g. 47.2.0]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
This was resolved in 3.0.0.11
