### ISSUE TITLE
[1.20.1] [Feature] Disable Soaked status per config

### ISSUE THREAD

**Issue by Maruhl** [Mithion/Mana-And-Artifice#722]
**Is your feature request related to a problem? Please describe.**
I don't know if it's a bug or if it's intentional. I have quite a few mods. For example, if I have the complete armor from AquaCulture2 on and am completely in the water, you can't move normally - or extremely slowly. This armor is for the water.

**Describe the solution you'd like**
I would like to be able to switch off this status effect completely.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Xplodin** [comment]
how does this work? I cant find any config for mna that does this
