### ISSUE TITLE
Levitation bug

### ISSUE THREAD

**Issue by Dan1ss1mo** [Mithion/Mana-And-Artifice#723]
**Describe the bug**
Permanent levitation buff doesn't work

**To Reproduce**
1. Get self levitation spell
2. Get a bunch of tarma roots and feathers
3. cast and observe

**Expected behavior**
levitation working while buff is applied for listed period of time

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/112878543/273256d3-e99d-4a22-9cea-15c9cec0014f)
Got the buff, everything works as it should
![image](https://github.com/Mithion/Mana-And-Artifice/assets/112878543/6168d7b5-a00e-4331-8c98-3519388892e9)
spell consumed two roots, gave me the buff but none of the levitation effects actually work
![image](https://github.com/Mithion/Mana-And-Artifice/assets/112878543/4b5c044a-8e1f-424f-a580-135969e57a49)
after taking fall damage i got temporary version of buff wich does work fine

casting spell again to remove buff also consumes one root and feather

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.10]
 - Forge Version [47.2.0]

**Additional context**
Tested it with jump boots, Spider climbing and water walking and it seems to work as intended with both permanent and regular version.

**Comment by Mithion** [comment]
This was resolved in 3.0.0.11
