### ISSUE TITLE
[1.20.1] Villager locked to only 1 trade

### ISSUE THREAD

**Issue by Aenodarr** [Mithion/Mana-And-Artifice#726]
**Bug itself**
The bug makes all villagers have only 1 trade per profession and doesn't switch trades when the trading station is replaced.
For example librarian always has the trade for paper and bookshelves (see in screenshots.) and doesn't change at all.

**To Reproduce**
1. Get a villager
2. Place a workstation - check trade
4. Replace a workstation - check trade again
5. In my case the result is no matter how many times the workstation is replaced the trade stays the same on every villager

**Expected behavior**
In vanilla villagers trade are not changed only at night or after a trade, however all the other time trades should be switched when replacing a workstation

**Screenshots**
Librarian trade:
![image](https://github.com/Mithion/Mana-And-Artifice/assets/129336492/5b6307dc-810f-40e1-9cee-44918c6267c7)

Mods installed while checking the bugs:
![image](https://github.com/Mithion/Mana-And-Artifice/assets/129336492/08409a80-7787-4cfc-844e-9ead8d44d93f)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.8] and [3.0.0.10]
 - Forge Version - [47.2.20]

**Additional context**
I'm using ATLauncher so it might play have some trouble with the mod however I'm not sure

**Comment by Dan1ss1mo** [comment]
that isn't a bug, there is a server config option which nerfs librarians. if it enabled 1 and second 2 will be the same, and they should sell enchanted books from level 3

**Comment by Aenodarr** [comment]
> that isn't a bug, there is a server config option which nerfs librarians. if it enabled 1 and second 2 will be the same, and they should sell enchanted books from level 3

Perhaps i'm mistaken, but i haven't found anything about that in the config (i'll double check when i return home), but from my testing other professions had the same problem, so i'll test things out again and write back

**Comment by Dan1ss1mo** [comment]
it is in you're world save, in serverconfig folder

**Comment by Aenodarr** [comment]
Oh, yes, you were right, i didn't know that the mod modified villager trades, so I thought it's a bug. I've changed the setting and everything works fine, thanks a lot!

**Comment by akajhomel** [comment]
howhow did you fix it?

**Comment by Aenodarr** [comment]
As stated above, you need to go into the world save and look for a server config, there'll be smth like "trader rebalance" (probably not in those exact words) you just replace "true" with "false" and it should work
--
Sent from  Mail app for Android Monday, 07 October 2024, 05:13am +03:00 from akajhomel  ***@***.*** :

**Comment by akajhomel** [comment]
> As stated above, you need to go into the world save and look for a server config, there'll be smth like "trader rebalance" (probably not in those exact words) you just replace "true" with "false" and it should work -- Sent from Mail app for Android Monday, 07 October 2024, 05:13am +03:00 from akajhomel ***@***.*** :
> […](#)
> how did you fix it? — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you modified the open/close state. Message ID: @ github . com>

yeahhh was that, thnkss
