### ISSUE TITLE
Tier-up advancement does not trigger when joining Demons

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#727]
**Describe the bug**
When joining the Demon faction, the player does not get the advancement for hitting Tier 3.

**To Reproduce**
1. Hit tier 2 and fill out enough Occulus tasks to tier up
2. Do the Ritual of the Burning Hells
3. Check your Advancements list and notice that _Journeyman_ isn't there.

**Expected behavior**
The player gains the _Journeyman_ advancement when hitting Tier 3 regardless of faction

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/cc16b0ed-8c4c-42b0-8866-82bd27e9c68e)
![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/1a9283ac-02bd-4d31-bf9b-bd890eb0d541)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.10

**Additional Context**
Tested the Council, Undead, and Fey rituals; the advancement is gained in all of these other cases.

**Comment by Dan1ss1mo** [comment]
my friend who was playing as demon successfully reached tier 3 as a demon on 3.0.0.9, in case that may be helpful

**Comment by AranaiRa** [comment]
Oh, internally the affected player hit tier 3. They just didn't get the advancement at the time of doing the ritual.

Further context I just learned, they were given the advancement later when they died.

**Comment by Mithion** [comment]
Just did it, worked fine.
