### ISSUE TITLE
Severe Server Lag Caused by Mana and Artifice Mod on Minecraft 1.20.1 Forge

### ISSUE THREAD

**Issue by codec-d** [Mithion/Mana-And-Artifice#728]
**Describe the bug**
The Mana and Artifice mod is causing significant server lag on a Minecraft 1.20.1 Forge server. Profiling shows that several of the mod's methods, especially those related to entities and AI, are consuming a large percentage of the server's processing time.
there are no mna flying mobs during issue.

**To Reproduce**
unclear on how to reproduce, large server. see penumbralcraft modpack.

**Expected behavior**
The mod should not consume an excessive amount of the server's processing power or cause noticeable lag during normal gameplay.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/58233486/d5ecca62-f722-4005-aa43-c5fdfaf9f034)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.10-all
 - Forge Version 47.2.17

**Additional context**
The top contributors to lag from the Mana and Artifice mod are:

com.mna.entities.faction.base.BaseFlyingFactionMob.readAdditionalSaveData() at 27.41%
net.minecraft.world.entity.ai.attributes.AttributeMap.load() at 27.36% (called from multiple places within the mod)
it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.put() at 14.49% (likely used heavily by the mod)
it.unimi.dsi.fastutil.objects.ObjectArraySet.add() at 12.48% (also likely used heavily)

No other mods on the server are exhibiting similar performance issues at this time. Let me know if you need any additional information to investigate this issue.

**Comment by codec-d** [comment]
i'll add this seems directly related to pixies

**Comment by Mithion** [comment]
ReadAdditionalSaveData is called by base MC when the mob is loading.  This is something else affecting how attribute maps are loaded, and isn't related to M&A.  

I checked and there's nothing unusual going on with pixies / wraiths that other mobs don't also do; in fact the lag is coming from the base mob (and by extension living entity) reading their save data.

Something may be spawning far too many pixies, lantern wraiths, chatterers, or living wards.  Try using something like InControl or a datapack to reduce the spawn weights.  You should also investigate performance optimization mods you may be using, but I'd check the spawn rate thing first.
