### ISSUE TITLE
Right clicking on eldrin alter crashes game

### ISSUE THREAD

**Issue by PaulRacey** [Mithion/Mana-And-Artifice#732]
**Describe the bug**

*Error: java.lang.IndexOutOfBoundsException: null*
This is the error I get, this error occurs when I right-click the alter both in single player and on a server.
**To Reproduce**
1. Get alter
2. Right click with anything
3. game crashes

**Expected behavior**
Whatever the alter is meant to do I guess, I have not played this mod before:
I do see a bar appear on the last frame before a crash saying 'eldin alter: 0.0/0.0'

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/149918598/b6dbd5e3-946f-423e-bb0a-22199aaffdc5)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.10
 - Forge Version 47.2.0
 - Minecraft Version (1.20.1)
**Additional context**
I am using the 'Dragon Magic and Relics mod', but that is the only one I see directly interfacing with MNA
https://pastebin.com/CJ10CdA3

**Comment by Mithion** [comment]
This is likely related to either Flywheel or Oculus.  Try disabling those and see if the issue persists.

**Comment by Dan1ss1mo** [comment]
seem to work fine for me with Oculus at 3.0.0.11
