### ISSUE TITLE
All the models minecraft are black. What do I do?

### ISSUE THREAD

**Issue by MrSvyatik** [Mithion/Mana-And-Artifice#735]
All the models are black. What do I do?

![image](https://github.com/Mithion/Mana-And-Artifice/assets/92268579/4753ecef-03dd-462d-a130-1f4eba4af4b2)

**Version Information (please complete the following information):**
 - [mna-forge-1.20.1-3.0.0.11-all.jar](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/5204009)
 - Forge Version 1.20.1 - 47.2.21

**Comment by Mithion** [comment]
Remove optifine if you have it, make sure drivers are up to date, especially video.

Then try disabling other visual enhancement mods, though most should be fine with MnA.

**Comment by MrSvyatik** [comment]
I installed the mod myself and the same thing

**Comment by Mithion** [comment]
This is something related to your instance/setup, and isn't directly MnA.  Sorry, I can't help you.
