### ISSUE TITLE
1.20.1 Cantrip Gui Crash

### ISSUE THREAD

**Issue by wmcook32** [Mithion/Mana-And-Artifice#736]
**Describe the bug**
Game crashes when opening the Cantrip GUI with HammerLib installed.

**To Reproduce**
1. Get item 'Any Manaweaving Wand'
2. Open Cantrip GUI ctrl+rightclick
3. Crash

**Expected behavior**
Not to crash upon opening the GUI

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.11
 - Forge Version: 47.2.20

**Additional context**
If HammerLib is installed the crash happens.

[Pastebin Link](https://pastebin.com/RY0vt8dL)

**Comment by Mithion** [comment]
The issue is on hammerlib's end.  They will need to fix it.

**Comment by danlizard** [comment]
According to HammerLib dev in relation to the RecipeManagerMixin,
> I do not think there's anything related to recipe searching going on there. They (MnA) are literally missing if(patterns != null) check

Would you mind being more explicit about what the issue is in HammerLib, so we can play telephone between HammerLib and MnA dev teams?
