### ISSUE TITLE
water can flow through transitory tunnel blocks, deleting things

### ISSUE THREAD

**Issue by Hiagg** [Mithion/Mana-And-Artifice#737]
**Describe the bug**
transitory tunnel blocks get destroyed by flowing fluids. it is inconsistent however even in seemingly identical conditions with already settled fluid. but it happens 100% of the time if the fluid is actively flowing when you activate the tunnel, or if you break one of the tunnel blocks beneath a fluid

**To Reproduce**
1. use transitory tunnel with water source on top
2. hope it works?
 i am able to reproduce it at least once in a minute
4. blocks get destroyed

**Expected behavior**
everything to go back to as it was before using the tunnel

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.0.0.10
 - Forge Version 47.2.20

![image](https://github.com/Mithion/Mana-And-Artifice/assets/13358034/b03d115b-8744-49fe-91e7-74d59901dd11)
![image](https://github.com/Mithion/Mana-And-Artifice/assets/13358034/b4aee410-9f91-4c66-be98-62b76ffdc7b0)

**Comment by Mithion** [comment]
This is resolved in 3.0.0.12
