### ISSUE TITLE
projectile stays behind visually sometimes

### ISSUE THREAD

**Issue by LoneWolf137** [Mithion/Mana-And-Artifice#738]
make a projectile spell and use it a bunch. it seams to happen most often if you use it on entities, but i had it happen against blocks too. It appears to be happening in random intervals, as i have gone for 2min while continuously casting and non stuck and then a few in short succession.  component doesnt seam to matter, but i only tested lowest speed projectiles

1. make Projectile spell
2. Use it a bunch
3. it sometimes stays behind and doesnt do its thing when it does

**Expected behavior**

it does its thing and doesnt stick

**Screenshots**
![2024-03-26_01 55 13](https://github.com/Mithion/Mana-And-Artifice/assets/42692808/c7d78a1c-f2ed-4e46-9f48-af8448a389c2)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.11
 - Forge Version 47.2.0

**Comment by AranaiRa** [comment]
I can corroborate that this is happening in a friend's instance too.

**Comment by Mithion** [comment]
I just sat for 4 straight minutes spamming projectiles in all ways I could think of.  It didn't happen.  Likely something else in the instance is screwing with the ability for clientside entities to despawn.

I added an extra fallback despawn check and changed the logic on despawning in the hope that it fixes it, but that's all the time I'm putting into this without further information on how to replicate this issue with only MnA and dependencies.  

Closing, feel free to re-open or create a new issue if further information becomes available.
