### ISSUE TITLE
Lantern Wraiths spawning above bedrock in nether

### ISSUE THREAD

**Issue by Papaturts** [Mithion/Mana-And-Artifice#739]
**Describe the bug**
Have an excessive spawning of lantern wraiths in the nether

**To Reproduce**
1. Build gold farm above nether room
2. Use Gold farm and watch the zombie piglins slow to a crawl spawning
3. Drop to nether roof to 40+ Lantern Wraiths have spawned within minutes of starting the farm

**Expected behavior**
Gold farm to work
And mobs not able to spawn above nether roof

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.19.2-2.1.0.6]
 - Forge Version [e.g. 43.3.7]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.
![Screenshot_2024_03_25-1](https://github.com/Mithion/Mana-And-Artifice/assets/97408568/a5fe1ce3-5bd7-4dac-b3ac-e0387203c072)
![2024-03-25_20 51 44](https://github.com/Mithion/Mana-And-Artifice/assets/97408568/142f8957-3552-4764-a639-a1c2c49145c4)

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
