### ISSUE TITLE
Lingering Rituals

### ISSUE THREAD

**Issue by BlueMond** [Mithion/Mana-And-Artifice#74]
Version 1.0.7.1
-I don't know if it's already a known bug-

Steps to reproduce:
-When drawing most any ritual, let's say specifically talk about the ritual of arcana

-Activate the ritual with purified vinteum dust, either before or after throwing a spell recipe in the center spot

-The required reagents appear, the ritual is not yet running, because it was not yet activated again with the reagents in their spots. (Runes glowing)

-Break any of the runes in the ritual while the runes are active/glowing.

Problem that results:
-Ritual does not deactivate, as expected. The mod seems to believe that an active ritual is still there, regardless of the presence of the runes. Persistently floating reagent requirements remain, and the inability to perform another ritual in that location.

**Comment by Mithion** [comment]
Breaking the chalk runes while a ritual is in the guiding reagents phase will now cancel the ritual and destroy the entity.  This fix will go out with 1.0.7.2.

**Comment by BlueMond** [comment]
Nice work 👍
