### ISSUE TITLE
Construct can't insert items in to runic anvil.

### ISSUE THREAD

**Issue by Oggas** [Mithion/Mana-And-Artifice#740]
**Describe the bug**
Construct can't insert items in to runic anvil.

**To Reproduce**
1. Create full wooden construct; Basic torso, Basic Legs, Smart Head, Grabber arm, Hammer Arm using an armor stand and animus dust.
2. Program lodestar as follows: 2.1. Take item (from barrel with only Superheated vinteum ingots). 2.2. Place item (into runic anvil). 2.3. Forge rune. 2.4. Take item (from runic anvil). 2.5. Place item (into second barrel). 
3. Place rune pattern Aura onto runic anvil.
4. Connect construct to lodestar using the bell of bidding and allow it to run.

This was all done in a new creative world. Before I started I read the codex and set my tier to tier 2.

**Expected behavior**
In previous versions what would happen is the construct would grab a Superheated vinteum ingot from the barrel. Place it in to the runic anvil. Smith to create an Aura rune. Grab said rune and put it in to the second barrel.

So what happens is that the construct grabs the Superheated vinteum ingot and then tries to put it into the runic anvil but fails.

**Screenshots**

![2024-03-27_19 58 53](https://github.com/Mithion/Mana-And-Artifice/assets/165203923/5f5dc25b-83e0-407c-8465-06dd47c12501)
![2024-03-27_19 59 23](https://github.com/Mithion/Mana-And-Artifice/assets/165203923/f1637f12-55e4-4dc1-acfb-2d3e668f3a5a)
![2024-03-27_19 59 46](https://github.com/Mithion/Mana-And-Artifice/assets/165203923/deda2b51-4559-4302-bac7-f29fc6a237b8)

**Version Information (please complete the following information):**
 - Minecraft 1.20.1
 - Mana and Artifice 3.0.0.11
 - GeckoLib 4.4.2
 - Curios API 5.7.2
 - Forge Version 47.2.0

**Additional context**
This mod was reproduced using only the three mods above but was first encountered in a pack with more mods.

**Comment by Mithion** [comment]
This is resolved in 3.0.0.12
