### ISSUE TITLE
Dupe Mote of * with Refined Storage Addon

### ISSUE THREAD

**Issue by leSemaleon** [Mithion/Mana-And-Artifice#741]
When I use JEI and press the plus sign while in the wireless crafting grid from refined storage addon, the recipe is laid out and Mote of * appears without any crafting.

1. Open wireless crafting grid from refined storage addon
2. Press Plus in JEI promt for mote of earth, for example
3. See that in crafting grid appear materials for mote and itself mote
4. It can take mote without craft on manawearing table

![ZJnKMFtHf9](https://github.com/Mithion/Mana-And-Artifice/assets/101531959/39d9ccab-ccf2-4a9e-986c-a69d8b3590f9)
![M8Kdg6VzRX](https://github.com/Mithion/Mana-And-Artifice/assets/101531959/b38ecac5-fd4d-4bf4-b63c-ec910e61f2d1)
![7jIJrj41ca](https://github.com/Mithion/Mana-And-Artifice/assets/101531959/19860fb2-a409-4d1e-9221-b358a567076b)
![55PvjrztL3](https://github.com/Mithion/Mana-And-Artifice/assets/101531959/793e98d6-756a-4c50-9121-4e3b75f021fb)

**Version Information (please complete the following information):**
 - Mod Version: 1.5.1.7
 - Forge Version 36.2.39

**Comment by Mithion** [comment]
1.16.5 is no longer receiving bugfixes, this will not be worked on.
