### ISSUE TITLE
demon fortress chest not spawning properly

### ISSUE THREAD

**Issue by wolfbain5** [Mithion/Mana-And-Artifice#743]
**Describe the bug**
the chest at the top of the tower of the demon fortress isnt spawning independantly

**To Reproduce**
1. goto demon fortress and loot the top chest
2. goto a different demon fortress and check the loot chest in the top, it will either match what you left behind, or be empty if you emptied it

**Expected behavior**
the loot box to have its own loot

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.11]

**Comment by Mithion** [comment]
Please fill out all required information as per the intake form.
