### ISSUE TITLE
Can not capture Wellsprings

### ISSUE THREAD

**Issue by RandomGuyJunior** [Mithion/Mana-And-Artifice#744]
**Describe the bug**
After completing Wellspring structure, it still acts as if not captured.

**To Reproduce**
1. Find a wellspring
2. Build the structure around it until you get the completion message.

**Expected behavior**
Wellspring should be visible without ungent, conduits can access its power, and player should get charged as well.

**Screenshots**
![afbeelding](https://github.com/Mithion/Mana-And-Artifice/assets/42807509/e5eab377-f2ea-4f49-a6da-6b0ceb7a248c)
![afbeelding](https://github.com/Mithion/Mana-And-Artifice/assets/42807509/35081403-3912-40b8-88e6-ef0e4372e292)

**Version Information (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Version: 1.20.1-3.0.0.11
 - NeoForge Version: 47.1.96

**Additional context**
An entire list of mods:

**Library, API, and Utility mods:**
- Architecture API
- Bookshelf
- CoroUtil
- CreativeCore
- Curios API
- Cupboard
- FTB Library
- Fusion (Connected Textures)
- GeckoLib
- Iceberg
- OctoLib
- Placebo
- Puzzles Lib
- Supermartijn642's Config Lib
- YUNG's API

**UI and Sound mods:**
- Advancement Plaques
- Ambient Sounds 5
- Durability Tooltip
- Dynamic Crosshair
- Enchantment Descriptions
- Food Effect
- Journeymap
- Jade
- Just Enough Items
- Pick Up Notifications
- Sound Physics Remastered
- Travelers Titels

**Performance and Compatibility mods:**
- AttributeFix
- Dimensional Threading Reforked
- Embeddium
- Embeddium++
- FastSuite
- FerriteCore
- Krypton
- Let me Despawn
- Mobtimizations- Entity Performance Fixes
- modernFix
- Packet Fixer
- Polymorph
- Radium Reforged
- Redirector [modern]
- TexTrue's Embeddium Options

**World Generation mods:**
- Terralith
- YUNG's Better Desert Temples
- YUNG's Better Jungle Temples
- YUNG's Better Nether Fortresses
- YUNG's Better Ocean monuments

**main content mods:**
- Create
- Mana and Artifice

**Other mods:**
- Not Enough Animations
- Oculus
- Essential mod
- FTB Quests
- FTB Teams
- Nature's Compass
- Zume

**Comment by Mithion** [comment]
You cannot capture wellsprings without a faction.
If you're testing in creative, you can use '/mna progression faction ...' to pick one.

**Comment by Thunderheadz753** [comment]
I am having this issue but I am already in a faction. I make the structure but it doesn’t capture the wellspring. It adds to my generation bonus but I can’t draw any power. The fume filter works fine but I would rather not try jerry rigging an automated system for that.

**Comment by Vankrow** [comment]
Same happening here, Mana on 3.1.0.4 and 1.20.1 of Minecraft, I'm on survival mode in a private server with my friends and already in a faction
