### ISSUE TITLE
Crash with Agrofix

### ISSUE THREAD

**Issue by border999** [Mithion/Mana-And-Artifice#745]
**Describe the bug**
Crash related to agrofix https://www.curseforge.com/minecraft/mc-mods/aggro-fix

**To Reproduce**
Unknown.

**Expected behavior**
No crash.

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.11-all
 - Forge Version: 1.20.1-forge-47.2.21

**Additional context**
https://gist.github.com/border999/80833e713afbb075199f3fd651c31044

**Comment by Mithion** [comment]
Looks to be an issue on aggrofix's end.
If they have a blacklist, try adding the lantern wraith and the deathcap to it as a workaround.
