### ISSUE TITLE
Game closes when trying to exit wand spell interface.

### ISSUE THREAD

**Issue by border999** [Mithion/Mana-And-Artifice#746]
**Describe the bug**
After entering the Wand spell menu using the left control + right click combo, Attempting to exit the interface closes the game itself.

**To Reproduce**
1. Open the wand spell menu for a wand in your hand.
2. Make some change to a spell you know ( not sure if this is required but felt pertinent to mention.
3. Attempt to close the gui using either "e" or the ESC key.

**Expected behavior**
Gui closing without killing the game.

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.11-all
 - Forge Version: 1.20.1-forge-47.2.21

**Additional context**
https://gist.github.com/border999/193e6d5c2de9ba3184c57bb064db2944

**Comment by Mithion** [comment]
The crash log you provided is incomplete - need the full latest.log file.  However.  This is a common issue with Hammerlib, and is on them to fix.  If you have that installed, try removing it.

**Comment by border999** [comment]
@Mithion https://github.com/dragon-forge/HammerLib/issues/50#issuecomment-2016649850

**Comment by Zeitheron** [comment]
It seems to be fixed with HammerLib 20.1.26, please verify and close the issue if it works.

**Comment by ShelLuser** [comment]
I can reproduce issues, but I'm not 100% sure if this is related. My bug seems to tie into an older (closed) bug: [#449](https://github.com/Mithion/Mana-And-Artifice/issues/449).

As soon as I use Cerublossum or Aum to craft a wand and then open the interface (press control, then right click) I immediately get an error: "Error setting spell data value: serversided validation failed!".

I'm running 1.20.1 using Forge 47.2.0, GeckoLib 4 4.4.2 and MNA 3.0.0.14.
