### ISSUE TITLE
Fire spells light furnace-likes in the dev instance, but not in an actual 

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#747]
**Describe the bug**
Fire spells cannot be used to light furnaces, smokers, and blast furnaces in an actual instance with just MnA and dependencies, despite working fine in a development instance.

**To Reproduce**
In a development instance:
- Create a Touch: Fire spell
- Sneak+Right click a furnace
- See the furnace light up

In a built instance:
- Create a Touch: Fire spell
- Sneak+Right click a furnace
- See that nothing happens

**Expected behavior**
The furnace should enter a lit state based on the relative power of the fire damage spell.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.11
 - Forge Version 47.2.21

**Additional context**
No mods were present other than MnA + Dependencies

**Comment by Mithion** [comment]
This is a little easter egg function that I'm not interested in putting additional time into debugging, especially if it's down to dev vs built.
