### ISSUE TITLE
Diamond Duplication

### ISSUE THREAD

**Issue by JuneOfJuipter** [Mithion/Mana-And-Artifice#748]
Diamond Duplication Glitch on minecraft 1.20.1 cause by AOE spell and Crystalize spell and huge groups of mobs

**To Reproduce**
1. get an an AOE Crystalize spell like cone crystalize  and a single diamond
2. Use on group of mobs (i used chickens, but i assume it works on all)
3. you capture more then one mob and have more diamonds after use

**Expected behavior**
i except one mob only get captured and not all of em

**Version Information (please complete the following information):**
mna-forge-1.20.1-3.0.0.11
 - Forge Version 47.2.21

**Comment by Mithion** [comment]
This is resolved in 3.0.0.12
