### ISSUE TITLE
1.19.2 Cannot invoke ... because "this.lootTableId" is null

### ISSUE THREAD

**Issue by NancalaStarry** [Mithion/Mana-And-Artifice#749]
**Describe the bug**
perhaps a mob cause this crash.

**To Reproduce**
1.enter this world
2.move around a little
3.crash

**Expected behavior**
No crash

**Version Information (please complete the following information):**
 - Mod Version 2.1.0.6-all
 - Forge Version 43.3.9

**Additional context**
crash-report: https://pastebin.com/zZTmWLwG
latest.log: https://mclo.gs/ROkVByh

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
