### ISSUE TITLE
The list of string now cannot be translated

### ISSUE THREAD

**Issue by TUsama** [Mithion/Mana-And-Artifice#75]
1. ![image](https://user-images.githubusercontent.com/21279092/92318334-5b151100-f03d-11ea-8143-9f1e4bdf693e.png)

2. 
![image](https://user-images.githubusercontent.com/21279092/93174129-133e6a00-f760-11ea-9bd1-3f1fc299c934.png)

It's the name of the recipe? anyway, I'm not sure if you can add a key for it for the I18n.

**Comment by TUsama** [comment]
![image](https://user-images.githubusercontent.com/21279092/107179170-cd38ba00-6a10-11eb-9cbe-963e0be70c11.png)

At least for the mod version 1.2.1.9, the string "Affinity" still can not be l10n.

**Comment by Mithion** [comment]
All of these are translateable in 1.3.0.0+
