### ISSUE TITLE
On Server: mna spells/general .toml is not correct correcting 1.19.2

### ISSUE THREAD

**Issue by doppeltrouble** [Mithion/Mana-And-Artifice#750]
when starting a server with mana and artifice installed the console tells me:
[05:51:57 WARN]: Configuration file /var/db/forge/./world/serverconfig/mna-spells.toml is not correct. Correcting
[05:51:59 WARN]: Configuration file /var/db/forge/./world/serverconfig/mna-general.toml is not correct. Correcting
i havent changed the config at all and it still decides to correct the file

1. Set up Arclight 1.19.2 server
2. Install Mana and Artifice
3. Start the server
4. And watch as it spams ([05:51:57 WARN]: Configuration file /var/db/forge/./world/serverconfig/mna-spells.toml is not correct. Correcting
[05:51:59 WARN]: Configuration file /var/db/forge/./world/serverconfig/mna-general.toml is not correct. Correcting) continually making the server unusable and going on for at least 6 hours after this time had passed i decided to give up and stop the server for a moment while i looked for a fix. I found a fix for 1.20.1 and up but my modpack only works on 1.19.2 so i would like to know if there is a fix for lower versions.

Expected behavior
Starts the server and lets players join with installed modpack and plugins

Screenshot
![image](https://github.com/Mithion/Mana-And-Artifice/assets/166976801/899c7083-dddd-428f-8f67-6c6bd86101e5)

**Version Information (please complete the following information):**
 - Mod Version: [2.1.0.5]
 - Forge Version [43.3.0]

I am using a Hybrid server called Arclight (for mods and plugins)
I have these plugins installed:
Projectkorracore
Jedcore
projectaddons
projectitems
Worldedit
Worldguard
I also have these mods installed:
Additional Placements
armortrims Backport
Balm 
Better chunkloading
Better FPS
Better Golem
Better Invisibility
Bookshelf
Caelus
Chisels and Bits
Chunk Pregenerator
Citadel
Clumps 
Configured
connected Glass 
continents
corgilib
cupboard curios
Dynamiccrops
Dynamiclights
Dynamic mining
Dynamic Surroundings
enhanced Nature
entity collision FPS fix
entityculling
fusion
geckolib
ice and fire
incendium
irons spells and spellbooks
jei
Journeymap
Max health fix
MNA
Mousetweaks
mowzies mobs
nullscape
Oh the biomes youll go
placebo
patchouli
playeranimationlib
projectE
Puzzleslib
Radon
rubidium-extra
rubidium
serene seasonsfix
serene seasons
snow und trees 
spiderstpo
stronger snowballs
corelib
tectonic 
Terrablender
Textrues rubidium options
Waystones 
Yungs Api
Yungs better strongholds

Can please someone help me?
and thank you if you do help me.
and if anyone needs anything ask.

**Comment by doppeltrouble** [comment]
also where can i find the Mna Source Code?
because i would try to backport the 3.0.0.9 fix for this to 1.19.2

**Comment by Mithion** [comment]
Mna is closed source.  

This bug was fixed in 1.20.1, which is being stabilized before older versions are addressed.

**Comment by doppeltrouble** [comment]
thanks a lot and i didnt know it was closed source

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
