### ISSUE TITLE
Practitioner's Pouch voiding items when its inventory is open

### ISSUE THREAD

**Issue by nanakisan** [Mithion/Mana-And-Artifice#751]
**Describe the bug**
Practitioner's Pouch voiding items when item isn't on the void patch filter. Despite there being valid items already in the pouch and free space for said items.

**To Reproduce**
1. Open practitioner's pouch
2. Drop a item / stack with pouch open
3. Pick up item / stack
4. Item / stack gets voided

**Expected behavior**
Items should be put in pouch regularly when there is valid space and already in pouch

**Screenshots**
![2024-04-15_21 51 07](https://github.com/Mithion/Mana-And-Artifice/assets/2136875/a4014e8b-3e07-4981-b2d1-6e962353156a)
![2024-04-15_21 51 09](https://github.com/Mithion/Mana-And-Artifice/assets/2136875/d75f64bd-96f1-4870-bddd-45d6458942ef)
![2024-04-15_21 51 20](https://github.com/Mithion/Mana-And-Artifice/assets/2136875/435e4df6-c154-465b-8088-bcf001548417)
![2024-04-15_21 51 22](https://github.com/Mithion/Mana-And-Artifice/assets/2136875/4b2de3c5-3d5d-4d0e-9673-c8b1020c484a)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.11]
 - Forge Version [47.2.21]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Followed your steps, didn't void the item at all.
What item were you dropping/collecting?  What patches are on the pouch?

**Comment by nanakisan** [comment]
Only patches on the pouch at time of discovery was Depth I and Void. item being collected was Spruce Logs. Method of dropping was done via ctrl clicking the stack.

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
