### ISSUE TITLE
spells not appearing

### ISSUE THREAD

**Issue by kaboom24** [Mithion/Mana-And-Artifice#752]
the earthquake spell does not appear in the inscription table neither does life drain or greater animus

**To Reproduce**
enter the inscription table and look for earthquake or life drain or greater animus
you will not find it
**Expected behavior**
I should be able to find it

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.11
 - Forge Version: 47.2.0

**Comment by Mithion** [comment]
That is intentional; you won't ever find them in the inscription table.  You find them elsewhere.
