### ISSUE TITLE
faction entering not working

### ISSUE THREAD

**Issue by kaboom24** [Mithion/Mana-And-Artifice#753]
**Describe the bug**
whenever you perform a ritual to enter a faction it does the animations but does not actually enter you in although i have only tested it with demon and council also the demon lord has a bossbar even when you dont summon him in the arena

**To Reproduce**
perform ritual to join faction
activate the npc
fail to join the faction

**Expected behavior**
it should add you into the faction and the demon lord should not have a bossbar unless summoned in the arena
**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.11
 - Forge Version 47.2.0
**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Just tried it, worked fine.
Make sure you are:
 - Tier 2
 - Completed enough tasks to tier up
 - Don't already have a faction
