### ISSUE TITLE
Server tick lag due to MNA and twilight forest interaction

### ISSUE THREAD

**Issue by CountBlumiere** [Mithion/Mana-And-Artifice#757]
Server lag caused by mod interaction with Twilight forest.

**To Reproduce**
1. Have mana and artifice and twilight forest on the same server together

**Expected behavior**
Not lag the server

**Screenshots**
Heres the spark profiler for more detail https://spark.lucko.me/K77nmpoMLq

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.11]
 - Forge Version [Latest version of Neoforge]

**Additional context**
Im not too sure if the problem is twilight forest or mana and artifice directly but i was told MNA was checking weather in the twilight forest which is the main causes the server tick lag

**Comment by Mithion** [comment]
According to the spark log, mna is 3.5% of tick time and isn't even the highest one...

**Comment by Mithion** [comment]
M&A does check if an entity is in water or rain but that's nothing; baseline entities do it every tick anyway as well.  That's the only thing I can think of that would qualify as "checking the weather in twilight forest".

I'm not at all convinced M&A is a cause of lag, in fact it's the opposite.  For all it does, it's very lightweight.

BattleChicken ran M&A alongside TF without issue on PebbleHost.  Perhaps consider some performance mods, especially the one that allows dimensions to tick on their own threads.  Our Discord server has plenty of server admins who could also recommend other performance mods.

Either way, this isn't an M&A issue, and I will be closing it.
