### ISSUE TITLE
Soaked when swimming in fluiads that arn't water (1.20.1)

### ISSUE THREAD

**Issue by Smiles-Saikou** [Mithion/Mana-And-Artifice#758]
**Describe the bug**
If another mod makes it where you can swim (the full sprint swimming) in a fluid that you can't normally swim in (namely, lava), you get the soaked effect. Despite not being in a fluid that would normally give you soaked. The most notable example of this bug is when using origins (forge) with MNA and have an origin that lets you swim in lava using a "origins:swimming" power.

**To Reproduce**
The easiest way to reproduce this behavior is while using origins (forge), the addon origins: minus, and the hellspawn origin.
After that, enter lava and start swimming.
You will then receive the soaked effect despite being in lava.

**Expected behavior**
You should not experience the soaking effect while in lava.
The easiest solution is most likely to add a check to the soaked effect that checks if you're in forge:#water when swimming.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.12
 - Forge Version 47.2.0

**Additional context**
This mainly affects using MNA with origins (forge)

**Comment by Mithion** [comment]
They're doing a mixin that makes the game think you're in water - nothing I can do about this one.
