### ISSUE TITLE
Crash on 2nd Manaweave, Latest mod version, MC 1.20.1

### ISSUE THREAD

**Issue by SpaceJeus** [Mithion/Mana-And-Artifice#759]
I am attempting to cast a first level cantrip, so 2 manaweave patterns with my wand. I get the first one out just fine, but the second one fails as soon as I right-click. Have tried using manual draw, and the selection wheel and hold. No difference in behavior.

 - Mod Version: 1.20.1-3.0.0.11
 - Forge Version 1.20.1-forge-47.2.20

Crash Report-Pastebin
https://pastebin.com/embed_js/Akmb5zDD

**Comment by SpaceJeus** [comment]
Figured out the cause, removing PMMO seems to have fixed the issue. Not sure what the conflict is.

**Comment by Mithion** [comment]
I put in some check code to help with this, but it's weird that they're somehow passing NULL for which hand is being used...we'll see if it fixes.
