### ISSUE TITLE
Codex mistake

### ISSUE THREAD

**Issue by xiaoknya** [Mithion/Mana-And-Artifice#761]
![image](https://github.com/Mithion/Mana-And-Artifice/assets/63701701/0c6918c6-2477-4781-8e2f-2e3adf34811a)
![image](https://github.com/Mithion/Mana-And-Artifice/assets/63701701/7cefde69-672c-4b71-86f0-8cbda57c1f03)

Hi Mith, would you mind taking a look at the titles or key values in these sections of the codex? It seems they might be incorrect, thx:)

**Comment by Mithion** [comment]
Thanks; fixed in dev.
