### ISSUE TITLE
Compatibility issue with Spice of Life Onion

### ISSUE THREAD

**Issue by ViewPointGames** [Mithion/Mana-And-Artifice#763]
**Describe the bug**
The client crashes to desktop when casting a "wall - break" spell that breaks blocks

**To Reproduce**
1. Install both MnA and SoLO (Spice of Life Onion)
2. Join or create a world
3. Make "wall - break" spell, any modifier should do
4. Cast spell
5. See crash error

**Expected behavior**
I expected the blocks to be broken and the game to continue as normal, with the blocks dropping their loottables.

**Screenshots**
No screenshots of the crash available, sorry. Here be dragons.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.12]
 - Forge Version: [1.20.1 - 47.2.17]
 - Spice of Life Version: [1.2.4]

**Additional context**
This is the pastebin link to the crash report: https://pastebin.com/FrUiR5qi
Since this holds more data than necessary, contact me if a new copy is needed please.

**Comment by Mithion** [comment]
At a glance this looks like it's on SOL: Onion's end - can you report there as well?  If they can provide a bit more context as to what their code is looking for, perhaps we can fix it.
