### ISSUE TITLE
Unable To Config Tier Health Boosts

### ISSUE THREAD

**Issue by boomberb** [Mithion/Mana-And-Artifice#768]
**Describe the bug**
Changes made to the configuration for tier health boosts are not saved on Mana and Artifice version 2.0.0.33 for Minecraft version 1.18.2, changes will be reverted to default.

**To Reproduce**
1. Install Mana and Artifice
2. Attempt to change the config for tier health boosts
3. Save changes

**Expected behavior**
Tier health boost config changes would be saved and work properly.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/168308859/97aefdd5-23a0-4d9a-a6dd-2d99c4b2e83c)

**Version Information (please complete the following information):**
 - Mod Version: 2.0.0.33
 - Forge Version 40.2.18

**Additional context**
This does not function with or without other mods installed.

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
