### ISSUE TITLE
Crash on Multiplayer server

### ISSUE THREAD

**Issue by CrusaderRabbit** [Mithion/Mana-And-Artifice#772]
**Describe the bug**
Server crash - NullPointerException

**To Reproduce**

User was using the occulus to see what i needed to advance to the next tier

**Expected behavior**
It not to crash the server.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.12]
 - Forge Version [e.g. 47.2.23]

**Additional context**

Crash Log:
https://pastebin.com/hfhNHWdz

**Comment by Mithion** [comment]
Resolved in 3.0.0.14
