### ISSUE TITLE
Crash upon opening a chest that contained Mana and Artifice items.

### ISSUE THREAD

**Issue by border999** [Mithion/Mana-And-Artifice#773]
**Describe the bug**
See Title

**To Reproduce**
1. Attempted to open a "loot" chest that contained mana and artifice items.
2. Crash/world closes.

**Expected behavior**
Open chest normally.

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.14-all
 - Forge Version 1.20.1-forge-47.2.30

**Additional context**
https://gist.github.com/border999/9fb9aecf0ea581769f4e925c3269f03f
https://github.com/SoSly/ArcaneAdditions/issues/89
Opened issue on both sides to ensure both mod authors are aware.

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
