### ISSUE TITLE
Random Client Crash in Multiplayer

### ISSUE THREAD

**Issue by GameIdiot153** [Mithion/Mana-And-Artifice#774]
**Describe the bug**
To be honest, I don't really know why this is happening.
Figured I might just post this here to get at least a sliver of information as to why this is happening.
Any answer is greatly appreciated.

**To Reproduce**
Don't really know to be honest.
Only times this happens is when one of my friends casts spells.

**Expected behavior**
The game continues to run fine.

**Version Information**
 - Mod Version: 3.0.0.12
 - Forge Version: 47.2.23

**Additional context**
Client Crash Report:
https://pastebin.com/B6DYDac2

**Comment by Mithion** [comment]
Try updating to 3.0.0.14, see if that fixes the issue.

**Comment by GameIdiot153** [comment]
Still didn't fix it.
Only crashes sometimes though.

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
