### ISSUE TITLE
Manaweaves will not bottle on Pedestals when a projector is activated by a Construct

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#775]
**Describe the bug**
When you set up a construct-automated manaweave bottling station, any time the construct activates the Manaweave Projector the resultant manaweave doesn't connect to the Pedestal.

If the player activates the Manaweave Projector instead, the resultant manaweave bottles just fine.

**To Reproduce**
1. Create the station set up in the screenshot below
2. Paste [this program](https://github.com/Mithion/Mana-And-Artifice/files/15217884/LodestarProgram_SingleManaweaveBottlingStation.txt) into a Lodestar.
3. Add bottles to the barrel and a pattern to the projector.
4. Connect a Construct to the Lodestar and observe.

**Expected behavior**
The manaweave projector activated by the construct has the same effect as being activated by the player.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/c9ff273f-5d32-4bcd-a758-055f0d1ff4b2)
Example used to set up the factory.

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.14]

**Comment by Veylyn** [comment]
I'm experiencing the same bug, except with construct activated manaweave projectors not connecting to manaweaving altars. Mod Version 3.0.0.14

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
