### ISSUE TITLE
Eldrin Altar Missing components.

### ISSUE THREAD

**Issue by Bushpeng** [Mithion/Mana-And-Artifice#776]
**Describe the bug**
First, I am new to MnA and its insanity (it's a good insanity), so please bear that in mind for this player mistake.

I had gotten to tier 4 and built the runic altar yesterday. I then created the greater conduits, and celebrated my success. Little did I know, you also need the wellsprings to actually power the greater conduits for spells to work, so in the best n00b fashion, I put in the ingredients to make the mote of magic and right clicked the runic altar with an empty hand. The ritual did start, and then stopped on the icon after the lights go into the altar indicating that it has started. It did continue to float on those particles while I did other things to come back to see if it worked. I then eventually made the stuff to see the wellsprings and build the structures to harness the powers.. however, I did get super tired and adulting is necessary for me, so I went to bed intending to finish with the wellsprings today..

However, when I logged into the server to build said structures for the wellsprings after finding them, I noticed the server was down. I started the server, then logged in only to be met with another crash report. There's the top line of that crash report as a SS in the appropriate section. Another player on the server with access to OP logged in and teleported near the Runic Altar only to immediately crash the server again. The server was started yet again, and the player logged in to crash the server. This surely isn't fun for anyone within the Runic Altar's render distance. The crash reports all say the same thing.

I did not see that the wellsprings being found/built within the Codex Arcana, so adding it somewhere in the book may help too. I'm just throwing out ideas since I had to watch videos to figure out what I did wrong here. Either that, or I'm blind and need to visit the eye doctor.. either is possible at this point.

**To Reproduce**
1. Get to tier 4 to be able to complete the ritual for the mote of magic on the Runic Altar
2. Set up said Runic Altar, but do not look for and find the wellsprings so there's no power going to greater conduits
3. Place greater conduits to power the Runic Altar
4. Obtain and place the items for the Mote of Magic in the Runic Altar setup
5. Right click the Altar with an empty hand and prepare to have it not finish.
6. Log off near the Altar and try to log back in after some time has passed. It was about 19 hours from when I logged off and logged back in, but that time may be shorter to crash said server.

**Expected behavior**
Seeing the error in the stack, I would have expected the spell to stop after a certain point and a message shown in chat. What the message says should be in MnA fashion. Since it's a NullPointerException - I'd suggest adding in if there's power coming from a wellspring to power the Runic Altar adequately for the ritual being performed.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/94489904/1c8c84b8-9345-4305-b679-347acdeac90b)

**Version Information (please complete the following information):**
 - Mod Version: [1.19.2-2.1.0.6]
 - Forge Version [1.19.2-43.3.0]
 
 This may also be present in other versions as well..

**Additional context**
The pastebin is syntaxed in JavaScript. Not sure if that's helpful or not, but I'm trying here!
https://pastebin.com/VzyDmA9G

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
