### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Magni45** [Mithion/Mana-And-Artifice#777]
**Describe the bug**
I have a server with a modpack including mna. When i try to join the server with a client with the same modpack i can't it returns the mssage java.lang.NullPointerException. This used to happen only when a client tried to join but now also happens when the server just tries to start (i regenerated the world)

**Expected behavior**
I expected the client to not crash

**Version Information:**
 - Mod Version: 3.0.0.14
 - Forge Version 47.2.0

This is the log from the server: https://pastebin.com/nLP0iFBw
This is the log from the client: https://pastebin.com/V6zvzPhf

**Comment by Mithion** [comment]
What launcher are you using?  Can you provide a link to the pack, or what other mods you're using?  Who is hosting the server?

**Comment by Magni45** [comment]
It is a curseforge modpack. https://www.curseforge.com/minecraft/modpacks/create-artifice is the link. I am hosting the server on exaroton and already tried contacting them and they have no solution:)

**Comment by Magni45** [comment]
I have now changed to version 3.0.0.12 and it works

**Comment by Mithion** [comment]
Closing as resolved.  Thanks for following up!
