### ISSUE TITLE
Lodestar interface interrupts player inventory interactibility

### ISSUE THREAD

**Issue by nanakisan** [Mithion/Mana-And-Artifice#778]
**Describe the bug**
If a group / command is dragged far enough down where either covers a slot in the player inventory. That slot cannot be interacted with such as picking up a rune of marking.

**To Reproduce**
1. Open lodestar
2. Write a program and add a group
3. Drag interface down where it covers an inventory slot with a group or command

**Expected behavior**
Be able to interact with inventory regardless of where on the interface window a group or command is located

**Video**
https://github.com/Mithion/Mana-And-Artifice/assets/2136875/bf71452d-d7c2-4ded-9715-8e637a619403

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.14]
 - Forge Version [47.2.30]

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
