### ISSUE TITLE
Crash - Lodestar conditional block at

### ISSUE THREAD

**Issue by Slickson77** [Mithion/Mana-And-Artifice#779]
**Describe the bug**
An assigned construct with a "conditional block at" step caused my client to crash

**To Reproduce**

With farmers delight, loadestone, construct, cutting board with dough on it

1. Have a conditional block command (can be the only one in the program)
2. use a rune of marking on the top of the cutting board
3. set the rune of marking in the conditional block
4. Set the dough as the conditional block in the command node
5. Assign the construct to the lodestone
6. expect crash

**Expected behavior**
no crash

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.14]
 - Forge Version [e.g. 47.2.20]

**Additional context**
[Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.]

(https://pastebin.com/si2LWGpE)

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
