### ISSUE TITLE
Game crashes due to the summoning animation

### ISSUE THREAD

**Issue by Vearmus** [Mithion/Mana-And-Artifice#78]
The mod version is 1.0.7.1.After summoning the faerie qeen ,i tried to give her the air focus,and the game crashed when i am right cliking,GIving the fire focus to the demon crashes the game too.It is the same when i summoned the wizards,game crashed when i am in the center of the ritual.

**Comment by Mithion** [comment]
This has been fixed in dev, and will go out with version 1.0.7.2 when it is released.
