### ISSUE TITLE
Unable to add Ritual to Practitioner's Pouch when MnA Gui Open is bound to the same key as sneak

### ISSUE THREAD

**Issue by Sar4h-3** [Mithion/Mana-And-Artifice#783]
**Describe the bug:**
When having the Gui key bound to the same key as sneaking, adding a new ritual in the Pouch is impossible since it is opened instead. 

**To Reproduce:**
1. Set Gui key to the same as sneaking (swapping sneak and sprint from what is normal would do it, and is the case for me)
2. Grab a Practitioners Pouch
3. Build up any ritual
4. Try to add said ritual to the pouch
5. See the pouch being opened instead of the Ritual being added to it

**Expected behavior:**
If the pouch is aimed at the center of a ritual, it should add the ritual to the pouch instead of opening it. 

(Not being able to cast spells while sneaking is also not the best, though I don't think there can be done much about that, if you choose to bind both sneak and Gui open to the same key...)

**Version Information:**
Probably all MnA versions, from 1.16 to 1.20
Currently playing on latest 1.20 version (3.0.0.14)

**Comment by Mithion** [comment]
Rebind the gui key to something else then, that's the point of configurable keybinds.  This won't be changed.
