### ISSUE TITLE
Lectern Codex Duplication

### ISSUE THREAD

**Issue by CodexArchive** [Mithion/Mana-And-Artifice#784]
**Describe the bug**
Breaking a lectern from MnA that's holding a Codex Arcana causes it to drop 2 copies of the codex instead of only one

**To Reproduce**
1. Get a Codex Arcana and a lectern from MnA
2. Place the lectern and give it the codex
3. Break the lectern without removing the codex
4. Recieve multiple Codex Arcanas

**Expected behavior**
Lectern should only drop a single codex if broken while holding one

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.0.0.14-all
 - Forge Version: 47.2.20

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
