### ISSUE TITLE
Construct Craft tasks only makes singles even if the output of the recipe makes more than one item

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#785]
**Describe the bug**
All construct craft tasks only make single items.

**To Reproduce**
1. Set up a glass panes recipe in the magician's workbench
2. Set up a crafting construct
3. Set up crafting logic
4. Observe the construct only craft a single glass pane each cycle

**Expected behavior**
The recipe output quantity matches the quantity when made by the player.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.14]
 - Forge Version [47.2.20]

**Additional context**
N/A

**Comment by Vargaskall** [comment]
[Construct Glass Issues.txt](https://github.com/Mithion/Mana-And-Artifice/files/15281226/Construct.Glass.Issues.txt)
