### ISSUE TITLE
Levitate spell still needs reagent in Fey faction

### ISSUE THREAD

**Issue by BlahajSimp** [Mithion/Mana-And-Artifice#786]
**Describe the bug**
While in a Faerie court faction you still need feather as a reagent in the levitate spell

**To Reproduce**
1. Join Faerie court
2. Craft any levitate spell
3. Cast it
4. You still need a feather as a reagent even when you are in the Fey faction

**Expected behavior**
Spell should cast without the need of reagent

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.14]
 - Forge Version [1.20.1-47.2.0]

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
