### ISSUE TITLE
Small typo "Youj"

### ISSUE THREAD

**Issue by x4dr** [Mithion/Mana-And-Artifice#787]
s/Youj feel  the presence of hundreds of wizards/You feel the presence of hundreds of wizards

![image](https://github.com/Mithion/Mana-And-Artifice/assets/9962272/3df53086-9078-4dd9-b67a-c78724870856)

**Comment by Mithion** [comment]
Thank youj!

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
