### ISSUE TITLE
when you touch water and get soaked effect, will trigger other mods' effect

### ISSUE THREAD

**Issue by llNoNamell** [Mithion/Mana-And-Artifice#793]
**Describe the bug**
other effect come with soaked effect.
**To Reproduce**
1.  touch the water to get soaked or stay in rainy weather

**Expected behavior**
 when the player touches the water or in rainy weather. they will get soaked and also trigger another effect from other mods. For example, right now in my server, every time a player gets soaked, they will get epicacg.nogravity at the same time.  When I remove epicacg, it becomes timelock from extrabotany.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [2.0.0.33]
 - Forge Version [40.2.17/40.2.21]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
That is some other mod doing it, this is not M&A.

**Comment by Acat1234** [comment]
Most dangeres rain ever
