### ISSUE TITLE
Codex entry on Levitation should explain that the status drops if you take damage

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#794]
**Is your feature request related to a problem? Please describe.**
The codex entry for levitation says it allows a limited form of flight, but does not specify that it's not suitable for combat and that damage causes it to dispel.

**Describe the solution you'd like**
A line should be added in the codex entry about conditions that cause the status to end.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Mithion** [comment]
"Limited flight" is fine.  We don't need to hand hold every little thing.
