### ISSUE TITLE
No Precision description on the gust spell

### ISSUE THREAD

**Issue by BlahajSimp** [Mithion/Mana-And-Artifice#795]
**Describe the bug**
Gust doesn't have a precision description in the Inscryption table and Rote book

**To Reproduce**
1. Get to tier 3
2. Add Gust and precision to the spell recipe
3. Hover over precision attribute
4. See gust.desc.precision and no real description

**Expected behavior**
You should see the description of what the precision does

**Screenshots**

![2024-05-17_18 54 39](https://github.com/Mithion/Mana-And-Artifice/assets/169538649/d97982e4-74fb-48f5-872a-1b50faeee21f)

**Version Information (please complete the following information):**
- Mod Version: [3.0.0.14]
- Forge Version [1.20.1-47.2.0]

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
