### ISSUE TITLE
Constructs with Ender Legs make suffocation damage noises when they teleport into walls

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#796]
**Describe the bug**
A construct with ender legs can pick a spot inside walls as a valid target. When it does, suffocation damage noises play despite the construct being immune to suffocation.

**To Reproduce**
1. Create a construct with ender legs.
2. Set up a logic flow where a valid block could be in a wall (such as a MagiChem Sort Materia task)
3. Watch the construct boop into the wall and make ouch noises.

**Expected behavior**
A construct in a wall makes no sound.

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/4ded8e07-ba28-4ba0-a6c4-85ffae4bb030)
This materia vessel storage area design made the problem obvious.

![image](https://github.com/Mithion/Mana-And-Artifice/assets/6653935/ba0efed5-667b-4b2b-a15a-133bbe0288eb)
An image of the construct inside the wall taken in spectator.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.14

**Additional context**
Discovered while using a construct to sort materia in MagiChem.

**Comment by Steven121314** [comment]
I experience this as well, except the path of the teleportation is through a wall, not necessarily the destination. The construct will make the damage sound while teleporting through my Railcraft coke oven.

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
