### ISSUE TITLE
Completely black textures - 1.20.1

### ISSUE THREAD

**Issue by Mdbgamer** [Mithion/Mana-And-Artifice#797]
**Describe the bug**
Tried putting together a kitchen sink pack for myself, and found Mana and Artifice to be the cause of a bug that made all of the vanilla textures go black. Removed every other mod, ran it with just Mana and Artifice(and required mods) and the problem persisted. Unsure if this is a bug in the mod itself or my computer being a hunk of junk.

**To Reproduce**
Download Forge, Curios API, Geckolib all on 1.20.1, then play the game. Not much to it.

**Expected behavior**
Having normal minecraft textures(obviously).

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/61175592/a8417ed1-26d1-4d2f-83d6-54ec2bd6958e)

**Version Information (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Version: 3.0.0.14
 - Forge Version: 47.2.32
 - Geckolib 4: 4.4.4
 - Curios API: 5.9.0+1.20.1

**Additional context**
I have an Intel HD 4000 graphics card. It's integrated. Old pc, about 2010 to 2011. It runs Minecraft and other modpacks just fine, so I have no idea if that's the actual issue. The mod ran just fine on a HP pavillion x360 laptop just fine on 1.18, so it's possible it's either a recent update broke it, or it's just older technology not agreeing with the mod itself. Just figured I'd put this these details in just incase it's a problem on my end.

I did do a quick search to see if this is a bug that has existed prior, but did not find anything. I may not have done an indepth enough search, so please forgive me if there's already an answer to this exact problem.

**Comment by Mithion** [comment]
Do you have optifine?

**Comment by LikeAYeah** [comment]
Same issue happened to me, no optifine or oculus.
Gonna wait for a patch to drop I guess.

**Comment by Mdbgamer** [comment]
No on the optifine. Literally ZERO other mods. JUST the mods for MnA.

**Comment by StAlexandre** [comment]
Same issue here. Also using an old graphics card Intel HD 4000, no Optifine, no Oculus

**Comment by Mithion** [comment]
This is a hardware incompatibility.  There is nothing I can do.

**Comment by Mdbgamer** [comment]
Figured I'd give an update, I waited for quite a while, and in the meantime got an upgrade to my RAM in the process(bumping it from 8 gb to 32 gb), but thats' besides the point. On the exact same hardware, that same version of the mod still threw black textures. I literally just updated it to 3.1.0.8 and the *problem is fixed.* Idk if it was ACTUALLY a hardware issue or if some bug was fixed in the updates between that version and this one, but I figure it might be important for you to know so you can look into this and others can find this.
