### ISSUE TITLE
Maybe a mistake on coloring the text?

### ISSUE THREAD

**Issue by tsukaerujuriki2** [Mithion/Mana-And-Artifice#799]
The text on infernal armour somehow has f in "if" being purple 
{
            "text": "、 and i"
          },
          {
            "text": "f I am burning, the flames empower the armor and allow me to move faster, resist knockback, and strike in melee with far more power than I would otherwise be able to",
            "color": "dark_purple"
          },

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
