### ISSUE TITLE
Codex Arcana Issues

### ISSUE THREAD

**Issue by CCheek** [Mithion/Mana-And-Artifice#8]
1: Jei opens up when using the book, this isn't really a problem though, since even when on a large scale it just pushes jei to the side.
2: The book pages seem to be out of order. (In the table of contents, the tabs seem fine)

**Comment by Mithion** [comment]
Resolved in 1.0.1-pre1 (ordering - JEI injects itself into most GUIs so until direct integration is added, this won't be fixed.  For the pre-alpha, I am not worrying about inter-mod interactions.
