### ISSUE TITLE
Ritual of the Flat Lands consuming Book of Shifting Lands when it fails

### ISSUE THREAD

**Issue by nanakisan** [Mithion/Mana-And-Artifice#800]
**Describe the bug**
Ritual of the Flat Lands consuming Book of Shifting Lands when it fails from either the area being too far or too big.

**To Reproduce**
1: Make ritual pattern
2: Make target area either too far or too large to trigger a failure
3: Insert runes of marking
4: Activate Ritual

**Expected behavior**
Ritual should return its catalyst Book of Shifting Lands when it fails

**Version Information (please complete the following information):**
- MnA 3.0.0.14
- Forge 47.2.30

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
