### ISSUE TITLE
Mod generates error when exiting Aum or Cerublossum wand options (control + right click).

### ISSUE THREAD

**Issue by ShelLuser** [Mithion/Mana-And-Artifice#801]
Apologies for this small offtopic comment but I'd like to start by saying how impressed both my gf and me are with this _amazing_ mod. We started experimenting with it today, and it's now part of our (private) LAN server and easily one of our favorites.

We found an issue, possibly a bug, and I think it might be related with an older (closed) bug: #449.

So we crafted 2 wands: cerublossum and aum by combining the flower and a stick. Following the instructions on the item description we opened the options by pressing left-control while right cilcking. So far, so good.  But as soon as we exit this screen then the mod triggers an error: "_Error setting spell data values, server side validation fialed!_", here's a quote from my latest.log:

[22mei2024 15:09:00.309] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Error setting spell data values; serverside validation failed!

This happens when my gf does this in survival, but also when I do this in creative. It also doesn't matter if we do this on our LAN server or in a singleplayer world. I also tried this with only this mod active to avoid possible issues with other mods.

For the record: this has no impact on the mod itself, my gf already managed to progress further by getting the codex, making a Vinteum wand (which does behave as it should!) and she also transmuted copper into silver. Even shot some fireworks? ;)

But I figured I'd still mention this because this will definitely confuse newer players.

We play with Forge 1.20.1 (47.2.0) and the latest version of the mod and its support mods:

Mana 3.0.0.14
Curios 5.7.0+1.20.1
Octolib 0.3

Hope this can help!

PS  I also commented about this elsewhere, but when thinking this over I figured a new report might be better.

**Comment by Mithion** [comment]
This was resolved with 3.0.0.15
