### ISSUE TITLE
Recipe conflict with Silent Gear

### ISSUE THREAD

**Issue by uhloin** [Mithion/Mana-And-Artifice#802]
1.20.1 version
Silent Gear is very popular mod and there is high probability of mixing it with mna in some modpack. But recipe flint + log for wickerwood head in MNA is already used for template in SG. MNA should change it to coal + log for example.

**Comment by Mithion** [comment]
You can make a datapack to change it, or install a mod called Polymorph: https://www.curseforge.com/minecraft/mc-mods/polymorph

**Comment by uhloin** [comment]
It's a good and universal solution, thank you
