### ISSUE TITLE
Constructs interact with a Seer stone will make them attack the mob targeted by the stone. 

### ISSUE THREAD

**Issue by Steven121314** [Mithion/Mana-And-Artifice#804]
As a tier 3 wizard, it's really annoying when my constructs won't protect me! They will target vanilla mobs but not the M&A ones. (Or mobs from other mods) I'm sick and tired of hulking zombies ambushing me outside of my tower! When I use the Bell of Bidding or a Lodestar, and tell my constructs to guard, they're only interested in attacking Zombies and Skeletons and other vanilla mobs.

I wish I could use a bell of bidding to make my constructs attack whatever a Seer stone is targeting. Just as I can assign them to a Lodestar or Delegation station.

It would even be cool if I used a Lodestar to tell a golem to guard, and placed a rune of marking located on a seer stone, so I could automate this process.

**Comment by Mithion** [comment]
This will invalidate the use of the perception stat on constructs, as their sight doesn't work like the seer stone - it'd be confusing and many would wonder why the construct isn't targeting the thing the seer stone sees (but the construct doesn't).  Their targeting has been improved (so they correctly target faction enemies), so it should be a non-issue requiring no configuration.

It's too much of a divergence from the way the constructs currently work to function reliably or clearly.
