### ISSUE TITLE
The Ritual of Forgotten Lore preview is missing reagents

### ISSUE THREAD

**Issue by ShelLuser** [Mithion/Mana-And-Artifice#805]
Credit where it's due: my gf is the one who discovered this, I'm just the messenger (pls no shoot me! ;)).

We're checking out rituals and Aya was going to perform the _Ritual of Forgotten Lore_. Now, the preview in the Codex only shows reagents on the 'top' and 'bottom' of the pattern (book, feather and ink sac). However, when you try to start or store the ritual then you'll get an error.

Aya snapped a screenshot which will show the issue: the pattern only shows 2 of each reagent, but we actually needed 4.

To be honest it seemed somewhat fitting to us, or as Aya put it: "_Maybe the lore about this ritual also got forgotten :P_", but I still figured I'd report this.

Here's the screenshot:

![2024-05-25_14 33 33](https://github.com/Mithion/Mana-And-Artifice/assets/25201078/467452fc-ad4f-44f5-a1bd-097830c25263)

We're playing with MNA version 3.0.0.14.

Hope this can help!

**Comment by AranaiRa** [comment]
You just did the ritual sideways. In general, it's better to activate the ritual first and THEN place reagents. With radially symmetrical patterns like this one it's easy to accidentally put things on the wrong spots.

**Comment by Mithion** [comment]
Closing as a non-issue in this case :)
