### ISSUE TITLE
Disenchanter Crash

### ISSUE THREAD

**Issue by jah83440** [Mithion/Mana-And-Artifice#806]
**Describe the bug**
After using the Disenchanter to produce a projection rune, the rune is successfully produced but then the game crashes.

**To Reproduce**
1. Place item and rune in disenchanter
2. Activate the disenchanter
3. Retrieve the rune
4. Wait a few minutes (it varied for us both times, but less than 5 minutes)

**Expected behavior**
Everything except the crash was expected.

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.0.0.14

 - Forge Version 47.2.0

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.
[iisYDGAU.txt](https://github.com/Mithion/Mana-And-Artifice/files/15458455/iisYDGAU.txt)

**Comment by Mithion** [comment]
You can fix this by switching to Oracle JDK instead of OpenJDK.  The latter has some kind of a bug that causes this crash.
