### ISSUE TITLE
Constructs can't make vellum

### ISSUE THREAD

**Issue by Veylyn** [Mithion/Mana-And-Artifice#807]
**Describe the bug**
Constructs cannot turn leather into vellum, failing completely when using a water source block, and deleting the leather when used on a filled cauldron

**To Reproduce**
1. Set up a filled cauldron or water source block
2. Program lodestar for construct to "Use item on block" with the leather on the cauldron/water source
3. Assign construct to the lodestar
4. Construct fails to make vellum, or deletes leather into cauldron

**Expected behavior**
Construct should turn leather into vellum

**Version Information:**
 - Mod Version: 3.0.0.14
 - Forge Version 47.2.20

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
