### ISSUE TITLE
Make books able to be put inside of Chiseled Bookshelf

### ISSUE THREAD

**Issue by SPYROHAWK** [Mithion/Mana-And-Artifice#808]
MnA adds several books to the game. From my count there's the Codex Arcana, Spellbook, Grimoire, Tome of Rote, faction-specific Tomes, Book of Marks, and Book of Recipies.

None of these can currently be inserted into a Chiseled Bookshelf.

I think it would be really nice if they could. Not only are they books and that's what the Chiseled Bookshelf is meant for, but also it allows players to create a "real" magical library of all of their spellbook on bookshelves.

There's not much more to add to this suggestion. It's pretty straightforward.

**Comment by ShelLuser** [comment]
First, just making sure, you are aware that MNA also provides its own book- and scroll -shelves, right?  They're much more accessible than Minecrafts chiseled variant.

Anyway, this behavior can be easily changed through use of a datapack. Minecraft provides the "#minecraft:items/bookshelf_books" tag which defines what book types can be added to its shelf. Override that tag and you can make it accept more books, though I'm unsure for now how Minecraft would pick up the rendering.

**Comment by SPYROHAWK** [comment]
> First, just making sure, you are aware that MNA also provides its own book- and scroll -shelves, right? They're much more accessible than Minecrafts chiseled variant.
> 
> Anyway, this behavior can be easily changed through use of a datapack. Minecraft provides the "#minecraft:items/bookshelf_books" tag which defines what book types can be added to its shelf. Override that tag and you can make it accept more books, though I'm unsure for now how Minecraft would pick up the rendering.

Somehow I was completely oblivious to that fact, I'll need to look into that. Thanks for the heads up.

I was just testing a bunch of magic / spellbook-adding mods in a pack I'm making with the vanilla one to see what was compatible (for the aforementioned magical library idea).

**Comment by Mithion** [comment]
This has been fixed in 3.0.0.15
