### ISSUE TITLE
Hellfire staff and beam spell.

### ISSUE THREAD

**Issue by Vearmus** [Mithion/Mana-And-Artifice#81]
Hold a hellfire staff with firedamage beam spell in main hand,and another beam spell which can have any component (even the heal) in the off-hand.Then hold the right click button.While the duration of the main hand beam runs out,the off-hand beam goes on,and all off-hand spell's aspects except the range  will be equal to the main hand hellfire beam spell.
This bug does not exist in peaceful mode.
[ScreenRecorder.zip](https://github.com/Mithion/Mana-And-Artifice/files/5243232/ScreenRecorder.zip)

**Comment by Mithion** [comment]
This has been fixed in 1.2.1.6
