### ISSUE TITLE
Lodestar has decided that I cannot edit my program anymore.

### ISSUE THREAD

**Issue by Steven121314** [Mithion/Mana-And-Artifice#810]
**Describe the bug**
I made a [complicated program](https://pastebin.com/g2Rf8yTV) in a Lodestar and now I can't open it to make it more complicated. Interestingly enough, the construct assigned to it is still following it like a champ!

**To Reproduce**
1. Place Lodestar
2. Put the [attached pattern](https://pastebin.com/g2Rf8yTV) into a patterning prism
3. Put it in the Lodestar
4. The player can no longer open the GUI of the Lodestar

**Expected behavior**
The Lodestar should open and allow me to edit the program.

**Version Information:**
 - Mod Version: 3.0.0.14
 - Forge Version 47.2.20

**Additional context**
Running alongside [ATM 9](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/relations/dependencies), most recent version.

**Comment by Mithion** [comment]
It's a packet size issue, which is a limitation of core minecraft.  I suggest you try installing a mod such as XLPackets (https://www.curseforge.com/minecraft/mc-mods/xl-packets) which may alleviate this issue.

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
