### ISSUE TITLE
Manaweaving Altar doesn't accept manaweave projectors activated by non-players

### ISSUE THREAD

**Issue by Veylyn** [Mithion/Mana-And-Artifice#813]
**Describe the bug**
A manaweave projector activated by a non-player source, such as a construct, does not provide a manaweave for nearby manaweaving altars. This includes construct activations, and other activations, such as Create deployers.

**To Reproduce**
1. Set up manaweaving altar and nearby manaweave projector
2. Program construct to activate projector
3. Projected manaweave does not connect to the manaweaving altar

**Expected behavior**
Activated manaweaves should connect to manaweaving altars, allowing automation of manaweaving.

**Version Information**
 - Mod Version: 3.0.0.15
 - Forge Version 47.2.20

**Additional context**
While this issue existed in 3.0.0.14 with construct activations, I had a workaround using Create deployers that allowed constructs to automate manaweaving. In 3.0.0.15, this system broke, with deployer-activated projectors also not working. If there was some way to activate bottled manaweaves automatically (such as them activating when fired from a dispenser) the fix to Issue #775 would be enough to enable this sort of automation.
When I implemented this automation with Create, I used Create version 0.5.1.f

**Comment by Mithion** [comment]
That's intentional; the manaweaving altar requires a valid player reference for tier checks.
