### ISSUE TITLE
Book-type items of this mod change randomly when changing texture packs

### ISSUE THREAD

**Issue by Acat1234** [Mithion/Mana-And-Artifice#814]
**Describe the bug**
That is the bug
**To Reproduce**
1. Get a book type item from this mod
2. Use any texture pack
3. The book has random textures

**Expected behavior**
For It to not be changed
**Screenshots**
![2024-06-14_08 37 15](https://github.com/Mithion/Mana-And-Artifice/assets/126712560/be1dd4c4-f7c2-45c0-b457-d6a4b42fcff8)
![2024-06-14_08 37 27](https://github.com/Mithion/Mana-And-Artifice/assets/126712560/f609bcf9-1d48-458d-8337-425487313232)

**Version Information
 - Mod Version: [3.0.0.15]
 - Forge Version [47.3.1]

**Comment by Acat1234** [comment]
The screenshot at the top means that it happens even after you remove the packs

**Comment by Mithion** [comment]
If you set up the packs and restart the game does it work?

**Comment by Acat1234** [comment]
Yes it does

**Comment by Mithion** [comment]
It's probably something to do with the way textures are atlased in the base game.  The new texture is probably atlased differently with the new pack, and the model's UV baking isn't updated.  I'm using the standard (Neo)Forge OBJ loader, so not much I can do about it in all likelihood.

If it works after a restart I'm not going to worry too much about it.
