### ISSUE TITLE
Transparent (I think) particles Show behind other transparent things

### ISSUE THREAD

**Issue by Acat1234** [Mithion/Mana-And-Artifice#815]
**Describe the bug**
If I use something with particles it shows behind transparent objects (clouds water ect)

**To Reproduce**
1. Get a Item with transparent particles
2. Use it near those objects
3. It shows behind it 

**Expected behavior**
Proper layering and it shows Infront not behind 

**Screenshots**
![2024-06-15_10 22 36](https://github.com/Mithion/Mana-And-Artifice/assets/126712560/2190edf6-dee3-4fac-9d74-7b1d5b2a64eb)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.15]
 - Forge Version [47.3.1]

**Additional context**
It happens with other mods too so It may be a Minecraft limitation if so sorry for wasting your time

**Comment by Mithion** [comment]
That's a long-standing problem with vanilla's render engine and how it merges transparent layers.  It's as good as it's going to get.
