### ISSUE TITLE
Crash and strange behaviour from using disenchanter

### ISSUE THREAD

**Issue by Oggas** [Mithion/Mana-And-Artifice#817]
**Describe the bug**
A while after using the disenchanter to disenchant an enchanted book my world crashed with error code 1, see the linked log. After the disenchantment animation was done and I got the enchantment on the projection rune, however the book still had the enchantment left on it.

**To Reproduce**
1. Put and enchantment book and projection rune into the disenchanter. (Be tier 3 btw)
2. Set up two lesser eldrin conduits about 4 blocks away from the disenchanter, about 6 blocks apart from eachother (one wind, one fire)
3. Set up 2 eldrin fume filters, one burning materials to supply fire eldrin and one for wind eldrin power.
4. Start the disenchantment process and wait.

**Expected behavior**
I expected the enchanted book to become a normal book. I did not expect the game to crash a little while later.

**Screenshots**
 
![image](https://github.com/Mithion/Mana-And-Artifice/assets/165203923/a952b2d3-e288-491c-9e1e-6bed57ecbf1d)

 
![image](https://github.com/Mithion/Mana-And-Artifice/assets/165203923/db46b7d4-5445-4ebd-bd30-4abb2fea6a63)

**Version Information (please complete the following information):**
Mod Version: Mana & Artifice 3.0.0.15
Curious API 5.9.1
GeckoLib 4.4.6
Forge Version 47.2.20

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

https://hastebin.com/share/usumicosiv.ruby

**Comment by Mithion** [comment]
Switch to SunJDK instead of OpenJDK.  This is a bug in the internals of OpenJDK.
