### ISSUE TITLE
Soaked effect wont constantly apply wen in water or rain

### ISSUE THREAD

**Issue by Acat1234** [Mithion/Mana-And-Artifice#819]
**Describe the bug**
That is the bug

**To Reproduce**
1. Go in rain/water
2. It wont constantly apply

**Expected behavior**
It stays at 15 sec until you get out of water/rain 

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0,15]
 - Forge Version [47.3.1]

**Comment by Mithion** [comment]
There's no need to apply it every tick to keep it at 15s - you either have it or you don't.  This is less network traffic and checks, and is more optimal on servers, even if it means you might lose soaked more quickly in some circumstances.
