### ISSUE TITLE
If a non player entity (ex. zombie) has mana boost, crashes server.

### ISSUE THREAD

**Issue by WhitePhant0m** [Mithion/Mana-And-Artifice#82]
[Crash Log](https://paste.gg/p/wphant0m/e776f616b127452bb0e4557950d7ed2f)

Apotheosis spawns boss mobs with random potion effects and if ex. a zombie boss mob spawns with mana boost, it crashes the server.

mana-and-artifice-1.0.8.6

**Comment by Mithion** [comment]
Sorry about that!  Fixed in dev to be released with 1.0.9.1.

**Comment by Mithion** [comment]
1.1.0.2 and up should fix this issue

**Comment by Shorepion** [comment]
I have a modpack (1.16.3) with M&A and a lot players have the same issue:
Is there a (manually) fix for MC1.16.3 or any chance that there will be a fix version 1.16.3 relased in the future?
(Otherwise I will have to update the whole modpack to 1.16.4/Forge 35.X.X)
✌️

**Comment by Mithion** [comment]
This has been fixed in the latest release version, 1.2.0.2.
