### ISSUE TITLE
Constructs mana cannon projectile flails around  

### ISSUE THREAD

**Issue by Acat1234** [Mithion/Mana-And-Artifice#820]
**Describe the bug**
When the Constructs shoot the mana cannon the projectiles jitter around

**To Reproduce**
1. Get a construct/w mana cannon+mana storage
2. have it shoot at something
3. It Flails around

**Expected behavior**
It goes in a straight line

**Screenshots**
It moves So I cant rly screenshot

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.15]
 - Forge Version [47.3.1]

**Comment by Mithion** [comment]
#812 tracking there
