### ISSUE TITLE
Remote control To manually control constructs  

### ISSUE THREAD

**Issue by Acat1234** [Mithion/Mana-And-Artifice#821]
**Is your feature request related to a problem? Please describe.**
I want a remote control type thing to control constructs.

**Describe the solution you'd like**
A remote or something that makes the camera bound to the construct and letting you control it, left click controls left arm right click controls right arm A new keybind for stopping the control (cuz I need 2x jump for rocket flight) Mabey a mana storage upgrade that makes it generate mana also A keybind for the teleport, please add this

**Comment by Mithion** [comment]
This isn't happening.
