### ISSUE TITLE
Purge Spell in 1.18.2 upcraftable through ritual of arcana

### ISSUE THREAD

**Issue by Darkdestroy56er** [Mithion/Mana-And-Artifice#823]
**Describe the bug**
In survival I created a undead faction spell being touch-purge upon lookin at the spell recipe there seemed to be a blank material not shown that when hovered over had no description. After gathering the other materials and activating the ritual of arcana the missing material is still not visable and doesn't allow the ritual to be completed.

**To Reproduce**
1. Be in the Undead Faction
2. Craft the touch-purge spell recipe in the inscription table
3. collect materials described in the spell recipe which will be missing a material
4. Use purified vinteum dust to start the ritual of arcana
5. attempt to place all listed materials from the spell recipe
6. use purified vinteum dust to attempt to finish ritual
7. Ritual will not continue

**Expected behavior**
After crafting the touch-purge spell recipe in the inscription it should be possible to look at the spell recipe and see all materials. After collecting all listed materials it should be possible to activate the ritual of arcana in a normal fascion and complete the ritual to collect the spell.

**Screenshots**
![Mana and Artifice Touch-Purge Spell](https://github.com/Mithion/Mana-And-Artifice/assets/173008136/da29935a-ea3e-4a19-a616-302981f38ebe)

**Version Information (please complete the following information):**
 - Mod Version: 2.0.0.33
 - Forge Version 40.2.0

**Additional context**
Doggy Talents Next
Inventory Pets
Xaero's Minimap
Xaero's World Map
Alex's Mobs
ApexCore
AppleSkin
Balm
Better chunk loading
Blood Magic
Bookshelf
Carry On
ChoiceTheorem's Overhauled Village
Citadel
Clumps
Corpse
Cosmetic Armor Reworked
Cucumber Library
Cupboard
Curios API
Diagonal Fences
Enchantment Descriptions
Fantasy's Furniture
Fast Leaf Decay
Framework
Friendly Fire
GeckoLib
Ice and Fire: Dragons
Inventory Profiles Next
Iron Chests
Iron Furnaces
Jade
JEI
Kotlin for Forge
libIPN
Macaw's Fences and Walls
Macaw's Furniture
MrCrayfish's Furniture Mod
MrCrayfish's Gun Mod
Mystical Agriculture
Open Parties and Claims
Patchouli
playerAnimator
Polymorph
Puzzles Lib
Simple Planes
Sophisticated Backpacks
Sophisticated Core
Stalwart Dungeons
Star Worm Equestrian (Upgrading Horses)
Towns and Towers
TrashSlot
TslatEntityStatus
Waystone Waypoint Maker
Waystones
XP Tome
YUNG's API
YUNG's Better Desert Temples
YUNG's Better Dungeons
YUNG's Better End Island
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.18.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
