### ISSUE TITLE
eldrin altar 

### ISSUE THREAD

**Issue by vacatex** [Mithion/Mana-And-Artifice#827]
**Describe the bug**
the eldrim altar rituals are not working

**To Reproduce**
Any attempts to make higher elemental motes do not work

**Expected behavior**
the ritual doesn't stop halfway through

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/173121278/cadb2ac9-c6a4-48b3-be90-17e2bff2c57a)

**Version Information (please complete the following information):**
 - Mod Version: [1.20.1-3.0.0.15]
 - Forge Version [47.2.0]

**Comment by Mithion** [comment]
The icon there is telling you that it doesn't have enough eldrin power.  It's looking for ender.  You'll need to generate more using either a Fume Filter or capturing a Wellspring.

**Comment by Basti407** [comment]
I have the same Problem. im trying to create a tier 4 pylon (Bind Wounds) and i captured multiple wellsprings of water and earth, summing up to generation Bonus 4.8 (Water) and 3.4 (Earth). When i look inside the occulus it tells me ive got 1000 of each stored and i have greater Conduits of each that connects to the altar. But when i start the ritual it always tells me its not enough. i even burned several motes at the fume. At first it emptied the storage completely and after a while it started refilling the storage. But still it shows me both eldarins are missing. Any thoughts?

Thats my setup:
<img width="3828" height="1859" alt="Image" src="https://github.com/user-attachments/assets/15a179c7-c659-4bc7-807a-dca98ce52fd7" />

**Comment by Basti407** [comment]
Btw the setup worked one time when i was creating a Greater Mote of Fire.
