### ISSUE TITLE
Book of Rote bugged while aligned to a Fae court and it is not the correct time of day

### ISSUE THREAD

**Issue by nightsreach21** [Mithion/Mana-And-Artifice#829]
**Describe the bug**
While attempting to craft spells in the Book of Rote while aligned with the Fae court of winter, I could not craft spells during the day. It would force all modifiers of the spell such as speed, duration, damage etc to 0 and I could not increase or decrease these values. As a result it would also make the spell complexity far too high so the spell wouldn't be able to cast ( but would be useless anyway as modifiers for the spell are all 0 )

Additionally:

- At night time you can make and cast spells as normal
- If you made spells at night and it is now day and you haven't Ctrl Right clicked the book of rote then you can still cast the same spells during the day
- If you ctrl right click to open the book of rote during the day it resets all spells as if you had crafted them in the book during the day thus making them unable to cast again

**To Reproduce**
1. Align yourself with the Fae court of Winter
2. Attempt to craft a rote spell in the Book of Rote during the day time (or night time if you are aligned with the Fae court of Summer)

**Expected behavior**
I expect the Book of Rote to remain functional as intended with no reductions in modifiers while crafting the spells in the book. For example I would've thought I could create a simple, unmodified projectile fire spell which is a basic spell, but even this fails.

**Screenshots**
![2024-06-19_21 51 46](https://github.com/Mithion/Mana-And-Artifice/assets/21356035/a27c0419-620c-4302-aabf-d6f71a973a45)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.15
 - Minecraft Version: 1.20.1
 - Forge Version:  47.3.0

**Comment by nightsreach21** [comment]
UPDATE: This bug also applies to crafting spells at the Inscription Table

**Comment by Mithion** [comment]
I found the bug - it has been fixed in dev.  Sorry about that!
