### ISSUE TITLE
After open the guide book for the first time, all GUI except this mod's Mana GUI failed to render

### ISSUE THREAD

**Issue by No3371** [Mithion/Mana-And-Artifice#83]
![圖片](https://user-images.githubusercontent.com/1814971/98452041-a60aec00-2186-11eb-9dd1-31152d762443.png)

As you can see, only the mana GUI shows, all other GUI is malfunctioning, including all text, icon, player models in hotbar, inventory and menus.
I'm on 1.16.3 Forge 34.1.10, with Optifine and Optiforge.

**Comment by TUsama** [comment]
你好，请问你是否使用了中文环境，并加载了来源于[此处](https://github.com/tusama/lwhk-simplified-chinese-translation/tree/1.15.2/translation/mana-and-artifice)的汉化？ 我有点怀疑是不是我的这个译本出了点格式上的差错，结果就变成了这样。

Hello, are you using the chinese langauage environment, and using the simplified chinese translation which you got from [here](https://github.com/tusama/lwhk-simplified-chinese-translation/tree/1.15.2/translation/mana-and-artifice)? I suspect that this translation has some fatal error, which may cause the problem like you shown above.

能够仔细描述一下你是在做了什么事清的发生了这个bug吗？这样可以更好地帮助我以及作者定位这个问题。非常感谢。

Could you please describe more what you did when this bug happen? it can help us locate this bug and fix it. thanks a lot!

**Comment by No3371** [comment]
我不記得我是使用日文還是中文了，但我直接使用 CurseForge 上的 JAR，沒有使用額外的漢化之類。
並沒有做什麼，當時在製作我的伺服器模組包，所以要逐個測試每個模組，單純是第一次打開那本書的時候這個問題就會發生。
重新啟動遊戲，這個問題仍然會存在，不需要再使用書本或任何動作，所以是與 Mana GUI 並存的問題。

**Comment by TUsama** [comment]
> 我不記得我是使用日文還是中文了，但我直接使用 CurseForge 上的 JAR，沒有使用額外的漢化之類。
> 並沒有做什麼，當時在製作我的伺服器模組包，所以要逐個測試每個模組，單純是第一次打開那本書的時候這個問題就會發生。
> 重新啟動遊戲，這個問題仍然會存在，不需要再使用書本或任何動作，所以是與 Mana GUI 並存的問題。

我在mcmod的相关页面上的评论区也遇到了与你相似的bug疑问，所以特意问了问。看来目前我这边的问题可以排除了。还有十分感谢你提供的相关细节。
当然，还麻烦你再用英文表述一遍这些细节，这样mithion估计才能看得懂（虽然谷歌翻译精确度确实挺高的）。

**Comment by Ausery** [comment]
I'm having the same problem, but I found out that the gui issue is fixed temporarily if you remove Optifine. However, I do really hope there will be a solution to this; to have compatibility with Optifine, since I can't bear to go back to the default resource pack after using shaders...

**Comment by Mithion** [comment]
Optifine is indeed not supported.

**Comment by RedMoikle** [comment]
If this is not supported, how can I remove the mana bar so I can just avoid using this mod in a modpack?

It seems once you open the book, you are stuck with it.

**Comment by pxlnght** [comment]
> If this is not supported, how can I remove the mana bar so I can just avoid using this mod in a modpack?
> 
> It seems once you open the book, you are stuck with it.

@RedMoikle 

1) Remove shaders from shaderpacks folder (or finesse your way thru the menus to turn them off).
2) Open the book from Mana and Artifice
3) On the bottom of the book there are little tabs. Click the rightmost tab until it says Never Show Hud.
4) Turn shaders back on.

This setting is also in mana-and-artifice-client.toml . But it's rewritten on launch, so that's not super helpful :p 

Alternatively, if you have regular backups of your server, you can open an old backup and move the old playerdata overtop of the current playerdata for yourself. But if you open the book again, it'll go kaput.
