### ISSUE TITLE
Levitation fails to allow flight

### ISSUE THREAD

**Issue by XevronTV** [Mithion/Mana-And-Artifice#831]
**Describe the bug**
Levitation displays the buff indicating that it is active, fails to work completely as you will just jump normally when attempting to take flight. Fall damage is still nullified for the entirety of the buff's timer or until dispelled. Tested in both Multiplayer and Singleplayer.

**To Reproduce**
1. Get Self Levitation via looting or crafting
2. Cast and attempt to fly
3. See error

**Expected behavior**
Expected slow flight upon cast.

**Screenshots**
Shows buff active:
![image](https://github.com/Mithion/Mana-And-Artifice/assets/120173092/7dde8f22-34dc-4d2e-86ab-a2c4f7e28203)

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.0.0.15-all
 - Forge Version: 47.3.0

**Additional context**
Modlist: https://pastebin.com/WFj54eX8

**Comment by Mithion** [comment]
Works fine with just M&A in dev - it may be some kind of incompatibility with your modlist.  If you can narrow it down to which one, I can look into fixing it.
