### ISSUE TITLE
Eldrin Altar server crash if unloaded mid-recipe

### ISSUE THREAD

**Issue by EtherChicken** [Mithion/Mana-And-Artifice#833]
After creating and starting a recipe with the Eldrin Altar, if you unload the chunk before it finishes collecting power, when you attempt to reload the chunk the server crashes.

**To Reproduce**
** ONLY REPRODUCABLE ON SERVERS **

1. Get tier 4 in MNA
2. Create the Eldrin Altar multiblock
3. Start a recipe and place a corresponding altar
4. Once the altar starts collecting power from the conduit, unload the chunk (Nether is a good option)
5. Once the chunk is unloaded, load it back in (Go back through portal)
6. Crashes server

**Expected behavior**
When loading back into the chunk with the altar, it should start where it left off, or stop the recipe and require a reactivation of it, rather than crashing.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.15
 - Forge Version 47.2.0

Server Crash Report Here:
https://pastebin.com/hFbcwshQ

(Due to Alex's Mobs, the client crashes on leaving a server so I do not know if it causes a client crash)

**Comment by Mithion** [comment]
I just tried this with a local server and it worked fine, including resuming the craft where it left off.  If you can provide any additional information to narrow this down, I can possibly investigate further.

**Comment by EtherChicken** [comment]
Just created a local server to try to reproduce, and was unable. It happened twice on my friends server hosted through a 3rd party service, so I am unsure if the local hosting has something to do with it.
I will update if it happens again with as much detailed info as I can.

**Comment by EtherChicken** [comment]
I was attempting to test on my local server, and I was just standing near the crafting Eldrin altar for ~7 minutes when the server randomly crashed.

Crash Report:
https://pastebin.com/A6Ekcj1p

**Comment by Mithion** [comment]
Thanks, found it - I've put a fix in for next update!
