### ISSUE TITLE
Random-ish crash

### ISSUE THREAD

**Issue by Acat1234** [Mithion/Mana-And-Artifice#838]
**Describe the bug**
The game crashes random-ishly

**To Reproduce**
1. It seams to happen around when I was experimenting with the runic malus
2. Wait...
3. Crash
**Expected behavior**
For the game to not crash

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.15]
 - Forge Version [47.3.1]

**Comment by Mithion** [comment]
This is completely useless information, could you please follow the intake form and submit the proper details or don't bother.
