### ISSUE TITLE
Hovering cursor over an enchanted rune item causes the player to crash.

### ISSUE THREAD

**Issue by Whitaker8237** [Mithion/Mana-And-Artifice#839]
Hovering the cursor over an enchanted rune causes the player to crash. The server does not crash.

**To Reproduce**
1. Get any enchanted rune.
2. Hover your cursor over the enchanted rune in any inventory slot.

**Expected behavior**
Hovering your cursor over the enchanted rune does not cause a crash.

**Version Information**
 - Mod Version: 3.0.0.15
 - Forge Version 47.3.0

**Additional context**
This is a modded server, so I don't expect much can be done, but I've reported this issue in the event there is a possible fix.

[crash report.txt](https://github.com/user-attachments/files/15949019/crash.report.txt)

**Comment by Mithion** [comment]
This was fixed in 3.0.0.20
