### ISSUE TITLE
I can't go on the server

### ISSUE THREAD

**Issue by PanosPlakidas** [Mithion/Mana-And-Artifice#84]
I was crafting a spell when the server crashed and from then i cant go on the server(i have all the right versions of the mods and the right version of forge) neither of this error message or because it stucks on enscrypting and if i press cancel it crashes my game

https://hastebin.com/exaginewoy.csharp
![2020-11-15 (1)](https://user-images.githubusercontent.com/74476853/99160259-f685ca80-26ed-11eb-924d-94ca5424dd9a.png)

**Comment by Mithion** [comment]
Not an M&A bug
