### ISSUE TITLE
[BUG] Mist Form Retains Creative Flight Randomly

### ISSUE THREAD

**Issue by JosTheDude** [Mithion/Mana-And-Artifice#841]
**Describe the bug**
Mist Form spell retains Creative Flight occasionally (seems to happen randomly) after use

**To Reproduce**
1. Cast Mist Form
2. Occasionally retains creative flight

**Expected behavior**
Creative flight is removed

**Screenshot/Video of Occurrence**
https://youtu.be/olYV_wz-48g | Video documenting the occurence alongside spell information
_Bug also ends if Mist Form is casted again_

**Version Information (please complete the following information):**
 - 2.1.0.6 (Mod Version)
 - Forge 1.19.2 (43.3.13) (Forge Version)

**Additional context**
Other Mods Installed: https://pastebin.com/nNdeFB7i

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.
