### ISSUE TITLE
Construct caster arms cannot transmute

### ISSUE THREAD

**Issue by Veylyn** [Mithion/Mana-And-Artifice#843]
**Describe the bug**
A construct with a caster arm cannot use a transmute spell to transmute a block. Tested with touch, projectile, cone, and emanation shapes

**To Reproduce**
1. make construct with caster arm with a transmute spell
2. Ensure construct has enough mana to cast
3. Use lodestar to command the construct to cast transmute on a transmutable block like stone
4. Construct's spell fails to transmute the block

**Expected behavior**
Construct's spell should transmute the block, as it is when the same spell is used by a player

**Version Information :**
 - Mod Version: 3.0.0.15-all
 - Forge Version: 47.2.20

**Comment by Mithion** [comment]
This is a complicated fix as transmute is tier and faction locked - a faction locked transmute will never be doable by construct, but I did make caster arms able to replicate a certain tier for the purposes of transmutation.  The tier of the recipe (default; does not take into account datapacks) will be the casting tier.

**Comment by Mithion** [comment]
This was fixed in 3.0.0.19
