### ISSUE TITLE
Can't craft construct's right arm

### ISSUE THREAD

**Issue by LukasReeves** [Mithion/Mana-And-Artifice#845]
**Describe the bug**
I can't craft the construct's right arm. When the correct recipe is made on the crafting table, it procudes the left arm instead of the right one. 

**To Reproduce**
1. Get items to craft the right arm
2. Use on crafting table
3. Instert correct recipe of the right arm

**Expected behavior**
It's supposed to make the right arm instead of the left one. 

**Screenshots**
A screeshot is presented to show the issue

![Screenshot_2024-06-29_15-04-55](https://github.com/Mithion/Mana-And-Artifice/assets/174207609/8507b6b5-7bdd-4199-81d0-17060ec5593d)

**Version Information :**
 - Mod Version: [3.0.0.15]
 - Forge Version [47.3.0]
 - game version [1.20.1]

**Additional context**
I'm using the mods rubidium, clumps, starlight, ferritecore, curios and geckolib 4 along with mana and artifice.

**Comment by Mithion** [comment]
You can put a construct's arm by itself in a crafting grid to swap it to the other side (right -> left or left -> right).
In addition, you can also use a mod like polymorph to select which one to craft.  MC matches mirrored recipes as each other, frustratingly, so even though the definitions are different, it treats them as the same.
