### ISSUE TITLE
Crushing recipe for Carpets to String uses incorrect tag

### ISSUE THREAD

**Issue by Spiritomi** [Mithion/Mana-And-Artifice#846]
**Describe the bug**
The crushing recipe for turning carpets into string using constructs uses the "minecraft:carpets" tag for its input, but this tag does not exist, thus leading to a broken recipe. This recipe should be using the "minecraft:wool_carpets" tag instead.

**To Reproduce**
1. Install JEI.
2. Create a new world.
3. Open the JEI menu and search for string.
4. Either left click it or press R while hovering over it to pull up recipes for string.
5. Navigate to the MNA Crushing tab to view crushing recipes for string.
6. The second recipe listed should be the carpet to string recipe, and the input is blank.

Alternatively:
1. Get a construct.
2. Get a grinding wheel.
3. Set up a lodestar to direct the construct to grind things on the grinding wheel.
4. Provide the construct with carpets.
5. It should be unable to process the grinding, as the recipe is bugged.

**Expected behavior**
The recipe in JEI should display any and all carpets as usable within the recipe, and constructs should be able to break down the carpets into string using a grinding wheel.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.15
 - Forge Version: 47.2.17 for 1.20.1

**Comment by Mithion** [comment]
This was fixed in 3.0.0.19
