### ISSUE TITLE
Faerie Court Permanent Summons During Inauspicious Times

### ISSUE THREAD

**Issue by Hubnester** [Mithion/Mana-And-Artifice#848]
**Describe the bug**
While aligned with the faerie courts (summer mode) and I cast a summon spell (summon - briarthorn barrier, only modification is increasing magnitude to 2) at inauspicious times (night) the summon doesn't die and according to Jade, doesn't have the reapers gaze debuff (also does this with 1 duration increase).

**To Reproduce**
1. Join faerie courts
2. Use summon spell with default duration during inauspicious times

**Expected behavior**
The summon should die after some amount of time.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.15
 - Forge Version 47.2.0

**Comment by Mithion** [comment]
I'm curious if 3.0.0.18+ fixed this, as I changed how auspicious calculations work.  Could you please confirm?

**Comment by Hubnester** [comment]
It is fixed in 3.0.0.18

**Comment by Mithion** [comment]
Fantabulous!  Thank you for confirming.
