### ISSUE TITLE
Cheaper Leather

### ISSUE THREAD

**Issue by Valurasa** [Mithion/Mana-And-Artifice#849]
**Describe the bug**

When making leather with the manaweaving altar it requires 6 rotten flesh and 1 bone ash, however after an inital making with it you can use an empty right hand click to remake the recipe but with a minimum of 2 rotten flesh instead of the 6.

**To Reproduce**
1. Get item 'Rotten Flesh x6 and Bone Ash x1'
2. Use with 'Manaweaving Altar to make leather'
3. Get item 'Rotten Flesh x2 Bone Ash x1'
4. Right click with empty hand on Altar to remake previous recipe.
5. See error of leather made with less than required ingredients.

**Expected behavior**
In theory I should be told that I don't have enough ingredients.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [1.20.1-3.0.0.15]
 - Forge Version [v. 
![2024-07-04_00 36 38](https://github.com/Mithion/Mana-And-Artifice/assets/174690152/1a48669a-8499-4b11-ab1b-8e15eeb22850)
![2024-07-04_00 36 54](https://github.com/Mithion/Mana-And-Artifice/assets/174690152/ddb98260-408c-4665-8496-fb38cd2881bf)
1.255.0.18685]

**Additional context**
Other Mods: 

Curios API V 5.9.2+1.20.1
GeckoLib V 1.20.1-4.4.7
Just Enough Items V 1.20.1-forge-15.3.0.8

**Comment by Mithion** [comment]
This was fixed in 3.0.0.19
