### ISSUE TITLE
Here is the translation of the mod into Russian

### ISSUE THREAD

**Issue by Rabbi-T-Rodjer** [Mithion/Mana-And-Artifice#850]
Hi. Here is the translation of the mod into Russian, for version 1.20.1, both the mod itself and the mod manual.
Thank you for the great mod, you did a very great job!
[assets.zip](https://github.com/user-attachments/files/16097980/assets.zip)

**Comment by Rabbi-T-Rodjer** [comment]
I noticed that in version 1.20.1 some lines of code were replaced, for example:
1.19.2 - mna:comComponents/
1.20.1 - mna:components/
Thus, if you use the translation for 1.19.2 in version 1.20.1, then there is no translation of the names of spells, descriptions of the effect and some other things.

In addition, I corrected the inaccuracies of machine translation a little and tried to use the same style in the translation of the mod and the translation of the manual as much as possible.

**Comment by Mithion** [comment]
Hi there, thank you so much!  However I require this to be submitted as a Pull Request and not an issue - could you please re-submit with the proper pipeline so it can be reviewed and merged:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Rabbi-T-Rodjer** [comment]
Uhhh... I tried to figure it out, and my brain exploded. Request, branches, commands... [Crying] I am a simple sales manager who knows how to work with an online translator, pleasehelpme. )

I actually read the instructions, and even watched a couple of videos on working with this site, but I don't have the skills and knowledge to work on it...
Maybe someone else who understands can do it? I do not claim any authorship, or mention, or anything at all. The main thing is for people to play.

**Comment by FluffUMen** [comment]
I'm sorry for the stupid question, but how do I install it?

**Comment by kron055** [comment]
Hello, I came across your translation, but I don't understand how to download it at all, all the ways that I know don't work. If it doesn't bother you, could you remove some kind of guide or make an instruction. Thank you in advance

**Comment by taciiit** [comment]
чел, почему норм гайда нет. я глупая русская женщина, которая хочет поиграть в майнкрафт со своим мальчиком корейцем, но мы сидим уже второй час над тем, чтобы перевести этот мод, а я просто хочу стрелять из пушек и выращивать капусту на своей свага ферме. напиши в какие папки это кидать

**Comment by LeWARfire** [comment]
Для таких же простых русских женщин как я хочу написать мини гайт как перевести этот мод:
1. Заходите в папку с модами и ищете этот нужный мод
2. Открываете его через WinRAR или что у вас там есть (не распаковывая)
3. Заходи в папку assets, а потом в mna
4. Там будут папки lang и guide, туда же уже закидываем из скаченного архива файлы (я на всякий удалила все другие языки)

А автору спасибо за перевод!
