### ISSUE TITLE
Fall damage while riding constructs

### ISSUE THREAD

**Issue by no-name-provided** [Mithion/Mana-And-Artifice#851]
**Describe the bug**
Golems don't take fall damage. Since fall damage is usually absorbed by a mount first (with only the excess carrying over to a player), I assumed the fall damage I received while riding my golem around was intentional. However, I recently saw a post on discord

<details>

> To the original person who asked , If you want fall damage immunity while mounted, I suggest looking at constructs - I went out of my way to remove the falling damage for them (and those mounted on them) as an enticement to use them. (Mithion)

</details>

that implied otherwise. If golems are indeed supposed to **negate** fall damage (rather than just ignoring it), then this feature is not functioning as intended. I believe I first encountered this on an old version of Minecraft, but I can confirm that it exists in the current version of Wellspring Adventures 2 and I've used the following steps to replicate the behavior on a minimal install (MnA+dependencies+JEI, no config changes). The affinity, material, and components have no apparent effect.

**To Reproduce**
1. Install MnA, required dependencies, and JEI
2. Reach tier 2
4. Make a wood golem with a basic torso, two shield arms, and sturdy legs. Give it fire affinity (so you don't need to make a spell)
5. Tell it to guard you
6. Mount it
7. Jump as high as possible, walk off a cliff, etc. Each action causes fall damage.

**Expected behavior**
No fall damage while riding a construct.

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.15]
 - Forge Version [e.g. 47.3.0]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
This was fixed in 3.0.0.17

**Comment by no-name-provided** [comment]
Thanks for the update. FYI: you left this fix out of the changelog.
