### ISSUE TITLE
Config option too disable the spell and etc, particle effects

### ISSUE THREAD

**Issue by Acat1234** [Mithion/Mana-And-Artifice#853]
**Is your feature request related to a problem? Please describe.**
Because the Minecraft rendering engine is kind of buggy and renders particles weirdly.

**Describe the solution you'd like**
I would like a config to disable the particles (yes I do know that minecraft settings allows disabling particles but that is all particles not just some of them)

**Comment by Mithion** [comment]
The MC version is sufficient and what I built around; I'm not doing a refactor that large to add this config.  It'd be hundreds if not thousands of files.
