### ISSUE TITLE
Server crash with Pylon placement/Single Player Crash with Adjustment to Pylon UI

### ISSUE THREAD

**Issue by Slickson77** [Mithion/Mana-And-Artifice#854]
**Describe the bug**
The Server crashes when you place a pylon down that has an effect.  The Inert pylon seemed fine, but as soon as you place one down (only tested in creative), the server crashes.  Setting the forge-server.toml to remove errored entity/block entity instead of crashing, doesn't help.  As soon as you load into a world and the pylon is rendered, there is an immediate crash

I tested this on a non-server ... the pylon places fine, but as soon as I tried to increase the radius of the effect (NightVision), my client crashed.

**To Reproduce-Server**
1. Make server
2. place pylon with effect
3. server crash

**To Reproduce-SinglePlayer**
1. place pylon with effect
2. OpenUI
3. Adjust Radius

**Expected behavior**
no crashy

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.18-all.jar
 - Forge Version 47.2.20

**Additional context**
I've added two crash reports from the server, they seem a little different.  The FirstPylonPlacement file is the initial crash when the pylon was first placed.  The ChangedForgeServerToml one is me trying to join again and immediately crashing when the pylon renders.

[SinglePlayercrash-2024-07-08_06.34.05-server.txt](https://github.com/user-attachments/files/16126350/SinglePlayercrash-2024-07-08_06.34.05-server.txt)

[FirstPylonPlacement_crash-2024-07-08_06.11.30-server.txt](https://github.com/user-attachments/files/16126208/FirstPylonPlacement_crash-2024-07-08_06.11.30-server.txt)
[ChangedForge-ServerToml_crash-2024-07-08_06.21.09-server.txt](https://github.com/user-attachments/files/16126210/ChangedForge-ServerToml_crash-2024-07-08_06.21.09-server.txt)

**Comment by Mithion** [comment]
This was fixed in 3.0.0.19
