### ISSUE TITLE
Affinity Bar Displays At Tier 0

### ISSUE THREAD

**Issue by FoxMcloud5655** [Mithion/Mana-And-Artifice#855]
**Describe the bug**
The affinity bar is displayed by default even at Tier 0, meaning that to get rid of it, you must read the Codex Arcana and remove the HUD.

Unrelated to the issue at hand, but a way to revert this change and put the UI at the old location would be extremely nice.  Affinity doesn't really matter in most cases, just a discount to spells of that affinity, and with this change, it makes it very much in your face, cluttering up the UI.

**To Reproduce**
1. Join the game as a new player.
2. See the Affinity Bar.

**Expected behavior**
The affinity bar to be hidden until the mana bar is shown for the first time.

**Version Information:**
 - M&A Version: - 3.0.0.18
 - Forge Version - 47.2.20

**Comment by Mithion** [comment]
This was fixed in 3.0.0.19
