### ISSUE TITLE
Mithion's Magnificent M...bag doesn't have belt slot support

### ISSUE THREAD

**Issue by vdrake77** [Mithion/Mana-And-Artifice#856]
**Describe the bug**
Not entirely sure this is a bug, but Practioner's pouches were recently tweaked to allow belt support; the super-special bag doesn't have this feature.

**To Reproduce**
1.  Have an MMMb
2. Try to put it on belt slot.
3.  Doesn't work

**Expected behavior**
It's an Infinity +1 Practitioner's pouch, it seems weird that it's missing this, even if it's not an enormous loss.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.18
 - Forge Version : 47.2.20

**Additional context**
It's a nice feature for the prac-pouch,  But I'd really appreciate it also fitting into the 'bundle' slot, too.

**Comment by Mithion** [comment]
This was fixed in 3.0.0.19
