### ISSUE TITLE
Ritual recipe of the ritual of the shadow soul is incorrectly labelled 

### ISSUE THREAD

**Issue by Baramos666** [Mithion/Mana-And-Artifice#857]
Searching for the ritual recipe of the ritual of the shadow soul doesn't have results 
It's instead found on a duplicate "Ritual Recipe : Mote of water" entry 

1.Open Codex search function
2a.Search "shadow" 
3.No ritual recipe for Ritual of the shadow soul

2b. Search "Mote of water"
3c. 2 ritual recipes for it and the first recipe leads to the ritual recipe of the ritual of the shadow soul

Expected results:
finding the ritual recipe for the ritual of the shadow soul when searching it instead of from searching the mote of water ritual recipe . 
PS: The link to the ritual recipe from the ritual page is working as expected

Screenshots:
![Screenshot from 2024-07-10 13-48-56](https://github.com/Mithion/Mana-And-Artifice/assets/43490889/fba56eab-495c-4858-bbe1-64958f6baf4a)
![Screenshot from 2024-07-10 13-49-28](https://github.com/Mithion/Mana-And-Artifice/assets/43490889/5c4c8d6c-9f12-41dc-8fba-6c3cb75624e4)

Version Information :
 - Mod Version: 3.0.0.19
 - Forge Version  47.2.19

**Comment by Mithion** [comment]
Resolved in 3.0.0.20
