### ISSUE TITLE
going back in the Codex Arcana brings you back to the Basics tab

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#858]
**Describe the bug**
going back in the Codex Arcana brings you back to the Basics tab (not the previous page and tab you were on)

**To Reproduce**
click on the back button when in the Codex Arcana or use any other method to go back

**Expected behavior**
going back in the Codex Arcana should bring you back to the page and tab you where on previously (not the Basics tab). As it is, going back makes you have to click on the desired tab and cycle through the pages again to get back to the page and tab you were previously on.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.19
 - Forge Version 47.3.0

**Comment by Mithion** [comment]
Resolved in 3.0.0.20

**Comment by Sarithule** [comment]
Awesome! thank you!
