### ISSUE TITLE
Elemental rune tier problem

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#859]
**Describe the bug**
In the Runesmithing tab of the Occulus, The water rune is tier 2 while the fire, earth, air, ender, and arcane runes are tier 3.
The Rune patterns for the Fire, Earth, Air, Ender, and Arcane runes claim they require tier 2 in the mouse over tool tip.
These patters will not allow crafting on the Runic anvil at tier 2 
There are a few tier 2 recipes (like the tier 2 pylons) that require runes which can not be made until tier 3 as it currently stands.
One of the optional objectives in the Occulus to advance toward tier 3 is to craft any tier 2 pylon.
No tier 2 pylon can be crafted when the player is at tier 2 because they require tier 3 elemental runes.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.19]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
Resolved in 3.0.0.20

**Comment by Sarithule** [comment]
Very nice, Thank you!
