### ISSUE TITLE
Gecko Lib beta 10 Unavailable

### ISSUE THREAD

**Issue by Kosomic** [Mithion/Mana-And-Artifice#86]
With the new release right now, currently you can't access it as the currently release of Gecko Lib only goes to beta 8,
forge will give the error on load stating you need the beta 10 library

![error](https://user-images.githubusercontent.com/60415197/99915435-9d133200-2cd1-11eb-98a5-99a5c12deae7.JPG)

**Comment by Mithion** [comment]
You can download it from here for the short term until a CF update is released.

https://repo.repsy.io/mvn/gandiber/geckolib/software/bernie/geckolib/forge-1.16.4-geckolib/3.0.0-beta.10/forge-1.16.4-geckolib-3.0.0-beta.10.jar
