### ISSUE TITLE
Boss advancement for killing Pig Dragon does not award despite repeated kills. (1.20.1)

### ISSUE THREAD

**Issue by StAlexandre** [Mithion/Mana-And-Artifice#860]
**Describe the bug**
When killing the Pig Dragon, multiple players have not received the defeat pig dragon advancement.

**To Reproduce**
1. Throw cookies and raw porkchop on to ground while respawning the ender dragon for the pig dragon.
2. Kill the Pig Dragon

**Expected behavior**
Receive the advancement "Ten Years In The Making"

**Screenshots**
![image](https://github.com/Mithion/Mana-And-Artifice/assets/106701551/5b5ec3d5-1b1e-4021-ab1f-26c778ade104)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.15
 - Forge Version: 47.3.1

**Additional context**
I can only assume it's because the criterion is asking for "mna:fpd" but the entity is "mna;tfpd"

**Comment by StAlexandre** [comment]
I later decided to go on a crusade against the other faction bosses, and found the issue there too. While I got their loot of faction marks and Master's Theses, I did not get the advancements

**Comment by Mithion** [comment]
Out of curiosity, how did you kill the bosses?

**Comment by StAlexandre** [comment]
I used two Runic Rapiers with sharpness 255 (due to IF and Simply Swords), each dealing 142.5 damage per hit.

**Comment by Mithion** [comment]
Resolved in 3.0.0.20
