### ISSUE TITLE
Alter of Arcana not using all items from chest

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#861]
**Describe the bug**
When using the Altar of Arcana to create a new spell on velum, only some of the required items are being consumed from the chest.
This may be because the chest it is taking the items from is located directly above the altar and may be getting in the way of the items appearing above the altar (But I don't know).

see pictures to possibly reproduce.

**Expected behavior**
All items required for the spell to be created should be consumed from the chest.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.19]
 - Forge Version [47.3.0]

![2024-07-11_03 48 44](https://github.com/Mithion/Mana-And-Artifice/assets/7463293/8e8a19ef-268e-4b25-9789-7ce6465d57a8)
![2024-07-11_03 58 36](https://github.com/Mithion/Mana-And-Artifice/assets/7463293/c31c5e1d-b586-46d4-b216-b26153e742bb)

**Comment by Mithion** [comment]
It's possible it is finding them in another chest - it will pull from 8 blocks away and doesn't sort by distance.  Is it possible you had the required item elsewhere for it to find?

**Comment by Sarithule** [comment]
Yes, this is possible. Probable even. I didn't even think of that haha. I just assumed it would take from the closest chest.

**Comment by Mithion** [comment]
I'm not seeing this locally testing with a single chest, so I'm going to assume that's what happened and close this as resolved.
