### ISSUE TITLE
Tier Two Pylons require runes that can only be crafted at Tier Three

### ISSUE THREAD

**Issue by ZargetGaming** [Mithion/Mana-And-Artifice#862]
**Describe the bug**
Cannon craft Tier Two Pylons (Haste, Insight, Leap, Spider Climbing) because their recipes require Air, Fire, Arcane, or Ender Runes, which can only be crafted in the Runic Anvil once you reach Tier Three, meaning the Occulus requirement of "Craft Any Tier Two Pylon" is unobtainable without circumventing with Villager trades.

**To Reproduce**
1. Get items: Runic Forge, Rune Pattern: [Air, Fire, Arcane, Ender], Superheated Vinteum Ingot
2. Use Runic Hammer on Anvil with above items
3. Have magic Tier Two
4. See error "You do not have the skill or knowledge"

**Expected behavior**
[Air, Fire, Arcane, Ender] Rune to be crafted

**Screenshots**

![image](https://github.com/user-attachments/assets/fcfc224a-1099-4a85-8ddd-dcd986d228c9)
![image](https://github.com/user-attachments/assets/90adef6d-4366-4c37-8914-9cf54badcd49)
![image](https://github.com/user-attachments/assets/8bbc334c-23d1-4fe4-aa0e-e3df59755d62)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.19-all.jar
 - Forge Version 47.3.0

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Resolved in 3.0.0.20
