### ISSUE TITLE
Ring of the Skies is not working correctly

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#864]
**Describe the bug**
When having the Ring of the Skies equipped, Fling Self will have the added mid air charges as it should but the ring does not add the strength to the fling that it should and it does not prevent the impact damage as it should. It also appears to not be using charge as it should.

**To Reproduce**
1. Equip Ring of the Skies (charged)
2. Use Fling Self Spell to propel into a wall

**Expected behavior**
The augmented Fling Self spell should be stronger, it should not cause damage when hitting walls, and it should use charge from the Ring of the Skies.

**Comment by Mithion** [comment]
Resolved in 3.0.0.20

**Comment by Sarithule** [comment]
Sweet, thank you! The fling self combo is the funnest way to get around and I was so sad when it was not working. So glad to know it is fixed now!
