### ISSUE TITLE
Able to Duplicate Spectral Swords

### ISSUE THREAD

**Issue by ZargetGaming** [Mithion/Mana-And-Artifice#865]
**Describe the bug**
Casting the Tier 3 cantrip that stores a spell in your wand, then scrolling to an empty hotbar slot before it casts will create the spectral sword in that hotbar slot called "Air", leaving your wand free to continue casting spells. These swords can be dispelled by pressing Q, but can be tossed from the inventory by dropping them off the side of the inventory screen.

**To Reproduce**
1. Get Chimerite Manaweaver's Wand and any Spectral Sword spell. (Mine is Spectral Sword + Poison)
2. Use sword spell in Cantrip slot at Tier 3
3. Cast cantrip, then scroll to an empty hotbar slot
4. Sword appears in that slot rather than replacing the wand

**Expected behavior**
Wand should be replaced with sword regardless of selected hotbar slot

**Screenshots**
![image](https://github.com/user-attachments/assets/2da17c17-6d72-48c5-a040-1d8eabfe0d41)

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.19-all.jar
 - Forge Version 47.3.0

**Additional context**
This will also work if you scroll to another item in your hotbar, replacing that item with the sword instead of the wand. Pressing Q dispels the sword and brings back the old item,

**Comment by Mithion** [comment]
Resolved in 3.0.0.20
