### ISSUE TITLE
Incorrect Tier Tooltips

### ISSUE THREAD

**Issue by no-name-provided** [Mithion/Mana-And-Artifice#866]
**Describe the bug**
Many tooltips have the wrong tier. For example, the altar of arcana's tooltip says "no tier requirement", but the only recipe is tier 2.  Wooden left arms are tier 2, but the tooltip says "no tier". This is exacerbated by addons that generate additional recipes.

**To Reproduce**
Install JEI and compare tooltips to recipes.

**Expected behavior**
The tooltip should reflect the information in the oculus.

**Screenshots**
![image](https://github.com/user-attachments/assets/134fb740-359f-4466-8601-98fd4dcc2208)

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.19]
 - Forge Version [e.g. 47.3.0]

**Additional context**
Tested on a minimal installation.

**Comment by Mithion** [comment]
It uses recipe analysis, so it will use the lowest tier it can find, and will default to "No Tier Requirement" if anything goes wrong as well.  It's just meant to be a rough estimate.
