### ISSUE TITLE
Tier 3 runes can be crafted by tier 2 players

### ISSUE THREAD

**Issue by no-name-provided** [Mithion/Mana-And-Artifice#867]
**Describe the bug**
Tier 3 runes can be crafted by tier 2 players by using a construct to do the hammering.

**To Reproduce**
1. Reach tier 2
2. Make a wickerwood construct with a hammer arm
3. Scribe an ender rune pattern
4. Place pattern on runic anvil, followed by superheated vinteum.
5. Make lodestar
6. Configure lodestar to runeforge at anvil
7. Assign construct to lodestar

**Expected behavior**
The construct should produce the same error I get when manually hammering. That it lacks the skill or knowledge to complete the task.

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.19]
 - Forge Version [e.g. 47.3.0]

**Additional context**
Tested on a minimal installation.

**Comment by Mithion** [comment]
You need to get an ender rune to make the pattern in the first place though - I don't see this as a huge issue.  Most things that you can do with said runes will also tier-lock you anyway.

Unless you somehow got the pattern in a different way?

**Comment by no-name-provided** [comment]
The ender rune pattern is at tier 2 - you can grab that from the book or JEI and scribe it by hand. The ender rune itself is tier 3. As for uses, several runes can be made this way. This enables early pylon creation, early access to enchantments like telekinetic retrieval, etc.

Even if I was supposed to need the pattern, wouldn't it be available via trade?

**Comment by Mithion** [comment]
Trade from what?  Other players?  They could just give you the runes too.

I think this was a good find and I appreciate the time taken to let me know, but I still consider it low priority (if I fix it at all, the fix would be very complex for a minimal benefit).

**Comment by no-name-provided** [comment]
Sorry, I thought you were asking about "runescribing recipes", which I seem to recall villagers/the wandering merchant trading in an older version of the mod. The rune "pattern" was obtained in the way I specified, by simply looking it up in the codex and scribing it myself.

This bug isn't game breaking, and it has little impact on game balance, so I don't much care how (or if) you fix it. Just figured it should be reported.

**Comment by Mithion** [comment]
That part I did do with 3.0.0.20 :)
