### ISSUE TITLE
[Crash] Incompatibility with Embeddium

### ISSUE THREAD

**Issue by SaltSouls** [Mithion/Mana-And-Artifice#869]
**Describe the bug:**
There seems to be a compatibility error with M&A's `MageLightRenderer` and Embeddium's `renderBlockEntity` that is causing the game to crash pretty consistently.

**To Reproduce:**
1. install Embeddium and M&A
2. load into world
3. place mage light
4. wait
5. crash
6. ???
7. profit

**Expected behavior:**
Shouldn't be crashing.

**Version Information:**
 - Embeddium: [0.3.25]
 - Mana & Artifice: [3.0.0.20]
 - Forge Version [47.3.5]

**Log Files:**
[Latest](https://gist.github.com/SaltSouls/e811f426807d156be4cadff836bc6583)

**Comment by no-name-provided** [comment]
Hmm... Slickson77 just added embeddium to Wellspring Adventures 2 (Embeddium 0.3.24, Forge 47.2.20). I wonder why it isn't crashing that modpack.

**Comment by SaltSouls** [comment]
> Hmm... Slickson77 just added embeddium to Wellspring Adventures 2 (Embeddium 0.3.24, Forge 47.2.20). I wonder why it isn't crashing that modpack.

Couldn't say, but the crash isn't always immediate. It usually crashes after about an hour or two of playing, though the error always seems to suggest an issue between Embeddium and M&A.
