### ISSUE TITLE
The mod wants me to downgrade curios version

### ISSUE THREAD

**Issue by Xaikii** [Mithion/Mana-And-Artifice#87]
> Mod File: mana-and-artifice-1.1.0.4.jar
> 	Failure message: Mod mana-and-artifice requires curios 1.16.4-4.0.2.1
> 		Currently, curios is 1.16.4-4.0.3.0
> 	Mod Version: 1.1.0.4
> 	Mod Issue URL: https://github.com/Mithion/Mana-And-Artifice/issues

**Comment by Mithion** [comment]
This is fixed in the latest beta version on curseforge
