### ISSUE TITLE
Game crash after using magic (started happening recently... am tier 4)

### ISSUE THREAD

**Issue by Deimos1054** [Mithion/Mana-And-Artifice#871]
**Describe the bug**
So... am not exactly sure how this happens, but am guessing that its after I use magic, after a while, my game just straight up crashes...

**To Reproduce**
Dont know...

**Expected behavior**
shouldnt crash...  (when I use the mod NotEnoughCrashes, it acts as if the mod isnt there... and the crashed with or without NEC, dont seem to give me Crashlogs... and the error code is 1... whatever that means...

**Screenshots**
Am gonna post modlist screenshots since I dont know what other screenshots should I post... since... what can I screenshot? when it just crashes and doesnt give me Crashlogs...

![Mods Screenshot 1](https://github.com/user-attachments/assets/175dbf14-486b-47d7-a9d3-dbb18be1e51d)
![Mods Screenshot 2](https://github.com/user-attachments/assets/0e15a7c1-9130-4cbf-b004-87f4cb285408)
![Mods Screenshot 3](https://github.com/user-attachments/assets/a4840726-d01e-4db0-bec9-e9c0f5e55596)
![Mods Screenshot 4](https://github.com/user-attachments/assets/e16bfdcd-0d38-494d-8a96-6c089f3a983c)
![Mods Screenshot 5](https://github.com/user-attachments/assets/35727428-7d92-46e4-9fc6-16ea795dc156)
![Mods Screenshot 6](https://github.com/user-attachments/assets/dccf5624-90bc-418d-96ab-893ce04440e3)

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.0.0.15
 - Forge Version: 47.2.0

**Additional context**
I do not know what to do... asked for help on aternos, and were trying to look into whats happening... unsure if we can do something though...

**Comment by Deimos1054** [comment]
it happens after doing anything...

Using Manaweavers wand
using spells...

**Comment by Mithion** [comment]
Update to 3.0.0.20

**Comment by Deimos1054** [comment]
ok, havent posted in a long while... cause I forgot, but If I remember correcty, it was something to do with Rubidium...
