### ISSUE TITLE
Amulet of the Battlemage to Check Both Hands For Valid "Sword"

### ISSUE THREAD

**Issue by Dimmondback** [Mithion/Mana-And-Artifice#874]
**Is your feature request related to a problem? Please describe.**
With the introduction of the Bone Scythe, the transcribing functionality of Bone Scythe is redundant. Amulet of the Battlemage will only ever check "the other hand" This means one of two scenarios:
  - You need another sword or Bone Scythe to trigger the damage bonus
   -- Note: When using another sword, the Bone Scythe doesn't provide any additional bonuses for using it
   -- Note: Placing the spell into a spell book in the "other hand" means you don't need a 2nd tool and have access to the entire spellbook while still getting the damage bonus and the melee damage of the Bonus Scythe
  - You place the spell you want to use in your "other hand" to gain the damage bonus but cannot gain the bonus for the spell transcribed on the Bone Scythe itself

**Describe the solution you'd like**
Proposed solution is to add an additional check to check both hands for valid weapon.

**Additional context**
Linked to bug related to Amulet of the Battlemage with Bone Scythe damage bug.

**Comment by Mithion** [comment]
This is intentional.  No one item will trigger both parts of AotB.
