### ISSUE TITLE
Wellspring pillars disappear when looking in specific direction

### ISSUE THREAD

**Issue by no-name-provided** [Mithion/Mana-And-Artifice#879]
**Describe the bug**
Wellspring pillars are culled _very_ prematurely, then restored.

**To Reproduce**
1. Make a wellspring prism
2. Stand near the center and look in a very specific, small range of vectors
3. See the wellspring pillars get culled
4. Look up/down or walk forward/backward, and see them reappear

**Expected behavior**
The wellspring prism shouldn't "flicker" as I poke around it. While some level of premature calling is, unfortunately, expected, this effect results in a particularly bothersome "flickering". I would expect the wellspring blocks to render until I look too far away, then stop rendering. Ideally, this would happen offscreen.

**Screenshots**
![image](https://github.com/user-attachments/assets/94020bab-6892-40fc-8ad5-0e60c69f2ccd)
![image](https://github.com/user-attachments/assets/a8635bb5-538d-4760-9675-f3bbfa3edc56)

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.3.0.20]
 - Forge Version [e.g. 47.2.20]

**Additional context**
Slightly modified WA2, local LAN game. Includes Dragon Magic & Relics.

**Comment by Mithion** [comment]
Not seeing this locally.  
Can you provide exact coordinate offsets from the pillar base?

**Comment by Sarithule** [comment]
I am getting this as well but not on all my captured springs. Only specific ones do this.

![PillarsDisappearing-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/3dccfd04-5159-45d2-a461-f6da8708d77f)

**Comment by Sarithule** [comment]
I don't know if this has anything to do with it but out of all 6 of my well springs, the only ones that seem to do this are ones that are on, or partially on water. It looks like no-name-provided's platform is also on water from the pictures he provided.

**Comment by Sarithule** [comment]
Upon further experimentation it looks like an important variable to get this bug to happen is that the player must be standing on the same level as the central blocks of the captured wellspring. doing so even outside of the wellspring will produce the effect as well.

**Comment by Mithion** [comment]
I'm looking like crazy and not seeing it - I straight up cannot replicate this one.  Tried a whole bunch of resolutions, on water, not on water, different y levels, nothing.

**Comment by no-name-provided** [comment]
It's a LAN party server, so I can't just hop on and grab a screenshot. Additional information: I wasn't the host, I was using LAN to join a "single player" game, my GUI was in scale 3 and my F3 screen probably looked something like this:

![image](https://github.com/user-attachments/assets/22f4e2a8-fb9b-4e0d-9e09-d1712e3c76e8)

As a reminder: this was experienced on Wellspring Adventures 2 while logged in via LAN. There were other glitches associated with LAN, like captured wellsprings disappearing for the players who didn't capture them, so this may be a packet issue.

**Comment by Mithion** [comment]
I wonder if it's an issue with embeddium, modernfix, immediatelyfast or similar?  Maybe it's capping the render bounding boxes of some blocks.  Could you try without each of them?

**Comment by Sarithule** [comment]
I disabled Embeddium and the pillars stopped having a problem with disappearing. I re-enabled Embeddium and they started disappearing again. I think it is a safe bet that it is an issue with Embeddium that only happens when you are standing one block above ocean level and your character is looking up at a very specific angle.

**Comment by Sarithule** [comment]
P.S.
I have also noticed this type of problem during the ritual of the wizards counsel. if you look up from the wizards when they are razing you into the air then they will disappear. Probably also an Embeddium issue.

**Comment by Mithion** [comment]
Closing as a specific interaction with Embeddium.  Thanks for all your effort in narrowing it down; but it's something they're doing on their end.

**Comment by no-name-provided** [comment]
Issue passed along to the embeddium team: https://github.com/embeddedt/embeddium/issues/382.

**Comment by Mithion** [comment]
@embeddedt thanks for the detailed explanation - this is definitely on my end.  I'll make some changes.
