### ISSUE TITLE
Issue with Occulus level up progress Step

### ISSUE THREAD

**Issue by TBone311xXx** [Mithion/Mana-And-Artifice#88]
Level 3, the Progress step for "Find a Stronghold" Does not recognize that I have stepped within a stronghold, unless the step needs me to enter The End, in which further clarification would fix.
Mana and artifice version: 1.1.0.4
Minecraft version: 1.16.4

**Comment by Mithion** [comment]
It's tied to the vanilla advanvement, so make sure you have that.
