### ISSUE TITLE
Construct Recipies for right wicker arms are producing left wicker arms

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#880]
**Describe the bug**
I have been trying to create right wicker arms for ax, hammer, grabber - both left and right recipes for these arms create left arms.
I have been trying to create a left wicker arms for fishing, and bladed - both left and right recipes for these create right arms.

**To Reproduce**
attempt to make wicker arms of both sides for each of the types of wicker arms

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.20]
 - Forge Version [e.g. 47.3.0]

**Comment by Mithion** [comment]
Minecraft matches recipes mirrored, which causes this behaviour.  Try a mod like Polymorph to select which one you want to craft, or alternately craft a construct arm with itself in a crafting grid to flip its side.

**Comment by Sarithule** [comment]
I would still consider this a bug. The codex says you can make an arm with a recipe which does not work without another mod or an undocumented technique. Minecraft only matches recipes that are mirrored from left to right. If you used a recipe that was mirrored from top to bottom you could use the same layout and items to differentiate the left and right arm.

![2024-07-30_17 48 59](https://github.com/user-attachments/assets/b88eac00-3766-4f76-8d4c-b3d2d2eda840)
