### ISSUE TITLE
Broken loot chests

### ISSUE THREAD

**Issue by BjoernSeine** [Mithion/Mana-And-Artifice#886]
**Describe the bug**
For some M&A loot chests (very rough estimate 10%), when I first try to open them nothing happens (the chest does not open); on a second try the chest opens but is empty. As far as I can tell this is not linked to any particular structure or chest in said structures; but I have only noticed it on M&A loot chests. Lootr is NOT installed. I suspect that a specific item in the loot table causes issues when it is rolled.

**To Reproduce**
1. Open chests in M&A structures
2. Sometimes observe the behaviour described above

**Expected behavior**
On first.

**Version Information:**
 - Mod Version: 3.0.0.20
 - Forge Version 47.2.5

**Comment by Mithion** [comment]
Please provide log files from when this happens.

**Comment by BjoernSeine** [comment]
https://hastebin.com/share/tivorazise.rust

I only copied the end of the log since it's a *really* long one and I couldn't find an option on either page to just upload the .txt. Pretty sure it's the event at 13:18:15; this time it happened on a manaweave cache. I saved & exited immediately after.

I'm now on version 3.0.0.21

**Comment by Mithion** [comment]
Excellent, this is exactly what I needed.  Thanks!
