### ISSUE TITLE
All codex entries marked unread after update

### ISSUE THREAD

**Issue by BjoernSeine** [Mithion/Mana-And-Artifice#887]
**Describe the bug**
After updating from version 3.0.0.20 to 3.0.0.21, all previously read codex articles are once again marked as unread.

**Version Information:**
 - Mod Version: 3.0.0.20 / 3.0.0.21
 - Forge Version 47.2.5

**Comment by Mithion** [comment]
I had to change how it was done, so it unfortunately reset.
