### ISSUE TITLE
Bone Scythe codex entry wrongly claims swords can be used to block

### ISSUE THREAD

**Issue by BjoernSeine** [Mithion/Mana-And-Artifice#889]
**Describe the bug**
The codex entry for the bone scythe states that "[...] it can be used to block, *like a sword*". However, blocking with swords was removed in Minecraft 1.9, the Combat Update. The codex entry should read "like a shield".

**Version Information:**
 - Mod Version: 3.0.0.21
 - Forge Version: 47.2.5

**Comment by Mithion** [comment]
No, it was certainly like a sword as the method still existed to overwrite.  I blame Mojang for not removing the method.
