### ISSUE TITLE
Ritual kit bugs

### ISSUE THREAD

**Issue by Hunt3rM4d** [Mithion/Mana-And-Artifice#89]
I've experienced 2 different things while trying to do rituals with the ritual kit (v. 1.1.0.8):
1. The ritual of the forgotten lore (the one to obtain the motes of magic) cannot be done with the kit. The message that is shown is that there are not enough bookshelves nearby. Context: I did the ritual targetting the center of a 7x7 area. In the border of that area (9x9) I put a total of 10, 12 and 17 bookshelves in my tests. In all of these cases the ritual wouldn't start.

2. Upon ritual completion (from the ritual kit) the items pop off the chalk runes, thus not being consumed by the ritual (I don't know if this is intended behavior). With this the user can basically do rituals for free.

**Comment by Mithion** [comment]
This is fixed in the latest version on Curseforge.  It's marked as "beta" (v1.2.0.1)
