### ISSUE TITLE
[Request] Single Item filter for Eat Item construct task

### ISSUE THREAD

**Issue by BjoernSeine** [Mithion/Mana-And-Artifice#892]
Many construct tasks that take a ledger as a black-/whitelist also have a single item slot that serves as a convenient alternative. I would like a similar slot for the "Eat Item" task which only has the ledger filter option; my specific use case is a construct handling my MagiChem distillery which I want to eat (only) alchemical waste.

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
