### ISSUE TITLE
Mana Shield Replaces Buff From Mana Boost

### ISSUE THREAD

**Issue by Red1004** [Mithion/Mana-And-Artifice#894]
**Describe the bug**
When having both the Mana Shield and Mana Boost effect active at the same time, the effect applied first gets replaced by the effect provided second.

**To Reproduce**
1. Get Mana Boost effect
2. Cast Mana Shield
3. See error

**Expected behavior**
Either to add the boosts together or prioritize the one that grants the largest boost.

**Screenshots**
![2024-07-26_07 56 09](https://github.com/user-attachments/assets/3fe5ffa7-49b7-49f7-b88f-afa07a9889ad)
![2024-07-26_07 56 42](https://github.com/user-attachments/assets/f4f8a4ce-6610-4022-aec3-e6de9b4c9169)
![2024-07-26_07 56 46](https://github.com/user-attachments/assets/c05e175e-758d-42e0-93f0-4636c1fa6381)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.21
 - Forge Version: 47.2.20

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
