### ISSUE TITLE
Faction-specific enchantment application

### ISSUE THREAD

**Issue by gunkman123** [Mithion/Mana-And-Artifice#898]
**Describe the bug**
The runic anvil isn't allowing for faction-related enchants to be applied to casting items.
Friend at Tier 3 in the Undead faction was unable to apply Frost Walker 1 to casting items.
I (Tier 4, Wizard Council) am unable to apply Power 4 to my staff.
We have attempted this with items being both inscribed with spells and blank, neither worked.

**Expected behavior**
The anvil should be glowing and allow the enchantments to be applied

**Screenshots**
![image](https://github.com/user-attachments/assets/1eb38cf2-68b1-454e-a7a2-8169a9f0ba6b)
![image](https://github.com/user-attachments/assets/3f818f37-094a-4488-9954-386856975ba0)

**Version Information:**
 - Mod Version: [1.20.1-3.0.0.21]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
Just tried this in my dev instance and it worked perfectly.  You must have another mod that is messing with enchantability rules.  You'll need to narrow it down and find out which one it is.

**Comment by gunkman123** [comment]
Tested by deactivating the only mod I could think that would do this.
Turns out it's due to the Universal Enchants mod by Fuzs. Specifically we were using v8.0.2-1.20.1.

**Comment by Mithion** [comment]
Resolving as other mod issue
