### ISSUE TITLE
Codex Entries marked unread after death

### ISSUE THREAD

**Issue by BjoernSeine** [Mithion/Mana-And-Artifice#899]
**Describe the bug**
After dying, all codex entries are marked as unread again. Seems to be consistent.

**To Reproduce**
1. Read at least one codex entry
2. /kill
3. Note that codex entry is marked as unread again

**Expected behavior**
Read codex entries should remain read after death.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.22
 - Forge Version 47.2.5

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
