### ISSUE TITLE
1.16.4 can't use purified vinteum dust to start the rituals

### ISSUE THREAD

**Issue by 5kedone** [Mithion/Mana-And-Artifice#90]
Hi I am using version mana-and-artifice-1.2.0.1.jar of mod and gecko 3.x ect , after I draw the ritual with the chalk when I right click on center block with the purified vinteum dust nothing happens ? 

Am I being dumb or is this a bug

**Comment by Mithion** [comment]
If nothing happens, then you have the pattern wrong.  Double check that every rune is in the right place, and the whole ritual is on the same y-level.

**Comment by 5kedone** [comment]
Yes I have checked multiple times even rewatched dw20 video 4 times just to make sure lol, will try running mod on own today encase it's a crossmod issue , it's possible I have 115 mods in my profile/instance

**Comment by Mithion** [comment]
Can you post a screenshot of the ritual?  Which one are you trying to do?

**Comment by 5kedone** [comment]
It was a config issue not sure what one I deleted whole config folder and let it rebuild started a new instance and now it works lol , all I can think of is a old config file was borked or summit , very strange will close this now lol
