### ISSUE TITLE
Breaking Blocks does not apply spell modifiers correctly when using create wand of symmetry

### ISSUE THREAD

**Issue by ViewPointGames** [Mithion/Mana-And-Artifice#900]
**Describe the bug**
Casting a break spell with modifiers like silk touch or using a collectors ring does not apply these to the targeted block when using the wand of symmetry from the create mod. Instead, the wand mirrors the modifiers, but they do not get applied to both targeted blocks, but only the other one.

**To Reproduce**
1. Install both MnA and Create
2. Get Wand of Symmetry, Book of Rote
3. Make any Break Spell (tested with Bolt Break) with Silk Touch modifier
4. Create a symmetry mirror on the ground
5. Place any block that can be silk touched (tested with vanilla stone), in a way that it gets mirrored by the symmetry wand
6. Cast the break spell on one of the blocks

**Expected behavior**
I expect both blocks to be broken with all modifiers correctly applied.

**Screenshots**
![image](https://github.com/user-attachments/assets/725cbf96-54d8-4f07-9ebf-42f95ce6a072)
![image](https://github.com/user-attachments/assets/5f8d1c29-1b64-4715-bb2f-3cfa8d3fa9e1)
![image](https://github.com/user-attachments/assets/ef697fbe-1336-495e-b2b2-d4ffd99ca130)

**Version Information (please complete the following information):**
 - Minecraft 1.20.1
 - Mod Version 3.0.0.20
 - Forge Version 0.47.2

**Additional context**
Create Mod is used for the wand of symmetry

**Comment by Mithion** [comment]
This is not a bug with M&A, this is some odd interop between it and create; and how they handle things.  This will not be worked on.
