### ISSUE TITLE
Altar of Spellcrafting Crash with Custom Containers

### ISSUE THREAD

**Issue by Lonemind** [Mithion/Mana-And-Artifice#901]
Minecraft crashes when using the Spellcrafting Altar in proximity to custom inventories.

Can be reproduced by placing an Essence Cask from Primal Magick near the Spellcrafting Altar. When the Altar is activated I assume it looks at all nearby containers and tries accessing their contents. The Cask from Primal Magick works like a deep storage unit for specific PM items. From reading the crash log I suspect this interaction is what causes Minecraft to crash.

 - MnA Version: [mna-forge-1.20.1-3.0.0.21-all]
 - Forge Version [47.2.20]

Crash Log:
https://mclo.gs/YTg4oCo

**Comment by Mithion** [comment]
IItemHandler's retrieval method specifically annotates the direction as @Nullable, meaning null is a valid value to pass in.  Primal Magick will need to handle this case on their end.
