### ISSUE TITLE
Shrinking self multiple times does self damage

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#903]
**Describe the bug**
Shrink Self seems to work correctly when cast for the first time but subsequent casts while the shrink effect is still active appears to remove the health every time but only reduces max health the first time it is cast.

**To Reproduce**
1. Create a Shrink Self spell.
2. Cast Shrink self spell once to see the normal reduction in max health.
3. Cast Shrink self spell again while the effect is still active.
4. Watch health become damaged.

**Expected behavior**
I would expect further applications to refresh the time the shrink is active and keep the max health reduction the same, but not damage health further.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.22]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
