### ISSUE TITLE
Shrink self to increase self fling range causes self fling to be inacurate.

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#904]
**Describe the bug**
When using Fling Self to fly around, use of the Shrink Self spell to increase range per fling causes the fling self spell to not be directed exactly to where the player is looking.

**To Reproduce**
1. Create Shrink Self spell with maxed out lesser magnitude (9) 
2. Create Fling Self spell with maxed out speed (3) and Feather Fall (unmodified)
3. Cast Shrink Self and while it is active, fly around with the Fling Self spell.
4. See error - Often you will not be flung in the exact direction you are pointing (can be off by around 15 to 20 degrees)

**Expected behavior**
Fling self should be accurate whether a player shrunk or not shrunk.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.22]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
Fling uses the character's current look angle, normalizing then scaling it by the speed of the spell.  I've double checked the math of the spell, and it is correct.

Something when shrunk causes this to change how the forward vector is calculated by the base game.  I'm calling this an issue with vanilla calculations and not putting any more time into it.
