### ISSUE TITLE
Interaction events fail to trigger while holding the hammer arm

### ISSUE THREAD

**Issue by The-Corrupted** [Mithion/Mana-And-Artifice#905]
**Describe the bug**
If you make a construct hammer arm ( tested with the obsidian and iron arm ) and attempt to place it on the gantry or armor stand by right clicking nothing happens. Equally, if you attempt to interact with any interactable while holding the hammer arm, the interaction will fail to trigger (unable to open chests,  interact with furnaces, crafting tables, etc).

**To Reproduce**
1. Create an obsidian or iron hammer arm
2. Right click on any interactable block while holding the arm.

**Expected behavior**
The hammer arm should successfully be placed on the gantry or armor stand and you should be able to interact with chests, crafting tables, etc while holding the arm.

**Version Information (please complete the following information):**
 - Mana and Artifice v3.0.0.22
 - Forge v47.3.5

**Additional context**

**Comment by Mithion** [comment]
This is an interoperability bug with better combat/epic fight, and works fine with just mna.  There is a community made datapack in the discord (addons channel) that addresses it.
