### ISSUE TITLE
Manaweaving Patterns on Manaweaving Table become dark and hard to see at night

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#906]
**Describe the bug**
It appears that the Manaweaving Patterns on the Manaweaving Table are being affected by the ambient light of the day/night cycle. This makes it difficult to see what patterns the Manaweaving table has on it when attempting to create stuff at night.

**To Reproduce**
1. Create Manaweaving Table and place it in the world in a well lit room.
2. Draw some Manaweaving Patterns near the Manaweaving Table so that it picks them up and displays them.
3. Observe the visibility between when it is day and when it is night 
4. See error - The Manaweaving patterns displayed on the Manaweaving Table will become almost invisible and dark when it gets dark out.

**Expected behavior**
The Manaweaving Patterns displayed by the Manaweaving Table should Not change how visible they are due to whether it is day or night.

**Screenshots**

Manaweaving Table during the DAY in a well lit room:
![2024-08-04_14 39 54](https://github.com/user-attachments/assets/29fb5432-8a19-4098-8528-3fba373c92e5)

Manaweaving Table during the NIGHT in a well lit room:
![2024-08-04_14 45 52](https://github.com/user-attachments/assets/3fa25d2b-1ba5-4f7e-b4f3-c3304a7c2959)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.22]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
