### ISSUE TITLE
Bug or Feature? Adding movement buffs togeather leads to ramping Jump speed

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#907]
**Describe the bug**
When applying Haste, Leap, Grow, Feather fall, Water walk, and Gravity well to your self, Holding down the jump button while moving forward will produce a ramping velocity so long as you don't run into anything. This effect is much more pronounced when on land instead of water.
I am not sure if this is intended behavior. Bug or feature?

**To Reproduce**
1. create separate spells to apply the following effects on yourself: 
    Haste (magnitude 5),
    Leap (magnitude 8),
    Grow (magnitude 9), 
    Feather fall (magnitude 1),
    Water walk, 
    Gravity well
4. find a nice long stretch of flat ground to travel across
5. run forward while holding the jump button down
6. See error - watch as your speed ramps up more and more with each jump

**Screenshots**
![Ramping Jump speed](https://github.com/user-attachments/assets/c3c122f3-20ab-4268-ba54-7353ee022205)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.22]
 - Forge Version [47.3.0]

**Comment by Sarithule** [comment]
If this is a bug then it is a really fun one. It is quite exciting to get going that fast as long as you can find a nice long stretch of flat surface where you don't run into anything :)

**Comment by Sarithule** [comment]
Upon further experimentation it appears that Grow is the a key component to achieve this effect. I am guessing that the combination of the speed buff from Grow mixed with the speed buff from Haste is interacting with the attempt to keep velocity while jumping from Leap which may be ending before it is expected to due to gravity well. the Jump buff from Grow may also be mixing with the jump buff from Leap.

**Comment by Mithion** [comment]
It's very much intentional.  You can turn it off via config, if you didn't actually want it for whatever reason.
![image](https://github.com/user-attachments/assets/9895b55d-8019-4cb0-884a-4629d2c508bf)

**Comment by Sarithule** [comment]
Nice :) it is good to know this is intentional. One more fun way to get around the world!
