### ISSUE TITLE
Construct spraying water to owner not working.

### ISSUE THREAD

**Issue by tsukaerujuriki2** [Mithion/Mana-And-Artifice#908]
The ability to spray water to the owner while following/guard seems to not work.

**To Reproduce**
Catch fire near the construct with tank torso and fluid nozzle

**Expected behavior**

Construct should extinguish me, with water while on fire

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.22]
 - Forge Version [1.20.1]

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
