### ISSUE TITLE
Some Sigils not affecting the player (probably the owner of the sigil)

### ISSUE THREAD

**Issue by tsukaerujuriki2** [Mithion/Mana-And-Artifice#909]
**Describe the bug**
Some Sigils activated wont affecting the player (probably the owner of the sigil).

It can be placed and activated, but it didn't have any effect on me.

grow, shrink, swift swim, divination, levitation and spider climbing.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.22]
 - Forge Version [1.20.1]

**Comment by Mithion** [comment]
Sigils intentionally do not affect their caster.
