### ISSUE TITLE
The Red Pin to remove recipy from HUD does not show in Curios inventory

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#910]
**Describe the bug**
The red pin that shows up next to your character model in the regular inventory which allows you to unpin a recipe from the HUD does not show up when opening the Curios inventory. I didn't even know it was there for a very long time until I read about it in the codex. This is because I always use the Curios inventory.

**To Reproduce**
1. get Codex Arcana
2. Pin a recipe to the HUD
3. Open the Regular inventory and see the red pin that lets you unpin the recipe from the HUD
4. See error - Open the Curios inventory and see that the red pin is missing.

**Expected behavior**
the red pin should be present in both the vanilla and the Curios inventory

**Screenshots**

Regular vanilla Inventory

![2024-08-06_05 02 58](https://github.com/user-attachments/assets/a5c0d096-4696-442f-aff2-08a50dbc6bf9)

Curios inventory

![2024-08-06_05 03 10](https://github.com/user-attachments/assets/65b0b546-5b7f-4dfd-85f9-abb61bbd1ac1)

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.22]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
The curios inventory is different than the player inventory.  The pin will not show there.
