### ISSUE TITLE
Crystal of Memories tooltip displays an outdated capacity when completely full

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#912]
**Describe the bug**
The Crystals of Memory tooltip says that it has 100 experience when completely full.

**To Reproduce**
1. Fill up a crystal of memories entirely
2. Look at the tooltip

**Expected behavior**
The crystal of memories lists 20000/20000, "the crystal is full", or some similar message

**Screenshots**
![image](https://github.com/user-attachments/assets/2f8da903-1da1-4e4c-ae0e-aebb90279138)

![image](https://github.com/user-attachments/assets/d637774f-8d7a-48e1-946c-64b30f0f7954)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.22

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
