### ISSUE TITLE
Greater Animus doesn't drop item after it wears off

### ISSUE THREAD

**Issue by Oggas** [Mithion/Mana-And-Artifice#913]
**Describe the bug**

**To Reproduce**
1. Get any item.
2. Cast greater animus on the item.
3. When the duration expires item doesn't drop, see error.

**Expected behavior**
I expect from how animus works that the item would drop again.

**Screenshots**

**Version Information (please complete the following information):**
 - Mana & Artifice: 3.0.0.22
 - Twilight forest 
 - Lootr
 - Xaeros maps

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
