### ISSUE TITLE
Use Item On Block Construct command not working

### ISSUE THREAD

**Issue by Creativious** [Mithion/Mana-And-Artifice#915]
**Describe the bug**

**To Reproduce**
1. Give axe to construct
2. Have the lodestar use the Use Item On Block command on a log
3. Nothing happens

**Expected behavior**
For the log to be stripped

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.22]
 - Forge Version [e.g. 47.2.17]

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
