### ISSUE TITLE
Can't switch modes or re-search for Biome Thaumaturgic Compasses 

### ISSUE THREAD

**Issue by Creepercharge** [Mithion/Mana-And-Artifice#916]
**Describe the bug**
Thaumaturgic Compasses when attuned to biomes can't switch between new/existing chunks and new chunks only.
The compasses also can't be reused to find new biomes

**To Reproduce**
1. Attune Compass to a biome with the locating ritual
2. Attempt to switch modes
3. Attempt to search for a new target

**Expected behavior**
Thaumaturgic compasses should switch modes and re-search for targets. however only the structure compass variants are able to

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.22
 - Forge Version: 47.2.20

**Comment by Mithion** [comment]
The biome locating code does not allow for "new generation only" like structures do.
