### ISSUE TITLE
Texture stitching causes crash during bootup on 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [Mithion/Mana-And-Artifice#917]
MC: 1.20.1
Forge 47.3.5
MNA: 3.0.0.22-all.jar

[Crash Report](https://mclo.gs/6DSJAaJ)

![image](https://github.com/user-attachments/assets/a105404a-a24c-4d7b-af1a-ef66312e0467)

something about the mna:entity/vortex_raid texture being too big

**Comment by Mithion** [comment]
There is a datapack in the M&A server that will help with this issue by reducing the texture size of some things; however it's a core MC bug on certain hardware as the root cause.
