### ISSUE TITLE
Crushing task fail statement bricks construct

### ISSUE THREAD

**Issue by Luna-Nocturna** [Mithion/Mana-And-Artifice#918]
**Describe the bug**
My constructs, when assigned to crush, stop functioning wholly if they fail to crush. This happens either if the red IF statement is connected to another task or is left open intending to reset to the start.

**To Reproduce**
Steps to reproduce the behaviour:
1A. Set up Lodestone with the following tasks:
1B. Gather using 2 marking runes for a small box.
1C. Crush at a grindstone with a rune of marking.
1D. Put the crushed item into inventory.
2. The task list functions fine until either there was no item to pick up or it couldn't put the last crushed item into the inventory yet.
3. The crushing task fails, the construct stops moving.
4. Diagnosis log also stops progressing, the construct is just frozen. I notice in the log the crushing task has a play (in progress?) icon.
5. It will however listen to bell commands and can be reassigned, however their purpose is automation and that's manual labour.

**Expected behavior**
The construct should follow the failed IF statement and either progress at the red output of the crush task or reset to the start if there's no output.

**Screenshots**

![image](https://github.com/user-attachments/assets/a5b9a710-5796-4a4a-8667-fe35fb4e6ae8)

![image](https://github.com/user-attachments/assets/3d180981-99c8-4a5e-a39f-250f1850465f)

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.22]
 - Forge Version [e.g. 47.3.6]

**Additional context**
I ran into this by automating MagiChem's power generation as intended. The Circle of Power (A block that generates energy used for the mod's devices to function.) burns item A, gets outputed as item B, which then again can be crushed into item A again to be reused as fuel. As the crushing can only be done by constructs this is the intended way.

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
