### ISSUE TITLE
Blink Spell With Ring of the Enderman Causes World to Freeze If Used On Blaze

### ISSUE THREAD

**Issue by J0RR3L** [Mithion/Mana-And-Artifice#919]
If you equip the Ring of the Enderman and use the blink spell on a blaze, the server and/or single player world will freeze but won't crash. As far as I've tried, no specific shape causes the bug; as long as it's the blink spell with the ring it will cause this bug to occur.

1. Create a blink spell with any shape that can target mobs using either the inscription table or the book of rote
2. Equip the Ring of the Enderman in one of your curio ring slots
3. Spawn or find a blaze
4. Use the blink spell on the blaze
5. Punch the blaze or inspect the world to confirm it has frozen
6. If the world has not frozen yet keep using blink on the blaze until it does

If the behavior is reproduced correctly, rather than teleporting behind the blaze, nothing will happen and the world will freeze. You can still move around the world but nothing will open/work and mobs stop moving entirely even if you try to punch them. Attempting to log out in single player will cause you to get stuck in the saving screen and you will have to kill the process with task manager to close Minecraft. Servers this is reproduced on will stop responding, causing players to disconnect. Despite that, the player count will not change in the servers tab and it will appear as online. The server will have to be forced to shut down by the host.

 - Mod Version: [e.g. 3.0.0.22]
 - Forge Version [47.3.0]

No other mods are required to recreate this bug. I tested it myself with only MNA and its dependencies.
This bug was initially discovered in a server but later tested in single player and I have confirmed it happens in both.
Reopening a world that previously froze and attempting to reproduce the behavior may not work initially but from my testing it will eventually freeze again.

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
