### ISSUE TITLE
Arcane Ritual won't complete

### ISSUE THREAD

**Issue by craft90** [Mithion/Mana-And-Artifice#92]
To start of, I'm running the FTB DireWolf20 1.16 modpack.

I tried to make a spell. The recipe was made without any issue. It's just a simple touch > light spell. I then gathered the materials, made the chalk circle, activated it and then it asked for the spell recipe. I placed it down and the regents turned up. So far so good. But even though I've placed all reagents the ritual won't fire. Nothing happens. The items just sits there. I don't know what I'm doing wrong. I'm just a tier 1 wizard... is it too difficult or something? But the Occulus wants me to cast a spell...

**Comment by Mithion** [comment]
Hey there -

Did you reactivate the center with purified vinteum dust after placing the reagents?  You need to do that twice, once to show the reagents and once to start the ritual.

Doing that tells the ritual to check again (much less laggy than checking all the time).  

Additionally, any reagent that is found no longer hovers, highlighting any that you're missing.

Try that and let me know!

**Comment by craft90** [comment]
I tried it and it worked this time... I guess I missed that part in the instructions.
