### ISSUE TITLE
ITieredItem Issue

### ISSUE THREAD

**Issue by incorruptable** [Mithion/Mana-And-Artifice#920]
**Describe the bug**
While moving cursor over a Metal Ritual Rune in chest, causes game to crash. Magic Level does not seem to have any bearing on the item, but the crash occurs regardless. Other mods included do not seem to have a direct cause beyond trying to access information for the production of the tooltip that appears when scrolling over the item in a chest.

**To Reproduce**
1. Metal Rune: Ritual
2. Have in chest
3. Move mouse over chest with any form of mod (used was FancyMenu and storage was Sophisticated Core) that tries to access information for tooltips to show the item information
4. Game Crashes.

**Expected behavior**
Expected the tooltip to pop up.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: mna-forge-1.20.1-3.0.0.22-all.jar
 - Forge Version: Forge-47.2.20

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

Pastebin of Crash Report: https://pastebin.com/WXuutSAu

**Comment by Mithion** [comment]
This has been resolved in 3.0.0.24
