### ISSUE TITLE
Eldrin Altar Not Drawing From Greater Conduits

### ISSUE THREAD

**Issue by nwrolson** [Mithion/Mana-And-Artifice#922]
In the latest release of MnA, the Eldrin Altar does not seem to be able to draw power from greater conduits nearby, no matter the placement.

![image](https://github.com/user-attachments/assets/5f13c9d8-1c4f-4f2e-a4b7-4bb27ddd8e44)

When right clicking the altar it successfully initiates the crafting process, but does not find any nearby conduits, giving the error
"Couldn't find Greater Eldrin Conduits with the right affinity close enough to the altar"

This seems to occur for at least any greater mote recipes I tried, but may occur with any recipe.
Mod version is the latest release, 3.0.0.24

**Comment by wuzzard** [comment]
Hey Mithion,

Do you have any thoughts on when this fix will be released (presumably 3.0.0.25)?

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
