### ISSUE TITLE
Pylon: Repair does not give tier progress for T4 when crafted

### ISSUE THREAD

**Issue by CFlatFlat** [Mithion/Mana-And-Artifice#923]
Crafting the Pylon: Repair item does not give any tier progress at all, despite crafting a T4 pylon being one of the tasks to get to T5.
 
1. Be Tier 4
2. Set up an Eldrin Altar
3. Craft a Pylon: Repair
4. Look in the Occulus and see that the task is still red

The task should light up as green since it is indeed a Tier 4 pylon.

 - Mod Version: 3.0.0.22 (0.24 causes my game to crash on startup)
 - Forge Version 47.3.0

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
