### ISSUE TITLE
New Runic Lights not accepted in Faerie Court Sanctum

### ISSUE THREAD

**Issue by StrixOcellata** [Mithion/Mana-And-Artifice#926]
**Describe the bug**
The build process for the Faerie Court Sanctum won't accept the new runic lights. The item count ticks up when they're placed, but their hologram (or whatever) still shows.

**To Reproduce**
1. Perform Sanctum Invocation after joining Faerie Courts
2. Begin build process and correctly place all items for first layer
3. Runic lights show as incorrect or still needed despite proper placement

**Expected behavior**
Build process should continue to second layer as usual.

**Screenshots**
![2024-08-28_23 31 09](https://github.com/user-attachments/assets/b9da2b46-1e37-447c-80b6-ee774b7ca1b6)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.24
 - Latest Neoforge 1.20.1 version

**Additional context**
Double checked with only MnA active from my modpack. Have not tried the build on regular Forge. Dropping back to 3.0.0.22 allowed me to build the sanctum with the old lights, and it stayed completed (still gives the buff) after returning to 3.0.0.24.

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
