### ISSUE TITLE
Add a Boolean parameter to Is Area Empty to evaluate true if *any* space is empty in the area

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#927]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use Is Area Empty to prevent farming constructs from constantly moving seeds from the hand to the dropoff chest when there's no plantable area.

**Describe the solution you'd like**
If the box is ticked true, the task evaluates to true if there's minecraft:air in any space in the designated region instead of the entire region needing to be minecraft:air

**Comment by Mithion** [comment]
No.  Such a scan task is largely inefficient for what it offers and can easily be programmed around by using the other conditions or changing the logic flow around.
