### ISSUE TITLE
Command: Place fluid in the world can't handle non-source fluid blocks (and maybe source too, didn't check)

### ISSUE THREAD

**Issue by jammer312** [Mithion/Mana-And-Artifice#928]
**Describe the bug**
Instead of replacing flowing water (and I assume other non-source and maybe even source blocks) with lava (probably also applies to other fluids) construct either tries to place fluid at the wrong location (if you marked a block from top side, it'll try to place fluid above it) or (if that location is occupied by something, including flowing water) complains that area isn't clear

**To Reproduce**
1. Mark a flowing water block with rune of marking
2. Tell a construct (via lodestar) to place a fluid there
3.  See it either place fluid in the wrong location or outright fail to do it

**Expected behavior**
Construct should properly replace fluid blocks, or at least not try to place fluids where you didn't tell it to place them

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.22
 - Forge Version 47.2.20

**Additional context**
Wellspring Adventures 2-1.29 modpack on a server

**Comment by jammer312** [comment]
![image](https://github.com/user-attachments/assets/4018756c-a4a4-4fd9-bdc6-14a73700cf22)
The wave should have reached the end of that red area but it never (you can see where a new one starts at the left and where the old one stopped at the right, these purple dots)  did unless I was casting it myself (from my book of rote with no enchantments)

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
