### ISSUE TITLE
The spell parameters of a caster arm cannot be adjusted after creation

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#929]
**Describe the bug**
CTRL+Clicking a caster arm with a spell does not bring up the spell modification GUI.

**To Reproduce**
1. Bind a spell to a construct caster arm
2. CTRL+Click

**Expected behavior**
The GUI opens for spell adjustment like any other casting medium

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.24

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
