### ISSUE TITLE
Request for Vinteum Ore rarity config option

### ISSUE THREAD

**Issue by xbony2** [Mithion/Mana-And-Artifice#93]
It spawns way too often imo. It would be useful to have a config to manage this.

**Comment by seebs** [comment]
I would endorse an option, because on a local game with three players, we've gotten way more than a stack of diamond ore so far, and a total of six vinteum ore. (1.2.0.2, in a modpack, but I don't see any relevant options?)

I think it is actually the rarest overworld ore in our game.

**Comment by xbony2** [comment]
Weird lol, I was seeing it everywhere 😅 good to be configurable anyway.

**Comment by seebs** [comment]
Ten minutes after I wrote that, a friend found a giant cave and over a stack of it, so yeah. (New theory: It's WAY more common at heights closer to 50, I was searching around 30-40.)

**Comment by xbony2** [comment]
Makes sense, 50 is too far from the ground to easily find it yet too far from the bottom to find it where people usually try to mine.

**Comment by Mithion** [comment]
I think vinteum is good where it is...and configs for worldgen are reportedly notoriously annoying.
