### ISSUE TITLE
Overwriting a spell on a caster arm does not change what construct actually casts with it

### ISSUE THREAD

**Issue by jammer312** [Mithion/Mana-And-Artifice#930]
You can change a spell on a caster arm and it will show the description of newly installed spell, but constructs you build using it will still use the first spell ever applied to it

**To Reproduce**
1. Make a caster arm, use transcription table to write a spell into it (spell A)
2. Build a construct with that arm, have it cast that spell
3. Dismantle that construct, take this arm and overwrite its spell with some other spell (spell B). Observe that its description changes (to match spell B), and using it casts spell B
4. Build a construct with that arm, have it cast a spell
4. See that it casts spell A and not spell B

**Expected behavior**
Overwriting a spell on a caster arm should result in constructs built using it casting the newly written spell

**Version Information (please complete the following information):**
 -  Mod Version: 3.0.0.22
 -  Forge Version 47.2.20

**Additional context**
Wellspring Adventures 2-1.29 modpack on a server

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
