### ISSUE TITLE
Constructs grab the wrong item when a single item filter is set

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#937]
**Describe the bug**
When a single item filter is set, the construct will always grab the first item in the container instead of the filtered item. Item filtering using a Ledger works as expected.

**To Reproduce**
1. Set up a lodestar task to take an object from from a container
2. Set a Take Item from Container task with a single item filter
3. Put the filtered item in the second slot of the container and any other item in the first slot
4. Observe

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.24

**Comment by Veylyn** [comment]
I am still having this issue in 3.1.0.1
