### ISSUE TITLE
Crystal of memories refuses to take xp past some point

### ISSUE THREAD

**Issue by jammer312** [Mithion/Mana-And-Artifice#939]
**Describe the bug**
At certain amounts of held (by player) experience crystals of memories just refuse to take any more

**To Reproduce**
1. Get to level 384
2. Use crystal of memories to drain xp
3. It'll stop at certain point at level 383 (and any other crystal will stop draining xp at the same point; if you return some xp, you can drain it again, but not past that point) (I did not check but that might be more points at which crystals stop working)

**Screenshots**
The point at which I experienced that issue:
![image](https://github.com/user-attachments/assets/bab4a2e7-2ef3-4943-b967-0d94f6108750)
**Version Information (please complete the following information):**
 -  Mod Version: 3.0.0.22
 -  Forge Version 47.2.20

**Additional context**
Wellspring Adventures 2-1.29 modpack on a server

**Comment by jammer312** [comment]
Not sure but it might not be related to actual total xp, but caused by something else entirely.
Used an enchanting table to spend 1 level, still couldn't use crystals to drain any xp, but I could go to level 384 and then back to the same point at level 382 (without getting stuck at level 383 as in original screenshot)
![image](https://github.com/user-attachments/assets/d63ed800-eb99-4960-a8d3-107b75090776)

**Comment by jammer312** [comment]
I think the reason might be that my levels didn't match the experience I collected (I used books from grimoire of gaia to raise my level). But still, all the non-MnA stuff worked correctly with it.
After I drained my level using sophisticated backpacks (experience pump upgrade) and then returned it to me the crystals started working again

**Comment by Mithion** [comment]
XP is not levels.  MC does it weird.  Crystal of Memories uses XP and doesn't care about levels.
