### ISSUE TITLE
Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [Mithion/Mana-And-Artifice#94]
Would it be possible to add waterlogging for all the non-full blocks, such as crystals? It could make for good decorations and prevent them from being used as air pockets underwater.

**Comment by Mithion** [comment]
The following blocks can now be waterlogged: Runescribing Table, Runic Anvil, Chimerite Crystal, Manaweave Projector, Manaweaving Altar, Brazier, and Pedestal
