### ISSUE TITLE
Frogs Cannot be Summoned

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#941]
**Describe the bug**
Frogs Cannot be Summoned

**To Reproduce**
1. Fill a Phylactery with frog souls'
2. cast summon
3. check screenshot for actual error

**Expected behavior**
a Frog is summoned

 **Screenshots**
![2024-09-07_03 16 52](https://github.com/user-attachments/assets/938ae898-86f7-4948-bf13-ada21fa77000)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.22
 - Forge Version 47.2.20

**Additional context**
`[Server thread/ERROR] [co.mn.ManaAndArtifice/]: java.lang.IllegalArgumentException: Unsupported mob type for FollowOwnerGoal`

-Thanks to Aranai for this last bit of info.

**Comment by Mithion** [comment]
¯\_(ツ)_/¯

Oh well.  Guess frogs aren't summons then.  Added them to the default configs of summon blacklists.
