### ISSUE TITLE
Found Wand/Staff/Bangle Key bind No Charge Loss

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#943]
**Describe the bug**
When you Place a Found Wand/Staff/Bangle into a Spell / Belt / Back slot in the curios menu and cast the spell it does not consume charge.

**To Reproduce**
1. Find a Wand / Bangle / Staff from a loot chest in a structure
2. place the Wand / Bangle / Staff into a Spell / Belt / Back slot
3. Cast the spell with a Key bind
4. Spell does NOT consume Charge

**Expected behavior**
The Wand / Staff / Bangle to Consume a Charge

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 3.0.0.22
 - Forge Version [e.g. 47.2.20

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
