### ISSUE TITLE
Key bind spells bypass claims

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#944]
**Describe the bug**
On the Wellspring Adventures pack, claims prevent other players from casting spells, however if you have the spell in a Spell / Belt / Back slot you are able to cast the spell and it will have its full effect on all spells EXCEPT the Break spell claims still block that particular part.

**To Reproduce**
1. be in a modpack with " Open parties and claims " mod
2. Craft a spell on a Bangle / Wand / Staff
3. Cast the spell from a Spell / Belt / Back slot with a keybind while in another players Claim

**Expected behavior**
be unable to cast the spell

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.22
 - Forge Version 47.2.20

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
