### ISSUE TITLE
Ritual of Forgotten Lore: Metal Rune - Practitoiners Pouch problem

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#946]
**Describe the bug**
When Setting up the Ritual of Forgotten Lore with metal runes and with 10 book shelves around the ritual, The practitioners pouch will store the ritual. After the ritual is stored you can complete the set up ritual as usual to obtain a mote of magic.  When you attempt to use the stored ritual on the same site with the metal runes surrounded by book shelves, it will claim that "You require more blocks that improve enchanting power surrounding this ritual. Check the codex"

**To Reproduce**
1. Create a Ritual of Forgotten Lore with metal runes and 10 book shelves around the ritual
2. Use the practitioners pouch on the center of the ritual and see that it has been stored in the quick wheel of the pouch
3. Use purified vinteum dust on the center of the ritual to complete it and obtain a mote of magic as a result
4. Use the stored ritual in the practitioners pouch to attempt to do the ritual again
5. See error pop up on screen even though the ritual completed successfully the first time.

**Expected behavior**
The stored ritual in the practitioners pouch should recognize that the metal runes are surrounded by the appropriate number of blocks that improve enchanting power

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.24]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
