### ISSUE TITLE
Shear doesn't harvest Glow Lichen when used with the Projectile Shape 

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#949]
**Describe the bug**
Shear doesn't harvest Glow Lichen when used with the Projectile shape.

**To Reproduce**
1. Create a spell in the book of rote that has the Shear effect and the Projectile shape
2. Use on Glow Lichen
3. See lichen fail to be harvested

**Expected behavior**
Glow Lichen should be affected by the shear spell when it is used with the Projectile shape like it works with the Touch shape.

**Player Information**
Player Level - 45
Player Tier - 3
Player Faction - Council of Wizards

**Version Information (please complete the following information):**
 - Mod Version: [3.0.0.24]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
Projectile doesn't target non-solid blocks; this is so it will go through tall grass.  Use a different shape.
