### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by WenXin20** [Mithion/Mana-And-Artifice#95]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Mana & Artifice v1.2.0.1`

The flowers are missing the block and item tag `minecraft:small_flowers`, which would allow the flowers to be pollinated by bees and used in recipes. The ingots could also use the forge tag `forge:ingots` and/or `forge:ingots/type`.

**Comment by Mithion** [comment]
small flowers, dusts, and ingot tags have been added.
