### ISSUE TITLE
Ability to reasign Runes of Marking while they are still in the Book of Marks

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#950]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to take a rune of marking out of the Book of Marks in order to assign it to a new position and then put it back in.

**Describe the solution you'd like**
I would love it if when the Book of Marks is in the off hand or main hand, when you are ducking and right clicking on a block, it will reassign the currently selected Rune of Marking in the book to the block that was just right clicked on. This would make it easy and intuitive to place way-points while I am exploring or see that I may be getting into a dangerous situation where i may die and need to Recall to the aria of danger.

**Describe alternatives you've considered**
One slot in the book of marks could be a dedicated quick slot that reassigns the mark it contains when a specified hot key is pressed. This quick slot could even require that the book of marks be upgraded in order to access it.

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
