### ISSUE TITLE
Ability to name Runes of Marking

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#951]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have multiple Runes of Marking that point to the same type of object like chests and I need to be able to tell what I intended for these to be used for. The ability to dye the Runes of marking is nice but the colors barely come through and colors are not descriptive of function.

**Describe the solution you'd like**
I would be very happy if I could name my assigned Runes of Marking so that I can tell what they are for.

**Describe alternatives you've considered**
If entering text is out of the question then perhaps an Icon could be created in the Runescribing Table where you could craft a custom mark to put on the Rune of Marking and this would show up in the lower right hand corner of the icon in place of the block picture.

Or 

you could put an item into it like you put an item into a filter and the item's icon would show up in the lower right hand corner instead of the block it is marking.

Or

The block it is marking could remain in the lower right hand corner and the Item Icon could occupy the lower left hand corner.

I do not know what the easiest way to implement this would be. Perhaps with an interface that could be opened like the book of rote's interface for editing spells is opened. Where you could drop an item from you inventory into a box (like the single item filter in some loadstar commands) and It's icon would show up on the Rune of marking's Icon.

**Comment by Mithion** [comment]
Excellent, closing as resolved.
