### ISSUE TITLE
Error when placing a crystalized cage of a wadering wizard into a scroll shelf

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#953]
**Describe the bug**
I bought a couple items from a wandering wizard, crystalized it (to see if i could) then went to put it away on a scroll shelf (the shelf was empty i did this to test and make sure it was repeatable)
**To Reproduce**
1. summon a wandering wizard
2. buy a couple items ( i purchased the links for swamp and swamp hut don't know if that is relevant)
3. crystalize the Wandering wizard
4. try to put the crystalized wandering wizard on the scroll shelf

**Expected behavior**
the crystalized wandering wizard would go onto the scroll shelf

**Screenshots**
![Error](https://github.com/user-attachments/assets/371a5489-ace0-4ad2-87b0-3b583306bdff)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.22
 - Forge Version 47.2.20

**Additional context**
might be a good idea to make it so the wandering wizard is just unable to be put in a crystalized cage

**Comment by Mithion** [comment]
Yeah I plan to make it so the WW can't be crystallized, for this and other reasons.
A mod that expands the maximum packet size would probably also alleviate this issue.

**Comment by Mithion** [comment]
Resolved in 3.1.0.0
