### ISSUE TITLE
Crash with a construct using Self - Blood Sacrifice

### ISSUE THREAD

**Issue by MageOfGaming** [Mithion/Mana-And-Artifice#955]
**Describe the bug**
Trying to make a construct use Blood Sacrifice crashes the game

**To Reproduce**
1. Flash a Self - Blood Sacrifice spell onto a caster arm
2. Make a construct with said Caster arm
3. Make Lodestar script with Cast spell at Target and give it a position (The range doesn't matters only that it works)
4. Use the bell of bidding to make the construct execute the program
5. Crash

**Expected behavior**
After the construct tried executing the lodestar program while using the Blood sacrifice Caster's arm it should crash with the Log linked below

**Version Information**
 - Mod Version: [mna-forge-1.20.1-3.0.1.0-all.jar]
 - Forge Version [47.4.0 (Recommended)]

**Crash-report**
https://pastebin.com/U3cV0GxB

**Comment by Mithion** [comment]
Resolved in 3.1.0.1
