### ISSUE TITLE
Hitting your own Simulacrum clones with Explosion crashes the server

### ISSUE THREAD

**Issue by MageOfGaming** [Mithion/Mana-And-Artifice#956]
**Describe the bug**
title

**To Reproduce**
1. Summon 2 Simulacrum Clones
2. Make a Bolt -  Explosion Spell
3. Cast the spell in very close proximity to yourself and the Clones
4. Hit the clones
5. Crash

**Expected behavior**
After Hitting the clones with Explosion the server should crash

**Version Information:**
 - Mod Version: [mna-forge-1.20.1-3.0.1.0-all.jar]
 - Forge Version [47.4.0 (Recommended)]

**Crash-Report**
https://pastebin.com/in4EG0vF

**Comment by Mithion** [comment]
Resolved in 3.1.0.1
