### ISSUE TITLE
Wellspring pillars disappear when looking in specific direction Re-Opened Due to New Info From Embeddium

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#957]
I am reposing this issue because I know you don't look back over Issues that have been closed but I think it is important because new information has been acquired. 

[no-name-provided](https://github.com/no-name-provided) passed the issue on to the Embeddium team and this was their response:

https://github.com/Mithion/Mana-And-Artifice/issues/879#issuecomment-2340701578

So it seems that this is actually an issue with the model and can be fixed on M&A's side

**Comment by Sarithule** [comment]
It also has some nice info on best practices for model dimensions as well :)

**Comment by Mithion** [comment]
While I don't intend to change the model dimensions (as it works in vanilla and that is the standard to which I develop the mod, not third party addons even though they may indeed be more correct), I did override the shouldrenderoffscreen method which should at least help to mitigate the issue.

The model change would require a much larger refactor of multiblock/fillter block models in general, which I don't plan to do in the near future, if ever.

**Comment by Mithion** [comment]
Resolved in 3.1.0.1
