### ISSUE TITLE
Spell particle effects render at wrong position (obstructing player view) when looking directly up or down

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#958]
**Describe the bug**
In first person view
When looking directly up, the spell particle generator will jump from the hand to directly above the player, blocking their view.
When looking directly down, the spell particle generator will jump from the hand to directly below the player, blocking their view.

**To Reproduce**
1. Enter 1st person view
2. Equip a spell that creates a spell effect in the hand of the caster
3. look all the way up
4. See the spell jump from the hand to the middle of your view
5. look all the way down
6. See the spell effect jump from you hand to the middle of your view

**Expected behavior**
The spell effect should stay in the casters hand no mater where they are looking.

**Possible Cause**
Gimbal Lock.

Here is a video on the issue of Euler rotation with gimbal lock
https://www.youtube.com/watch?v=zc8b2Jo7mno

Here is a video on Quaternions (which solve gimbal lock) and how they can be used 
https://www.youtube.com/watch?v=1yoFjjJRnLY

You know, If you don't already know all this jazz.

**Possible Solutions**
If Euler angles are hard-coded into the game and Quaternions can't be used then perhaps creating a special cases for the angles in question could solve this issue. 
Given that it is a small set of angles it could be possible to assign an alternate position calculation for the location of the particle effects for these specific cases.
If it is impossible to get the particle effects to follow the hand when looking directly up or down then having them turn off at these angles would be better then having them obstruct the players view.
A VERY simple solution would be to restrict the character up/down view rotation very slightly so that the rotation can never reach the exact angles of completely up or completely down, if that is possible. if the restriction is small enough it wouldn't even be noticeable.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.1.0]
 - Forge Version [47.3.0]

**Comment by Sarithule** [comment]
It appear that the origin of the hand particle generator also deviates from the hand when the angle of looking up or down gets extreme as well.

looking directly up the spell effect jumps to the middle of the screen.
![2024-09-13_13 29 41](https://github.com/user-attachments/assets/87d64fac-bad2-40ae-8492-ad821f0cf636)

looking directly down the spell effect jumps to the middle of the screen.
![2024-09-13_13 30 31](https://github.com/user-attachments/assets/ea4a93cb-354e-447b-ae39-320aa0ba701a)

when rotating upwards the spell effect begins to deviate away from the hand up and to the right of the screen.
![2024-09-13_13 30 22](https://github.com/user-attachments/assets/aaf6c0d9-191c-4a1c-bbb2-ac942b27cd21)

when rotating downwards the spell effect begins to deviate from the hand directly above it.
![2024-09-13_13 30 40](https://github.com/user-attachments/assets/21c1463f-c34b-451f-9f28-a20813145b93)

When looking straight ahead the spell effect appears to be where it was intended to be.
![2024-09-13_13 30 44](https://github.com/user-attachments/assets/b46d96c3-bb37-4921-8a18-769e5ca1d89b)

**Comment by Sarithule** [comment]
Here is a website that describes how to convert Euler angles into Quaternions.
https://www.euclideanspace.com/maths/geometry/rotations/conversions/eulerToQuaternion/index.htm

Hopefully this can be helpful!

**Comment by Mithion** [comment]
It wasn't gimbal lock, I'm unfortunately intimately familiar with that issue.
I did finally put the time in to fix this though.

**Comment by Mithion** [comment]
Resolved in 3.1.0.1
