### ISSUE TITLE
(Chain spell shape) various animation issues

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#959]
**Describe the bug**
1. When casting a chain spell there is a strange horizontal artifact that does not look like it belongs as part of the effect.
2. When casting a chain spell The lightning effect does not originate from the casters hand, it originates from a random position around the casters screen.
3. When casting a chain spell on creature, the lightning animation does not play.

**To Reproduce**
Steps to reproduce the behavior (Horizontal line, random origin of lightning) :
1. Be in 1st person view
2. Create a chain spell
3. Use on a block
4. see a horizontal line of varying width appear across the screen, see lightning originating from random positions around the screen of the player.

**Screenshots**
![2024-09-13_12 32 49](https://github.com/user-attachments/assets/e0d3f6dd-436b-47bc-bb6a-e967bfa4fbf6)
![2024-09-13_12 32 50](https://github.com/user-attachments/assets/1fa185ee-70d6-4bd8-9488-a210629ec584)
![2024-09-13_12 27 28](https://github.com/user-attachments/assets/52334beb-1cba-493a-9558-47e0eedd2f3a)

Steps to reproduce the behavior (no lightning animation)
1. Be in 1st or 3ed person view
2. Create a chain spell
3. Use on a creature
4. see the creature be affected by the spell but there is no lightning animation.

**Screenshots**
![2024-09-13_12 52 48](https://github.com/user-attachments/assets/ee03bb53-69da-4ad8-9fd8-f32c98fc4050)
![2024-09-13_12 52 51](https://github.com/user-attachments/assets/69b60b7e-c6a1-4341-935e-b6ff42537161)

**Expected behavior**
A bolt of lightning like effect should appear from the casters hand without an extra line across the screen when hitting a block as well as when hitting a creature.

**Version Information (please complete the following information):**
 - Mod Version: [3.0.1.0]
 - Forge Version [47.3.0]

**Comment by Mithion** [comment]
I'm not seeing the issue with the artifact.
I did better approximate the bolt's origin and improve it chaining between entities:
![2024-09-14_10 14 31](https://github.com/user-attachments/assets/a317cce3-6c64-434f-b394-afd32c38ee75)

Due to the fractal nature of the bolt it won't always perfectly emit from the player's hand, but it's good enough.

**Comment by Mithion** [comment]
(artifact isn't happening with blocks, either)
![2024-09-14_10 17 23](https://github.com/user-attachments/assets/4cd72219-86e8-4a65-a7a0-90fb0fcbf15b)

**Comment by Mithion** [comment]
Resolved in 3.1.0.1
