### ISSUE TITLE
Ticking Entity upon death

### ISSUE THREAD

**Issue by MLMII** [Mithion/Mana-And-Artifice#96]
After updating to 1.2.0.3 the game crashes upon character death; whether that is from a mob or using the /kill command.   Reverting to 1.2.0.2 prevents this issue.  If it matters, I was not a mage yet.

Thank you for your time.

[crash-2020-12-21_21.23.40-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/5727786/crash-2020-12-21_21.23.40-client.txt)

**Comment by Mithion** [comment]
This has been resolved in 1.2.0.4.
Sorry about that!

https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/3146123
