### ISSUE TITLE
Ice Affinity Fissure Spells use Water Particles

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#961]
**Describe the bug**
When an Ice-affinity spell with a Fissure shape is used, water bubble particles follow the ground instead of ice vapor. The particle poof at the end uses the correct particles (though Ice Spike will block them and they won't spread nicely).

**Screenshots**
![image](https://github.com/user-attachments/assets/e7227b2d-8c27-4530-ba3e-18331b904b6f)
![image](https://github.com/user-attachments/assets/a030ce46-7653-4e66-8946-de76deba5294)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.0

**Comment by Mithion** [comment]
Resolved in 3.1.0.1
