### ISSUE TITLE
Crushing Byproducts don't take Ender affinity into account

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#963]
**Describe the bug**
When a construct does a Crushing recipe that has byproducts, only one set of byproducts are generated regardless of the stack size of the input item.

**To Reproduce**
1. Install MagiChem or make a temporary Crushing recipe with a byproduct
2. Have the construct grab a stack of Ruined Projection Apparati (or whatever temporary recipe item you made) and crush it
3. Observe the output items

**Expected behavior**
The construct generates one set of byproducts for each input item in the stack

**Screenshots**
![image](https://github.com/user-attachments/assets/6ac2d802-6a91-4318-a17f-5f7bc4a8ff6b)
(The outputs here should be 6 / 6 / 6 / 12)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.0

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
