### ISSUE TITLE
can't store ritual in practioners pouch 

### ISSUE THREAD

**Issue by Sarithule** [Mithion/Mana-And-Artifice#964]
**Describe the bug**
When the ritual is laid out with metal runes, and has been activated with purified vintium dust to display the needed reagents, once all the reagents have been placed and you attempt to store the ritual in the practitioners pouch, it is Not stored in the practitioners pouch and there is no text that pops up.
If you do not activate the ritual with purified vintium dust and lay out the needed reagents without the guide that activating it provides, then trying to store the ritual in a practitioners pouch will be successful.

**To Reproduce**
1. place a ritual using metal runes
2. activate the ritual with purified vintium dust
3. Place the reagents according to the floating markers
4. attempt to store the ritual in a practitioners pouch
5. See nothing happen and the ritual not be stored in the practitioners pouch

**Expected behavior**
the Practitioners pouch should be able to store a ritual when it has been activated to provide the reagents guide (once all the reagents have been placed)

**Version Information (please complete the following information):**
 - Mod Version: [3.1.0.1]
 - Forge Version [47.3.0]

**Comment by neoshock1463** [comment]
### Work Around
**Good news!**

For anyone who needs to store the ritual, start by placing all the individual runes and activate the ritual enough to place the reagents. Then break a piece of the ritual and replace the broken piece. In effect, you'll have the entire ritual ready to start when you use the purified vinteum. Now save the ritual and it works without a hitch!

**For clarification in step wise order:**
1. Place runes
2. With purified vinteum in hand, interact with center
3. Place reagents as directed by ritual
4. Break a rune which does not have a reagent
5. Replace rune
6. Save the ritual

I hope this helps, this hasn't been tried with the M bag, with chalk runes, or with variable (wildcard) reagents.

**Comment by Mithion** [comment]
As a minor update, you also don't need to break a rune, you can shift + rclick with Purified Vinteum Dust on the center rune to deactivate the ritual, then save it.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
