### ISSUE TITLE
Curse of Agony Bug & Crash

### ISSUE THREAD

**Issue by Food-dude-99** [Mithion/Mana-And-Artifice#965]
**Describe the bug**
Casting the spell component "Curse of Agony" using any shape does not give mobs or players the effect. However it does consume the reagent in hot bar or of hand. Also server error occurs and an eventual crash is caused by the error.
**To Reproduce**
1. Get Curse of Agony with any shape and Chorus Fruit in hot bar or off hand
2. Use on any mob, yourself, or other player while on a server (haven't tested in single player)

**Expected behavior**
The mob, yourself, or other player receives the Curse of Agony effect.

**Screenshots**
![bug](https://github.com/user-attachments/assets/11d5f86f-98a0-4fd4-9fd2-8cc0085d8f44)

**Version Information (please complete the following information):**
 - Mod Version: [3.1.0.1]
 - Forge Version [47.3.0]

**Additional context**
https://mclo.gs/wFwMsYL - Crash Report

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
