### ISSUE TITLE
Tinkered Spells not actually reducing cost

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#966]
**Describe the bug**
when I Tinker a spell to lower its cost to my main affinity, and hold the spell, the mana cost that it shows its going to spend on my mana bar is not the value of mana that is actually consumed by casting the spell.

**To Reproduce**
1. Get a spell
2. Use the Affinity Tinkerer table to change its affinity to your main (100%) affinity
3. hold the spell in your hand to see how much it should cost to cast that spell
4. cast the spell and have it cost way more

**Expected behavior**
to have the tinkered spell cost as much as is shown in the tool tip and what it shows it is going to cost on the mana bar

**Screenshots**
![before](https://github.com/user-attachments/assets/4ab1c1b2-5fe9-4576-9d43-1a6c3535140a)
![after](https://github.com/user-attachments/assets/435d79b8-d477-4062-bef6-e61cb1c0d334)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.2.20

**Additional context**
I have only tested this with tinkering to arcane affinity as its my main affinity, but it does this for all my spells.

**Comment by TheDraeval** [comment]
this problem seems to persist with wands, staves, and bangles that are enchanted with Efficiency as well.

**Comment by AranaiRa** [comment]
Adding on to this, once you save and quit the world and log back in the tinkered spell's active particles and sound effects revert to their base affinity. Hand particles remain in the tinkered state, and casting the spell progressed the tinkered affinity as expected.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
