### ISSUE TITLE
rote blood golem bar not present

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#967]
**Describe the bug**
after getting blood golem rote there is no bar for it in the oculus

**To Reproduce**
1. use torn pages to rote the spell Blood Golem
2. open Oculus

**Expected behavior**
for there to be a bar under the Blood Golem spell showing it is rote

**Screenshots**
![2024-09-17_12 26 12](https://github.com/user-attachments/assets/25694de1-d238-4498-a2cd-76eda3628df1)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.2.20

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
