### ISSUE TITLE
Armor possibly causing crash on server

### ISSUE THREAD

**Issue by GoldenMaster8** [Mithion/Mana-And-Artifice#969]
When a player is damaged while wearing mage armor (could possibly be any M&A armor) the server crashes (Other mods present)

1. Get any m&a armor
2. have another player or non m&a mob to hit you
3. Server crashes

Expected behavior: not to crash

 - Mod Version: 3.1.0.1
 - Forge Version : Neoforge: 47.1.106

[crash-2024-09-18_03.41.07-server.txt](https://github.com/user-attachments/files/17038084/crash-2024-09-18_03.41.07-server.txt)

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
