### ISSUE TITLE
MnA/HMaG/Apotheosis ... no idea who's fault!

### ISSUE THREAD

**Issue by Slickson77** [Mithion/Mana-And-Artifice#970]
**Describe the bug**

This is on the WA2 public server.

Server crashing due to null entity thing with Camo attribute and HMaG and Apotheosis.  No idea who can fix.  For now, setting the ForgeServer to remove errored entities works fine.

**To Reproduce**
I don't know, Draeval was just out exploring and it happened.

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.2.20

**Additional context**
[https://pastebin.com/2eQcssgP](https://pastebin.com/2eQcssgP)

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
