### ISSUE TITLE
Shift Clicking voids items in Practitioner's Pouch while inventory is full

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#972]
**Describe the bug**
If your inventory is full, shift clicking an item in a Practitioner's Pouch voids it.

**To Reproduce**
1. Put an item in a Practitioner's Pouch.
2. Fill every slot of your inventory.
3. Open the GUI and shift-click the item inside the pouch. Observe that it vanishes.

**Expected behavior**
The item is not moved.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
