### ISSUE TITLE
Null Pointer error caused by the Camouflage effect

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#973]
**Describe the bug**
The Camouflage effect caused a persistent world-crashing bug until the Forge remove erroring entities config was enabled.

**To Reproduce**
Steps to reproduce the issue are unknown.

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1

**Additional context**
May have been caused by an Embers-Camouflage loot wand going off.
[crash-2024-09-20_19.54.08-server.txt](https://github.com/user-attachments/files/17083285/crash-2024-09-20_19.54.08-server.txt)
[2024-09-20-2.log.gz](https://github.com/user-attachments/files/17083287/2024-09-20-2.log.gz)

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
