### ISSUE TITLE
Ascended Range > Emination

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#974]
**Describe the bug**
Ascended Range foes not appear to effect emanation spells

**To Reproduce**
1. get a wand/ staff/ bangle
2. enchant it with ascended range
3. put an emanation spell on the wand/staff/bangle
4. cast the spell

**Expected behavior**
increase the width and height of the emanation spell by a factor of what the ascended range enchantment equaled to

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.2.20

**Comment by Mithion** [comment]
Width and Height are different attributes than Range, the Range modifier simply enables multiple values.  This is working as intended.
