### ISSUE TITLE
Rune of Marking zones extend one block outside the designated area

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#975]
**Describe the bug**
When you set two runes of marking in a Construct task (either by a Rune of Marking pair or by two singles) the area of effect seems to extend one block beyond the designated area.

**To Reproduce**
1. Create a sugar cane farm.
2. Mark the middle block.
3. Watch a construct harvest the entire sugar cane.
4. Modify the designated area to only affect the top block.
5. Watch the construct harvest the middle and top blocks of the sugar cane.

**Expected behavior**
Constructs only interact with the explicit designated area.

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
