### ISSUE TITLE
Projector patterns do not appear on manaweave altar when activated by a construct.

### ISSUE THREAD

**Issue by NerdimusPrime** [Mithion/Mana-And-Artifice#976]
**Describe the bug**
 When I activate a manaweave projector it consumes its stored mana and the programmed shape appears on a nearby manaweave altar. When a _construct_ activates the projector, it consumes its mana, but the shape does _not_ appear on the altar.

**To Reproduce**
1. Set up a manaweaving altar, a manaweave projector next to it, and add a pattern to the projector.
2. Use a rune of marking on the projector (any face).
3. In the delegation station/lodestar, add action Activate Block, and set the location with the rune of marking.
4. Tell construct to interact with the delegation station/lodestar.

**Expected behavior**
When the construct activates the projector, its programmed shape appears on the altar.

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.1.0.1
 - Forge Version 47.3.0

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
