### ISSUE TITLE
Diamond Fluid Nozzle not crafting

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#977]
**Describe the bug**
when i go to craft a Diamond Fluid Nozzle for my construct it does not craft and consumes the resources

**To Reproduce**
1. get the items to craft a diamond fluid nozzle
2. place them on the pedestals around the eldrin altar
3. activate the alar

**Expected behavior**
for it to craft a diamond fluid nozzle

**Screenshots**
![2024-09-25_01 36 19](https://github.com/user-attachments/assets/5c3c49b2-8d3c-4a38-be8d-6058d703d379)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 42.2.20

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
