### ISSUE TITLE
Tier 2 Task Fails to Show as Complete With Some Pylons

### ISSUE THREAD

**Issue by asnover** [Mithion/Mana-And-Artifice#978]
**Describe the bug**
The task "Craft any tier 2 pylon" does not show as complete after crafting a light or freeze pylon.

**To Reproduce**
1. Reach tier 2
2. Make a light or freeze pylon :)

**Expected behavior**
The task should show as complete

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.3.6

**Additional context**

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
