### ISSUE TITLE
Issue with Runescribing Table

### ISSUE THREAD

**Issue by NinFluffy** [Mithion/Mana-And-Artifice#98]
Hello,

I can't seem to be able to place Rune Patterns (the brown plates, the one you have to fire up in the Runeforge) inside the Runescribing Table. This is part of the Tier 2 Occulus requirements. This also means I can't craft mundane rings and all those things.

This is played on the Direwolf20 pack on FTB.

**Comment by Mithion** [comment]
You have to place a single blank plate into the slot, stacks won't work.

I've improved it in dev so that it will split them out for you, so look for that next version but thats the limitation for now.

**Comment by Mithion** [comment]
Fixed in 1.2.1.6
