### ISSUE TITLE
Mod Incompatability: Curio

### ISSUE THREAD

**Issue by Noromical** [Mithion/Mana-And-Artifice#981]
Channeled spell shapes such as Cone, do not work when the spellbook is slotted in a curio slot.

The Curio Mod adds extra slots, including a Spell slot, which, the Curio mod, does in fact register Spell Books, Grimoires, and Books of Rote as being valid slots, even allowing access to the quick select wheel while said book is slotted, all allowing you to cast spells via a separate hotkey.
However, from what I've tried, any spell that requires you to hold the button, rather than simply click to activate, will not trigger.

Since this is more a mod incompatibility than an actual bug, I was hoping to at least get it on the list of known incompatibilities.

**Comment by Mithion** [comment]
This is intentional.  Channelled spells will not cast in curio slots, same with bound.
I originally didn't send a message to try to limit chat spam, but I've added a message with this information for clarity as it seems to get confused often enough.
