### ISSUE TITLE
Construct going into negative mana

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#982]
**Describe the bug**
i have a construct that i use to "open the door" for me it casts touch(radius1)>transitionary tile and if its activated too often it will go into the negatives for its mana but continue to try to cast the spell

**To Reproduce**
1. craft a construct that can cast transitionary tile
2. have a seer stone that can see you so the construct knows when you are around
3. stand and let the construct continue to cast the spell over and over
4. watch the constructs mana go negitive

**Expected behavior**
for the mana to hit 0 and stop and for him to be unable to complete the task and for it to fail

**Screenshots**
![2024-09-29_21 15 52](https://github.com/user-attachments/assets/a192a3f6-1df0-4746-939a-5e0233b43091)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 47.2.20

**Additional context**
adding a whole bunch (12+) mana crystals allows it to regen fast enough to get around this issue

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
