### ISSUE TITLE
mana weavers wand not casting self buff spells with componants

### ISSUE THREAD

**Issue by TheDraeval** [Mithion/Mana-And-Artifice#983]
**Describe the bug**
trying to cast a self > buff spell that requires a component results in no spell being cast.

**To Reproduce**
1. craft a self > buff spell that requires a component as part of its casting
2. place that spell in a mana weavers wand 
3. draw the mana weaving patters to cast the spell
4. no spell is cast

**Expected behavior**
to have the spell cast, ideally consuming the component from the inventory or a practitioners pouch 

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version 42.2.20

**Additional context**
none of these spells can currently be cast by the mana weavers wand in this way
- Water walking (Wakebloom)
    - Night vision (Fermented Spider Eye)
    - Levitation (Tarma Root)
    - Grow (Desert Nova)
    - Shrink (Cerublossom)
    - Leap (Slime Ball)
    - Spider Climbing (Web)
    - Swift Swim (Cod)

**Comment by Mithion** [comment]
This is intentional, cantrips cannot cast spells with reagent requirements.
