### ISSUE TITLE
Curio Spells Can Be Cast In Spectator Mode

### ISSUE THREAD

**Issue by bryceio** [Mithion/Mana-And-Artifice#984]
**Describe the bug**
Spells equipped in curio slots can be cast while in spectator mode using the spell keybind.

**To Reproduce**
1. Equip spell in curio slot.
2. Switch to spectator mode.
3. Press spell keybind.

**Expected behavior**
Spectator mode players are supposed to be unable to interact with the world. Spells should not be able to be cast by a spectator.

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.0
 - Forge Version 47.3.0

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
