### ISSUE TITLE
Construct swimming in water-loged blocks

### ISSUE THREAD

**Issue by Eonwe98** [Mithion/Mana-And-Artifice#986]
**Describe the bug**
When i spawned a construct and when the construct walks over water logged upside-down stairs and top-slabs the construct swims in them.

**To Reproduce**
1. make construct
2. have construct follow you over water logged top-slabs and water logged upside-down stairs. It does not occur in my testing to not water logged slabs/stairs in the same orientation.
3. ...
4. See construct swimming in block.

**Expected behavior**
A construct to stand on and walk on the block not swim in them?

**Screenshots**
![image](https://github.com/user-attachments/assets/3fb34fa6-ca04-41ad-96ac-4bd187f914b7)

**Version Information (please complete the following information):**
 - Mod Version: [1.20.1-3.1.0.1]
 - Forge Version [47.3.10]

**Additional context**

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
