### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by PetrusSeer** [Mithion/Mana-And-Artifice#987]
**Describe the bug**
Server or single player game crash back to client when using Dragon Survival

**To Reproduce**
1. Play as a dragon while Mana and Artafice is installed

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 mna-forge-1.20.1-3.1.0.1-all.jar
Forge - 47.3.0
**Additional context**
the crash seems to happen randomly to others on our server but is caused by pose stack not being empty

**Comment by LKD-PIX** [comment]
the pose stack not empty is very likely related to sodium, i have seen this on my packs in the past

**Comment by Mithion** [comment]
Crash report not supplied, closing issue.  Feel free to post the actual crash report and re-open.
