### ISSUE TITLE
Constructs grab the incorrect item when single item filter is used

### ISSUE THREAD

**Issue by Veylyn** [Mithion/Mana-And-Artifice#988]
**Describe the bug**
When the single item filter is used in the lodestar, constructs will grab items from the top of the designated inventory, instead of the set item. This was reported as closed in #937 however I am still having this issue in 3.1.0.1

**To Reproduce**
1. Set up a lodestar task to take an object from from a container
2. Set a Take Item from Container task with a single item filter
3. Put the filtered item in the second slot of the container and any other item in the first slot

**Expected behavior**
Construct should take filtered item

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version: 47.2.20

**Comment by AranaiRa** [comment]
As per demonstration by Mori, it appearas that all single-item filters within the same program will use the FIRST single item filter that was set.

**Comment by Mithion** [comment]
[single_item_filter.txt](https://github.com/user-attachments/files/18268330/single_item_filter.txt)

Just tried this and it's working fine.  I set up a chain that is designed to take an oak log and then a cherry log from chest a -> chest b using single item filters.

Please provide more information if available.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
