### ISSUE TITLE
Use Item on Block construct command is not filling buckets from urns.

### ISSUE THREAD

**Issue by Veylyn** [Mithion/Mana-And-Artifice#989]
**Describe the bug**
While attempting to fill buckets from an urn of the molten core, I noticed my construct diagnostics saying the bucket is used on the urn, but the bucket wasn't filling. This may be connected to #915. I have not tested if other applications of the command work or not

**To Reproduce**
1. Place a lodestar, and urn of the molten core
2. Give a construct a bucket
3. Program the lodestar to Use Item on Block on the urn
4. Have the construct execute the lodestar program
5. See error

**Expected behavior**
Construct should fill the bucket with lava

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version: 47.2.20

**Comment by Mithion** [comment]
Buckets don't implement as "use on block", they implement "use" and then perform a raycast to attempt to hit a block.  Constructs using "use item on block" call the "use on block" method, which for buckets simply returns a result of PASS.  This is working as intended, and demonstrates one of the many inconsistencies with Mojang's approach to MC development.

Fluid constructs with tanks and nozzles are designed for this purpose; they can interact specifically with fluids in several ways.
