### ISSUE TITLE
Mod Conflict (visuals only), Total Darkness.

### ISSUE THREAD

**Issue by Wilevar** [Mithion/Mana-And-Artifice#99]
With Total Darkness installed, as the ambient light level drops spell particles become less and less visible, until being completely invisible at night/in the Nether. Likely the same in the End, but haven't gotten there to test. ^_^;

**Comment by Mithion** [comment]
Particles are diffuse rendered, meaning they're affected by local light - since light emission alongside visual effects is not reasonably possible in MC, it makes the particles look weird to have them so bright when it's dark yet not emit light.
