### ISSUE TITLE
Shaped/Shapeless Recipes in the Codex do not display an output number

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#991]
**Describe the bug**
Recipes that use the `crafting` type in the Codex do not display the number of items created if the result is higher than one.

**To Reproduce**
1. Create a recipe that results in more than one item
2. Check the recipe in the Codex

**Expected behavior**
The output item shows the number crafted in the corner.

**Screenshots**
![image](https://github.com/user-attachments/assets/aebd9eea-10f5-45f0-8dca-1e49bfd66f98)
The recipe in JEI

![image](https://github.com/user-attachments/assets/c5ed39e6-d983-483d-bcd4-023b8ad42875)
The recipe in the Codex

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
