### ISSUE TITLE
Crash when striking zombies whilst under greater invisibility

### ISSUE THREAD

**Issue by Oggas** [Mithion/Mana-And-Artifice#992]
**Describe the bug**
When under greater invisibility under the sky and punch a zombie or husk the game crashes.

**To Reproduce**
1. Turn it to night.
2. Activate greater invisibility on self.
3. Find zombie.
4. Punch zombie.
5. Crash.

**Expected behavior**
I would expect the zombie to aggro on me perhaps but not for the game to crash. This doesnt seem to be an issue with skeletons or endermen for instancce.

**Version Information (please complete the following information):**
 - Mana and Artifice 3.1.0.1
 - Forge Version 47.3.0
 - GeckoLib 4.4.9
 - Curios API 5.10.0
 - Jei 15.12.2.51
 - MagiChem 0.4.5 pre1

**Additional context**
Love the mod, keep up the great work!

**Comment by Oggas** [comment]
Worth noting this also happens with pillagers (illagers?) it seems

**Comment by RonnieWi** [comment]
Here to 2nd this, but to add a crash report. Happens when hitting zombies, husks, pillagers, and some other mobs from other mods as well with spells.
[crash-2024-11-01_22.54.29-server.txt](https://github.com/user-attachments/files/17605661/crash-2024-11-01_22.54.29-server.txt)

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
