### ISSUE TITLE
Spell Complexity Fails to Update

### ISSUE THREAD

**Issue by asnover** [Mithion/Mana-And-Artifice#993]
**Describe the bug**
When using the inscription table, adding a component will change the complexity as expected. When removing the component, the complexity fails to update.

**To Reproduce**
1. Go to the table and add a shape.
2. Add a component, then remove the component.

**Expected behavior**
The complexity should go back down when removing the component.

**Screenshots**
![With Component](https://i.imgur.com/e74JJJ7.png)
![Without Component](https://i.imgur.com/yg07wm2.png)

**Version Information (please complete the following information):**
 - Mod Version: [3.1.0.1]
 - Forge Version [47.2.0]

**Additional context**
Additional Mods:
- Arcane Additions 1.9.6
- Burnt 1.7.3
- Caelus 3.2.0+
- Curios 5.7.2+
- DMNR 3.1.10
- GeckoLib 4.4.4
- Lootr 0.7.33.83
- Lucent 1.5.5

The complexity will correct itself when you close and reopen the inscription table menu.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
