### ISSUE TITLE
Incorrect Mana Crystal Position

### ISSUE THREAD

**Issue by asnover** [Mithion/Mana-And-Artifice#994]
**Describe the bug**
The mana crystal appears to be phased inside the pedestal

**To Reproduce**
1. Place a mana crystal on a pedestal :)

**Expected behavior**
The crystal should be centered on the pedestal

**Screenshots**
![Oh the Horror!](https://i.imgur.com/VSfpYg4.png)

**Version Information (please complete the following information):**
 - Mod Version: [3.1.0.1]
 - Forge Version [47.2.0]

**Additional context**

- Arcane Additions 1.9.6
- Burnt 1.7.3
- Caelus 3.2.0+
- Curios 5.7.2+
- DMNR 3.1.10
- GeckoLib 4.4.4
- Lootr 0.7.33.83
- Lucent 1.5.5

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
