### ISSUE TITLE
Mangrove root and felled oak spell

### ISSUE THREAD

**Issue by Oggas** [Mithion/Mana-And-Artifice#995]
**Is your feature request related to a problem? Please describe.**
I get frustrated when I try to farm mangrove wood. Since the magrove trees spawn/grow with a lot of mangrove roots and these are not broken as a part of the felled oak spell.

**Describe the solution you'd like**
It would be lovely if the felled oak spell treated mangrove roots as any tree block and broke these as well.

**Describe alternatives you've considered**
The only other viable option is for me to use chain break to get rid of the roots in an easy manner. This does require a rather higher tier though. 

**Additional context**
Great work on the mod as always!

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
