### ISSUE TITLE
Please don't

### ISSUE THREAD

**Issue by LKD-PIX** [Mithion/Mana-And-Artifice#996]
**I'm always frustrated when:**
 My logs get adulterated by a random content mod in my big modpack, while debugging performance.

**Describe the solution you'd like**
Don't do
 ```
this.isDebug = (ManagementFactory.getRuntimeMXBean().getInputArguments().toString().indexOf("-agentlib:jdwp") > 0);
    boolean HIDE_CONSOLE_NOISE = this.isDebug;
    if (HIDE_CONSOLE_NOISE) {
      ForgeLoggerTweaker.setMinimumLevel(Level.WARN);
      ForgeLoggerTweaker.applyLoggerFilter();
    } 
```

**Describe alternatives you've considered**
Using gradlew task or buildscript to set a debug variable only in IDE runs instead of detecting a start argument.

**Comment by GamerSocke** [comment]
This fucking bullshit caused problems for almost one fucking year.

**Comment by The-Wrench** [comment]
this ruined a nice modpack for about half a year
